### ISSUE TITLE
Feature Request: Simple Health Check Endpoint - Volume server

### ISSUE THREAD

**Issue by LazyDBA247-Anyvision** [seaweedfs/seaweedfs#1627]
Hi,
when running seaweedfs in k8s env. (or any deployment in k8s)
the [liveness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command) is an important tool to keep your software healthy and restart pods if they are misbehaving. 

the master/filer/s3 have pretty easy HTTP routes that can be checked.
the volume server only HTTP route is '/status' which checks ALL the volumes that exist and is pretty heavy...

can we add another route to the volume server (or even maybe to all?) something like '/hc' that will be a simple internal check ( filer example, can connect to backend db?, master he is the selected master or can connect to a master, volume server can see the disk usage?) 
and return 20X status code.

Regards.

**Comment by chrislusf** [comment]
I suppose you are thinking about livez endpoint?

https://kubernetes.io/docs/reference/using-api/health-checks/

The healthz endpoint is deprecated (since Kubernetes v1.16), and you should use the more specific livez and readyz endpoints instead.

**Comment by LazyDBA247-Anyvision** [comment]
Hi @chrislusf,
no, i was talking about : 
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command

not trying to monitor the k8s, trying to monitor seaweedfs pods/containers...
so need to check that they are responsive.

the link you send is about monitoring the k8s API... 

regards.

**Comment by chrislusf** [comment]
I mean you want readyz instead of livez?

**Comment by LazyDBA247-Anyvision** [comment]
both can be used with the same endpoint as long as you have the service do a good health check :)

readyz ( called readiness probe) - just verifies that the dependant services / internal stuff is ready and can start responding to requests (waiting for DB to be ready, storage, connection to other services),
as long as the k8s don't get OK(200) on the readiness probe, the service/DNS won't be getting published to "other" services, and the pod will be killed eventually (won't be started and you will have to manually fix this).

livez (called liveness probe) - make sure the service continues to work as planned, and if any problem with the response, pod will be restarted and may be moved to another host...

The readiness probe will run only until READY... liveness probe will continue running through all the lifetime of the pod.

I want an easier liveness probe for the volume server than the '/status'. 
When the volume server has 5K+ volumes, it takes some time and a huge HTTP response...

so having a more dedicated and simple HTTP route, will make the seaweedfs pods, more k8s friendly :)

regards.

**Comment by chrislusf** [comment]
ok. btw: why one volume server has 5K+ volumes? Around 100 is more "healthy".

**Comment by LazyDBA247-Anyvision** [comment]
daily buckets:

- thumbnails/crops - low volume usually 5GB-10Gb
- videos - first day, all videos are kept, can grow to 30-50 volumes (even more) write 0.5 - 1.5TB+ (depend on the number of streams), after a couple of hours that we will start removing many videos that found less important, after several days same 1TB bucket can be reduced to 10GB-50GB

so after 2-3 months, we get a volume server with only 10-30TB of data, but thousands of volumes...

we went with smaller daily buckets so that the vacuum will be effective, we used to use one video bucket, but deleting videos would delete but not cause to remove more than 30% of a specific volume... with daily buckets the cleaning works much better.
 
do you have a better design/implementation that will enable us to clean & control the volume count?

**Comment by chrislusf** [comment]
volumes are similar to resizable hard drives. 
If the old buckets are not purged entirely, you can just put all data into one bucket.

**Comment by DG-Wangtao** [comment]
volume server will meet issue #3964 if `/status` is used as a liveness probe/readiness probe while the size of response body is larger than 10KB, caused by https://github.com/kubernetes/kubernetes/issues/122948, and `probe.Warn` (instead of `probe.Succeess` currently) after https://github.com/kubernetes/kubernetes/pull/122970.

As @LazyDBA247-Anyvision said here, we need a simple health check endpoint.

**Comment by chrislusf** [comment]
there is `/healthz` http handler now

https://github.com/seaweedfs/seaweedfs/blob/master/weed/server/volume_server.go#L115

**Comment by DG-Wangtao** [comment]
Thank you. It would be a better choice to use `/healthz` as the default route with `livenessProbe` and `readinessProbe` in k8s helm chart.

**Comment by chrislusf** [comment]
> Thank you. It would be a better choice to use `/healthz` as the default route with `livenessProbe` and `readinessProbe` in k8s helm chart.

Yes. Please help to make PRs since this may need to change in many places.

**Comment by DG-Wangtao** [comment]
@chrislusf  Hi, I made a PR here #5990, I replaced the default route of readiness/liveness of the volume server in the helm chart values file. It works well in my test k3s environment.
