### ISSUE TITLE
[filer]authentication issue: want to combine mongodb with filer

### ISSUE THREAD

**Issue by jiaqigan** [seaweedfs/seaweedfs#1993]
Want to use mongodb to repalce the local disk store for filer, and I added username and password for the mongodb. When I tried to start the filer server by using command './weed server -filer=true', the server wouldn't start and I got 'F0414 09:26:34  4802 configuration.go:25] failed to initialize store for mongodb: (Unauthorized) command createIndexes requires authentication
'.

**Comment by chrislusf** [comment]
Current code does not have authentication for mongodb. You can help to add the support?

https://github.com/chrislusf/seaweedfs/blob/master/weed/filer/mongodb/mongodb_store.go#L37

**Comment by baursn** [comment]
see #5601
