### ISSUE TITLE
Multipart uploads fail with "The specified multipart upload does not exist. [...]"

### ISSUE THREAD

**Issue by MannerMan** [seaweedfs/seaweedfs#2453]
**Describe the bug**
We use pgbackrest postgres backup tool to send weekly backups to seaweed via S3 filer. This Sunday many backups had failed with the error: `The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed`. Attemps to re-run backups fail with the same error. We have been using pgbackrest and seaweed for almost a year now and not run into this problem before, and it did not coincide with a seaweed version upgrade.

**System Setup**

  * List the command line to start master: `/usr/local/sbin/weed master -ip.bind 0.0.0.0 -ip 10.84.101.100 -mdir /opt/seaweedfs/seaweed-backup001.int/master -defaultReplication 001 -garbageThreshold=0.05`
  *   List the command line to start volume: `/usr/local/sbin/weed volume -port 8080 -metricsPort 9327 -publicUrl http://seaweed-backup001.int -max 72 -ip.bind 0.0.0.0 -ip 10.84.101.108 -dir /opt/seaweedfs/seaweed-backup001.int/volume -mserver 10.84.101.100:9333 -dataCenter sto4 -rack rack1 -idle Timeout=300`
  * List the command line to start filer: `/usr/local/sbin/weed filer -port 8889 -metricsPort 9328 -ip.bind 0.0.0.0 -ip 10.84.101.108 -s3 -master 10.84.101.100:9333 -dataCenter=sto4 -rack=rack1 -s3.config=s3_config.json -concurrentUploadLimitMB=2048 -maxMB=32`
    OS version: CentOS 8
    output of weed version: `version 30GB 2.74 182f43ae5fa2aed5a2526aaa23390e9b8d376e63 linux amd64`
  *  filer.toml
  ```
[postgres]
enabled = true

hostname = "pg-backup001-db001.int"
port = 5432
username = "seaweedfiler"
password = "<redacted>"
database = "seaweedfiler"          # create or use an existing database
sslmode = "require"
connection_max_idle = 10
connection_max_open = 10
connection_max_lifetime_seconds = 300

# if insert/upsert failing, you can disable upsert or update query syntax to match your RDBMS syntax:
enableUpsert = true
upsertQuery = """INSERT INTO "%[1]s" (dirhash,name,directory,meta) VALUES($1,$2,$3,$4) ON CONFLICT (dirhash,name) DO UPDATE SET meta = EXCLUDED.meta WHERE "%[1]s".meta 
!= EXCLUDED.meta"""
  ```

**Expected behavior**
Multipart uploads should work

**Additional context**
Seaweed filer outputs this error in log: 
`	E1116 08:55:46 13802 filer_multipart.go:73] completeMultipartUpload dev-pgbackrest b4526bed-0534-4024-a238-fff3a24f33dd error: <nil>, entries:0`

Please let me know if I can provide additional details.

**Comment by chrislusf** [comment]
could you list entries under `/buckets/dev-pgbackrest/.uploads`?

**Comment by MannerMan** [comment]
> could you list entries under `/buckets/dev-pgbackrest/.uploads`?

Hm, I tried with mc client but it cannot see this folder it seems.
```
$ mc ls seaweed/dev-pgbackrest/.uploads
mc: <ERROR> Unable to stat `seaweed_sto/dev-pgbackrest/.uploads`. Object does not exist.
```
`mc ls seaweed/dev-pgbackrest/` gives me folders `archive/` and `backup/`, which are created by pgbackrest.

**Comment by chrislusf** [comment]
ok. Seems there are too many temp folders there. 

For now, you can delete those folders? I will see how to reproduce this problem locally.

**Comment by MannerMan** [comment]
> ok. Seems there are too many temp folders there.
> 
> For now, you can delete those folders? I will see how to reproduce this problem locally.
Sure, but is this a safe operation so we don't loose any important data? We archive transaction log continuously to seaweed from our databases so uploads pretty much occur constantly. We could temporarily stop it though.

**Comment by chrislusf** [comment]
you can delete folder older than 1 hour.

**Comment by chrislusf** [comment]
those leftover folders should not exist if the multipart uploads succeed. So I wonder why these folders are left there.

**Comment by MannerMan** [comment]
> you can delete folder older than 1 hour.

Currently deleting with;
`mc find seaweed_sto/dev-pgbackrest/.uploads/ --older-than 1h --exec "mc rm {}"`

> those leftover folders should not exist if the multipart uploads succeed or aborted. So I wonder why these folders are left there.

We have had a lot of instances where backups have been terminated due to running too long, for example from the problems we had in #2145. So I guess these are leftovers from such cases, where a multipart upload is terminated in progress. I checked the size of the .uploads folder for our prod bucket with
`mc ls -r --json seaweed_sto/prod-pgbackrest/.uploads/ | jq -s 'map(.size) | add'`
And it returned 22TB :P 
It would probably be nice to have some internal mechanism in seaweed to delete invalid/leftover/aborted multipart uploads

**Comment by MannerMan** [comment]
> ok. Seems there are too many temp folders there.
> 
> For now, you can delete those folders? I will see how to reproduce this problem locally.

.uploads is now empty/deleted, backups still fail unfortunately:
```
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]: ERROR: [039]: raised from local-2 protocol: HTTP request failed with 404 (Not Found):
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        *** Path/Query ***:
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        /dev-pgbackrest/backup/dev-pg-app002/20211118-105515F/pg_data/base/16482/16987.zst?uploadId=d8cb124e-acde-4f4c-a432-f26006212eee
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        *** Request Headers ***:
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        authorization: <redacted>
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        content-length: 5911
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        content-md5: HoeN2RZlF60WAwbBKpaLpw==
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        host: seaweed-backup001-vip.sto4.int
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        x-amz-content-sha256: 2925e706bbe56acad05fa6bcbe349ebb7de633c9fdd068e998cb3a47ba7ee4ba
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        x-amz-date: <redacted>
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        *** Response Headers ***:
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        accept-ranges: bytes
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        content-length: 485
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        content-type: application/xml
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        date: Thu, 18 Nov 2021 09:57:14 GMT
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        server: SeaweedFS S3 30GB 2.74
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        x-amz-request-id: 1637229434667515887
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        *** Response Content ***:
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        <?xml version="1.0" encoding="UTF-8"?>
Nov 18 10:57:14 dev-pg-app002-db002.sto2.int pgbackrest_backup[1938164]:        <Error><Code>NoSuchUpload</Code><Message>The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.</Message><Resource>/dev-pgbackrest/backup/dev-pg-app002/20211118-105515F/pg_data/base/16482/16987.zst</Resource><RequestId>1637229434667499179</RequestId><Key>backup/dev-pg-app002/20211118-105515F/pg_data/base/16482/16987.zst</Key><BucketName>dev-pgbackrest</BucketName></Error>
```

Filer still logs:
`E1118 10:57:14 36498 filer_multipart.go:73] completeMultipartUpload dev-pgbackrest d8cb124e-acde-4f4c-a432-f26006212eee error: <nil>, entries:0`

**Comment by MannerMan** [comment]
Is there any additional information I can provide to help resolve this issue?

**Comment by chrislusf** [comment]
Please run filer with a debug option, "weed -v=4 filer ..." and show the outputs at that point of time.
Also, please share the output of `volume.list` in `weed shell`.

**Comment by MannerMan** [comment]
> Please run filer with a debug option, "weed -v=4 filer ..." and show the outputs at that point of time. Also, please share the output of `volume.list` in `weed shell`.

Ran filer with -v=4 for 15 minutes while doing backup from a dev database server. Unfortunately log was very flooded due to production and test environments uploading transaction log continusly. It ended up being 100mb large. I did some filtering on it like so:
`cat filer.log | grep -v prod-pgbackrest | grep -v acce-pgbackrest | grep -v "prod-pg" | grep -v "acce-pg" > filer_filtered.log`

To remove (hopefully inrelevant) logs concerning prod and test (acce) environments.

Here is filtered output:
[filer_filtered.log](https://github.com/chrislusf/seaweedfs/files/7588775/filer_filtered.log)
Backup is started from dev database server around 15:06:30
Backup fails (visible in this log) at 15:10:23

If important log output is missing I can provide the full log.

`volume.list`:
[volume_list.txt](https://github.com/chrislusf/seaweedfs/files/7588776/volume_list.txt)

**Comment by MannerMan** [comment]
@chrislusf Is there any further information I can provide?

**Comment by chrislusf** [comment]
thanks for the logs. but I could not tell here. 

Seems listing `/buckets/dev-pgbackrest/.uploads/84e1e2b0-dd0a-432d-a520-ef532bc20e8a` simply returned no entries for the uploaded parts.

The log showed at least one other upload succeeded. So not all multipart uploads are failing, which is even more strange.

**Comment by MannerMan** [comment]
> thanks for the logs. but I could not tell here.
> 
> Seems listing `/buckets/dev-pgbackrest/.uploads/84e1e2b0-dd0a-432d-a520-ef532bc20e8a` simply returned no entries for the uploaded parts.
> 
> The log showed at least one other upload succeeded. So not all multipart uploads are failing, which is even more strange.

Could it be an issue with filer store? We're currently using `postgres` (not `postgres2`..), and  the `filemeta` table has grown to over 900gb. Logs such as these are common;
```
2021-12-13 09:41:56.984 CET pid=4175870,backend=client backend,tid=0,host=10.84.101.130,db=seaweedfiler,user=seaweedfiler,app="[unknown]" ERROR:  canceling statement du
e to user request
2021-12-13 09:41:56.984 CET pid=4175870,backend=client backend,tid=0,host=10.84.101.130,db=seaweedfiler,user=seaweedfiler,app="[unknown]" STATEMENT:  SELECT NAME, meta 
FROM "filemeta" WHERE dirhash=$1 AND name>$2 AND directory=$3 AND name like $4 ORDER BY NAME ASC LIMIT $5
```
Table statistics currently shows `2 740 552 314` active tuples/rows in `filemeta`, so doing ORDER BY will probably be very slow. The pkey index is ordered by dirhash, name so it will not be optimal for this either.

I tried to double the amount of ram in the postgres box from 64 to 128GB, with relevant postgres settings tuned accordingly. Still the same error though when trying to do backups.

We're thinking of deploying a new seaweed cluster using another filer-store if it is the culprit, which store would you recommend for a large deployment?

**Comment by chrislusf** [comment]
here is the output on my local empty table:
```
postgres=# explain SELECT NAME, meta FROM filemeta WHERE dirhash=1 AND name>'some' AND directory='/root' AND name like 'some%' ORDER BY NAME ASC LIMIT 5
postgres-# ;
                                                                 QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.14..8.17 rows=1 width=548)
   ->  Index Scan using filemeta_pkey on filemeta  (cost=0.14..8.17 rows=1 width=548)
         Index Cond: ((dirhash = 1) AND ((name)::text > 'some'::text) AND ((name)::text >= 'some'::text) AND ((name)::text < 'somf'::text))
         Filter: (((name)::text ~~ 'some%'::text) AND ((directory)::text = '/root'::text))
(4 rows)

postgres=# explain SELECT NAME, meta FROM filemeta WHERE dirhash=1 AND name>'some' AND directory='/root' AND name like '%' ORDER BY NAME ASC LIMIT 5;
                                      QUERY PLAN
---------------------------------------------------------------------------------------
 Limit  (cost=0.14..8.17 rows=1 width=548)
   ->  Index Scan using filemeta_pkey on filemeta  (cost=0.14..8.17 rows=1 width=548)
         Index Cond: ((dirhash = 1) AND ((name)::text > 'some'::text))
         Filter: (((name)::text ~~ '%'::text) AND ((directory)::text = '/root'::text))
(4 rows)

```

**Comment by kmlebedev** [comment]
@MannerMan Hi, Does the problem reproduce on the latest version?
There were several fixes around Multipart uploads

**Comment by MannerMan** [comment]
@kmlebedev Unfortunately we're no longer running seaweedfs, so I am not able to test! I'll close the issue however since no-one else has reported this problem, it's probably resolved :+1:

**Comment by richardARPANET** [comment]
`botocore.errorfactory.NoSuchUpload: An error occurred (NoSuchUpload) when calling the CompleteMultipartUpload operation: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.
make: *** [Makefile:81: seed] Error 1`

this is happening

**Comment by kmlebedev** [comment]
> `botocore.errorfactory.NoSuchUpload: An error occurred (NoSuchUpload) when calling the CompleteMultipartUpload operation: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. make: *** [Makefile:81: seed] Error 1`
> 
> this is happening

@richardARPANET can you add context?
You use postgreSql?
Can you check multipart upload folder? Though fs.ls /buckets/your_bucket/.upload | weed shell
