### ISSUE TITLE
fsck: Orphan entries while filer.copy running

### ISSUE THREAD

**Issue by KyleSanderson** [seaweedfs/seaweedfs#2578]
**Describe the bug**
When running `weed filer.copy` (per the recommendation) and then `volume.fsck` it's returning orphans for already split files as the file entry has not been committed yet. This results in data loss when using the `-reallyDeleteFromVolume` option.

**System Setup**
- 5.4
- `unknown command: version` | `version 30GB 2.85 19555385 linux amd64`
- ```[leveldb2]
enabled = true
dir = "/data/filerldb2"```

**Expected behavior**
No data loss.

**Additional context**
There doesn't appear to be a way to configure volumes or anything with the k8s operator, so I've written my own deployment. Filer fails to deploy properly because the index is locked by the other rs. Additionally it's pretty painful to use something like k8s with seaweedfs because you cannot specify which filer.toml to use.

**Comment by chrislusf** [comment]
Is the `volume.fsck` run after the `weed filer.copy`, or at the same time?

**Comment by KyleSanderson** [comment]
Same time.

**Comment by chrislusf** [comment]
Not good to run it at the same time, with the reason as you described.

Maybe later an "age" setting can be added to skip volumes too close to current timestamp.

**Comment by KyleSanderson** [comment]
From what I'm seeing (I'm only like 3 hours into code - so pretty fresh) it looks like this is never a safe operation if there are any clients connected. I agree with the expert tag on the flag, however the documentation seems to indicate that removing the entry is as good as a deletion (from an encryption perspective). Running fsck twice does not guarantee the same operation, and as such is never safe to run in its present state.

This is my completely naive understanding of it.

**Comment by chrislusf** [comment]
This should have been fixed with the above 2 PRs.
