### ISSUE TITLE
filer.copy: No resume / checksum to skip work.

### ISSUE THREAD

**Issue by KyleSanderson** [seaweedfs/seaweedfs#2580]
**Describe the bug**
weed filer.copy should only upload new files, and should not restart from the beginning.

**System Setup**
- 5.4
- `unknown command: version` | `version 30GB 2.85 19555385 linux amd64`

**Expected behavior**
compare file sizes, if they match run adler32 between the files.

**Additional context**
Bad things can happen during a transfer, starting from scratch is not good behaviour. https://github.com/chrislusf/seaweedfs/pull/2579

**Comment by greplerio** [comment]
consider xxhash3 over adler32 for better collision prevention.

**Comment by chrislusf** [comment]
See `weed filer.copy -h`. Current code has option `-check.size` to skip copying if size did not change.
