### ISSUE TITLE
[volume.check.disk] looping write of missed records

### ISSUE THREAD

**Issue by kmlebedev** [seaweedfs/seaweedfs#2659]
**Describe the bug**
looping write of missed records after volume.fix.replication

volume.check.disk -v -force
```
load collection registry volume 306 index size 59312 from fast-volume-2.s3-fast-volume.service.dcix.consul:8080 ...
load collection registry volume 306 index size 59488 from fast-volume-4.s3-fast-volume.service.dcdp.consul:8080 ...
volume 306 fast-volume-4.s3-fast-volume.service.dcdp.consul:8080 has 3707 entries, fast-volume-2.s3-fast-volume.service.dcix.consul:8080 missed 0 entries
volume 306 fast-volume-2.s3-fast-volume.service.dcix.consul:8080 has 3709 entries, fast-volume-4.s3-fast-volume.service.dcdp.consul:8080 missed 2 entries
read 306,31333835303964 fast-volume-2.s3-fast-volume.service.dcix.consul:8080 => fast-volume-4.s3-fast-volume.service.dcdp.consul:8080
read 306,31333835313463 fast-volume-2.s3-fast-volume.service.dcix.consul:8080 => fast-volume-4.s3-fast-volume.service.dcdp.consul:8080
load collection registry volume 306 index size 59312 from fast-volume-2.s3-fast-volume.service.dcix.consul:8080 ...
load collection registry volume 306 index size 59520 from fast-volume-4.s3-fast-volume.service.dcdp.consul:8080 ...
volume 306 fast-volume-4.s3-fast-volume.service.dcdp.consul:8080 has 3707 entries, fast-volume-2.s3-fast-volume.service.dcix.consul:8080 missed 0 entries
volume 306 fast-volume-2.s3-fast-volume.service.dcix.consul:8080 has 3709 entries, fast-volume-4.s3-fast-volume.service.dcdp.consul:8080 missed 2 entries
read 306,31333835303964 fast-volume-2.s3-fast-volume.service.dcix.consul:8080 => fast-volume-4.s3-fast-volume.service.dcdp.consul:8080
read 306,31333835313463 fast-volume-2.s3-fast-volume.service.dcix.consul:8080 => fast-volume-4.s3-fast-volume.service.dcdp.consul:8080
load collection registry volume 306 index size 59312 from fast-volume-2.s3-fast-volume.service.dcix.consul:8080 ...
load collection registry volume 306 index size 59552 from fast-volume-4.s3-fast-volume.service.dcdp.consul:8080 ...
volume 306 fast-volume-4.s3-fast-volume.service.dcdp.consul:8080 has 3707 entries, fast-volume-2.s3-fast-volume.service.dcix.consul:8080 missed 0 entries
volume 306 fast-volume-2.s3-fast-volume.service.dcix.consul:8080 has 3709 entries, fast-volume-4.s3-fast-volume.service.dcdp.consul:8080 missed 2 entries
read 306,31333835303964 fast-volume-2.s3-fast-volume.service.dcix.consul:8080 => fast-volume-4.s3-fast-volume.service.dcdp.consul:8080
read 306,31333835313463 fast-volume-2.s3-fast-volume.service.dcix.consul:8080 => fast-volume-4.s3-fast-volume.service.dcdp.consul:8080
load collection registry volume 306 index size 59312 from fast-volume-2.s3-fast-volume.service.dcix.consul:8080 ...
load collection registry volume 306 index size 59584 from fast-volume-4.s3-fast-volume.service.dcdp.consul:8080 ...
volume 306 fast-volume-4.s3-fast-volume.service.dcdp.consul:8080 has 3707 entries, fast-volume-2.s3-fast-volume.service.dcix.consul:8080 missed 0 entries
volume 306 fast-volume-2.s3-fast-volume.service.dcix.consul:8080 has 3709 entries, fast-volume-4.s3-fast-volume.service.dcdp.consul:8080 missed 2 entries
read 306,31333835303964 fast-volume-2.s3-fast-volume.service.dcix.consul:8080 => fast-volume-4.s3-fast-volume.service.dcdp.consul:8080
read 306,31333835313463 fast-volume-2.s3-fast-volume.service.dcix.consul:8080 => fast-volume-4.s3-fast-volume.service.dcdp.consul:8080
load collection registry volume 306 index size 59312 from fast-volume-2.s3-fast-volume.service.dcix.consul:8080 ...
load collection registry volume 306 index size 59616 from fast-volume-4.s3-fast-volume.service.dcdp.consul:8080 ...
volume 306 fast-volume-4.s3-fast-volume.service.dcdp.consul:8080 has 3707 entries, fast-volume-2.s3-fast-volume.service.dcix.consul:8080 missed 0 entries
volume 306 fast-volume-2.s3-fast-volume.service.dcix.consul:8080 has 3709 entries, fast-volume-4.s3-fast-volume.service.dcdp.consul:8080 missed 2 entries
read 306,31333835303964 fast-volume-2.s3-fast-volume.service.dcix.consul:8080 => fast-volume-4.s3-fast-volume.service.dcdp.consul:8080
sync volume 306 on fast-volume-2.s3-fast-volume.service.dcix.consul:8080 and fast-volume-4.s3-fast-volume.service.dcdp.consul:8080: doVolumeCheckDisk source:id:"fast-volume-2.s3-fast-volume.service.dcix.consul:8080" grpc_port:18080 volume 306: rpc error: code = Unknown desc = read needle blob offset 6987655248 size 122: EOF
```

**System Setup**
```
2.88
```

**Comment by aland-zhang** [comment]
**I also found that volume.fix.replication does not fix data on restarted node replicas.
The fuse side uses the fio stress test tool to continuously write data, and restarts the seaweedfs-volume-3.seaweedfs-volume:8080 container. It is found that the two commands volume.fix.replication and volume.balance do not respond, and the data is not synchronized until the restart. volume node, and then execute volume.check.disk -nonRepairThreshold 0.9 -force, an error is reported and data cannot be synchronized.**
Error message for one of the volume ids:
volume 1 seaweedfs-volume-0.seaweedfs-volume:8080 has 1375 entries, seaweedfs-volume-3.seaweedfs-volume:8080 missed 1255 entries
volume 1 seaweedfs-volume-3.seaweedfs-volume:8080 has 147 entries, seaweedfs-volume-0.seaweedfs-volume:8080 missed 27 entries
sync volume 1 on seaweedfs-volume-3.seaweedfs-volume:8080 and seaweedfs-volume-0.seaweedfs-volume:8080: doVolumeCheckDisk source:id:"seaweedfs-volume-3.seaweedfs-volume:8080" diskInfos:{key:"" value:{volume_count:5 max_volume_count:200 free_volume_count:195 active_volume_count:4 volume_infos:{id:7 size:6694880 file_count:8 replica_placement:1 version:3 modified_at_second:1644668138} volume_infos:{id:3 size:359727368 collection:"myfs" file_count:6351 delete_count:5079 deleted_byte_count:59257036 replica_placement:1 version:3 compact_revision:5 modified_at_second:1644669161} volume_infos:{id:1 size:313101872 collection:"myfs" file_count:5678 delete_count:4306 deleted_byte_count:42648816 replica_placement:1 version:3 compact_revision:6 modified_at_second:1644669162} volume_infos:{id:4 size:268224552 collection:"myfs" file_count:1547 delete_count:1440 deleted_byte_count:44772616 read_only:true replica_placement:1 version:3 compact_revision:5 modified_at_second:1644667232} volume_infos:{id:8 size:9052040 file_count:11 replica_placement:1 version:3 modified_at_second:1644665635}}} grpc_port:18080 target:id:"seaweedfs-volume-0.seaweedfs-volume:8080" diskInfos:{key:"" value:{volume_count:6 max_volume_count:200 free_volume_count:194 active_volume_count:6 volume_infos:{id:11 size:37691368 file_count:24 replica_placement:1 version:3 modified_at_second:1644668089} volume_infos:{id:1 size:386693816 collection:"myfs" file_count:1944 delete_count:1797 deleted_byte_count:30175166 replica_placement:1 version:3 compact_revision:6 modified_at_second:1644668610} volume_infos:{id:2 size:336826768 collection:"myfs" file_count:151 replica_placement:1 version:3 compact_revision:7 modified_at_second:1644668833} volume_infos:{id:5 size:312774504 collection:"myfs" file_count:135 delete_count:4 deleted_byte_count:6045802 replica_placement:1 version:3 compact_revision:6 modified_at_second:1644668826} volume_infos:{id:9 size:40974480 file_count:23 replica_placement:1 version:3 modified_at_second:1644668084} volume_infos:{id:12 size:35870192 file_count:24 replica_placement:1 version:3 modified_at_second:1644667982}}} grpc_port:18080 volume 1: rpc error: code = Unknown desc = read needle blob offset 378305080 size 4194332: EOF

**Comment by aland-zhang** [comment]
Upgrade from v2.88 to v2.89 k8s docker environment, continue to serve, restart containers one by one.
After executing volume.check.disk -nonRepairThreshold 0.99 -force -slow
It is found that the file_count check of several volumes is still inconsistent！
![WechatIMG585](https://user-images.githubusercontent.com/929393/154023607-99c5c8ca-f672-43ae-b0ba-a2ab6aa01f73.jpeg)

**Comment by kmlebedev** [comment]
> Upgrade from v2.88 to v2.89 k8s docker environment, continue to serve, restart containers one by one. After executing volume.check.disk -nonRepairThreshold 0.99 -force -slow It is found that the file_count check of several volumes is still inconsistent！ ![WechatIMG585](https://user-images.githubusercontent.com/929393/154023607-99c5c8ca-f672-43ae-b0ba-a2ab6aa01f73.jpeg) The main fear is that after the upgrade restarts the services one by one, the data will be lost. Under the condition of 2 replica, if the file_count is inconsistent, Will the data not be lost after multiple restarts? Data is priceless, and all technologies must first ensure that data is not lost.

Yes, there is a possibility of data loss during the update. Therefore, I first upgrade on servers with one replica, then run volume.check.disk and upgrade on servers with second replicas

**Comment by chrislusf** [comment]
added a fix https://github.com/chrislusf/seaweedfs/commit/94f824e1ce4bc9400d8f3ede1a5420f65ba6b5aa
