### ISSUE TITLE
Replication volumes distribute on a same machine

### ISSUE THREAD

**Issue by ningfdx** [seaweedfs/seaweedfs#3240]
**Improvement**
Seems like we can use the same distribute logic in Erasure-Coding https://github.com/chrislusf/seaweedfs/wiki/Erasure-Coding-for-warm-storage#architecture, to achieve data security.

@chrislusf , If you agree with it, I'm glad to achieve that.

**Screenshots**
![weed](https://user-images.githubusercontent.com/17705801/175918255-cb7dab5f-8800-4e6b-9a58-b12cc580f797.png)

**Comment by chrislusf** [comment]
Please spec out the distribution logic change first.

**Comment by ningfdx** [comment]
Configure different node as different rack solve this problem. Seems no need to improve it.
