### ISSUE TITLE
[master]create new volume id incorrect in some cases

### ISSUE THREAD

**Issue by paochiang** [seaweedfs/seaweedfs#3291]
**Describe the bug**
when `defaultReplication=001` and  there are 1 `seaweedfs master` and 2`seaweedfs volume server`.
if `seaweedfs master` cannot access one `seaweeedfs volume server`(all `seaweedfs volume server` can access the `seaweedfs master`)，the `seaweedfs master` will make another seaweedfs constantly create many new Volume IDs.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
```
#Configure iptables to simulate network failure
iptables -t filter -I INPUT -s 0.0.0.0/0 -p tcp --dport 8082  -j DROP
iptables -t filter -I INPUT -s 0.0.0.0/0 -p tcp --dport 18082  -j DROP
iptables -t filter -I FORWARD -s 0.0.0.0/0 -p tcp --dport 8082  -j DROP
iptables -t filter -I FORWARD -s 0.0.0.0/0 -p tcp --dport 18082  -j DROP
iptables -t filter -I OUTPUT -s 0.0.0.0/0 -p tcp --dport 8082  -j DROP
iptables -t filter -I OUTPUT -s 0.0.0.0/0 -p tcp --dport 18082  -j DROP


#setup seaweedfs
mkdir -p /tmp/volume0
mkdir -p /tmp/volume1
/root/weed314 master -port=9333 -mdir=/tmp/master0 -defaultReplication=001 -ip=localhost -volumeSizeLimitMB=1000 > master0.log 2>&1 &
/root/weed314 volume -port=8080 -dir=/tmp/volume0 -ip=localhost -mserver=localhost:9333 > volume0.log 2>&1 &
/root/weed314 volume -port=8082 -dir=/tmp/volume1 -ip=localhost -mserver=localhost:9333 > volume1.log 2>&1 &
/root/weed314 filer -port=8888  -ip=localhost -master=localhost:9333 > filer.log 2>&1 &
/root/weed314 mount -filer=localhost:8888 -cacheCapacityMB=0 -cacheDir=/tmp/cache001 -dir=/root/lbjmnt1 > mount1.log 2>&1 &

#write one file  to trigger the creation of the new Volume ID
cp /root/1M.jpeg /root/lbjmnt1/
```
- OS version
CentOS Linux release 7.9.2009 (Core)
- output of `weed version`
version 30GB 3.14 3c79c770562ef4f7c0d4e57a88f616eb3671b9cd linux amd64
- if using filer, show the content of `filer.toml`
default config

**Expected behavior**
when need to create new Volume id,  if `seaweedfs master` cannot access one `seaweeedfs volume server`,  do not create so many Volume ID on other `seaweedfs volume server`. btw, need to create correctlly Volume ID.

**Screenshots**
ls /tmp/volume0/ -al
<img width="673" alt="image" src="https://user-images.githubusercontent.com/28077875/178091910-df4bf9a4-2581-4df4-816c-66110026cbd6.png">

ls /tmp/volume1/ -al
<img width="608" alt="image" src="https://user-images.githubusercontent.com/28077875/178092357-13c7f6ce-ba28-4ae2-9d4d-08461be8355e.png">

[master0.log](https://github.com/chrislusf/seaweedfs/files/9075887/master0.log)

**Additional context**
A similar problem was observed in my another environment.(2.85 version， `defaultReplication=002` and  there are 3 `seaweedfs master` 、 3 `seaweedfs volume server` )

[another-master-0.log](https://github.com/chrislusf/seaweedfs/files/9075888/another-master-0.log)
[another-master-1.log](https://github.com/chrislusf/seaweedfs/files/9075889/another-master-1.log)
[another-master-2.log](https://github.com/chrislusf/seaweedfs/files/9075890/another-master-2.log)
The other two  `seaweefs volume servers`have always created new Volume IDs until the disk space is not enough.

volume0 disk is empty

volume1 disk:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/28077875/178092205-03c8bcd6-6b7a-4442-a333-48f223050766.png">

volume2 disk：
<img width="881" alt="image2" src="https://user-images.githubusercontent.com/28077875/178092194-9ce8b127-4d03-4cfa-b4dc-aabf38f66873.png">

**Comment by chrislusf** [comment]
Interesting. In this case, the successful ones needs to delete the created volumes.

**Comment by paochiang** [comment]
> Does this happen on some k8s/docker systems or physical machines?

Both,  **System setup** chapter is directly on a physical machine, **Additional context**  chapter is on k8s.

**Comment by kmlebedev** [comment]
It seems here, at least quickly, you can add a backoff to volume server

**Comment by paochiang** [comment]
I think this was fixed in：https://github.com/seaweedfs/seaweedfs/commit/1e0d64c04883a8d7b09677e9721f9e189743e2f3.
