### ISSUE TITLE
[vacuum] compact volume 1080: cannot hydrate needle from file: size mismatch	

### ISSUE THREAD

**Issue by kmlebedev** [seaweedfs/seaweedfs#3366]
**Describe the bug**

One volume on two volume servers regularly can't make a compact

**System Setup**
```
3.14
```

**Expected behavior**
I would like to have a recommendation, and preferably right in the log, how you can fix such a volume

**Screenshots**
![Screenshot 2022-07-26 at 15 42 58](https://user-images.githubusercontent.com/9497591/180988343-2d322706-6835-485a-853d-9baded5716d0.png)

**Additional context**
log message:
```
E0726 10:32:16     1 volume_grpc_vacuum.go:46] compact volume 1080: cannot hydrate needle from file: size mismatch
```

**Comment by kmlebedev** [comment]
Most often, everything worked out through `weed fix /data` on the volume server

**Comment by kungf** [comment]
hi, @kmlebedev I met this problem too, do you know the root casue of "cannot hydrate needle from file: size mismatch"
