### ISSUE TITLE
Collection contents remain after delete

### ISSUE THREAD

**Issue by kemenyt** [seaweedfs/seaweedfs#3389]
**Describe the bug**
I am trying to speed up the deletion of some temporary files by storing them in a collection and then dropping the collection, but when I drop the collection the files remain.
**Steps**

1.`curl -F file=@./dummy.txt localhost:8888/abc/?collection=abc`
2. `curl localhost:9333/col/delete?collection=abc`
3. `curl -H"Accept: application/json" localhost:8888/abc?pretty=true`

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount": [docker-compose.yml](https://github.com/seaweedfs/seaweedfs/files/9232586/docker-compose.txt)
- output of `weed version`: version 30GB 3.00 b1dac20c linux amd64
- if using filer, show the content of `filer.toml`: [filer.toml](https://github.com/seaweedfs/seaweedfs/files/9232592/filer.txt)

**Expected behavior**
Expected the files to be at least soft deleted 

**Actual behavior**
`/abc/dummy.txt` is still served: 
```➜  ~ curl -H"Accept: application/json" localhost:8888/abc?pretty=true
{
  "Path": "/abc",
  "Entries": [
    {
      "FullPath": "/abc/dummy.txt",
      "Mtime": "2022-08-01T09:13:07Z",
      "Crtime": "2022-08-01T09:13:07Z",
      "Mode": 432,
      "Uid": 0,
      "Gid": 0,
      "Mime": "text/plain",
      "Replication": "",
      "Collection": "abc",
      "TtlSec": 0,
      "DiskType": "",
      "UserName": "",
      "GroupNames": null,
      "SymlinkTarget": "",
      "Md5": "xj0OXw/jFA1QzRe6Mc+CJA==",
      "FileSize": 23704,
      "Rdev": 0,
      "Inode": 0,
      "Extended": null,
      "chunks": [
        {
          "file_id": "10,011959c45ae3",
          "size": 23704,
          "mtime": 1659345187742543491,
          "e_tag": "xj0OXw/jFA1QzRe6Mc+CJA==",
          "fid": {
            "volume_id": 10,
            "file_key": 281,
            "cookie": 1506040547
          },
          "is_compressed": true
        }
      ],
      "HardLinkId": null,
      "HardLinkCounter": 0,
      "Content": null,
      "Remote": null,
      "Quota": 0
    }
  ],
  "Limit": 100,
  "LastFileName": "dummy.txt",
  "ShouldDisplayLoadMore": false,
  "EmptyFolder": false
}%```

**Comment by chrislusf** [comment]
You are mixing filer API and volume server API. The belong to different layers.

You can use volume server to upload and use collection to delete.
