### ISSUE TITLE
Typo in Wiki for Directories and Files section

### ISSUE THREAD

**Issue by apatel-fn** [seaweedfs/seaweedfs#3395]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/seaweedfs/seaweedfs/discussions

**Describe the bug**
Typo on wiki
`Although one "weed filer" can only sits in one machine,`
Should be:
`
Although one "weed filer" can only sit in one machine,`

**Additional context**
Link to subsection typo: https://github.com/seaweedfs/seaweedfs/wiki/Directories-and-Files#use-cases

**Comment by chrislusf** [comment]
Btw, the wiki is open to everyone.
