### ISSUE TITLE
Stall on trival writes to fuse

### ISSUE THREAD

**Issue by rn-src** [seaweedfs/seaweedfs#3422]
I've got a seaweedfs install with master, 3 volumes, 1 filer and a fuse mount. All volumes are on the same dc/rack. replication is 002. read is fast, but write will stall for several seconds even for a small write, but succeeds. 
i.e. do an edit with vi and save, it is 10 seconds before it saves.

OS: Alpine Linux 3.16
I've got 1 master, 3 volumes, 1 filer, and a fuse mount.

Update: I've changed replication to 000 at request, and fixed replication, but no change.

version 30GB 3.19 03c6f978f42a55810441c7a5a6c77da567bc99b7 linux amd64

I have set these as suggested in the optimization section.
        -volumePreallocate
        -volumeSizeLimitMB=30000

**Expected behavior**
saves, but without the ten second stall

**Additional context**
With -v=4 ...

I have noticed it seems to like to create new volumes even for tiny edits, and even though I have restarted the master, volume, filer, and fuse servers, I get triplicate replicas (as it was first configured for).   That said, here are the logs...

This is the log normally

I0808 23:01:10.107821 weedfs_dir_lookup.go:49 dir Lookup cache hit /docker-modules/apache2/run-docker
I0808 23:01:10.108417 filehandle_read.go:70 file handle read /docker-modules/apache2/run-docker [0,4096) from 1 views
I0808 23:01:10.108512 filehandle_read.go:72   read /docker-modules/apache2/run-docker [0,532) from chunk 16,0501192e6eae45
I0808 23:01:10.112065 slot_pool.go:49 ++> 1
I0808 23:01:10.112219 slot_pool.go:60 --> 0
I0808 23:01:10.112267 page_writer.go:54 ReadDirtyDataAt 0 [0, 4096)
I0808 23:01:10.112434 weedfs_file_sync.go:102 doFlush /docker-modules/apache2/run-docker fh 0
--- stalls here ---
I0808 23:01:17.040869 weedfs_dir_lookup.go:49 dir Lookup cache hit /docker-modules
I0808 23:01:17.041027 weedfs_dir_lookup.go:49 dir Lookup cache hit /docker-modules/apache2
I0808 23:01:17.041199 weedfs_dir_lookup.go:49 dir Lookup cache hit /docker-modules/apache2/run-docker
I0808 23:01:17.041597 page_writer.go:34 1 AddPage [0, 533)
I0808 23:01:17.041622 dirty_pages_chunked.go:44 1 memory AddPage [0, 533)
I0808 23:01:17.041643 slot_pool.go:49 ++> 1
I0808 23:01:17.044215 weedfs_attr.go:53 /docker-modules/apache2/run-docker setattr set size=533 chunks=1
I0808 23:01:17.044364 weedfs_file_sync.go:102 doFlush /docker-modules/apache2/run-docker fh 0
I0808 23:01:17.044402 upload_pipeline.go:144  uploaderCount 0 ++> 1

This is the log when I do a kill -3 <weed mount process>

I0808 23:01:36.051317 weedfs_dir_lookup.go:49 dir Lookup cache hit /docker-modules
I0808 23:01:36.051463 weedfs_dir_lookup.go:49 dir Lookup cache hit /docker-modules/apache2
I0808 23:01:36.051636 weedfs_dir_lookup.go:49 dir Lookup cache hit /docker-modules/apache2/run-docker
I0808 23:01:36.052019 filehandle_read.go:70 file handle read /docker-modules/apache2/run-docker [0,4096) from 1 views
I0808 23:01:36.052058 filehandle_read.go:72   read /docker-modules/apache2/run-docker [0,533) from chunk 16,050121449e101d
I0808 23:01:36.055413 slot_pool.go:49 ++> 1
I0808 23:01:36.055524 slot_pool.go:60 --> 0
I0808 23:01:36.055553 page_writer.go:54 ReadDirtyDataAt 2 [0, 4096)
I0808 23:01:36.055739 weedfs_file_sync.go:102 doFlush /docker-modules/apache2/run-docker fh 0

**Comment by chrislusf** [comment]
The log is not the stack trace I am looking for.

How to setup your env? Docker? Please share steps.

**Comment by chrislusf** [comment]
> I have set these as suggested in the optimization section.
> -volumePreallocate
> -volumeSizeLimitMB=30000

remove these "optimization" first and try. Your disk space may not be enough.

**Comment by rn-src** [comment]
> The log is not the stack trace I am looking for.
> 
> How to setup your env? Docker? Please share steps.

That's what the info log had, and no other log was output.  are you looking for another log, or did it just not print what you needed?

No docker.  Just download and run per the instructions.

> > I have set these as suggested in the optimization section.
> > -volumePreallocate
> > -volumeSizeLimitMB=30000
> 
> remove these "optimization" first and try. Your disk space may not be enough.

I'll try it, but it isn't nearly using up my drive.

**Comment by rn-src** [comment]
I found the problem.  I used the wrong -rack value in the filer.  I guess the pause is a failure mode.  Shorter fail would be better, but the configuration was me.

**Comment by chrislusf** [comment]
@rn-src could you please share the command line you used?

**Comment by rn-src** [comment]
weed -logdir=/varlog/seaweedfs/filer filer -ip=192.168.1.99 -ip.bind=0.0.0.0 -master=localhost:9333 -rack=rack-$(hostname)

They all became rack1 at some point and I missed changing this one.
