### ISSUE TITLE
du outputs wrong size

### ISSUE THREAD

**Issue by paularlott** [seaweedfs/seaweedfs#3424]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/seaweedfs/seaweedfs/discussions

example of a good issue report:
https://github.com/seaweedfs/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/seaweedfs/seaweedfs/issues/1008

Describe the bug

If I place some files into a folder then copy the folder to a weed mount when I run `du -sk` on both the original folder and the copy I get different sizes e.g. original is 16K copy on weed mount reports 2K. weed mount is always under reporting by a long way.

System Setup

OS Ubuntu 22.04 for master, volume and filers.

3 x masters
3 x filers using CockroachDB or leveldb3 (2 different tests and not at the same time, both systems seem to take far too long to restore the meta data)
6 x volume servers

filer.toml

```
[filer.options]
recursive_delete = false

[leveldb3]
enabled = false
dir = "/var/seaweedfs/filer/filerldb3"
```

```
/usr/local/bin/weed -logtostderr volume \
  -ip xxxx -ip.bind 0.0.0.0 \
  -port 8080 -port.grpc 18080 \
  -max 0 -index leveldb \
  -dir /var/seaweedfs/volume \
  -dataCenter=syd1 -rack=rack1 -mserver=xxxx:9333,xxxx:9333,xxxx:9333
```

Masters:

```
/usr/local/bin/weed -logtostderr master \
  -ip xxxx -ip.bind 0.0.0.0 \
  -port 9333 -port.grpc 19333 \
  -mdir=/var/seaweedfs/master -defaultReplication=001 \
  -volumeSizeLimitMB=30000 \
  -peers=xxxx:9333,xxxx:9333,xxxx:9333
```
weed version

version 30GB 3.20 0854171d228951b002efd72076c267f852f2cb15 linux amd64

Expected behavior

The output of du should match.

Thanks.

**Comment by paularlott** [comment]
I've just retested with the dev build of: version 30GB 3.20 d8c54b527e55db48b9a28bb3f9216f0993b0e295 linux amd64

On the local drive it's reporting at 27052 while on the SeaweedFS mount it's reporting as 12533, in this test anyway.

I'm using replication of 001 so it's not something to do with that as it's almost half?

Thanks

**Comment by chrislusf** [comment]
It should not be related to replication.

If I used `weed -v=4 mount -dir=mm -filer=192.168.2.7:8888 -debug` to mount, and run `du -sk` for a specific file of size 8402 bytes.

```
chris@chris-linux:~$ du -sk ~/sw/mm/buckets/test/weed.txt
9       /home/chris/sw/mm/buckets/test/weed.txt
```

The last logs look like this:

```
I0812 13:04:04.236252 weedfs_dir_lookup.go:49 dir Lookup cache hit /buckets/test/weed.txt
2022/08/12 13:04:04 tx 332:     OK, {n7318693933101768089 g1 tE=1s tA=1s {M0100644 SZ=8402 L=1 0:0 B17*512 i0:7318693933101768089 A 1660334007.000000 M 1660334007.000000 C 1660334007.000000}}
```

**Comment by paularlott** [comment]
@chrislusf Sorry, I've just spent some time going through this and yes it is fixed, it was me being slow.

I think SeaweedFS must be more efficient at storing data than the existing file system I was comparing it to, and so I was expecting a slight difference but not as much as it was. The directories I am comparing are full of lots of small files so I think the difference is wasted space on the old file system. Summing the file sizes by hand on SeaweedFS does give the exact numbers.

So based on this when I store a file in SeaweedFS it's actually only using the file size of disk space + 40 byte header?

**Comment by chrislusf** [comment]
the reported is logical size. The actual physical size is not tracked on each file level.

**Comment by paularlott** [comment]
That's useful to know, thanks.
