### ISSUE TITLE
filer服务使用目录上传，有时成功，有时失败

### ISSUE THREAD

**Issue by kakuilan** [seaweedfs/seaweedfs#3435]
**Describe the bug**
使用docker部署了master、volume、filer三个服务。
- 使用curl上传文件，路径带目录，显示都成功，但是在web端看不到文件；
- 在web端新建目录并上传，有些目录可以上传成功并可查看，有些目录提示成功但刷新并没有文件。
- 只在根目录上传就没问题

**System Setup**
- docker-compose如下
![图片](https://user-images.githubusercontent.com/2321437/184327927-5253ff11-294c-427c-b0c8-d67d0d11e161.png)

- 操作系统：win10下使用vagrant虚拟机，linux为 CentOS Linux release 7.9.2009 (Core)

- weed版本为3.20
- filer.toml如下
![图片](https://user-images.githubusercontent.com/2321437/184328058-5253bbd3-fbf9-4b2e-872a-dcbf5871ada9.png)

- 数据库DDL
```SQL
CREATE TABLE `filemeta` (
  `dirhash` bigint(20) unsigned NOT NULL COMMENT 'first 64 bits of MD5 hash value of directory field',
  `name` varchar(1000) NOT NULL DEFAULT '' COMMENT 'directory or file name',
  `directory` text COMMENT 'full path to parent directory',
  `meta` longblob,
  PRIMARY KEY (`dirhash`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

```

**Screenshots**
这些是异常操作相关截图

- curl上传成功
![图片](https://user-images.githubusercontent.com/2321437/184329106-73c3b97d-ab64-45c8-8a8c-3180e712005b.png)
但web端并没有该文件
![图片](https://user-images.githubusercontent.com/2321437/184329178-41382eac-f27c-45b2-8579-90cd02d01231.png)

- web端在2018目录批量上传，显示成功
![图片](https://user-images.githubusercontent.com/2321437/184330434-95c96c2a-f9d6-4ef3-8df3-3d6ac042c022.png)
数据库里面也有文件记录
![图片](https://user-images.githubusercontent.com/2321437/184330603-d45c898e-54ba-4a62-a42b-ddffe0af4077.png)
但刷新页面，目录还是空白
![图片](https://user-images.githubusercontent.com/2321437/184330686-a92ba1eb-b948-4cf4-8ee2-18fcc76e82fb.png)

- web端在2020目录批量上传成功，并正常显示
![图片](https://user-images.githubusercontent.com/2321437/184331143-199f180a-58af-4156-a6d6-6f8ab4676622.png)
数据库记录如
![图片](https://user-images.githubusercontent.com/2321437/184331653-74b9299b-b04a-495c-bac7-c0d1079d1cb6.png)

**Additional context**
不知道目录名字有些什么规则，有些可以上传，有些却不行。

**Comment by chrislusf** [comment]
It is strange that the dirhash is 0 for failed cases. Not sure what is the problem.
