### ISSUE TITLE
 curl -F file=@report.js "http://localhost:8888/javascript/?pretty=y"  can't return fid  

### ISSUE THREAD

**Issue by dzh6699** [seaweedfs/seaweedfs#3438]
**Describe the bug**

 curl -F file=@report.js "http://localhost:8888/javascript/?pretty=y"  
can't return fid  ,Only file size

**System Setup**

- OS version
3.20
- output of `weed version`
- if using filer, show the content of `filer.toml`
default

**Comment by chrislusf** [comment]
it is expected.

**Comment by dzh6699** [comment]
> 
This parameter is inconsistent with the document description

![image](https://user-images.githubusercontent.com/29142176/184525466-a2e4c443-9391-4a79-ab09-5bec7531c4da.png)

**Comment by chrislusf** [comment]
please help to fix the doc
