### ISSUE TITLE
[INFO] Go protobuf module deprecated message

### ISSUE THREAD

**Issue by Dando-Real-ITA** [seaweedfs/seaweedfs#3454]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/seaweedfs/seaweedfs/discussions

example of a good issue report:
https://github.com/seaweedfs/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/seaweedfs/seaweedfs/issues/1008

**Describe the bug**
When building, we get:
`go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.`
The new repository has a more recent version of protobuf

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
- output of `weed version`
- if using filer, show the content of `filer.toml`

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
updated
