### ISSUE TITLE
Filer-Change-Data-Capture ,   Folder size statistics  ,TTL

### ISSUE THREAD

**Issue by huamr** [seaweedfs/seaweedfs#3456]
A folder set TTL .
When files expired , there is no event notification. As a result, Folder size statistics  is inaccurate..

https://github.com/seaweedfs/seaweedfs/wiki/Filer-Change-Data-Capture

**Comment by chrislusf** [comment]
Correct. No notification for TTL entries. The way for file size statistics needs to factor in this.
