### ISSUE TITLE
How to create collection

### ISSUE THREAD

**Issue by uncarman2017** [seaweedfs/seaweedfs#3464]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/seaweedfs/seaweedfs/discussions

example of a good issue report:
https://github.com/seaweedfs/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/seaweedfs/seaweedfs/issues/1008

**Describe the bug**
When I use the post command: "http://xxx.xxx.xxx.xxx:9333/dir/assign?collection=showroom" to create a collection, on some server, it works, but somes not.
Can u give me a line command to create collection manually?

**Comment by chrislusf** [comment]
this is the right command

**Comment by uncarman2017** [comment]
but on some seaweedfs master node, the command is timeout, the version is "30GB 2.91"

**Comment by chrislusf** [comment]
Need a reproducible setup.
