### ISSUE TITLE
volume写满后继续写会失败

### ISSUE THREAD

**Issue by uroot666** [seaweedfs/seaweedfs#3500]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**情况**：限制单个volume最大可写1G，然后创建40G的PVC，在pod里面使用dd写入文件，一共写入三次，第二次会将volume写满，第二次写入失败。

**环境**：
外部部署SeaweedFS 3节点集群（3 master、3 volume、3 filer），给K3S提供存储。filer使用mongo副本集作为filerstore。k3s里面创建svc作为外部三个filer的负载均衡。
SeaweedFS版本：version 30GB 3.22 fa4d0093e17f710c3da00545022646cb96a6fd98 linux amd64
CSI版本：commit b4d5be34718fd4d49cc25ac8f49755b691c6a870
操作系统：CentOS Linux release 7.9.2009 (Core)
k3s版本：v1.23.7+k3s1

启动命令：
nohup /opt/seaweedfs/weed master -metricsPort=1234 -ip=192.168.1.2 -port=9333 -mdir=/data/weedfs/master -peers=192.168.1.2:9333,192.168.1.3:9333,192.168.1.4:9333 -defaultReplication=002 -volumeSizeLimitMB=1000 > /data/weedfs/log/master.log 2>&1&
nohup /opt/seaweedfs/weed volume -metricsPort=1235 -ip 192.168.1.2 -port 9222 -ip.bind 192.168.1.2 -publicUrl 192.168.1.2:9222 -dir /data/weedfs/volume -max 20 -mserver 192.168.1.2:9333,192.168.1.3:9333,192.168.1.4:9333 -dataCenter dc1 -rack rack1 > /data/weedfs/log/volume.log 2>&1&
nohup  /opt/seaweedfs/weed filer -s3 -master=192.168.1.2:9333,192.168.1.3:9333,192.168.1.4:9333 -ip=192.168.1.2 -port=8888 > /data/weedfs/log/filer.log 2>&1&

filer.toml 内容：
[mongodb]
enabled = true
uri = "mongodb://root:root@192.168.1.2:27017,192.168.1.3:27017,192.168.1.4:27017/?replicaSet=test"
option_pool_size = 0
database = "seaweedfs"

**截图**：
![8aMVgveXSJ](https://user-images.githubusercontent.com/18516722/186384313-ccc6b34d-3bb8-436b-8b96-7cae3416c193.jpg)
![image](https://user-images.githubusercontent.com/18516722/186384864-60a7d9b3-c939-46c3-9b35-279870d2b50c.png)

**Comment by chrislusf** [comment]
the disk usage is checked periodically and not enforced byte by byte.

I think the next write would fail.
