### ISSUE TITLE
I lost files when I uploaded them in bulk

### ISSUE THREAD

**Issue by dzh6699** [seaweedfs/seaweedfs#3518]
**Describe the bug**
Files uploaded in batches are lost

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
readhat 7 
- output of `weed version`
3.23
- if using filer, show the content of `filer.toml`
default
**Expected behavior**

**Screenshots**

Ready to upload,   11 files
![image](https://user-images.githubusercontent.com/29142176/186805609-4e550a19-74b6-424e-87fe-3ca4184d8675.png)

uploading
![image](https://user-images.githubusercontent.com/29142176/186805662-399890f1-7f66-43e3-ba41-af5b7b18d50b.png)

result ,  6 files

![image](https://user-images.githubusercontent.com/29142176/186805837-04768802-0f32-4e46-a4bc-728c82d58a62.png)

**Comment by chrislusf** [comment]
seems something wrong with the javascript in the filer UI.

**Comment by chrislusf** [comment]
@blacktear23 could you please take a look here?

**Comment by blacktear23** [comment]
@dzh6699 after you uploaded, wait some seconds then use shift+f5 to refresh, then can you see the lost files?

**Comment by dzh6699** [comment]
> @dzh6699 after you uploaded, wait some seconds then use shift+f5 to refresh, then can you see the lost files?

no, i can't

**Comment by dzh6699** [comment]
> @dzh6699 after you uploaded, wait some seconds then use shift+f5 to refresh, then can you see the lost files?

![image](https://user-images.githubusercontent.com/29142176/187069189-944023c2-7139-4d3e-8c45-4b5cff558bf4.png)

**Comment by dzh6699** [comment]
![image](https://user-images.githubusercontent.com/29142176/187069232-349fa37e-53eb-4381-9e60-edd93009b185.png)

**Comment by blacktear23** [comment]
@dzh6699 It should be fixed after next release.
