### ISSUE TITLE
Failure to delete losted volume node `vid loc` from `vid2Locations` causes queries to potentially wait for additional timeouts

### ISSUE THREAD

**Issue by famosss** [seaweedfs/seaweedfs#3520]
**Describe the bug**
When a volume fails, such as not being able to ping. The `master` resets the volume server, but the `filer` does not update the `vid2Locations` in `vidmap`, resulting in the `urlStrings(lookupFileIdFn(fileId))` obtained during the query and the faulty volume. When the get request hits the faulty volume, it takes a long time to wait for a timeout

**version**
3.23

**Comment by chrislusf** [comment]
@famosss can you check whether this line of code is executed for your case? 

https://github.com/seaweedfs/seaweedfs/blob/f5156cf3a8d08622574865532ef5139537384b40/weed/wdclient/masterclient.go#L268

**Comment by famosss** [comment]
> @famosss can you check whether this line of code is executed for your case?
> 
> https://github.com/seaweedfs/seaweedfs/blob/f5156cf3a8d08622574865532ef5139537384b40/weed/wdclient/masterclient.go#L268

Not executed. Stopping the volume server does not affect performance, but if the volume server is directly shut down (cannot be pinged), performance will be affected. I raised an issue first, and I will `pr` to fix it later
