### ISSUE TITLE
How to fix "fail to load vif" during volume.configure.replication

### ISSUE THREAD

**Issue by eleaner** [seaweedfs/seaweedfs#3528]
I have all my 14 HDD on one machine. I initially set each of them as if it belongs to a separate rack, and I set the replication to 020. Later, under the assumption that it might hinder performance, I decided to move them all to a single rack. Then in an attempt to fix the replication, I executed

volume.configure.replication -collectionPattern * -replication 002

Unfortunately, it ended in a particular error.

error: volume configure volume_id:370  replication:"002": volume 370 fail to load vif

I cannot find much information about it. any ideas on how to fix it?

**Comment by chrislusf** [comment]
can you do a `ls -al` on the folder?

**Comment by eleaner** [comment]
@chrislusf, how can I find which folder it is?
