### ISSUE TITLE
volumeSizeLimitMB is not honored during upload

### ISSUE THREAD

**Issue by imrebuild** [seaweedfs/seaweedfs#3546]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/seaweedfs/seaweedfs/discussions

example of a good issue report:
https://github.com/seaweedfs/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/seaweedfs/seaweedfs/issues/1008

**Describe the bug**
File is still being written into volume even it's already beyond volumeSizeLimitMB.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
    - `./weed server -dir="./data" -master.volumeSizeLimitMB 100 -volume.max 0`
- OS version: Linux
- output of `weed version` : version 30GB 3.24 b7a887fea16ecef7832a60818bf9b30e6600a258 linux amd64

**Expected behavior**
File should be writen into new volume right after the old volume is full.

**Screenshots**
![image](https://user-images.githubusercontent.com/42030593/187274169-4e6958ee-4004-4403-b74e-69e4fe71e3ac.png)
![image](https://user-images.githubusercontent.com/42030593/187274293-98fa9fe8-45e7-41c8-8983-d7307edd77a6.png)
![image](https://user-images.githubusercontent.com/42030593/187274995-03163542-6207-406d-9c74-0d80f4e4b667.png)

**Additional context**
File is uploaded through `./weed upload -debug ~/1.mkv`. The file size is 505M.
This server is actually localhost, so the upload process is very fast.
This `master.volume_growth` is set to 1 for all `copy_*` parameters. However the volume can still reach 124.00 MiB when I set `copy_1` to 5.

**Comment by chrislusf** [comment]
This is expected. The volume server needs time to report to master, and master can redirect the writes.
If the upload is too fast, the volume will run over the limit.

**Comment by imrebuild** [comment]
Looks like it's only controlled by master server. 

I tried to start server with different volumeSizeLimitMB and the volume status is switching between unwritable and writable.

Thanks for the explanation.
