### ISSUE TITLE
Is it possible to upgrade or migrate the Seaweedfs from version 0.76 to the latest stable version without losing data?

### ISSUE THREAD

**Issue by chatreek** [seaweedfs/seaweedfs#3547]
Hi, I am just a newbie to using the SeaweedFS. Currently, my company is using the legacy version (0.76) of SeaweedFS and I want to upgrade to the last stable version without losing data. Is it possible to do that? Please suggest.

**Comment by chrislusf** [comment]
Sorry, not possible because the old data model is unable to iterate through all the files.
