### ISSUE TITLE
[Feature Request] Option to Disable CORS on Filer

### ISSUE THREAD

**Issue by jerebear12** [seaweedfs/seaweedfs#3611]
--The Issue--
The Filer, by default, will deny all incoming requests from scripts in web applications due to the  [CORS policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). Requests sent that do not pass the CORS check(figure 1 on the page referenced) will fail and not display an error code to the client(in this case, the browser). The Filer cannot be used as an API by the browser unless the CORS policy is ignored by the Filer.

--System Setup--
Version:
![Weed_Version](https://user-images.githubusercontent.com/72420925/188712430-75be5ed7-4ecd-45fd-9306-cccc2d1e6c63.png)

Filer start command:
![InkedSeaweed_Service_File_Redacted](https://user-images.githubusercontent.com/72420925/188720016-ae1f26bb-6d0f-4987-b4d5-3250157ddfa4.jpg)

Master start command:
![InkedSeaweed_Master_Service_File_Redacted](https://user-images.githubusercontent.com/72420925/188720052-6b057012-edf0-436a-b1e0-e37c88edb48c.jpg)

Volume start command:
![InkedSeaweed_Volume_Server_Service_File_Redacted](https://user-images.githubusercontent.com/72420925/188720090-774988bf-d0aa-4e22-ab01-7cde5e11376e.jpg)

--Current Behavior--
Requests performed in the browser will fail and not display an error code to the javascript. If the page is inspected, the 'network' tab will display the request in red indicating failure. The only way past this is a local Filer or a development proxy server.

![errored_out_requests](https://user-images.githubusercontent.com/72420925/188716196-4540d663-eabe-485d-a5ee-8eab6d403f6f.JPG)

![request_data_redacted](https://user-images.githubusercontent.com/72420925/188716213-9a888abc-ca6c-48d8-9d2e-d07447c0f253.JPG)

--Expected Behavior--
We want HTTP requests performed by JavaScript code in the browser to pass the CORS check and return a valid response. The Filer would be expected to allow cross-origin requests. The option to enable this could be a flag passed to the 'weed filer' command or possibly a variable in the 'filer.toml' or 'security.toml' file.

**Comment by chrislusf** [comment]
Can the request have a "Origin" header?

Current code is:
```
	if r.Header.Get("Origin") != "" {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Credentials", "true")
	}
```

**Comment by jerebear12** [comment]
I believe POST requests made by the browser will always have an Origin header that contains the request's address. I think PUT and DELETE will as well.

**Comment by jerebear12** [comment]
@chrislusf We are still getting this error. Any suggestions?

**Comment by chrislusf** [comment]
you can add some debug message around here, and see why it did not work.
https://github.com/seaweedfs/seaweedfs/blob/master/weed/server/filer_server_handlers.go#L48

**Comment by jerebear12** [comment]
Thanks. I'm testing a few things with that code.
