### ISSUE TITLE
[Mount]logical error in new inode allocation

### ISSUE THREAD

**Issue by VictorSFF** [seaweedfs/seaweedfs#3619]
**Describe the bug**
In weed_mount, during file lookup, it will try to allocate a new inode for a new file.
Upon inode conflicts, it will allocate the next inode number.
There is a logical bug in the allocation algorithm:

In func (i *InodeToPath) Lookup:

...
		if !isHardlink {
			for _, found := i.inode2path[inode]; found; inode++ {
				_, found = i.inode2path[inode]
			}
		}
...

It will obviously run error, it should be:
...
		if !isHardlink {
			for _, found := i.inode2path[inode]; found; inode++ {
				_, found = i.inode2path[inode + 1]
			}
		}
...

**Comment by chrislusf** [comment]
Send a PR?

**Comment by VictorSFF** [comment]
OK, I will. Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
