### ISSUE TITLE
Failed to write to local disk / flush data failed: volume XXX is read only

### ISSUE THREAD

**Issue by PUSHRCDN** [seaweedfs/seaweedfs#3628]
**Describe the bug**
When a volume becomes read only, some files being uploaded will end up being corrupted and will display a size of 0 bytes.

**System Setup**
- weed master -defaultReplication=001 -volumeSizeLimitMB=10240
- Ubuntu 22.04.1 LTS
- a cluster of 4 servers, 40 disk drives, weed mount on server 1. FTP server running on the same server to allow uploads to the mount
- weed version 30GB 3.23  linux amd64

- master.toml:

```
[master.maintenance]
# periodically run these scripts are the same as running them from 'weed shell'
scripts = """
  lock
  ec.encode -fullPercent=95 -quietFor=1h
  ec.rebuild -force
  ec.balance -force
  volume.deleteEmpty -quietFor=24h -force
  volume.balance -force
  volume.fix.replication
  s3.clean.uploads -timeAgo=24h
  unlock
"""
sleep_minutes = 17          # sleep minutes between each script execution
```

- filer.toml:

```
[redis3] # beta
enabled = true
address = "localhost:[redacted]"
password = "[redacted]"
database = 0
```

**Expected behavior**
This issue is observed on a setup where files are being uploaded to a weed FUSE mount via FTP. Expected behaviour would be for the file to be stored correctly. However, the resulting file will be corrupted, displaying a size of 0 bytes. This issue only happens when a volume is in read only state. 

**Screenshots**
Upload via FTP:
`Sep  8 02:03:45 SFS-FSN1-DC1-0001 pure-ftpd: (2220@[redacted]) [NOTICE] /home/sfs/2220/[redacted].mp4 uploaded  (7672027944 bytes, 9162.76KB/sec)`

Weed warning log:

`E0908 02:03:45.668145 weedfs_file_sync.go:106 /2220/[redacted].mp4 doFlush: flush data: upload data: unmarshalled error http://[redacted]:8082/438,72c1e1bd517e8b: failed to write to local disk: volume 438 is read only`

Another file:

`W0908 02:03:33.442864 upload_content.go:164 uploading 2 to http://[redacted]:8082/438,72c1e61248936c: unmarshalled error http://[redacted]:8082/438,72c1e61248936c: failed to write to local disk: volume 438 is read only`

Running stat on the file:

```
root@SFS-FSN1-DC1-0001 ~ # stat /home/sfs/2220/[redacted].mp4
  File: /home/sfs/2220/[redacted].mp4
  Size: 0         	Blocks: 0          IO Block: 512    regular empty file
Device: 2ch/44d	Inode: 11673039407198328606  Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/ ftpuser)   Gid: ( 1000/ftpgroup)
Access: 2022-09-08 01:50:07.000000000 +0200
Modify: 2022-09-08 01:50:07.000000000 +0200
Change: 2022-09-08 01:50:07.000000000 +0200
 Birth: -
```

**Comment by chrislusf** [comment]
how did the volume become read only?
