### ISSUE TITLE
S3 connection to Cloudflare R2 generates error when attempting to sync from SeaweedFS to R2

### ISSUE THREAD

**Issue by devilshdespot** [seaweedfs/seaweedfs#3636]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/seaweedfs/seaweedfs/discussions

example of a good issue report:
https://github.com/seaweedfs/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/seaweedfs/seaweedfs/issues/1008

**Describe the bug**
S3 connection to Cloudflare R2 generates error when attempting to sync from SeaweedFS to R2 because of "Header 'x-amz-storage-class' with value '' not implemented"  R2 api does not support x-amz-storage-class as per https://developers.cloudflare.com/r2/platform/s3-compatibility/api/

**System Setup**
- Command to start is 'weed server -dir=/seaweed -s3 -volume.max=50'
- OS version: Debian 11 x64
- output of `weed version`  version 30GB 3.26 c07ab9c060eafe26cc0b4246d507d5b33f32f317 linux amd64
- if using filer, show the content of `filer.toml` Just the blank filer.toml, I have not customized this for the limited test.

**Expected behavior**
The ability to use the s3 api for r2 or to create a new option like we have for b2 for remote config for cloud storage.

**Screenshots**

**Additional context**
Example of error output from issuing filer sync

E0909 19:55:09.629338 filer_sync_jobs.go:47 process directory:"/buckets/cloudflare1/.uploads/9893f4f49e373ee7f2dc110590bb758de0cc84bb" event_notification:{new_entry:{name:"0038.part" chunks:{file_id:"9,249792ab3c60" size:4194304 mtime:1662778272520053410 e_tag:"HRVX+lxnmBczayn2mTB1GA==" fid:{volume_id:9 file_key:9367 cookie:2460695648}} chunks:{file_id:"9,24a9e4b6e2fb" offset:4194304 size:4194304 mtime:1662778273015395623 e_tag:"g+nJ6OX2HoX14OtlGcL88w==" fid:{volume_id:9 file_key:9385 cookie:3837190907}} chunks:{file_id:"9,24ab42fa6467" offset:8388608 size:2097152 mtime:1662778273440090068 e_tag:"77DHnTJcz1Nctg2rfOPGYA==" fid:{volume_id:9 file_key:9387 cookie:1123705959}} attributes:{file_size:10485760 mtime:1662778273 file_mode:432 crtime:1662778273 md5:"\x97\xd0J\xdag\t9Ǌw\xbe\xb4_H\xc5\xea"}} delete_chunks:true new_parent_path:"/buckets/cloudflare1/.uploads/9893f4f49e373ee7f2dc110590bb758de0cc84bb" signatures:-1336353119} ts_ns:1662778273440178234: upload to cloudflare1/testbucket/.uploads/9893f4f49e373ee7f2dc110590bb758de0cc84bb/0038.part: NotImplemented: Header 'x-amz-storage-class' with value '' not implemented

**Comment by kmlebedev** [comment]
It seems that the .Upload folder can be excluded from synchronization

**Comment by kmlebedev** [comment]
Funny my choice :) https://github.com/seaweedfs/seaweedfs/pull/3638

**Comment by chrislusf** [comment]
@kmlebedev your check is more solid. You can make it into a function?

**Comment by kmlebedev** [comment]
> @kmlebedev your check is more solid. You can make it into a function? I used it twice here.

ok

**Comment by kmlebedev** [comment]
done

**Comment by kmlebedev** [comment]
@devilshdespot Hello, did you manage to test this on version 3.27?

**Comment by devilshdespot** [comment]
@kmlebedev I have not, I apologize, I will get to look at this over the weekend  Thanks so much for your patience.

**Comment by kmlebedev** [comment]
> [sync] override amz storage class, None to delete (

Ok,Try set option `-storageClass=""`

**Comment by nivekuil** [comment]
@kmlebedev 

```
weed filer.remote.sync -dir /buckets/my-bucket -storageClass=''
```
```
synchronize /buckets/my-bucket to remote storage...
I1001 04:29:03.572001 filer_remote_sync_dir.go:217 resume from 2022-09-08 22:54:38.024659342 +0000 UTC
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x1d39e84]

goroutine 1 [running]:
github.com/seaweedfs/seaweedfs/weed/command.followUpdatesAndUploadToRemote.func1(0xc00067cff0)
	/go/src/github.com/seaweedfs/seaweedfs/weed/command/filer_remote_sync_dir.go:41 +0x44
github.com/seaweedfs/seaweedfs/weed/pb.AddOffsetFunc.func1(0xc00067cff0)
	/go/src/github.com/seaweedfs/seaweedfs/weed/pb/filer_pb_tail.go:99 +0x4b
github.com/seaweedfs/seaweedfs/weed/pb.makeSubscribeMetadataFunc.func1({0x2976968, 0xc0005939a0})
	/go/src/github.com/seaweedfs/seaweedfs/weed/pb/filer_pb_tail.go:73 +0x3dd
github.com/seaweedfs/seaweedfs/weed/pb.WithGrpcFilerClient.func1(0xc0000be380)
	/go/src/github.com/seaweedfs/seaweedfs/weed/pb/grpc_client_server.go:264 +0x6f
github.com/seaweedfs/seaweedfs/weed/pb.WithGrpcClient(0xb?, 0xc00077fb58, {0xc000242630, 0xf}, 0x48?, {0xc00077fb48?, 0x88?, 0x22a1920?})
	/go/src/github.com/seaweedfs/seaweedfs/weed/pb/grpc_client_server.go:149 +0x185
github.com/seaweedfs/seaweedfs/weed/pb.WithGrpcFilerClient(0x0?, {0x2357a0b?, 0x0?}, {0x294b820, 0xc0000128e8}, 0xc00048de60)
	/go/src/github.com/seaweedfs/seaweedfs/weed/pb/grpc_client_server.go:262 +0xab
github.com/seaweedfs/seaweedfs/weed/pb.WithFilerClient(...)
	/go/src/github.com/seaweedfs/seaweedfs/weed/pb/grpc_client_server.go:256
github.com/seaweedfs/seaweedfs/weed/pb.FollowMetadata({0x2357a0b, 0xe}, {0x294b820, 0xc0000128e8}, {0x235e805, 0x11}, 0x1196e0?, 0xc0?, {0x7ffe86c2cf56, 0x1b}, ...)
	/go/src/github.com/seaweedfs/seaweedfs/weed/pb/filer_pb_tail.go:28 +0x145
github.com/seaweedfs/seaweedfs/weed/command.followUpdatesAndUploadToRemote(0x3ac1ec0, 0x1b?, {0x7ffe86c2cf56, 0x1b})
	/go/src/github.com/seaweedfs/seaweedfs/weed/command/filer_remote_sync_dir.go:61 +0x4e5
github.com/seaweedfs/seaweedfs/weed/command.runFilerRemoteSynchronize.func1()
	/go/src/github.com/seaweedfs/seaweedfs/weed/command/filer_remote_sync.go:94 +0x2c
github.com/seaweedfs/seaweedfs/weed/util.RetryForever({0xc0001196e0, 0x2d}, 0xc00077fe98, 0xc00077fe80)
	/go/src/github.com/seaweedfs/seaweedfs/weed/util/retry.go:38 +0x54
github.com/seaweedfs/seaweedfs/weed/command.runFilerRemoteSynchronize(0x3aa5438?, {0xc000050070?, 0x3?, 0x3?})
	/go/src/github.com/seaweedfs/seaweedfs/weed/command/filer_remote_sync.go:93 +0x213
main.main()
	/go/src/github.com/seaweedfs/seaweedfs/weed/weed.go:81 +0x38c
```

**Comment by kmlebedev** [comment]
@nivekuil Thank you very much. fixed
