### ISSUE TITLE
different behavior between rsync vs cp after weed mount

### ISSUE THREAD

**Issue by Queetinliu** [seaweedfs/seaweedfs#3651]
**Describe the bug**
I have a folder with many files under the subfolder,it not convinent to upload files on weed filer from web browser.so i weed mount then cp the dir to the mount point,then i can see the file on web browser but download it with error.If one upload file from web browser,the file is text/plain;but cp file to weed mount is text plain with charset=utf-8.But when i use rsync copy file to the mount point,i can download file from web browser.

**System Setup**
- OS version
- centos 8.2
- output of `weed version`
- version 8000GB 1.50 linux amd64
- if using filer, show the content of `filer.toml`
- [filer.options]
recursive_delete = false
[leveldb2]
enabled = true
dir = "/data/domdemdata/filerldb2"                                    # directory to store level db files

**Expected behavior**
I prefer to use cp to files ,it's faster than rsync.

**Additional context**
I use xshell connect to the server,no master i use utf-8 or not,cp can't act right.

**Comment by chrislusf** [comment]
1.50 is too old. can you use latest version to check the behavior?

**Comment by Queetinliu** [comment]
ok.I will try as you said

**Comment by Queetinliu** [comment]
I am mistake,in fact my weed version is version 30GB 2.61

**Comment by Queetinliu** [comment]
I found with weed version 8000GB 1.50 linux amd64 cp is normal,but with weed version 30GB 2.61 56ee1d5 linux amd64 cp behaves wrong.

**Comment by chrislusf** [comment]
can you use latest version to check the behavior?

**Comment by chrislusf** [comment]
closing since no updates.
