### ISSUE TITLE
Please help to restore data from filer

### ISSUE THREAD

**Issue by jiaqigan** [seaweedfs/seaweedfs#3715]
Hi, I tried to download some files form filer server, but it failed. 

![image](https://user-images.githubusercontent.com/52802365/190944040-a7bef15c-1387-4606-bb5e-36c9c2585f64.png)
E0919 11:09:53  6103 filer_server_handlers_read.go:244] failed to stream content /atudata/Vanceview_20211102145249_0003/Vanceview_20211102145249_0003.20220912081045.2.dtlog/Vanceview_20211102145249_0003.20220912081045.2.dtlog.zip: read chunk: http://xxxx:8080/15,02f21f2b03d47e6d?readDeleted=true: 404 Not Found 

Is there any way to restore this file?

**Comment by chrislusf** [comment]
please follow issue template.
