### ISSUE TITLE
In maintenance scripts, the command 'volume.delete Empty -quietFor=24h -force' is not executed

### ISSUE THREAD

**Issue by aoberest** [seaweedfs/seaweedfs#3718]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/seaweedfs/seaweedfs/discussions

**Describe the bug**
Hello
In 'master' logs I don't see the execution of the command 'volume.deleteEmpty -quietFor=24 -force'

My scripts in master.toml
```
scripts = """
  lock
    s3.clean.uploads -timeAgo=24h
    volume.balance -force
    volume.deleteEmpty -quietFor=24h -force
    volume.fix.replication
  unlock
"""
```

I saw in logs only this:
```
sep 19 14:24:47 master3 weed-master[23270]: I0919 14:24:47.058107 master_server.go:317 executing: lock []
sep 19 14:24:47 master3 weed-master[23270]: I0919 14:24:47.059028 master_server.go:317 executing: s3.clean.uploads [-timeAgo=24h]
sep 19 14:24:47 master3 weed-master[23270]: I0919 14:24:47.069307 master_server.go:317 executing: volume.balance [-force]
sep 19 14:25:02 master3 weed-master[23270]: I0919 14:25:02.072000 master_server.go:317 executing: volume.fix.replication []
sep 19 14:25:17 master3 weed-master[23270]: I0919 14:25:17.074505 master_server.go:317 executing: unlock []
```
Should the result of the 'volume.deleteEmpty -quietFor=24h -force' work be displayed in the logs of the masters?
I think this command is not executed.

**System Setup**
weed version 30GB 3.28 901e8157de1b486f3eca7f52d525cc36523aed4f linux amd64
- OS version Centos 7

**Expected behavior**
Executing the "volume.deleteEmpty -quietFor=24h -force" command in maintenance scripts.

**Additional context**
If i executing in bash
```
echo "lock; s3.clean.uploads -timeAgo=24h; volume.balance -force; volume.deleteEmpty -quietFor=24h -force; volume.fix.replication; unlock" | weed shell
```
All commands works fine

**Comment by kmlebedev** [comment]
@aoberest I just tested this and haven't noticed any problems. https://github.com/seaweedfs/seaweedfs/issues/3421#issuecomment-1249235988
Since the scripts are executed on the master, and if you have several of them, then on the leader, and you must first make sure that the configuration is identical for all

**Comment by aoberest** [comment]
@kmlebedev Thanks for answer
But i don't saw `volume.deleteEmpty -quietFor=24h -force` in your output
Do you use this command ? 
Can add this 'volume.deleteEmpty -quietFor=24h -force' and test ? 

```
server1_1  | I0916 11:19:16.774397 master_server.go:259 adminScripts:   lock
server1_1  |   ec.encode -fullPercent=95 -quietFor=1h
server1_1  |   ec.rebuild -force
server1_1  |   ec.balance -force
server1_1  |   volume.balance -force
server1_1  |   volume.fix.replication
server1_1  |   unlock
```

**Comment by CsterKuroi** [comment]
@aoberest any update?

**Comment by CsterKuroi** [comment]
got it.
