### ISSUE TITLE
Upload succeeded but 404 when downloading

### ISSUE THREAD

**Issue by shichanglin5** [seaweedfs/seaweedfs#3738]
**Describe the bug**

If the upload path (`/a/b`) has a corresponding entry in the filer and the entry is a directory, then when trying to upload the same path (`/a/b`) with file, the path will be automatically uploaded as a prefix (/a/b -> /a/b/b), resulting in download ( `/a/b`) in response to client with 404

`weed/server/filer_server_handlers_write_autochunk.go:152`
```go
	// fix the path
	path := r.URL.Path
	if strings.HasSuffix(path, "/") {
		if fileName != "" {
			path += fileName
		}
	} else {
		if fileName != "" {
			if possibleDirEntry, findDirErr := fs.filer.FindEntry(ctx, util.FullPath(path)); findDirErr == nil {
				if possibleDirEntry.IsDirectory() {
					path += "/" + fileName   //path as a prefix
				}
			}
		}
	}
```

**Expect behavior**
The same path, if the upload is successful, the download should also be successful

**Comment by shichanglin5** [comment]
I tested Amazon s3. A path can be either a file or a directory. When using the client to download, if it is a file, it will be downloaded directly; when viewing it in the console, if it is also a directory, an additional directory with the same name will be displayed.
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/48707349/192267721-8aaa523f-46ee-442c-a74f-32433a0d05ea.png">

**Comment by chrislusf** [comment]
This is hard to support. Need a major filer store rewrite. Need to de-support POSIX mount S3 folders.
