### ISSUE TITLE
Please help to restore data from filer

### ISSUE THREAD

**Issue by jiaqigan** [seaweedfs/seaweedfs#3749]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
I've tried to download some files by using commds like "curl -g "http://localhost:8888/path/to/file/file.zip" -O", but the download process stopped automatically. And here's what I got in the logfile below:

E0919 11:09:53 6103 filer_server_handlers_read.go:244] failed to stream content /atudata/Vanceview_20211102145249_0003/Vanceview_20211102145249_0003.20220912081045.2.dtlog/Vanceview_20211102145249_0003.20220912081045.2.dtlog.zip: read chunk: http://xxxx:8080/15,02f21f2b03d47e6d?readDeleted=true: 404 Not Found

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- weed \
-logdir=/data/seaweed/log \
server \
-ip=ip1 \
-master.port=9333 -master.volumeSizeLimitMB=8000000 \
-master.dir=/data/seaweed/master \
-master.defaultReplication=100 \
-master.peers=ip1:9333,ip2:9333,ip3:9333 \
-dir=/data/seaweed/volume/ -volume.port=8080 -dataCenter=dc1 \
-filer=true -filer.port=8888
- OS version
- linux centos7
- output of `weed version`
- version 8000GB 3.00 b1dac20c704cf5322c6c516e5f064eb00701aec9 linux amd64
- if using filer, show the content of `filer.toml`

**Screenshots**
![image](https://user-images.githubusercontent.com/52802365/192554349-2bc4107b-1533-4701-9683-7d4891d64f8f.png)

**Additional context**
Could you please tell me what might be the cause of this problem, and is there any way to restore these lost files?

**Comment by chrislusf** [comment]
the error is "http://xxxx:8080/15,02f21f2b03d47e6d" is not found.
Try to see whether it exists in the replica.

**Comment by jiaqigan** [comment]
Could you please be more specific on how to check the replica data by file id?

**Comment by jiaqigan** [comment]
I ran this "volume.fsck -findMissingChunksInFilerPath=/atudata/Vanceview_20211102145249_0003/Vanceview_20211102145249_0003.20220912081045.2.dtlog -findMissingChunksInFiler -v" command, and found some missing file chunks, is there any way to restore them?
![1664443888710](https://user-images.githubusercontent.com/52802365/192996077-643440ea-7eb8-43e2-bd06-6d13d65eb122.jpg)
