### ISSUE TITLE
It's very slow to upload files to filer server or even fails when uploading to "http://my_server_ip:8888/buckets/......"

### ISSUE THREAD

**Issue by Ru-Yi-168** [seaweedfs/seaweedfs#3756]
Problem: It's very slow to upload files to filer server or even fails when uploading to "http://my_server_ip:8888/buckets/......"

**About my system:**

**OS:** ubuntu-22.04.1-live-server-amd64
**weed version:** version 30GB **3.29** 1ffb1e696e1...... linux amd64
Although I use filer, but `filer.toml` was NOT created, so I guess I'm using the default parameter values.

**Description:**

I setup a SeaweedFS cluster with 3 servers, running the following command(via **systemd**):

```
Server1: /usr/local/bin/weed server -ip=192.168.1.81 -master.port=9333 -volume.port=9501 -filer -filer.port=8888 -master.dir=/data/seaweedfs/master -dir=/data/seaweedfs/volume -master.peers=192.168.1.82:9333,192.168.1.83:9333 -master.defaultReplication=010 -dataCenter=dc1 -rack=rack1 -volume.max=8 -volume.fileSizeLimitMB=1000

Server2: /usr/local/bin/weed server -ip=192.168.1.82 -master.port=9333 -volume.port=9501 -filer -filer.port=8888 -master.dir=/data/seaweedfs/master -dir=/data/seaweedfs/volume -master.peers=192.168.1.81:9333,192.168.1.83:9333 -master.defaultReplication=010 -dataCenter=dc1 -rack=rack2 -volume.max=8 -volume.fileSizeLimitMB=1000

Server3: /usr/local/bin/weed server -ip=192.168.1.83 -master.port=9333 -volume.port=9501 -filer -filer.port=8888 -master.dir=/data/seaweedfs/master -dir=/data/seaweedfs/volume -master.peers=192.168.1.81:9333,192.168.1.82:9333 -master.defaultReplication=010 -dataCenter=dc1 -rack=rack3 -volume.max=8 -volume.fileSizeLimitMB=1000

```

The file **/etc/systemd/system/seaweedfs.service** in each server is like:

```
[Unit]
Description=SeaweedFS
After=network.target

[Service]
Type=simple
User=root
Group=root

ExecStart=/usr/local/bin/weed server -ip=192.168.1.82 -master.port=9333 -volume.port=9501 -filer -filer.port=8888 -master.dir=/data/seaweedfs/master -dir=/data/seaweedfs/volume -master.peers=192.168.1.81:9333,192.168.1.83:9333 -master.defaultReplication=010 -dataCenter=dc1 -rack=rack2 -volume.max=8 -volume.fileSizeLimitMB=1000
WorkingDirectory=/usr/local/bin/
StandardOutput=file:/data/seaweedfs/logs/seaweedfs.log
StandardError=file:/data/seaweedfs/logs/seaweedfs.log
SyslogIdentifier=SeaweedFS

[Install]
WantedBy=multi-user.target

```

In order to do the following test, I downloaded an image file:

`curl https://1.dam.s81c.com/p/08f951362fa700ec/20220926-ls-sustainability-smart-paper-26988-720x360.png -o test.png`

After the SeaweedFS cluster is running, paste the following batch command into the terminal and execute:

```
(
curl -F "filename=@test.png" "http://192.168.1.81:8888/buckets/a1/test1.png"
curl -F "filename=@test.png" "http://192.168.1.81:8888/buckets/a2/test2.png"
curl -F "filename=@test.png" "http://192.168.1.81:8888/buckets/a3/test3.png"
curl -F "filename=@test.png" "http://192.168.1.81:8888/buckets/a4/test4.png"
curl -F "filename=@test.png" "http://192.168.1.81:8888/buckets/a5/test5.png"
curl -F "filename=@test.png" "http://192.168.1.81:8888/buckets/a6/test6.png"
)
```

Sometimes, it takes me about 20 seconds to finish the above commands. It seems too slow. But sometimes, I even got the following error:

`{"name":"test.png","size":36273}{"name":"test.png","size":36273}{"error":"rpc error: code = Unknown desc = failed to find writable volumes for collection:a3 replication:010 ttl: error: No more writable volumes!"}{"error":"rpc error: code = Unknown desc = failed to find writable volumes for collection:a4 replication:010 ttl: error: No more writable volumes!"}{"error":"rpc error: code = Unknown desc = failed to find writable volumes for collection:a5 replication:010 ttl: error: No more writable volumes!"}{"error":"rpc error: code = Unknown desc = failed to find writable volumes for collection:a6 replication:010 ttl: error: No more writable volumes!"}
`

But if I paste the following batch command into terminal and execute: (Note: I only replace"**/buckets/**" with "**/buckett/**")

```
(
curl -F "filename=@test.png" "http://192.168.1.81:8888/buckett/a1/test1.png"
curl -F "filename=@test.png" "http://192.168.1.81:8888/buckett/a2/test2.png"
curl -F "filename=@test.png" "http://192.168.1.81:8888/buckett/a3/test3.png"
curl -F "filename=@test.png" "http://192.168.1.81:8888/buckett/a4/test4.png"
curl -F "filename=@test.png" "http://192.168.1.81:8888/buckett/a5/test5.png"
curl -F "filename=@test.png" "http://192.168.1.81:8888/buckett/a6/test6.png"
)

```
It only takes me about 1 second or less to finish the above commands. So I guess there might be something wrong with the path "http://192.168.1.81:8888/buckets/". Because I also tried other path names such as "http://192.168.1.81:8888/aa/......" or "http://192.168.1.81:8888/buck/........", they all run fast and successfully. 

Here is the screenshot:

![error](https://user-images.githubusercontent.com/114624430/192911039-89a015f5-f153-47d1-9b82-3758ae5b4f0f.jpg)

**Comment by chrislusf** [comment]
Increase `volume.max`
