### ISSUE TITLE
It seems that the actual Java client (3.13) lacks calculating of `Content-MD5` at the client side when uploading files.

### ISSUE THREAD

**Issue by kvtb** [seaweedfs/seaweedfs#3760]
**Describe the bug**

It seems that the actual Java client (3.13) lacks calculating of `Content-MD5` at the client side when uploading files.

**Comment by chrislusf** [comment]
What is your use case?

**Comment by kvtb** [comment]
> What is your use case?

To ensure there is no bitrot during network transmission and retry on checksum mismatch
