### ISSUE TITLE
Please help to retrieve missing file chunks

### ISSUE THREAD

**Issue by jiaqigan** [seaweedfs/seaweedfs#3784]
**Describe the bug**
I ran this "volume.fsck -findMissingChunksInFilerPath=/atudata/Vanceview_20211102145249_0003/Vanceview_20211102145249_0003.20220912081045.2.dtlog -findMissingChunksInFiler -v" command, and found some missing file chunks, is there any way to restore them?

**System Setup**
weed
-logdir=/data/seaweed/log
server
-ip=ip1
-master.port=9333 -master.volumeSizeLimitMB=8000000
-master.dir=/data/seaweed/master
-master.defaultReplication=100
-master.peers=ip1:9333,ip2:9333,ip3:9333
-dir=/data/seaweed/volume/ -volume.port=8080 -dataCenter=dc1
-filer=true -filer.port=8888
OS version
linux centos7
output of weed version
version 8000GB 3.00 https://github.com/seaweedfs/seaweedfs/commit/b1dac20c704cf5322c6c516e5f064eb00701aec9 linux amd64
if using filer, show the content of filer.toml

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/52802365/193718873-3e498083-f8a8-44a6-bb07-ec880ea1494c.png)

**Additional context**
Could you please help me with how  to restore these lost files or is there any guidance for that operation? Thanks a lot.

**Comment by chrislusf** [comment]
the logs said "find", not "found", missing file chunks. There are nothing found missing yet.
