### ISSUE TITLE
`mount -t weed` breaks after version 3.30

### ISSUE THREAD

**Issue by BakerBunker** [seaweedfs/seaweedfs#3790]
The problem is roughly same as #3767. After 3.30 update, I can't mount by `mount` command, it fails silently. `weed mount` still works normally, but i can't add extra options with this command.

**Comment by chrislusf** [comment]
can you help to add some debug message around here?

https://github.com/seaweedfs/seaweedfs/blob/master/weed/command/fuse.go#L193
