### ISSUE TITLE
How to migrate filer storage from leveldb to mysql

### ISSUE THREAD

**Issue by winwill2012** [seaweedfs/seaweedfs#3806]
**Describe the bug**
Not a bug, just consult

**System Setup**
- `../weed filer -port=5889 -master=192.168.254.7:9333,192.168.254.8:9333,192.168.254.11:9333 -collection=filer`
- `Centos 6`
-  weed version is `version 30GB 1.88 b056707 linux amd64`
- below is filer.toml content
```
[memory]
enabled = false

[leveldb]
enabled = true
dir = "."					# directory to store level db files

[mysql]
enabled = false
hostname = "localhost"
port = 3306
username = "root"
password = ""
database = ""              # create or use an existing database
connection_max_idle = 2
connection_max_open = 100
....
```

**Expected behavior**
I want to migrate leveldb records to mysql， and disable leveldb， enable mysql.

**Additional context**
There are about 500000 records in leveldb already, is there any tutorial for the migration ?

thanks

**Comment by kmlebedev** [comment]
1. echo fs.meta.save | weed shell
2. restart weed
3. echo fs.meta.load | weed shell

**Comment by winwill2012** [comment]
ok, thanks!

**Comment by winwill2012** [comment]
There was another problem:
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/9719716/194734766-b5322bda-0a26-4532-91b9-769f2ab51c80.png">

**Comment by chrislusf** [comment]
check `weed` binary versions.

**Comment by winwill2012** [comment]
version 30GB 1.88 b056707 linux amd64
