### ISSUE TITLE
S3 exported metrics can be overflooded by inexistent buckets

### ISSUE THREAD

**Issue by ginn13** [seaweedfs/seaweedfs#3809]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

I've recently connected [minio-gateway](https://github.com/minio/minio/blob/master/docs/gateway/s3.md) to easily browse buckets in Seaweed S3. Thereafter I've noticed hard load on my prometheus instance. Amount of metrics in prometheus almost doubled in just several hours. Moreover, browsing SeaweedFS grafana dashboard started to make Prometheus insanely consume memory and CPU. 

After some time I realised, that minio gateway liveness probe makes each time a [request](https://github.com/minio/minio/blob/a9f1ad79240686039a895a2e0cca988a4b2948d0/cmd/gateway/s3/gateway-s3.go#L234) to s3 backend for inexistent bucket just to check the connection and credentials.

Which consequently leads to overflood of exported metrics list in filer s3:
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/11777877/194779071-b8d89984-4a5c-45c9-a470-7583f313a170.png">
<img width="760" alt="image" src="https://user-images.githubusercontent.com/11777877/194779905-91a430e4-9da0-4319-a56a-1ee6b1789efc.png">

Looks like any request to even inexistent bucket got exported.
Workaround: disable liveness/readiness probes for minio gateway.
Proposal: exclude inexistent bucket names from exported metrics and aggregate all requests to inexistent buckets.

**Comment by chrislusf** [comment]
what is the version?

**Comment by chrislusf** [comment]
this should have been fixed in https://github.com/seaweedfs/seaweedfs/pull/3785

**Comment by ginn13** [comment]
Okay, thank you, @chrislusf !

**Comment by chrislusf** [comment]
thanks to @kmlebedev !
