### ISSUE TITLE
[vacuum] cannot hydrate needle from file: size mismatch

### ISSUE THREAD

**Issue by kmlebedev** [seaweedfs/seaweedfs#3835]
**Describe the bug**

One volume regularly can't make a compact

**System Setup**

3.31

**Expected behavior**
I would like to have a recommendation, and preferably right in the log, how you can fix such a volume when there is no second replica

**Additional context**

![Screenshot 2022-10-12 at 15 22 11](https://user-images.githubusercontent.com/9497591/195318243-4bb0dac7-06b0-40c0-b24c-7fe2ea5fe736.png)

```
Oct 12, 2022 @ 15:14:36.665 | E1012 10:14:36.664977 volume_grpc_vacuum.go:63 failed compact volume 1777: cannot hydrate needle from file: size mismatch
```

**Comment by kmlebedev** [comment]
volume.list
```
DataNode fast-volume-3:8080 hdd(volume:1278/1600 active:1278 free:322 remote:0)
  volume id:853  size:620119072  collection:"monitoring-thanos"  file_count:42  delete_count:1  deleted_byte_count:31457301  replica_placement:10  version:3  compact_revision:33  modified_at_second:1664541139
DataNode fast-volume-0:8080 hdd(volume:1259/1600 active:1258 free:341 remote:0)
 volume id:853  size:1079987944  collection:"monitoring"  file_count:68  delete_count:14  deleted_byte_count:396953201  replica_placement:10  version:3  compact_revision:32  modified_at_second:1664541139
```

volume.check.disk 
```
> volume.check.disk -force -slow -volumeId 853
volume 853 fast-volume-3:8080 has 40 entries, fast-volume-0:8080 missed 0 entries
volume 853 fast-volume-0:8080 has 40 entries, fast-volume-3:8080 missed 0 entries
```

**Comment by chrislusf** [comment]
> > volume.vacuum -volumeId 853

this needs to set the threshold.

**Comment by kmlebedev** [comment]
need use
`volume.fsck -v -verifyNeedles -forcePurging -reallyDeleteFromVolume`
https://github.com/seaweedfs/seaweedfs/pull/3879

**Comment by kmlebedev** [comment]
to long be reproduced after `volume.fsck -v -verifyNeedles -forcePurging -reallyDeleteFromVolume`
`
