### ISSUE TITLE
大量删除文件，磁盘并未减少

### ISSUE THREAD

**Issue by thwlxmyljz** [seaweedfs/seaweedfs#3839]
1、存储时加了ttl=90d，volume节点启动参数-dir加了多个分区目录
2、运行了几天发现存储调用量很大，磁盘不够了
3、写程序使用存储时返回的fid，调用master的http接口进行删除，服务器返回202
4、大量调用删除后，估计都删除一半数据了，期间也调用了/vol/vacuum接口
5、查看volumn节点的磁盘，发现磁盘并没有什么变化，过很久看（一天后）还是没有变化
6、该怎么办呢？

**Comment by thwlxmyljz** [comment]
查看磁盘使用：df 命令

**Comment by thwlxmyljz** [comment]
使用docker部署的服务，磁盘挂载到docker里

**Comment by chrislusf** [comment]
ttl volumes are not compacted.

**Comment by minyutang** [comment]
这个文件在web页面上查看已经删除了，但是dat文件会变成当天的。这个怎么清理来释放空间呢

**Comment by chrislusf** [comment]
@minyutang use a low garbage threshold when gc in weed shell.
