### ISSUE TITLE
An error occurred building android apk with gradle, When I use feaweedfs for storage

### ISSUE THREAD

**Issue by zmysysz** [seaweedfs/seaweedfs#3840]
Repetition steps:

1. system linux centos or ubuntu
2. environment prepare 
    a) install jdk1.8, ndk18, Android SDK 29
    b) add environment variables
3. mount seaweed dir & cd 
4. wget https://github.com/wildfirechat/android-chat/archive/refs/heads/master.zip & unzip master.zip
5. cd android-chat-master & ./gradlew build assembleDebug --info --stacktrace
6. i got the error

Execution failed for task ':chat:packageDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > java.util.zip.ZipException: invalid code lengths set

![image](https://user-images.githubusercontent.com/1826231/195547414-b2cc8108-9e61-4ef3-8bbc-f1de42d7309b.png)

**this is worked fine on local disk or NFS**

thanks for any help

**Comment by chrislusf** [comment]
> 2\. environment prepare
>     a) install jdk1.8, ndk18, Android SDK 29
>     b) add environment variables

Please add exact scripts.

**Comment by chrislusf** [comment]
what is the SeaweedFS version?

**Comment by zmysysz** [comment]
> what is the SeaweedFS version?

![image](https://user-images.githubusercontent.com/1826231/196079291-3cf10825-c4c2-431e-babb-b73356d6e98b.png)

**Comment by chrislusf** [comment]
please upgrade first.

**Comment by chrislusf** [comment]
Updates?

**Comment by zmysysz** [comment]
> 
my colleagues are working on it
but i donot think the version is the problem, it is possible there is no impletemented about the system filelock on seaweedfs mount...

**Comment by chrislusf** [comment]
please try the new version. it has a lot of good fixes.
