### ISSUE TITLE
Volume server lacks API to query index of EC volumes

### ISSUE THREAD

**Issue by kvtb** [seaweedfs/seaweedfs#3850]
Volume Server API functions which query volume index ( `ReadAllNeedles`, `ReadNeedleMeta`, `VolumeTailSender`, ...) do not work with EC volumes.

There is basically no way to query the index of a volume after it is converted to EC, except to convert a volume back to .dat, although EC volumes do have queriable index files.

**Comment by chrislusf** [comment]
they are implemented when needed. Currently no need for these.

**Comment by kvtb** [comment]
It is needed for incremental backup be able to continue if source volume converted to EC before it finished backing it up.

**Comment by chrislusf** [comment]
please send PRs.
