### ISSUE TITLE
`AppendAtNs` is not guaranteed to monotonically increase.

### ISSUE THREAD

**Issue by kvtb** [seaweedfs/seaweedfs#3852]
Is not guaranteed that `AppendAtNs` will increase for each sequential entry.

Sequential records may contain the same `AppendAtNs` or even decreasing ones.

Although such events are not very likely, they may cause `tailVolume` to malfunction and cause loss of data during synchronization.

Each new `AppendAtNs` should not be generated using `uint64(time.Now().UnixNano())` but `max(uint64(time.Now().UnixNano()), lastAppendAtNs+1)` here and in few more places around the codebase

https://github.com/seaweedfs/seaweedfs/blob/824f7ad9e192c1999fdb5da3a9af8c112904cc66/weed/storage/volume_write.go#L159-L166

**Comment by chrislusf** [comment]
please send a PR
