### ISSUE TITLE
needle's `Flags` has only 1 free bit left

### ISSUE THREAD

**Issue by kvtb** [seaweedfs/seaweedfs#3862]
needle's `Flags` has only 1 free bit left (`0x40`), it has sense to reserve it now for "flags have more bytes" for not to break binary format when 8 bits won't be enough

https://github.com/seaweedfs/seaweedfs/blob/b324a6536c07ff57340ff62b5d5318d05ff5666c/weed/storage/needle/needle_read.go#L15-L21

**Comment by chrislusf** [comment]
this is correct.
