### ISSUE TITLE
Needle's meta data is not protected by CRC32

### ISSUE THREAD

**Issue by kvtb** [seaweedfs/seaweedfs#3863]
CRC32 covers only needle's data, while needle's meta data (`Pairs`, `Mime`, `Name`, ...) is not protected by CRC and is prone to silent bit rot.

**Comment by chrislusf** [comment]
this is correct. they are not used in filer layer.

**Comment by kvtb** [comment]
> this is correct. they are not used in filer layer.

What has it to to with filer?

I am not using filer anyway.

**Comment by kvtb** [comment]
Needle header - `Cookie` and `NeedleId`- are also not covered by CRC and could rot.

Actually, to avoid adding new field (break and bloat the file format) - `Cookie` can be generated as `crc32(metadata)` or even `hmac(metadata)` instead of random (where `metadata` includes `NeedleId` from the prefix, and everything from the trailer, including `crc32(data)`)
