### ISSUE TITLE
Files not syncing when use fuse mount

### ISSUE THREAD

**Issue by li-zhixin** [seaweedfs/seaweedfs#3878]
**Describe the bug**

1. Setup seaweed server and use fuse mount.
2. Update a file use seaweed server web UI(like http://10.0.0.1:8888/). 
3. List file on mount folder, the file just uploaded does not exist.
4. remount, then the file just uploaded was found.

**System Setup**

- Server Command: `/usr/local/bin/weed server -dir=/storage -filer=true`
- Mount Command: `/usr/local/bin/weed mount -filer=10.0.0.1:8888 -dir=/mnt/weed -filer.path=/`
- OS version: `Centos7`
-  `weed version`：`version 30GB 3.32 758d70bdc09834066cfd835d0041f38ac77a1d42 linux amd64`

**Expected behavior**
After uploading a file through the UI,  no need to remount it, and the uploaded file can be seen in the mounted folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/21377170/196385792-305ca5fe-870a-4886-87f1-94949c202ca7.png)
![image](https://user-images.githubusercontent.com/21377170/196385662-72325470-1c97-4a00-96c2-429f44c8e5ed.png)
![image](https://user-images.githubusercontent.com/21377170/196385430-d01625cc-7037-47dd-94fc-4d83f16e6042.png)

**Comment by chrislusf** [comment]
can not reproduce. Please run `weed -v mount` to see any errors.
