### ISSUE TITLE
"EACH_COLLECTION" stopped working

### ISSUE THREAD

**Issue by eleaner** [seaweedfs/seaweedfs#3888]
**Describe the bug**
"EACH_COLLECTION" does not work
when no collections are selected
when directly named collections are processed 

**System Setup**
running docker chrislusf/seaweedfs:3.32

master command: 
entrypoint: "/bin/sh"
command: -c "/usr/bin/weed -logtostderr=true master -mdir=/data -defaultReplication=002  -ip.bind=0.0.0.0 -ip=master -port=9933  -metricsPort=9324 -port.grpc=19933 -volumePreallocate -volumeSizeLimitMB=30000"
    
volume commands: 'volume -max=0  -index=leveldb -dir=/weed -disk=hdd -mserver=master:9933 -ip.bind=0.0.0.0  -port=8700  -metricsPort=9300 -port.grpc=18700'

version 30GB 3.32 758d70bd linux amd64

**Expected behavior**
I expect 'ec.encode -collection EACH_COLLECTION -fullPercent=95 -quietFor=1h' to work for every collection in the cluster

**Screenshots**
![image](https://user-images.githubusercontent.com/5169203/197335041-9800385b-45ae-4bc0-830e-0344d1801a0d.png)

**Comment by chrislusf** [comment]
does it hang indefinitely? what are the logs in `172.26.0.9:8702`?

**Comment by eleaner** [comment]
I think we misunderstand each other. 

The parameter "-collection EACH_COLLECTION" is ignored and does nothing. 
I understood that it should process each existing collection.

But when I specify the collection name, it works

Maybe I should write that EACH_COLLECTION is ignored?

**Comment by chrislusf** [comment]
I see. EACH_COLLECTION is not supported yet for `ec.encode`

**Comment by chrislusf** [comment]
I suppose usually not all collections should be EC at the same time. Supporting EACH_COLLECTION may not be a good idea.

**Comment by eleaner** [comment]
ok, what you say makes sense
but it is not really what help on the command says
in such case the help should be adjusted

**Comment by chrislusf** [comment]
Only `ec.rebuild`, `volume.balance`, and `ec.balance` supports EACH_COLLECTION. I do not find EACH_COLLECTION mentioned in other commands.

**Comment by eleaner** [comment]
my fault
bad assumptions!
