### ISSUE TITLE
[volume.merge] merge small volume files

### ISSUE THREAD

**Issue by kmlebedev** [seaweedfs/seaweedfs#3904]
Since some of the files are deleted after recording, this generates an uncontrolled growth of volume IDs

**Comment by guol-fnst** [comment]
Maybe these small volumes can be merged to one big volume  one by one when volume is being vacuumed.

**Comment by chrislusf** [comment]
merging is not supported

**Comment by kmlebedev** [comment]
done https://github.com/seaweedfs/seaweedfs/pull/4907
