### ISSUE TITLE
[weed mount] panic

### ISSUE THREAD

**Issue by paochiang** [seaweedfs/seaweedfs#3913]
**Describe the bug**
weed mount panic when read data. weed mount log:
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/28077875/198283168-b816d108-15f7-49f4-9745-aa6a1c099f52.png">

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
Ubuntu 18.04.5 LTS
- output of `weed version`
version 30GB 3.22 7c58e9782a373438be6836dea90874db7c55bd32 linux amd64
Based on release version 3.22, I added some PR. See: https://github.com/seaweedfs/seaweedfs/compare/3.22...paochiang:seaweedfs:3.22-r3.1.0-fixread

**Expected behavior**
no panic

**Additional context**
product environment, it's hard to reproduce

**Comment by chrislusf** [comment]
Thanks for reporting! this should have been fixed in https://github.com/seaweedfs/seaweedfs/pull/3527

**Comment by paochiang** [comment]
> Thanks for reporting with details! this should have been fixed in #3527

@chrislusf 
It's not right, because the version I used(https://github.com/paochiang/seaweedfs/tree/3.22-r3.1.0-fixread) has added this fix(https://github.com/paochiang/seaweedfs/commit/cec3f033202c84dd71d8f7b13c0dc922357462ed).

**Comment by chrislusf** [comment]
Hard to tell. The `rc.downloaders` is surely initialized. and chunkView should never be nil either.

**Comment by chrislusf** [comment]
What is the use case it was running?

**Comment by paochiang** [comment]
> What is the use case it was running?

Deep learning, model training.

**Comment by chrislusf** [comment]
what is the read write pattern?

**Comment by paochiang** [comment]
Sorry, I didn't know that.  I'll ask next week, but I'm not sure if I can get the useful information.

**Comment by paochiang** [comment]
> what is the read write pattern?

There are append write and sequential read modes, but it is not clear if there are other modes.

**Comment by paochiang** [comment]
@chrislusf 
I looked up all the `weed mount` logs, new Panic found in `weed mount`:
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/28077875/201569096-0fd7f524-b83a-4233-8d13-f6185e1db975.png">

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/28077875/201569185-55f02781-2737-4466-a820-5a20a57066e4.png">

seaweed code: https://github.com/paochiang/seaweedfs/tree/3.22-r3.1.0-fixread

**Comment by chrislusf** [comment]
the branch is missing a few changes. For example, the SwapFileChunk ReadDataAt() is missing a read lock.

**Comment by paochiang** [comment]
Thank you, I will do a check.
