### ISSUE TITLE
[Bug]All HTTP services breaking with TLS certificates in security.toml

### ISSUE THREAD

**Issue by jerebear12** [seaweedfs/seaweedfs#3916]
### Describe the bug
All http pages go down and TLS handshake fails when TLS certificates are set in security.toml

Our team is trying to set up HTTPS on the Filer and secure the other servers. A coworker ran into this and sent me this info so I could post it here.

### System Setup
- Startup command in service file screenshots
- SeaweedFS Version 3.31
- Ubuntu 22.04 LTS VM on Windows

### Expected behavior
TLS handshake succeeds and all services work with security in place. Filer runs on HTTPS instead of HTTP.

#### Service Files:
![MasterService](https://user-images.githubusercontent.com/72420925/198392823-5d1d1fcb-9c87-4eda-ab73-72be86c5a3af.JPG)
![HDDVolumeService](https://user-images.githubusercontent.com/72420925/198392839-8ffe14e6-ed36-44d4-a673-fed16d73b9c4.JPG)
![NVMEVolumeService](https://user-images.githubusercontent.com/72420925/198392852-1ff9e13d-c0c0-4a16-8bdc-c5e234af39f2.JPG)
![FilerService](https://user-images.githubusercontent.com/72420925/198392865-11edb63e-c565-401a-8072-93124ee058a9.JPG)

#### Logs:
![MasterLogs](https://user-images.githubusercontent.com/72420925/198394745-1d369c78-0a93-4ae5-9b23-5ec47ce91e7c.JPG)
![HDDVolumeLogs](https://user-images.githubusercontent.com/72420925/198395064-9a43b550-246e-4bc6-916c-8de2cc9f39c9.JPG)
![NVMEVolumeLogs](https://user-images.githubusercontent.com/72420925/198395316-a7178e26-92d5-4c69-9fdd-5ab7acebc7b6.JPG)

#### Modifications to security.toml:
![security toml](https://user-images.githubusercontent.com/72420925/198395843-fd08dfec-5ca7-4c14-81e1-cd0c1f684672.JPG)

### Additional context 

**Servers Running on this VM as separate services**
- Master
- Filer
- Cassanda
- Volume on HDD
- Volume on NVMe

SeaweedFS was installed and Master, Volume, Filer with CassandraDB servers were created without security first.
This was verified by viewing the HTTP pages and uploading files via the Filer HTTP page
Once the cluster was online and running I attempted to implement security based on the Security Configuration page in the [wiki](https://github.com/seaweedfs/seaweedfs/wiki/Security-Configuration).

I generated the scaffold file and copied it into a security.toml with nano.
- weed scaffold -config=security

I downloaded and performed a build on certstrap 
- git clone https://github.com/square/certstrap
- cd certstrap
- go build

I then created the CA
- ./certstrap init –common-name “SeaweedFS CA”
- Passphrase SeaweedSecurityTest

I then created the certificates
- ./certstrap request-cert –common-name volume01
- ./certstrap request-cert –common-name master01
- ./certstrap request-cert –common-name filer01
- ./certstrap request-cert –common-name client01

The passphrase SeaweedSecurityTest was used for all certificates
The .crt  and .key files were created

I then signed the security certificates
- ./certstrap sign –CA “SeaweedFS CA” –common-name volume01
- ./certstrap sign –CA “SeaweedFS CA” –common-name master01
- ./certstrap sign –CA “SeaweedFS CA” –common-name filer01
- ./certstrap sign –CA “SeaweedFS CA” –common-name client01

All were signed with passphrase SeaweedSecurityTest
The .key files were signed.
I edited the security.toml file based on the example on the wiki

As I had set /etc/seaweed fs as the config directory in the service files I copied the security.toml file to the /etc/seaweedfs directory
- cd ~
- sudo cp security.toml /etc/seaweedfs/

I restarted the Master, Filer, Volume-hdd and Volume-nvme services and the http pages no longer worked and I was getting a handshake error in the log file

**Comment by chrislusf** [comment]
seems there are some spelling errors in `grpc.volume` section.

**Comment by jerebear12** [comment]
Ah! Good eye. Will investigate.

**Comment by kmlebedev** [comment]
> Ah! Good eye. Will investigate.

You can check tls with `make dev_tls` in docker folder

**Comment by jerebear12** [comment]
We fixed the typo and restarted all services only to find these messages in the log files:

Master:
![MasterLogs2](https://user-images.githubusercontent.com/72420925/199108276-53f67cb5-1228-4631-9757-7ebb5092148a.JPG)


VolumeHDD:
![VolumeHDDLogs2](https://user-images.githubusercontent.com/72420925/199108330-4575e310-7d53-4dbe-b332-1d22e2670020.JPG)
[VolumeHDDLogs2.txt](https://github.com/seaweedfs/seaweedfs/files/9904937/VolumeHDDLogs2.txt)

VolumeNVME:
![VolumeNVMELogs2](https://user-images.githubusercontent.com/72420925/199108349-88671288-2d02-4cad-a528-d3c345979538.JPG)
[VolumeNVMELogs2.txt](https://github.com/seaweedfs/seaweedfs/files/9904939/VolumeNVMELogs2.txt)

**Comment by chrislusf** [comment]
you can start with `weed -v=1 master ...` and `weed -v=1 volume ...` to check for more detailed logs.

**Comment by jerebear12** [comment]
Only the Master logs were affected:

![MasterLogs3](https://user-images.githubusercontent.com/72420925/199327142-9dba3f08-3222-4a83-9231-9d85e959261d.JPG)
[MasterLogs3.txt](https://github.com/seaweedfs/seaweedfs/files/9913616/MasterLogs3.txt)

**Comment by chrislusf** [comment]
Increase open file limit.

**Comment by jerebear12** [comment]
We tried increasing the file limit. Still getting the same errors. 

![MasterLogs4](https://user-images.githubusercontent.com/72420925/200379063-c8678a34-8aee-4985-8c82-4e7c1f0e3228.JPG)
[MasterLogs3.txt](https://github.com/seaweedfs/seaweedfs/files/9954165/MasterLogs3.txt)

![VolumeNVMELogs3](https://user-images.githubusercontent.com/72420925/200379155-511df9a2-403e-4029-91cc-b1c5b6a6156a.JPG)
[VolumeNVMELogs3.txt](https://github.com/seaweedfs/seaweedfs/files/9954170/VolumeNVMELogs3.txt)

We believe this is reproducible using the information given seeing as this is the second machine we're having this issue on. Is there anything else you need to narrow down the problem?

**Comment by chrislusf** [comment]
It is not easy to follow all the steps. Need to make it a reproducible case with docker compose.

**Comment by jerebear12** [comment]
I created the docker-compose file. I couldn't reproduce the error but HTTPS isn't working. This repo only works on Linux due to docker networking constraints.

https://github.com/jerebear12/docker-compose

Any thoughts on why HTTPS isn't working?
