### ISSUE TITLE
[S3API] Metadata and Content-Type not set when using minio client 

### ISSUE THREAD

**Issue by aronneagu** [seaweedfs/seaweedfs#3943]
**Describe the bug**
Upload a file to Seaweed S3 endpoint (backed by an Azure Storage Container) using the python minio client results in Metadata being empty, and the incorrect Content-Type being set in Azure (see screenshot)

Minio Python SDK: https://min.io/docs/minio/linux/developers/python/API.html

**System Setup**
```
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
# Weed was built from source from commit 4193dafce1282df4386b7898380af02ee7cbb657
> weed version
version 30GB 3.33  linux amd64
python3 --version
Python 3.8.0
```

**Steps to reproduce**
Save the following as a bash script and run it. Export the variable ACCOUNT_KEY (was provided in private, starts with rwe...) before running the script: `export ACCOUNT_KEY=rwe...`

```
#!/bin/bash
# Set env vars for ACCOUNT_KEY
export ACCOUNT_NAME="seaweedsa"
pip3 install minio
TMPDIR=$(mktemp -d)
echo Log files are saved in": $TMPDIR"
/usr/local/bin/weed -logdir=${TMPDIR} server -dir=${TMPDIR} -s3 2>/dev/null &
server_pid=$!
echo "remote.configure -name=azure -type=azure -azure.account_name=$ACCOUNT_NAME -azure.account_key=$ACCOUNT_KEY" | weed shell
echo "remote.mount -remote=azure/seaweed -dir=/buckets/seaweed" | weed shell
echo "s3.configure -access_key=$ACCOUNT_NAME -secret_key=$ACCOUNT_KEY -user=me -actions=Read,Write,List,Tagging,Admin -apply" | weed shell
/usr/local/bin/weed -logdir=${TMPDIR} filer.remote.sync -dir=/buckets/seaweed 2>/dev/null &
sync_pid=$!
cat <<EOF >min.py
from minio import Minio
import io, os
client = Minio("localhost:8333",
                        access_key=os.environ['ACCOUNT_NAME'],
                        secret_key=os.environ['ACCOUNT_KEY'],
                        secure=False)
result = client.put_object(
    "seaweed", "test-object", io.BytesIO(b"hello"), 5,
    metadata={"Uploaded_by": "aneagu"},
    content_type="application/parquet",
)
EOF
python3 min.py
echo "Waiting for sync to complete" && sleep 2
kill $sync_pid
kill $server_pid
```

**Expected behavior**
Adding `metadata` and `content_type` argumensts to `put_object` function would upload the file to SeaweedFS S3 with those metadata/content-type and that would be saved in Azure Storage as well.
Was expecting to see `Content-type: application/parquet` and `Metadata = My-Project: one`

**Screenshots**
The screenshot is from Azure Storage Explorer, showing that `Metadata` is empty and the `Content-Type` is `Application/octet-stream`
![seaweed_test_object](https://user-images.githubusercontent.com/1262715/199787339-9175c606-f7e3-4050-b1db-37ae35390ecd.PNG)

**Additional context**
We are trying to use seaweedfs as a drop in replacement for minio, so it's important to be able to use the existing tooling (Minio Python SDK)

**Comment by aronneagu** [comment]
Adding another datapoint to the thread

The metadata on file (querying the filer) is below
![image](https://user-images.githubusercontent.com/1262715/199956065-28128390-6c2c-4c8e-976e-fb38bdec4a27.png)

I was expecting that under `remoteEntry` would see something along the lines
```
"remoteEntry":  {
    "remoteContentType": "application/parquet"
    "remoteMetadata": {
       "Uploaded_by": "aneagu"
    }
```

**Comment by kmlebedev** [comment]
@aronneagu Can you build the weed from the [PR](https://github.com/seaweedfs/seaweedfs/pull/3949) and check ?

**Comment by aronneagu** [comment]
Awesome,
I can see now the `Content-Type` being set, but the `Metadata` is still empty

![image](https://user-images.githubusercontent.com/1262715/200014891-d1756a39-aae9-4f75-8768-37086cd7dced.png)

**Comment by kmlebedev** [comment]
> fix filer.remote.sync to azure with ContentType #3949

@aronneagu add fix https://github.com/seaweedfs/seaweedfs/pull/3949/commits/b7377c92a61f0c50f0574dff6f4877365a1b1cab 
Check

**Comment by aronneagu** [comment]
This has worked! Thank you very much for your help guys

![image](https://user-images.githubusercontent.com/1262715/200034906-33544e74-45c5-4f0c-8140-6782c3f0c61e.png)
