### ISSUE TITLE
[Feature request] Filer support for multiple remotes

### ISSUE THREAD

**Issue by aronneagu** [seaweedfs/seaweedfs#3951]
This is a new feature requests.
It would be a useful if Filer would support multiple remotes, for example (aws and azure) that could be kept in sync with their respective remotes.

The use case would be to write once to Filer, and Filer would sync that file to **BOTH** Aws and Azure

Spoke with @chrislusf and thinks it only needs a few tweaks.
Let me know if you need a script that can reproduce this

**Comment by kmlebedev** [comment]
This function is implemented, but you will need to configure, for example, rabbitmq and three queues, one incoming from the filer, then rabbitmq itself copies all messages into two queues, one for Amazon and the second for azure, and two weed replication applications are launched
See https://github.com/seaweedfs/seaweedfs/wiki/Async-Replication-to-Cloud

**Comment by aronneagu** [comment]
That's exactly what I am looking for! Thank you.
