### ISSUE TITLE
[BUG]HTTPS and TLS fail when using Docker

### ISSUE THREAD

**Issue by jerebear12** [seaweedfs/seaweedfs#3966]
**Describe the bug**
HTTPS does not work when TLS certificates are used for GRPC connections in a docker instance.

**System Setup**
Ubuntu 20 LTS VM
[Files Used](https://github.com/jerebear12/docker-compose)
- docker-compose.yml starts three containers that draw from the seaweedfs base image
- Each Dockerfile uses the COPY command to copy the TLS certificates and the security.toml file into themselves.
- One master, one filer, and one volume are all started using the "host" networking setting to bind to the host's ports and IP.

*Commands Used*
`docker compose build --no-cache`
`docker compose up`

*The only modified part of the security.toml is this:*
```
[grpc.volume]
cert = "/etc/seaweedfs/certs/volume01.crt"
key = "/etc/seaweedfs/certs/volume01.key"
allowed_commonNames = ""    # comma-separated SSL certificate common names

[grpc.master]
cert = "/etc/seaweedfs/certs/master01.crt"
key = "/etc/seaweedfs/certs/master01.key"
allowed_commonNames = ""    # comma-separated SSL certificate common names

[grpc.filer]
cert = "/etc/seaweedfs/certs/filer01.crt"
key = "/etc/seaweedfs/certs/filer01.key"
allowed_commonNames = ""    # comma-separated SSL certificate common names
```

**Expected behavior**
Seaweed starts with all three components functional. HTTPS is used on all UIs, especially the Filer.

**Additional context**
Currently each UI works with HTTP. The cert files are referenced in the security.toml file which is being placed in `/etc/seaweedfs`. The `/etc/seaweedfs/certs` folder is created in each Dockerfile. Please use the files linked above to test/debug. They only work on Linux due to networking constraints in Docker.

**Comment by chrislusf** [comment]
the certificates are only used for gRPC APIs, not for https.

**Comment by jerebear12** [comment]
Ah, thank you for the clarification. 

Where can I enable HTTPS on the filer?

**Comment by chrislusf** [comment]
> Where can I enable HTTPS on the filer?

Not supported. You can use some proxy to handle it.

**Comment by jerebear12** [comment]
Ok. Thank you very much!
