### ISSUE TITLE
[filer] Renaming doesn't work with symbol plus in name

### ISSUE THREAD

**Issue by JiffsMaverick** [seaweedfs/seaweedfs#3969]
**Describe the bug**
Renaming with Filer UI doesn't work if file or folder has symbol plus (+) in name.

**System Setup**
- List the command line to start:
  ```
  /srv/seaweedfs/weed server -options=/srv/seaweedfs/master.conf
  ```
  /srv/seaweedfs/master.conf:
  ```
   s3=true
   dir=/srv/seaweedfs/data
   s3.config=/srv/seaweedfs/config.json
   metricsPort=9999
   master.port=9333
   master.dir=/srv/seaweedfs/meta
   master.peers=127.0.0.1:9333
   s3.port=9000
   volume.port=8080
   Ip=127.0.0.1
   filer.port=8888
   volume.index=leveldbMedium
   volume.publicUrl=%my_public_url%
   ```
- OS version: Debian 10.13
- Output of `weed version`: `version 30GB 3.34 47db75a695e7318dc1f98e4c1e014dfe7843282d linux amd64`
- If using filer, show the content of `filer.toml`:
  ```
  recursive_delete = false

  [leveldb2]
  enabled = true
  dir = "/srv/seaweedfs/meta/filerldb2"
  ```

**Expected behaviour**
I expected successful renaming.

**Screenshots**
Here is an error in logs (I tried to rename folder "name+name" to "test":

`I1111 20:57:53.834462 common.go:70 response method:POST URL:/buckets/project/test?mv.from=/buckets/project/name+name with httpStatus:400 and JSON:{"error":"failed to get src entry '/buckets/project/name name', err: filer: no entry is found in filer store"}`

**Additional context**
Steps to reproducing:
1. Open Filer UI
2. Create file or folder with name: 1+1
3. Try to rename this dir/folder
4. Nothing happening

**Comment by chrislusf** [comment]
should be a bug to escape for url in the ui page.

**Comment by JiffsMaverick** [comment]
@chrislusf I tried the new version 3.35. Unfortunately I got same bug. 

```
I1114 17:04:24.835277 common.go:70 response method:POST URL:/buckets/project/test?mv.from=/buckets/project/name+name with httpStatus:400 and JSON:{"error":"failed to get src entry '/buckets/project/name name', err: filer: no entry is found in filer store"}
```

**Comment by JiffsMaverick** [comment]
@chrislusf I just want to make sure you've already seen the message above.

**Comment by chrislusf** [comment]
Works for me though.

**Comment by JiffsMaverick** [comment]
@chrislusf It's very strange. I use latest version 3.35.

1) Open Filer Web UI
2) Create empty folder `name+name`
3) Trying to rename to `test`
4) Get error

```
I1128 10:20:15.030669 s3.go:257 Start Seaweed S3 API Server 30GB 3.35 b1d7963e57ca2013fe9d11c4336c51e8c1c022e6 at http port 8333
I1128 10:20:15.031149 filer_grpc_server_sub_meta.go:279 + listener s3@95.217.146.115:40558
I1128 10:20:15.031164 filer_grpc_server_sub_meta.go:34  s3@95.217.146.115:40558 starts to subscribe /etc/ from 2022-11-28 10:20:15.029893126 +0000 UTC
I1128 10:22:39.154369 common.go:70 response method:POST URL:/buckets/test-bucket/test?mv.from=/buckets/test-bucket/name+name with httpStatus:400 and JSON:{"error":"failed to get src entry '/buckets/test-bucket/name name', err: filer: no entry is found in filer store"}
```

**Comment by JiffsMaverick** [comment]
@chrislusf It's very strange. I use latest version 3.35.

1) Open Filer Web UI
2) Create empty folder `name+name`
3) Trying to rename to `test`
4) Get error

```
I1128 10:20:15.030669 s3.go:257 Start Seaweed S3 API Server 30GB 3.35 b1d7963e57ca2013fe9d11c4336c51e8c1c022e6 at http port 8333
I1128 10:20:15.031149 filer_grpc_server_sub_meta.go:279 + listener s3@x.x.x.x:40558
I1128 10:20:15.031164 filer_grpc_server_sub_meta.go:34  s3@x.x.x.x:40558 starts to subscribe /etc/ from 2022-11-28 10:20:15.029893126 +0000 UTC
I1128 10:22:39.154369 common.go:70 response method:POST URL:/buckets/test-bucket/test?mv.from=/buckets/test-bucket/name+name with httpStatus:400 and JSON:{"error":"failed to get src entry '/buckets/test-bucket/name name', err: filer: no entry is found in filer store"}
```
