### ISSUE TITLE
fuse mount exit unexpectly

### ISSUE THREAD

**Issue by SigmaStar** [seaweedfs/seaweedfs#3985]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/seaweedfs/seaweedfs/discussions

example of a good issue report:
https://github.com/seaweedfs/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/seaweedfs/seaweedfs/issues/1008

**Describe the bug**
If there are more than one process reading and writing fuse mount point, sometimes the weed mount process exit with segmentation fault.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
- output of `weed version`
- if using filer, show the content of `filer.toml`
./weed master
./weed volume -max=500 -mserver="localhost:9333" -port=8080
./weed filer -port=8888 -master="localhost:9333"
./weed mount -filer=localhost:8888 -dir=./mnt/

**Expected behavior**
Normal

**Screenshots**
![image](https://user-images.githubusercontent.com/22829962/202054527-797613f5-c91d-4ad9-8278-5b29074489ae.png)

**Additional context**
there are more than one processes reading and writing dir. Also while running mast there are some warnings which indicate that some file cannot be deleted but I have deleted them many ages ago.

**Comment by zemul** [comment]
weed 3.34

[Trasnport endpoint is not connected ]
it also appears at my mount point, but there was no error or fatal message in the log.

**Comment by zemul** [comment]
Please tell me how to reproduce this error. @sigmaStar

**Comment by zemul** [comment]
Need some `recover` positioning issues. @chrislusf

**Comment by SigmaStar** [comment]
I'm sorry I can't. Because I think it's not the problem of weed mount. My weed filesystem is corrupted, and maybe this exit is because failed operation submitted to the fuser. I think maybe we can add some corrupted file records to weed and then reproduce this error.

**Comment by chrislusf** [comment]
the recent versions, 3.38, 3.39, have a lot of changes about mount. Please use the latest versions to test.

**Comment by Super-six-java** [comment]
May I ask if you have resolved this issue? Did you solve it by upgrading to versions 3.38 and 3.39？thank you so much
