### ISSUE TITLE
file truncate do not delete trunks oversize

### ISSUE THREAD

**Issue by neo-v** [seaweedfs/seaweedfs#3986]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/seaweedfs/seaweedfs/discussions

**Describe the bug**
os.truncate call setAttr to set file size to truncate size.
seaweed move trunk oversize to truncatedChunks but do nothing.

**System Setup**
version 30GB 3.14  linux amd64

**Expected behavior**
delete trunks oversize to free disk space.

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
Is this a report just by reading the source code?

The server side would delete the unused trunks.

**Comment by neo-v** [comment]
> Is this a report just by reading the source code?
> 
> The server side would delete the unused trunks.

IDE show warnings 
func (wfs *WFS) SetAttr:
var truncatedChunks []*filer_pb.FileChunk
this result of append is never used, except maybe in other appends (SA4010)go-staticcheck

**Comment by neo-v** [comment]
thanks, after a debug,i know how it works.
