### ISSUE TITLE
No Windows binaries since 3.28

### ISSUE THREAD

**Issue by AntonOks** [seaweedfs/seaweedfs#4014]
There are no Windows binaries build / available since [3.28](https://github.com/seaweedfs/seaweedfs/releases/tag/3.28)
I haven't seen such an announcement... so is this known / by intention?

**Comment by julor** [comment]
@chrislusf

**Comment by chrislusf** [comment]
Pending on https://github.com/mattn/go-ieproxy/issues/45

**Comment by julor** [comment]
How to build large disk version in windows OS？
`go build -tags "large_disk" -ldflags "-extldflags" -o weed_large_disk.exe weed.go`？

**Comment by chrislusf** [comment]
https://github.com/seaweedfs/seaweedfs/releases/tag/3.51
