### ISSUE TITLE
The performance of image resize operation is a bit poor

### ISSUE THREAD

**Issue by winwill2012** [seaweedfs/seaweedfs#4041]
**Describe the bug**
The performance of image resize operation is bit poor.

**System Setup**
- OS version：**CentOS release 6.10 (Final)**
- weed version：**version 30GB 1.88 b0567077v2 linux amd64**

**Expected behavior**
Better performance.

**Screenshots**
There is a noticeable spike in CPU usage：
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/9719716/206367043-3c7f2c35-689f-4dfd-b632-dd0b2b8f2dd4.png">
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/9719716/206367079-e41a16d5-c062-433c-b332-e0e790b76e13.png">
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/9719716/206367178-3d457f23-6ba2-4447-bcfe-661e220d05ff.png">

This is the screenshot of pprof svg：
<img width="1580" alt="image" src="https://user-images.githubusercontent.com/9719716/206366814-4a7f1c70-a622-4b63-aa4d-695c69fbf046.png">
see details here： [https://img.9xun.com/newstatic/25367,06700f1d765b8a12.svg](https://img.9xun.com/newstatic/25367,06700f1d765b8a12.svg)

Do you have performance test or any optimize plan?  thanks.

**Comment by chrislusf** [comment]
* this is an old feature.
* there are no other package with better performance.

**Comment by winwill2012** [comment]
oh，the feature is very helpful and we use is frequently.
