### ISSUE TITLE
S3 Gateway fails to start when installed via Helm

### ISSUE THREAD

**Issue by nadenf** [seaweedfs/seaweedfs#4074]
**Describe the bug**
Installing Seaweed on Kubernetes using Helm chart fails to start the S3 Gateway.
This is because the S3 gateway command is binding to localhost when it should be listening on all interfaces.

**System Setup**
Installing from latest master (at time of this issue) version of charts using a k3s cluster (v1.26.0+k3s1).

**Expected Behaviour**
S3 Gateway should start and be accessible from other pods either via Service or directly hitting the Pod.

**Comment by chrislusf** [comment]
do you plan to send a PR?
