### ISSUE TITLE
It is not possible to request a file via master if the volume is in a read-only state

### ISSUE THREAD

**Issue by kyklaed** [seaweedfs/seaweedfs#4088]
I have one master server and one volume server, I have moved one of the volumes to the read-only state. The server has lost information about volumes that are in the read-only state. The file can be requested only from the volume server.

Procedure of actions:
1) Uploading a file
2) I make the volume read-only
```
lock
volume.marknode 172.16.202.6:8080 -volumeId 3 -readonly
unlock
```
3) Trying to upload a file
```
wget 172.16.202.6:9333/3,013c6a774d
--2022-12-27 11:52:18-- http://172.16.202.6:9333/3,013c6a774d
Connecting to 172.16.202.6:9333... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-12-27 11:52:18 ERROR 404: Not Found.
```

**System Setup**
./weed master -ip=172.16.202.6
./weed -v=4 volume -index=leveldb  -pprof=true  -max=100 -mserver="172.16.202.6:9333" -port=8080 -dir=/storage
- ubuntu 22/04
- The problem was found on version 3.37, 3.36, 3.28, the latest version on which it works is 3.26
- version 3.27 have problem with set read-only from shell 
```
volume.mark -node 172.16.202.6:8080 -volumeId 3 -readonly
error: rpc error: code = Unknown desc = grpc VolumeMarkReadonly with master: 172.16.202.6:9333%!(EXTRA *errors.errorString=set volume 3 to read only on master: rpc error: code = Unimplemented desc = method VolumeMarkReadonly not implemented)
```

**Expected behavior**
I expect that the master will allow requesting files from volumes that have moved to the read-only state.

**Comment by chrislusf** [comment]
Thanks for the detailed issue report!
