### ISSUE TITLE
mount: can not  ensure ordered file handle lock and unlock by orderedMutex

### ISSUE THREAD

**Issue by lizhengui007** [seaweedfs/seaweedfs#4091]
**Describe the bug**
Seaweedfs  can not make IO in ordered  by file handle lock when I test.  The emaphore.NewWeighted is set to math.MaxInt64. The code is below in func newFileHandle(https://github.com/seaweedfs/seaweedfs/commit/22064c342585bddaa7ebdb21e39cac7db87826df)
	fh := &FileHandle{
		fh:      handleId,
		counter: 1,
		inode:   inode,
		wfs:     wfs,
		fh:           handleId,
		counter:      1,
		inode:        inode,
		wfs:          wfs,
		orderedMutex: semaphore.NewWeighted(int64(math.MaxInt64)),
	}

I think it is a bug. I think semaphore.NewWeighted should be set to 1. Only in this way can we guarantee to prevent concurrency.

**System Setup**

OS version is ubuntu18.04
weed version : 3.34 ( the fault also happened in latset version )

**Comment by chrislusf** [comment]
please add the reason why you think it is a bug.

**Comment by lizhengui007** [comment]
I think semaphore.NewWeighted should be set to 1.  Only in this way can we guarantee to prevent concurrency.

**Comment by lizhengui007** [comment]
> please add the reason why you think it is a bug.


The real purpose of orderedMutex is to prevent IO concurrency. If it is set to infinite, it is the same as no lock. How can it prevent concurrency? I think your original intention should be that this is 1.

**Comment by lizhengui007** [comment]
> 

@chrislusf

**Comment by chrislusf** [comment]
this is removed in https://github.com/seaweedfs/seaweedfs/pull/4089

**Comment by chrislusf** [comment]
the PR https://github.com/seaweedfs/seaweedfs/pull/4089 is merged.
