### ISSUE TITLE
Utilize Hardware Offload for EC

### ISSUE THREAD

**Issue by wzrdtales** [seaweedfs/seaweedfs#4106]
In almost all professional realms Mellanox (now nVidia) cards are in use, those come from the 4th gen with an EC offload, which may be used as well to accelerate the encoding (and on connectx-5 also decoding).

https://github.com/IcicleF/cx5-ec-offload/blob/master/test.cpp
http://www.shihaiyang.me/papers/triec-sc19.pdf
http://www.shihaiyang.me/papers/ecbench-bench18.pdf

**Comment by chrislusf** [comment]
This particular hardware requirement is not generic enough.

Mostly this EC is for online EC. SeaweedFS is using offline EC and is not latency sensitive.

**Comment by ddorian** [comment]
Someone who has that kind of hardware should sponsor or write the patch themself.

**Comment by wzrdtales** [comment]
> Someone who has that kind of hardware should sponsor or write the patch themself.

Cool down, no reason to become unfriendly, unless you want people to run away. This is purely a suggestion and not an order or something, before one even thinks about sponsoring something there must be a discussion about its sense and applicability of it.

> Mostly this EC is for online EC. SeaweedFS is using offline EC and is not latency sensitive.

Even for offline it could be beneficial, if you would have many TB to process in a run, but I get your argument.

> This particular hardware requirement is not generic enough.

You mean not common enough with not generic enough? If yes, then that is not true, no one uses Intel NICs anymore and mellanox is about the default unless you are getting custom SOCs, or you settled for now unfortunately dead horses like NFP (netronome). DPUs will become more common in the next few years though, so there will be even more hardware and more powerful offloads.

**Comment by ddorian** [comment]
> Cool down, no reason to become unfriendly, unless you want people to run away.

It was a short sentence, not a hostile one. But you're doing feature requests for things that you don't even need/use.

**Comment by wzrdtales** [comment]
> It was a short sentence, not a hostile one. But you're doing feature requests for things that you don't even need/use.

It is not your decision how something is received, it is only your decision how to write it in the first place. And again you stating assumptions you can't validate, but that is your opinion which is completely ok. Just to correct you, we made use of the same offload in another project already.

**Comment by chrislusf** [comment]
The EC encoding can be implemented in an external process, which can allow encoding in other languages or hardware.

**Comment by ddorian** [comment]
> And sorry for throwing ideas in, this didn't receive well on you. We wont anymore then.

Getting so butthurt from randoms on the internet, I'm amazed how you've survived. You can still use the software or ask for this feature regardless of my comment(s). I believe in you to get past this adversity.
