### ISSUE TITLE
[Question] How to implement the Identity and access management of fuse mount?

### ISSUE THREAD

**Issue by qiuyuyin** [seaweedfs/seaweedfs#4118]
**How to implement the Identity and access management of fuse mount?**
If we want to use the FUSE monut on the linux, we can input the _weed mount -filer=localhost:8888_  to access to the filer, but what can I do to implement the authentication, we don't want all the use can mount the filter, there is the an idea that using JWT to access but how to use it in the fuse mount cli?

**Comment by hxxxxh** [comment]
So how did you solve this problem? @qiuyuyin 

> **How to implement the Identity and access management of fuse mount?** If we want to use the FUSE monut on the linux, we can input the _weed mount -filer=localhost:8888_ to access to the filer, but what can I do to implement the authentication, we don't want all the use can mount the filter, there is the an idea that using JWT to access but how to use it in the fuse mount cli?
