### ISSUE TITLE
The bucket naming rules conflict when docking with minio

### ISSUE THREAD

**Issue by TDCBQ** [seaweedfs/seaweedfs#4143]
When uploading buckets through java minio, minio prompts me that the buckets to be transferred do not conform to the naming rules of S3 buckets

My bucket name is 10000_ test

However, it cannot be used in the S3 naming specification_ To name it. aws-cli passed the name, but the seaweedfs server did not verify the bucket name

So I suggest checking the incoming bucket name on the seeweedfs server to ensure that the system has stronger compatibility

**Comment by chrislusf** [comment]
do you know the doc for s3 bucket naming convention?

**Comment by TDCBQ** [comment]
Of course, is there anything wrong with my expression? Can you point out the mistakes

**Comment by chrislusf** [comment]
I do not see any user mistake here. Just want to know the "official" s3 bucket naming convention.

**Comment by TDCBQ** [comment]
The Amazon S3 bucket that you use to store CloudTrail log files must have a name that conforms with naming requirements for non-US Standard regions. Amazon S3 defines a bucket name as a series of one or more labels, separated by periods, that adhere to the following rules:

The bucket name can be between 3 and 63 characters long, and can contain only lower-case characters, numbers, periods, and dashes.

Each label in the bucket name must start with a lowercase letter or number.

The bucket name cannot contain underscores, end with a dash, have consecutive periods, or use dashes adjacent to periods.

The bucket name cannot be formatted as an IP address (198.51.100.24).


information sources:https://docs.amazonaws.cn/en_us/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html

**Comment by lyang24** [comment]
working on a pr to fix this issue https://github.com/seaweedfs/seaweedfs/pull/4189/files
