### ISSUE TITLE
Two questions about IAM

### ISSUE THREAD

**Issue by TDCBQ** [seaweedfs/seaweedfs#4144]
1)There is a problem with the deletion algorithm
![image](https://user-images.githubusercontent.com/37407560/213111124-219bfd8e-70e8-421c-90a6-1010f98e06e6.png)
![image](https://user-images.githubusercontent.com/37407560/213111692-1e145fb6-a346-4cee-95d2-8bb799ad1f89.png)
This should be changed
s3cfg.Identities[idx].Credentials[:i],
s3cfg.Identities[idx].Credentials[i+1:]...,
2)The last user added a duplicate Accesskey problem
![image](https://user-images.githubusercontent.com/37407560/213112457-07706383-8c6e-43f1-b8ee-072dd191a5ac.png)
There is a problem when the code judges that the user parameters are repeated

**Comment by chrislusf** [comment]
PR is welcome!

**Comment by TDCBQ** [comment]
Okay, sure next time
