### ISSUE TITLE
No more writable volumes

### ISSUE THREAD

**Issue by noinhotnn** [seaweedfs/seaweedfs#4145]
Version 8000G 3.29 Windows
Replicate : 100
Server Volume1&2: Free 40% DISK ~ 1.7T (4TB Total)
Start server with -max=0 and volumeSizeLimitMB=500
Try to run : vacuum  with garbageThreshold=0
master.toml
```
scripts = """
  lock  
  volume.deleteEmpty -quietFor=24h -force
  volume.balance -force
  volume.fix.replication
  s3.clean.uploads -timeAgo=24h
  unlock
"""
```
sleep_minutes = 180          # sleep minutes between each script execution

Volumes created: 8170
Seem it maximum volumes but many volumes empty or not full. Is there problem with reclaim disk space after deletion or update!?

**Comment by chrislusf** [comment]
what is output of "volume.list" in "weed shell"?

**Comment by noinhotnn** [comment]
Weed shell
![image](https://user-images.githubusercontent.com/13940206/213368050-448ac9ec-2b79-4422-adba-4b16317767f7.png)
Filer display error
![image](https://user-images.githubusercontent.com/13940206/213368407-a9cf8dd3-c14c-409b-be1d-786fece395e5.png)

**Comment by noinhotnn** [comment]
Volume 1&2
![image](https://user-images.githubusercontent.com/13940206/213369393-faf46d9c-26dd-4c90-a5a6-e01e4d57a6e6.png)
Master
![image](https://user-images.githubusercontent.com/13940206/213369603-42a71cc4-0595-4a5d-9733-a2564b1cc46a.png)

**Comment by chrislusf** [comment]
can you share the output of "volume.list" in "weed shell" as text?

**Comment by noinhotnn** [comment]
@chrislusf 
[Log.txt](https://github.com/seaweedfs/seaweedfs/files/10454126/Log.txt)

**Comment by chrislusf** [comment]
it looks ok. Does the master restart help? What are the logs in master and volume servers?

**Comment by chrislusf** [comment]
btw: better use 3 volume servers, so that you can tolerate one volume server down and still can read and write.

**Comment by noinhotnn** [comment]
I try restart master first time but not work
Here volume log
![image](https://user-images.githubusercontent.com/13940206/213375789-d0f26ca6-cb4d-41b4-89b4-882193578ef5.png)

**Comment by chrislusf** [comment]
* Not a good idea to run it on windows. 
* The volume server is busy compacting. Runs fine.

**Comment by noinhotnn** [comment]
Thanks i add more volume and wait master complete

**Comment by chrislusf** [comment]
what is the output of "Check Writable Volume Status"?
https://github.com/seaweedfs/seaweedfs/wiki/Master-Server-API#check-writable-volume-status

**Comment by noinhotnn** [comment]
Master compact completed but nothing change
"Check Writable Volume Status"
[Log01.txt](https://github.com/seaweedfs/seaweedfs/files/10455010/Log01.txt)

**Comment by noinhotnn** [comment]
With "/vol/status?pretty=y"
[Log02.txt](https://github.com/seaweedfs/seaweedfs/files/10455032/Log02.txt)

**Comment by noinhotnn** [comment]
I think maybe the problem with old collection
Collection 2022 and 2021 stopped receiving data and data size of each volumes never achieved 500MB (i find update date of file .dat not change)
![image](https://user-images.githubusercontent.com/13940206/214994806-cf64b6f3-9df4-4ea8-baa7-a19c0cf398a2.png)
Should I redefine fixed collections?

**Comment by noinhotnn** [comment]
I fixed by add collection parameter when upload data.
