### ISSUE TITLE
[Question]Replication Level and Uploads

### ISSUE THREAD

**Issue by jerebear12** [seaweedfs/seaweedfs#4147]
## Question

When replication is configured as 020, and there are only 2 Volume Servers available, does Seaweed refuse uploads on purpose?

## System Setup

- We are testing replication on a 5 Master, 3 Filer, 4 Volume Server, ~9 Volumes setup
- SeaweedFS version is 3.40
- Programs are started as services inside VMs on Windows machines

## Current Behavior

When we have 4 Volume Servers running with replication level 020, and we shut down 2 of the Volume Servers to simulate a failure, we are unable to upload files through the Filer. We see a 500 Internal Server Error status code response from POST request to the Filer. 

The logs from the weed.INFO file in the Filer look like:
![filer-003-log](https://user-images.githubusercontent.com/72420925/213576992-50d6ee1f-0f83-46b3-aa63-4016817a5fd7.png)

## Additional Context

We suspect the answer is yes but ***we want to confirm that the issue is with our replication level***(or lack of the level being complete in this test).

Feel free to ask for any more info!

**Comment by chrislusf** [comment]
Yes!

**Comment by jerebear12** [comment]
Thank you!
