### ISSUE TITLE
Add Zstd compression support

### ISSUE THREAD

**Issue by zamazan4ik** [seaweedfs/seaweedfs#4149]
**Describe the bug**
According to the documentation, Gzip is the only algorithm for automatic compression. Zstd is a quite popular compression algorithm nowadays since it has a good CPU/compression efficiency ratio.

**Expected behavior**
Zstd will be allowed to use as a compression algorithm.

**Comment by chrislusf** [comment]
this has been attempted before. It's possible. But need some storage format changes.

**Comment by aierui** [comment]
Hi @chrislusf  What are the considerations for modifying the format?

**Comment by chrislusf** [comment]
Each needle has one bit to indicate it is compressed, by gzip. To support more compression format, it needs to have more bits.

**Comment by kyocooro** [comment]
Can you show me where to edit to create a custom version of seaweedfs that uses zstd instead of gzip?

Thank you

**Comment by yfdyh000** [comment]
> Can you show me where to edit to create a custom version of seaweedfs that uses zstd instead of gzip?
> 
> Thank you

https://github.com/seaweedfs/seaweedfs/commit/92f906b6fcce2ef72661bb825075e2826b8f3aa1

**Comment by kmlebedev** [comment]
@chrislusf You can try changing the library for example to https://github.com/klauspost/compress

**Comment by charlesmelby** [comment]
Why not make the compression format configurable?
E.g. MongoDB/WiredTiger allows journaling and block compression to be configured separately but globally
https://www.mongodb.com/docs/manual/core/wiredtiger/

**Comment by filiphanes** [comment]
> Each needle has one bit to indicate it is compressed, by gzip. To support more compression format, it needs to have more bits.

what if that 1 bit meant only that it is compressed by configured method, and specific method would be in config or maybe volume header if it is extensible
