### ISSUE TITLE
Mount is not supported on freebsd amd64

### ISSUE THREAD

**Issue by jSML4ThWwBID69YC** [seaweedfs/seaweedfs#4156]
**Describe the bug**
As the title says. Trying to run ```weed mount``` on FreeBSD fails. 

**System Setup**
OS: Freebsd 13.1

Tested with seaweedfs-3.37_1 from the ports tree. Also tested v3.4.0 from https://github.com/seaweedfs/seaweedfs/releases/tag/3.40. The same not supported message in both cases. 

**Expected behavior**
Expected ```weed mount``` to work. 

**Additional context**
I can't find any documentation that states that ```weed mount``` is unsupported. The only thing I've seen is this, https://github.com/seaweedfs/seaweedfs/issues/1769#issuecomment-783359358, that indicates it is supported. 

So is ```weed mount``` supported on FreeBSD? If not, can it be? The objective is to mount SeaweedFS over FUSEFS.

**Comment by chrislusf** [comment]
it is supported

**Comment by jSML4ThWwBID69YC** [comment]
Thank you for confirming. I'll see if I can figure out why it's saying it's not. Any ideas welcome.

**Comment by chrislusf** [comment]
please report exact errors following the issue template.
