### ISSUE TITLE
[Question]Can filer.sync support clusters with multiple filers?

### ISSUE THREAD

**Issue by jerebear12** [seaweedfs/seaweedfs#4159]
### Describe the question

I see that filer.sync allows cross cluster replication. Can a single cluster that contains say, two Filers, replicate to a cluster containing two Filers? Following the example format in [the documentation](https://github.com/seaweedfs/seaweedfs/wiki/Filer-Active-Active-cross-cluster-continuous-synchronization) that would look like this in my mind:

```
cluster1  <-- filer.sync --> cluster2 
    |                               |_______
    +- filer1 <-- filer.sync --> filer2     +- filer1 <-- filer.sync --> filer2 
```

Would this be possible to achieve by simply having the metadata store that the two Filers in a cluster talk to be a single database instance like Cassandra(in our case ScyllaDB)?

### Desired behavior

Two clusters with two filers each in Active-Passive or Active-Active configuration. Both clusters would sit behind a single reverse proxy that would identify two Filers as the primary cluster and two as the secondary or backup cluster.

### Additional context
With our use case, we are looking to have something like two separate data centers each with identical data. We are interested in having a primary data center and a back up. 

I'm open to hearing any whys or why nots on this potential set up!

**Comment by jerebear12** [comment]
If we have two clusters, cluster a and cluster b, each with three Filers, would we have to run `filer.sync` between each filer?

Like:
```
filer1a <-- filer.sync --> filer1b
filer2a <-- filer.sync --> filer2b
filer3a <-- filer.sync --> filer3b
```

I understand this may not be possible because each Filer in this case is not representing it's own cluster.

**Comment by chrislusf** [comment]
`filer1a <-- filer.sync --> filer1b` this should be enough. If not, it is a bug.

**Comment by jerebear12** [comment]
Ok! We may try this. Thanks.
