### ISSUE TITLE
[Question]Query about S3 file-level permissions

### ISSUE THREAD

**Issue by TDCBQ** [seaweedfs/seaweedfs#4160]
System Setup
seaweed version is 3.39

Expected behavior
 I want to ask, if user A wants to access a file in user B's bucket, can user B only open the permissions of this file to user A instead of the entire bucket
Is the permission division of s3 objects differentiated to the file level
Can you tell me how to do it

**Comment by chrislusf** [comment]
there are no file level permission control in s3 APIs
