### ISSUE TITLE
There is a problem with S3 MultipartUpload, only generated_ COPYING_ file

### ISSUE THREAD

**Issue by TDCBQ** [seaweedfs/seaweedfs#4170]
**Describe the bug**
There is a problem with S3 MultipartUpload, only generated_ COPYING_ file
For example, I use the S3 interface to MultipartUpload  a 200M file in blocks, it will only generate_ COPYING_ File, no real target file will be generated，and then it faild

**System Setup**
seaweed version is 3.39

**Expected behavior**
Can MultipartUpload files normally

**Comment by TDCBQ** [comment]
MultipartUpload files using the S3a.fs dependency package will fail. I will not fail to upload files through minio

**Comment by TDCBQ** [comment]
supplement：
![image](https://user-images.githubusercontent.com/37407560/215919566-e88d569d-74b8-483c-b878-3bef547e1e19.png)
![image](https://user-images.githubusercontent.com/37407560/215919736-d9a8ec59-342d-4941-801d-c2452f76fa7b.png)

**Comment by chrislusf** [comment]
Are there multiple filers? Need to know how everything is configured.

**Comment by TDCBQ** [comment]
I only started a filer
weed env
![image](https://user-images.githubusercontent.com/37407560/215940197-1501a77d-eee8-45f1-afd2-67419b2debff.png)

hadoop env
![image](https://user-images.githubusercontent.com/37407560/215940172-10c1080e-3063-4340-ab8b-0f1fab37615c.png)

hadoop core-site.xml
![image](https://user-images.githubusercontent.com/37407560/215941488-6fca1ea9-65f0-401b-b141-72aa712a4236.png)

<configuration>
          <property>
                <name>fs.s3a.access.key</name>
                <value>123456</value>
          </property>
                <property>
                <name>fs.s3a.secret.key</name>
                <value>123455</value>
          </property>
                <property>
                <name>fs.s3a.endpoint</name>
                <value>http://192.168.188.140:8333</value>
          </property>
                <property>
                <name>fs.s3a.impl</name>
                <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
          </property>
                <property>
                <name>fs.s3a.connection.ssl.enabled</name>
                <value>false</value>
          </property>
                <property>
                <name>fs.s3a.path.style.access</name>
                <value>true</value>
          </property>
                <property>
                <name>fs.defaultFS</name>
                <value>s3a://test/</value>
          </property>
</configuration>

--------------------------------------------
Reoccurrence
shell command

hdfs dfs -put /home/jdk-8u202-windows-x64.exe /

The file should be larger than 150M, and the problem will be easier to display

**Comment by TDCBQ** [comment]
```
fs.s3a.multipart.threshold
```
This parameter determines the size of the partition
```
<property>
  <name>fs.s3a.multipart.threshold</name>
  <value>128MB</value>
  </description>
</property>
```
This is his default value
When hdfs uploads files, files that exceed the partition size will generate different files according to the partition size and can be accessed normally
The file MultipartUpload to seaweedfs through hdfs cannot be renamed because of this parameter
Is there any lack of response processing logic? Because I didn't find any problems when uploading to minio with the same parameters

**Comment by chrislusf** [comment]
how to configure hdfs with s3 after downloading the hadoop-3.3.3? Please provide detailed commands.

```
app/hadoop-3.3.3 ()  > bin/hdfs dfs -ls
2023-02-01 00:03:55,467 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
-ls: Fatal internal error
java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:288)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:524)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:342)
	at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:252)
	at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:235)
	at org.apache.hadoop.fs.shell.FsCommand.processRawArguments(FsCommand.java:105)
	at org.apache.hadoop.fs.shell.Command.run(Command.java:179)
	at org.apache.hadoop.fs.FsShell.run(FsShell.java:327)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:81)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:95)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:390)
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
	... 18 more
```

**Comment by TDCBQ** [comment]
## Download java1.8
yum -y install java-1.8.0-openjdk java-1.8.0-openjdk-devel
## Download Hadoop And Decompress
```
wget https://mirrors.tuna.tsinghua.edu.cn/apache/hadoop/common/hadoop-3.3.3/hadoop-3.3.3.tar.gz

tar -xzvf hadoop-3.3.3.tar.gz -C /weedfs
```
## Configure environment variables
```
echo "export JAVA_HOME=$(dirname $(dirname $(readlink $(readlink $(which javac)))))" >> /etc/profile
echo "export PATH=\$PATH:\$JAVA_HOME/bin" >> /etc/profile
echo "export CLASSPATH=.:\$JAVA_HOME/jre/lib:\$JAVA_HOME/lib:\$JAVA_HOME/lib/tools.jar" >> /etc/profile
source /etc/profile
echo 'export PATH+=":/weedfs/hadoop-3.3.3/bin:"' >> ~/.bashrc
echo 'export HADOOP_CLIENT_OPTS="-Xmx4g"' >> ~/.bashrc
source ~/.bashrc
```

## Configure dependent packages
```
ln -s $HADOOP_HOME/share/hadoop/tools/lib/*aws* $HADOOP_HOME/share/hadoop/common/lib/
```
## Modify hadoop's core-site.xml file

vim /weedfs/hadoop-3.3.3/etc/hadoop/core-site.xml

```
<configuration>
          <property>
                <name>fs.s3a.access.key</name>
                <value>123456</value>
          </property>
                <property>
                <name>fs.s3a.secret.key</name>
                <value>123455</value>
          </property>
                <property>
                <name>fs.s3a.endpoint</name>
                <value>http://192.168.188.140:8333</value>
          </property>
                <property>
                <name>fs.s3a.impl</name>
                <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
          </property>
                <property>
                <name>fs.s3a.connection.ssl.enabled</name>
                <value>false</value>
          </property>
                <property>
                <name>fs.s3a.path.style.access</name>
                <value>true</value>
          </property>
                <property>
                <name>fs.defaultFS</name>
                <value>s3a://test/</value>
          </property>
</configuration>
```

## Command
```
hdfs dfs -ls /
```
This is my configuration. You can refer to it

**Comment by chrislusf** [comment]
Thanks for all the details! I can reproduce it. 

Please confirm the fix.

**Comment by TDCBQ** [comment]
Yes, this problem has been fixed
