### ISSUE TITLE
[shell] Can't upload to the S3 cloud mount, multiple errors on upload

### ISSUE THREAD

**Issue by egguy** [seaweedfs/seaweedfs#4180]
**Describe the bug**
After the closing of the bug #4175, I updated my installation to restart the filter.remote.sync command.

When using the command `weed filer.remote.sync -dir=/media -filer localhost:8889` the filer seems to start synchronisation, but after a few seconds, a lot of transport error appear, and nothing has been written to the remote storage.

**System Setup**
The system consists of 2 VM:

    1 weed master on the server1
    2 weed volume on server1 and server 2
    2 filer on server 1 and 2
        The filers use leveldb2
        the filers are replicated
    Use of the Cloud drive functionality on /media, to synchronise files to an S3 storage
        The remote storage is a S3 store by OVH

The 2 servers run on Ubuntu 20.04, with the same patch level, updated 1 week ago

weed version: `version 30GB 3.42 8821d6b1619b7a55b515a98391193297e77cbe52 linux amd64`

The filer is configured from the command line without a file:
weed filer -port 8889 -ip.bind 0.0.0.0 -ip X.X.X.X -s3  -master X.X.X.X:9333 -dataCenter=XXXX -rack=XXX -metricsPort=9328

**Expected behavior**
When using `weed filer.remote.sync -dir=/media -filer localhost:8889` the filer is expected to write back the files stored in the filer's dir to the remote storage.

**Additional context**

I was running the sync process continuously in a tmux term. Had to cut it for two days, when I restarted it, it started to have problem.

I tried to run `remote.meta.sync` before re-running the command, but this didn't change the outcome.

When using rclone to list the created file on the remote storage, the files don't appear, but the directory to host the file is created. Using rclone to copy the file manually to the destination is successful, and the file can be read back.

This is the output:
```
I0206 12:01:16.748098 filer_remote_sync_dir.go:193 create ovhMedia/media-prod/ged/f7ba/7a16/CI_1-KBIVC9_20230131091836485.0dcd.jpg
I0206 12:01:16.788175 filer_remote_sync_dir.go:193 create ovhMedia/media-prod/ged/67f7/c306/photoLIL23015716_001_1.0f94.jpg
I0206 12:01:16.788417 filer_remote_sync_dir.go:193 create ovhMedia/media-prod/ged/f59b/3d23/CI_1-KKJ3PU_20230131104737592.c26a.jpg
I0206 12:01:16.802860 filer_remote_sync_dir.go:193 create ovhMedia/media-prod/ged/d5af/a577/CI_1-KKIWCN_20230131143327110.c528.jpg
I0206 12:01:16.836960 filer_remote_sync_dir.go:193 create ovhMedia/media-prod/ged/ebeb/3e20/photoLIL22053406_001_3.f769.jpg
I0206 12:01:16.855845 filer_remote_sync_dir.go:193 create ovhMedia/media-prod/ged/5f82/ec9b/CI_1-KL1ZL2_20230201100140538.52e6.jpg
^CI0206 12:01:16.859267 filer_remote_sync_dir.go:193 create ovhMedia/media-prod/ged/3c76/5140/photoCAM23005511_001_1.39a0.jpg
I0206 12:01:16.859670 filer_remote_sync_dir.go:193 create ovhMedia/media-prod/ged/0ff2/87c3/CI_1-KKIWCN_20230131143344915.5233.jpg
I0206 12:01:16.860099 retry.go:25 retry writeFile: err: upload to ovhMedia/media-prod/ged/b57d/6447/photoBCZ23016369_001_1.543c.jpg: RequestError: send request failed
caused by: Put "$OVH_CLOUD/b57d/6447/photoBCZ23016369_001_1.543c.jpg": net/http: HTTP/1.x transport connection broken: http: ContentLength=20809 with Body length 0
I0206 12:01:16.860335 retry.go:25 retry writeFile: err: upload to ovhMedia/media-prod/ged/fef8/3530/CI_1-KKUA2C_20230201135816116.af45.jpg: RequestError: send request failed
caused by: Put "$OVH_CLOUD/fef8/3530/CI_1-KKUA2C_20230201135816116.af45.jpg": net/http: HTTP/1.x transport connection broken: http: ContentLength=64284 with Body length 0
I0206 12:01:16.862122 retry.go:25 retry writeFile: err: upload to ovhMedia/media-prod/ged/7c5d/a902/photoCAM22074219_001_3.bbf7.jpg: RequestError: send request failed
caused by: Put "$OVH_CLOUD/7c5d/a902/photoCAM22074219_001_3.bbf7.jpg": net/http: HTTP/1.x transport connection broken: http: ContentLength=28119 with Body length 0
I0206 12:01:16.862994 filer_remote_sync_dir.go:193 create ovhMedia/media-prod/ged/94fe/2584/photoDIU21005900_001_1.71e8.jpg
```

Thanks for this great piece of software.

**Comment by egguy** [comment]
After a bit more testing, I discovered I had problems with rclone as well. This seems to happen when rclone upload multiple files in batch.

The S3 provider is OVH.

ex: 
```
2023-02-10 00:30:24 ERROR : 00e7/6d09/001.1aea: Failed to copy: s3 upload: 400 Bad Request: <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>XAmzContentSHA256Mismatch</Code><Message>The provided 'x-amz-content-sha256' header does not match what was computed.</Message><RequestId>tx07c6751b87c4472190780-0063e58210</RequestId><ClientComputedContentSha256></ClientComputedContentSha256><S3ComputedContentSha256>&lt;html&gt;&lt;h1&gt;Unprocessable Entity&lt;/h1&gt;&lt;p&gt;Unable to process the contained instructions&lt;/p&gt;&lt;/html&gt;</S3ComputedContentSha256></Error>
```

**Comment by chrislusf** [comment]
should be related to this https://github.com/seaweedfs/seaweedfs/blob/master/weed/remote_storage/s3/wasabi.go#L58

debugging this is tricky though.

**Comment by chrislusf** [comment]
try to turn on this value `s3.v4_signature` when configuring the remote storage. not so sure.

**Comment by egguy** [comment]
Sorry, I forgot to add in the debug, I've toggled this flag, but the result is the same.

**Comment by chrislusf** [comment]
added a fix https://github.com/seaweedfs/seaweedfs/commit/545d5d0cc39956b5bec0df3ee62e57af4d9c22c6 for a similar issue. Please try it.

**Comment by egguy** [comment]
Thx for the fix.
After testing it (compiled the weed binary on my machine, then upload, and run the sync from the new binary, with latest version running for filer/volume/master), the error messages have disappeared, but it doesn't seems to upload.
E.g.
```
# ~/weed filer.remote.sync -dir=/media -filer localhost:8889 2>&1 |grep media-prod/ged/a3f6/cdb0/photoMTU23001360_001_10.9b27.jpg
I0220 06:40:56.771449 filer_remote_sync_dir.go:171 delete ovhMedia/media-prod/ged/a3f6/cdb0/photoMTU23001360_001_10.9b27.jpg
I0220 06:40:56.874020 filer_remote_sync_dir.go:193 create ovhMedia/media-prod/ged/a3f6/cdb0/photoMTU23001360_001_10.9b27.jpg
# rclone lsd  ovh-s3:media-prod/ged/a3f6/cdb0/
# empty result
```

Tried multiple times, it tries to copy it again.

With rclone lsd, i've found the `media-prod/ged/a3f6` directory is created with inside, directory are created today, but not `cdb0`.

**Comment by chrislusf** [comment]
Thanks for the update!
