### ISSUE TITLE
About the problem that the doEcEncode execution throws panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by liangyihan** [seaweedfs/seaweedfs#4193]
**Describe the bug**

After running for a period of time, the weed master will stop running. Looking at the log, we found that an exception of panic: runtime error: index out of range [0] with length 0 was thrown.As shown below:
![image](https://user-images.githubusercontent.com/45417436/217765915-d2a460db-b82e-4cbe-aff5-6be31efdccde.png)
Print source code to view errors:
func doEcEncode(commandEnv *CommandEnv, collection string, vid needle.VolumeId, parallelCopy bool) (err error) {
	// find volume location
	locations, found := commandEnv.MasterClient.GetLocations(uint32(vid))
	fmt.Printf("11111111111111111111111 found ec %d shards on %v\n", vid, locations)
	fmt.Println()
	fmt.Printf("22222222222 found %v ", found)
	fmt.Println()
	fmt.Printf("333333333 location[0]= %v\n", locations[0])
	if !found {
		fmt.Printf("55555555 volume %d not found", vid)
		fmt.Println()
		return fmt.Errorf("volume %d not found", vid)
	}
	// fmt.Printf("found ec %d shards on %v\n", vid, locations)

	// mark the volume as readonly
	err = markVolumeReplicasWritable(commandEnv.option.GrpcDialOption, vid, locations, false)
	if err != nil {
		return fmt.Errorf("mark volume %d as readonly on %s: %v", vid, locations[0].Url, err)
	}

	// generate ec shards
	err = generateEcShards(commandEnv.option.GrpcDialOption, vid, collection, locations[0].ServerAddress())
	if err != nil {
		return fmt.Errorf("generate ec shards for volume %d on %s: %v", vid, locations[0].Url, err)
	}

	// balance the ec shards to current cluster
	err = spreadEcShards(commandEnv, vid, collection, locations, parallelCopy)
	if err != nil {
		return fmt.Errorf("spread ec shards for volume %d from %s: %v", vid, locations[0].Url, err)
	}

	return nil
}
When the result locations=[], found=false, the panic: runtime error: index out of range [0] with length 0 exception is thrown, and then the master stops working.As shown below:
![image](https://user-images.githubusercontent.com/45417436/217767453-08526949-c9f2-4600-9edd-575022ffcd11.png)

and  "volume %d not found" this error has never been returned, so I infer that when locations=[], find=false, whether we can consider
len(locations) in if !found && len(locations) > 0 {} is removed,To fix the problem.

**System Setup**
- OS version centos7
- output of `weed version`  seaweedfs 3.15

**Comment by chrislusf** [comment]
Thanks for the analysis! Next time you are welcome to send a PR directly.
