### ISSUE TITLE
[filer.remote.sync] Transport connection broken error

### ISSUE THREAD

**Issue by aronneagu** [seaweedfs/seaweedfs#4194]
**Describe the bug**
Running `filer.remote.sync` returns an error and does not copy file to the remote (Azure Storage)

**System Setup**
```
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```
```
> weed version
version 30GB 3.42 8821d6b1619b7a55b515a98391193297e77cbe52 linux amd64
```
```
# Weed server
/usr/local/bin/weed server -volume.max=16 -s3
# Adding and mounting the remote
echo "remote.configure -name=azure -type=azure -azure.account_name=seaweedsa -azure.account_key=rwexf8T...t4ss9MQ==" | weed shell
echo "remote.mount -remote=azure/seaweed -dir=/buckets/seaweed" | weed shell
# Weed filer.remote.sync, in a separate cmd tab
/usr/local/bin/weed filer.remote.sync -dir=/buckets/seaweed
```

**Expected behavior**
Running a simple weed server, with a remote pointing to Azure Storage, and running a filer.remote.sync.
Uploading a file to Filer UI (http://localhost:8888/buckets/seaweed) uploads the filer to Filer, but its not being copied to remote

**Screenshots**
filer.remote.sync logs:
```
Put "https://seaweedsa.blob.core.windows.net/seaweed/13-53.36204a77?timeout=61": net/http: HTTP/1.x transport connection broken: http: ContentLength=704 with Body length 0
I0209 10:22:04.822710 filer_remote_sync_dir.go:193 create azure/seaweed/13-53.36204a77
I0209 10:22:51.855969 retry.go:25 retry writeFile: err: azure upload to seaweed/13-53.36204a77: -> github.com/Azure/azure-pipeline-go/pipeline.NewError, /go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157
HTTP request failed
```

Referencing a similar ticket here https://github.com/seaweedfs/seaweedfs/issues/4180

**Comment by chrislusf** [comment]
Does this happen for all files going to Azure or just one of them?

**Comment by chrislusf** [comment]
I do not have any Azure account to test with. I think the problem is around https://github.com/seaweedfs/seaweedfs/blob/master/weed/remote_storage/azure/azure_highlevel.go#L44
or 
https://github.com/seaweedfs/seaweedfs/blob/master/weed/remote_storage/azure/azure_highlevel.go#L80

Most likely the line 44.

**Comment by aronneagu** [comment]
Hi Chris,

I've sent you the secret key for the `seaweedsa` storage account via Slack a while back (think December). Can send it again if needed.
So far I've seen the failure with both files that I tried. It's not an intermittent issue.

**Comment by aronneagu** [comment]
Is there anything else I can provide to make it easier to reproduce?
