### ISSUE TITLE
Help to use seaweedfs instead of minIo

### ISSUE THREAD

**Issue by Chanukya001** [seaweedfs/seaweedfs#4212]
I want to know if it's possible to use the seaweedfs with AWS SDK in Java.
basically want to use S3 with seaweedfs instead of MinIO and want to use the existing code for it. So I would like to know if the seaweedfs can work with AWS SDK for JAVA.
nodejs with seaweedfs s3 wouldn't help in our use case. 
Please let me know asap.

**Comment by chrislusf** [comment]
It should. Please create a reproducible github issue if not working.
