### ISSUE TITLE
filer cluster data mismatch

### ISSUE THREAD

**Issue by forever765** [seaweedfs/seaweedfs#4222]
**Describe the bug**
- SeaweedFS architecture: `5 x master, 6 x volume server, 5 x filer`. Haproxy uses `http` mode and `leastconn` balancing algorithm to provide load balancing for filer.
- When high concurrent writing via s3 api (approximately equal to 10k connections), the data of multiple filers is inconsistent.
- For example, write 100 million files to the same bucket, filer A owns 90 million files, and filer B owns 95 million files. In short, the list of files owned by multiple filers is inconsistent.
- Example again, For another example, the s3 path of a file is `s3://aaa/bbb`, 
When I use the `fs.ls /buckets/aaa/bbb` command to view this file, fs returns that the file exists, But when I download the file using s3 client, filer returns:
```
NoSuchKey: The specified key does not exist. status code: 404, request id: 1676785072987715946, host id:
```

Q1: Is there any way to repair the filer meta database? Such as scan all files from volume server, regenerate filer meta data?
Q2: If I use an external database such as rocksdb or redis as the filer meta database, can data inconsistency be avoided?
Here is another question similar to mine: https://github.com/seaweedfs/seaweedfs/issues/4115#issuecomment-1397216212

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
```
weed master -options=/etc/seaweedfs/master.option

peers=172.16.84.105:9333,172.16.84.106:9333,172.16.84.107:9333,172.16.84.108:9333,172.16.84.109:9333
defaultReplication=001
mdir=/home/seaweedfs/meta/
volumePreallocate
volumeSizeLimitMB=80000
v=2
logdir=/var/log/seaweedfs/master/
metricsPort=19091
```
```
master.toml
[master.maintenance]
scripts = """
  lock
  volume.balance -force
  volume.fix.replication
  s3.clean.uploads -timeAgo=24h
  unlock
"""
sleep_minutes = 720

[master.volume_growth]
copy_1 = 7
copy_2 = 12
copy_3 = 12
copy_other = 1
```

```
weed volume -options=/etc/seaweedfs/volume.option

max=0
concurrentUploadLimitMB=2048
dataCenter=aaa
rack=bbb
index=memory
fileSizeLimitMB=2048
dir=/cloud/data3/seaweedfs/,/cloud/data4/seaweedfs/,/cloud/data5/seaweedfs/,/cloud/data6/seaweedfs/,/cloud/data7/seaweedfs/,/cloud/data8/seaweedfs/,/cloud/data9/seaweedfs/,/cloud/data10/seaweedfs/
mserver=172.16.84.105:9333,172.16.84.106:9333,172.16.84.107:9333,172.16.84.108:9333,172.16.84.109:9333
v=2
logdir=/var/log/seaweedfs/volume/
metricsPort=19092
```

```
weed filer -options=/etc/seaweedfs/filer.option

s3
s3.config=/etc/seaweedfs/s3-account.conf
ip.bind=0.0.0.0
ui.deleteDir=false
master=172.16.84.105:9333,172.16.84.106:9333,172.16.84.107:9333,172.16.84.108:9333,172.16.84.109:9333
v=8
logdir=/var/log/seaweedfs/filer/
metricsPort=19093
```

- OS version
`Centos7.9, kernel 5.4.204-1.el7`
- output of `weed version`
`8000GB 3.42 8821d6b1619b7a55b515a98391193297e77cbe52 linux amd64`

**Expected behavior**

**Screenshots**

**Additional context**
`volume.fix.replication` command returns nothing

**Comment by chrislusf** [comment]
How is using sticky session?

**Comment by forever765** [comment]
@chrislusf I think haproxy can do sticky session, but since I have written billions of files to SeaweedFS, is there a way to remedy this?

**Comment by chrislusf** [comment]
you can export the metadata from one filer and import to the other one.

**Comment by forever765** [comment]
metadata restore too slow, I rebuilt the cluster using cassandra as metabase, it works fine, thank you for your reply.
