### ISSUE TITLE
Obsolete entry in filer when a collection is deleted

### ISSUE THREAD

**Issue by ericlingit** [seaweedfs/seaweedfs#4224]
**Describe the bug**

When a collection is deleted, the deletion isn't noticed by the filer. As a result, filer thinks those files still exist.

**How to reproduce the bug**

1. System setup:
    - `version 30GB 3.42 8821d6b1619b7a55b515a98391193297e77cbe52 linux amd64`
    ```
    mkdir 3 4 5
    ./weed master -volumeSizeLimitMB=1 &
    ./weed volume -dir=./3 -port=8083 -max=0 &
    ./weed volume -dir=./4 -port=8084 -max=0 &
    ./weed volume -dir=./5 -port=8085 -max=0 &
    ./weed filer &
    ```
1. Upload a file `testfile.txt` to the filer to directory `/aaa`, and specify a `collection` path parameter:
    ```
    curl -F file=@testfile.txt "http://localhost:8888/aaa/testfile.txt?collection=mycollection"
    ```
1. Delete the collection:
    ```
    curl "http://localhost:9333/col/delete?collection=mycollection"
    ```
1. Launch a web browser and navigate to http://localhost:8888/aaa.

**Expected behavior**
- An empty directory in http://localhost:8888/aaa.

**Actual behavior**
- `testfile.txt` shows up in http://localhost:8888/aaa.
- Error message when attempting to download it: `operation LookupFileId 882,a72505bebab305 failed, err: urls not found`.

**Additional context**
- I loaded the above setup with around 6 million 1KB files under the directory `/aaa` (via the filer). I then called the Filer's delete API (`curl -X DELETE http://localhost:8888/aaa?recursive=true`) and discovered that it takes *a very long time* (multiple hours) to delete over 6 million files. So I figured that it's probably faster to delete the collection. This is when I noticed that the filer still shows those files as available.
- I limited `-volumeSizeLimitMB=1` to test what would happen if there is a large number volume files present.

**Comment by chrislusf** [comment]
It does not work this way.

You can use S3 buckets, and delete one bucket directly.
