### ISSUE TITLE
The usage of the directory mounted in the container is not accurate

### ISSUE THREAD

**Issue by zhouhuahao** [seaweedfs/seaweedfs#4235]
**Describe the bug**
use seaweedfs-csi-driver，the usage of the directory mounted in the container is not accurate

**System Setup**

- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
3 master、4 volume
nohup /usr/local/bin/weed master -ip=10.88.206.77 -port=9333 -defaultReplication="001" -mdir=/data1/weedfs/master  -peers=10.88.206.78:9333,10.88.206.79:9333 > /var/log/weedfs/master/master.log 2>&1&
nohup /usr/local/bin/weed volume -port=10002 -dir=/data0/seaweedfs/volume/volume01 -max=7 -fileSizeLimitMB=200 -mserver=10.88.206.77:9333,10.88.206.78:9333,10.88.206.79:9333 -dataCenter=dc1 -rack=rack1 > /var/log/seaweedfs/volume2.log 2>&1&
nohup /usr/local/bin/weed filer -port=8888  -master=10.88.206.77:9333,10.88.206.78:9333,10.88.206.79:9333 -ip=10.88.206.77  > /var/log/weedfs/filter/filter.log 2>&1&
nohup /usr/local/bin/weed s3 -config=/etc/seaweedfs/s3-config.json -filer=10.88.206.77:8888 -ip.bind=10.88.206.77 -port=8333 > /var/log/weedfs/s3/s3.log 2>&1&

- OS version：ubuntu20.04

- weed version：3.42

- filer.toml：
[leveldb2]
enabled = true
dir = "/data1/weedfs/filer/data" 

**Expected behavior**
The use of  directory mounted in the container increased by 10G

**Screenshots**
![1676959572542](https://user-images.githubusercontent.com/26668580/220261388-1d5f9cf7-e178-4bed-8dcd-8df699ac26bf.png)

**Comment by dzh6699** [comment]
resolved

**Comment by chrislusf** [comment]
logic size and on disk size are different.

**Comment by zhouhuahao** [comment]
what is the relationship between logic size and on disk size
