### ISSUE TITLE
Authentication error of SeaweedFS S3 using AWS SDK java

### ISSUE THREAD

**Issue by Chanukya001** [seaweedfs/seaweedfs#4237]
**Describe the bug**
I am using AWS SDK Java for the seaweedFS and I'm facing the following issue.
The bug is I am getting a error (please refer to the screenshot provided below) - Signed request requires setting up SeaweedFS S3 authentication (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: 1676970620120198000; S3 Extended Request ID: null), S3 Extended Request ID: null

I am able to list the buckets and list the contents of the buckets but unable to upload the object into the buckets using the code.

[Also i would like to know that should I subscribe to AWS S3 API by paying to it to use this service or resolve this error? 
Should I subscribe to that API to use the AWS S3 services through JAVA AWS SDK or can i get that for free by using SeaweedFS without paying to subscribe?]

**System Setup**
- output of `weed version`
- /data # weed version
   version 30GB 3.42 8821d6b16 linux arm64
- Have configured the s3 in weed shell (on docker) as you have instructed in previous issues.
> s3.configure
{
  "identities": [
    {
      "name": "me",
      "credentials": [
        {
          "accessKey": "any",
          "secretKey": "any"
        }
      ],
      "actions": [
        "Read:foo",
        "Write:foo",
        "List:foo"
      ],
      "accountId": ""
    }
  ]
}

-But I still face the authentication issue.

**Expected behavior**
To have the objects uploaded into the s3 bucket

**Screenshots**
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/91115780/220322069-a2aa7107-3586-4e56-a99b-acb99e2cbf72.png">

**Additional context**
I am providing the code that i have used.

package org.example;

import com.amazonaws.AmazonServiceException;
import com.amazonaws.ClientConfiguration;
import com.amazonaws.SdkClientException;
import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.*;
import com.amazonaws.services.s3.transfer.TransferManager;
import com.amazonaws.services.s3.transfer.TransferManagerBuilder;
import com.amazonaws.services.s3.transfer.TransferManagerConfiguration;
import com.amazonaws.services.s3.transfer.Upload;
import java.io.File;
import java.util.List;
public class Main{
    static String bucketname = "javabucket";
    public static void main(String[] args) throws Exception {

        String filePath = "/Users/firstUser/Downloads/samp.txt";

        File file = new File(filePath);
        AmazonS3 s3Client=null;
        String keyName = "path/to/" + file.getName();

        try {
            AWSCredentials credentials = new BasicAWSCredentials("ANY-ACCESSKEYID", "ANY-SECRETACCESSKEY");
            ClientConfiguration clientConfiguration = new ClientConfiguration();
            clientConfiguration.setSignerOverride("AWSS3V4SignerType");

            s3Client = AmazonS3ClientBuilder
                    .standard()
                    .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(
                            "http://localhost:8333", Regions.US_WEST_1.name()))
                    .withPathStyleAccessEnabled(true)
                    .withClientConfiguration(clientConfiguration)
                    .withCredentials(new AWSStaticCredentialsProvider(credentials))
                    .build();
            //System.out.print(s3Client.getRegion());
 

            if (!s3Client.doesBucketExistV2(bucketname)) {

                // Because the CreateBucketRequest object doesn't specify a region, the
                // bucket is created in the region specified in the client.
                s3Client.createBucket(new CreateBucketRequest(bucketname));

                // Verify that the bucket was created by retrieving it and checking its location.
                String bucketLocation = s3Client.getBucketLocation(new GetBucketLocationRequest(bucketname));
                System.out.println("Bucket location: " + bucketLocation);

            } else {
                System.out.println("Bucket already exists");
                System.out.println("Now trying to upload the object into the bucket!");
                
                //way-1 of uploading file into the bucket and this line causes the seaweedFS authentication required error
                
                s3Client.putObject(bucketname,file.getName(),file);
                
                //this method doesnt upload anything but just executes.
                TransferManager tm = TransferManagerBuilder.standard()
                    .withS3Client(s3Client)
                    .build();
            Upload upload = tm.upload(bucketname, keyName, file);

            System.out.println("uploaded");
            }
            System.out.println("Listing buckets");
            // list s3 buckets
            for (Bucket bucket : s3Client.listBuckets()) {
                System.out.println(" - " + bucket.getName());
            }
        } catch (AmazonServiceException e) {
            e.printStackTrace();
        } catch (SdkClientException e) {
            e.printStackTrace();
        }
        getContent(s3Client);
    }
    public static void getContent(AmazonS3 s3client){
        ObjectListing listing = s3client.listObjects(bucketname);
        List<S3ObjectSummary> summaries = listing.getObjectSummaries();
        System.out.println(listing);
        while (listing.isTruncated()) {
            listing = s3client.listNextBatchOfObjects (listing);
            summaries.addAll (listing.getObjectSummaries());
        }
        if(summaries.size()==0){
            System.out.println("The bucket is empty!");
        }
        for (S3ObjectSummary summary : summaries) {
            System.out.println("Object name: " + summary.getKey() + " file size:" + summary.getSize());
        }
    }
}

**Comment by chrislusf** [comment]
The credential is wrong.

**Comment by Chanukya001** [comment]
Even if i put the credentials in code as "any" it still fails...

**Comment by chrislusf** [comment]
worked for me.

**Comment by chrislusf** [comment]
please show how you started the servers, following the issue template.
