### ISSUE TITLE
Nodion's sponsor logo is not displayed in readme

### ISSUE THREAD

**Issue by andrew-demb** [seaweedfs/seaweedfs#4249]
**Describe the bug**

Nodion's (https://nodion.com) logo isn't displayed in readme while viewing it from the GitHub UI.

**System Setup**

- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount" - N/A
- OS version - Linux Debian 11
- Browser - Google Chrome
- output of `weed version` - N/A
- if using filer, show the content of `filer.toml` - N/A

**Expected behavior**

Nodion's logo displayed correctly.

**Screenshots**

Readme screenshot: ![image](https://user-images.githubusercontent.com/12499813/221527924-eeecf5fb-72cf-4c43-83cd-2a04ff3240c8.png)

**Additional context**

Link to the image: https://camo.githubusercontent.com/a366ecdea9fffccca36b6fb777f6870c497f4d47f3bed17f345b26ae57ca9cf4/68747470733a2f2f7777772e6e6f64696f6e2e636f6d2f696d672f6c6f676f2e737667

![image](https://user-images.githubusercontent.com/12499813/221528243-b6c20214-9e47-4273-9d4d-dca5ca486681.png)

**Comment by chrislusf** [comment]
Thanks! Are you related to Nodion? Maybe help to get an "official" link?

**Comment by andrew-demb** [comment]
No, I am not.
Probably it can be retrieved from the website and saved to the repository?
