### ISSUE TITLE
cannot bind metrics port to ipv6

### ISSUE THREAD

**Issue by nivekuil** [seaweedfs/seaweedfs#4271]
**Describe the bug**
metrics bind ipv6 address is formatted wrong:
`2023/03/05 09:43:28 listen tcp: address ffff:ffff:ffff:ffff:ffff:ffff:687b:83af:9090: too many colons in address`
I believe this bug was introduced in https://github.com/seaweedfs/seaweedfs/commit/fe670a6241c752536de82aea7d358ecf03252099#diff-014d1186206a3991c7649ef2b7490a5fff7395500f438eaa5a4f0526967e3b81R290/fe670a6241c752536de82aea7d358ecf03252099
I think it needs to use `joinHostPort`

**Comment by chrislusf** [comment]
Send a PR?

**Comment by nivekuil** [comment]
It would involve either duplicating code or refactoring packages, because `util.JoinHostPort` can't be used from `stats` without creating a circular import.

**Comment by chrislusf** [comment]
It's ok to duplicate a small piece of code.

**Comment by rpodgorny** [comment]
maybe this can be closed now?
