### ISSUE TITLE
Java client help

### ISSUE THREAD

**Issue by Pseudow** [seaweedfs/seaweedfs#4291]
Hi I am new to SeaweedFS and I had some questions to ask:
- If I want to use SeaweedFS with **only the master without a Filer** with my Java applications do I have to implement myself all the methods? *(Because the java client only uses Filer options)*
- Will using a Filer with HDFS impact my performances? I was actually thinking of implementing my own metadata system with my Postgres database.
- Could I add my **own metadata** linked to some files with the **Filer** for example I would like to put labels for files?

Thanks for your answers!

**Comment by Pseudow** [comment]
I was exploring the code and found out **FilerClient** was a subclass of **FilerGrpcClient**

**Comment by Pseudow** [comment]
In that way could I add my own metadata linked to some files?

**Comment by chrislusf** [comment]
* Correct. You may re-use some functions within current java client. You are also welcome to add public APIs for that.
* No. The data will not go through filer. Only metadata will go to filer.
* Yes. Check `Entry` in the `filer.proto` .

**Comment by PedroMPagani** [comment]
@Pseudow By any chance did you manage to create the master client?

**Comment by Pseudow** [comment]
sorry for the delay I am not sure I understood your question what do you call a 'master client'?
