### ISSUE TITLE
An exception occurred when the file was downloaded through the URL

### ISSUE THREAD

**Issue by MapleXiao2** [seaweedfs/seaweedfs#4297]
![QQ截图20230312012330](https://user-images.githubusercontent.com/89175500/224502808-aca2f7cd-1607-4a79-aed9-638ef2c50789.png)
Using the postman, the returned data contained the contents of the red box, so the file was corrupted.
How can I solve this problem?

**Comment by chrislusf** [comment]
make it reproducible.

**Comment by MapleXiao2** [comment]
1. Get fid and upload files.
 ![(E0F%D$E{{F) {`{RT1O7KQ](https://user-images.githubusercontent.com/89175500/224525254-d338bec2-2cec-461b-8a13-2f3fc1336cc0.png)
2. Then access it directly through the URL
![uTools_1678597115136](https://user-images.githubusercontent.com/89175500/224525340-016be99f-f4df-43d1-970c-36de528d44f6.png)

**Comment by chrislusf** [comment]
use `cur -F ... `, without PUT method.
