### ISSUE TITLE
mount: data inconsistencies between multiple hosts 

### ISSUE THREAD

**Issue by Michael754267513** [seaweedfs/seaweedfs#4319]
I have more than 100 clients to mount seaweed. When I write the file to one of the mount nodes, only some nodes can see the file.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/17563605/225863918-33ecfa93-0809-46b0-b1d7-f37e0232a8f0.png">

**Comment by Michael754267513** [comment]
The data size of my mount directory is 10GB+

**Comment by chrislusf** [comment]
Please follow issue template and add missing info.

**Comment by Michael754267513** [comment]
version  3.35 is too older， update new version 。
