### ISSUE TITLE
Touch()'ing a file should update its last modified time

### ISSUE THREAD

**Issue by dalbani** [seaweedfs/seaweedfs#4337]
**Describe the bug**
While copying a file "over itself" via the S3 protocol, I discovered that SeaweedFS didn't update its last modified time.

**Expected behavior**
The last modified time should be be updated, just like the regular `touch` shell command.
I am not really familiar with the SeaweedFS codebase, but a quick try with the following change seemed to work:
```golang
// weed/pb/filer_pb/filer_client.go
func Touch(filerClient FilerClient, parentDirectoryPath string, entryName string, entry *Entry) (err error) {

	return filerClient.WithFilerClient(false, func(client SeaweedFilerClient) error {
		entry.Attributes.Mtime = time.Now().Unix()  // <==== update mtime to current time

		request := &UpdateEntryRequest{
			Directory: parentDirectoryPath,
			Entry:     entry,
		}
```

**Comment by chrislusf** [comment]
thanks for the tip!
