### ISSUE TITLE
Give the client part of the volume

### ISSUE THREAD

**Issue by mykgspace** [seaweedfs/seaweedfs#4347]
Hello! I have 3 nodes, each with a disk, each with 20GB. I mount these disks and add them to the weed cluster. After that, I need to give one client a 10GB volume (out of a possible 60GB), another 15GB volume, and so on.
Can you please tell me if I can use your system to give the client only a part of the total volume?

Thank you in advance!

**Comment by washcycle** [comment]
You could create them a collection and mount that, or you could use the s3 endpoint and use an S3 configuration and credentials and give those to your client.

I've never done this, but it sounds like that might work for you.
