### ISSUE TITLE
The master leader node keeps changing

### ISSUE THREAD

**Issue by shichanglin5** [seaweedfs/seaweedfs#4437]
**Describe the bug**
When the leader node of  the cluster restarts due to https://github.com/seaweedfs/seaweedfs/issues/4435, raft re-elects and selects a new leader node. However, every once in a while, the logs print the following information. 
use `grep master_server master.log. `

<img width="781" alt="image" src="https://user-images.githubusercontent.com/48707349/235416433-6442d927-34b3-4508-85ea-89e1e106caee.png">

**It seems to be a problem with raft, and in the end, we recover the cluster by stopping all master nodes and restarting**

**Below is the promethues monitor**
PromQL `irate(SeaweedFS_wdclient_connect_updates{job="$cluster"}[1m])`
<img width="856" alt="image" src="https://user-images.githubusercontent.com/48707349/235418047-44ec27df-644d-41e3-9761-31d4dfe90462.png">

PromQL `SeaweedFS_master_is_leader{job="$cluster"}>0`
<img width="856" alt="image" src="https://user-images.githubusercontent.com/48707349/235418184-c2922f9f-09c5-4eb9-9812-fa9c419bc6bd.png">

**Comment by shichanglin5** [comment]
@chrislusf  do you know what may have caused this

**Comment by shichanglin5** [comment]
> @chrislusf do you know what may have caused this

is [realease 3.48](https://github.com/seaweedfs/seaweedfs/releases/tag/3.48) missing bug fix https://github.com/seaweedfs/raft/pull/7

**Comment by kmlebedev** [comment]
@shichanglin5  The built-in raft is very unfinished, I would recommend using the hashicorp raft
```
 weed master --help
  -raftHashicorp
    	use hashicorp raft
```

**Comment by kmlebedev** [comment]
> My cluster has switched the leader twice for no reason. Can the default raft run stably?

default raft does not support changing the configuration on the fly without cluster initialization. Also it cannot be considered stable as it is not fully implemented.
