### ISSUE TITLE
volume fix replication can't change old volume replications!

### ISSUE THREAD

**Issue by lygn128** [seaweedfs/seaweedfs#4466]
**Describe the bug**
1 i install 1 master which ./weed master  -port 12379 -mdir /data07/ -peers 172.168.6.17:12379
2 install 3  volume server on 3 node;
3 when i change   ./weed master -defaultReplication=002 -port 12379 -mdir /data07/ -peers 172.168.6.17:12379 and restart master and volume

4 use weeg shell:  i run      volume.fix.replicatin,    the old volume show change to three replication, but in fact, the old volumes keep single replication forever;

**System Setup**
./weed volume -max=24 -port 13379 -dir /data07/ -mserver 172.168.6.17:12379
 ./weed master -defaultReplication=002 -port 12379
- OS version
ubuntu 20.04
- output of `weed version`
3.46

**Expected behavior**
 the old volume show change to three replication, but in fact, the old volumes keep single replication forever;

**Screenshots**
<img width="983" alt="微信图片_20230515111855" src="https://github.com/seaweedfs/seaweedfs/assets/3850927/937bf160-ccba-46e4-abdd-54a5fb7cef58">

**Additional context**

**Comment by meotimdihia** [comment]
I don't sure my problem is the same as this, but I tried these commands too:

```shell
lock; volume.check.disk ; unlock
lock; volume.check.disk -force ; unlock
lock; volume.fix.replication -n ; unlock
lock; volume.fix.replication ; unlock
```

And there is still 50% of volumes that don't have replication. I have 15000 volumes.
I searched and couldn't find the solution.

**Comment by meotimdihia** [comment]
I used this command: 
```shell
lock; volume.configure.replication -replication 010 -collectionPattern *; unlock
lock; volume.fix.replication ; unlock
```

And it looks like Seaweeds created duplicated replications and missing them. I dunno how to fix this problem.

**Comment by lygn128** [comment]
i find the replication num is right from web for a volume, but when i run volume.fix.replication, i enconter some volume informations "replicating volume 11 002 from 172.168.6.18:13379 to dataNode 172.168.6.17:13379"

**Comment by chrislusf** [comment]
This works as expected.

As @meotimdihia mentioned, the `volume.fix.replication` does not change old volume configurations. Use `volume.configure.replication` for that.
