### ISSUE TITLE
[volume] memory leak 

### ISSUE THREAD

**Issue by kmlebedev** [seaweedfs/seaweedfs#4469]
**Describe the bug**

Memory consumption per server volume is growing all the time, before the arrival of the OOM killer

**System Setup**
```
3.48
```

**Expected behavior**
Timely release of unused memory

**Screenshots**
2 days
![Снимок экрана 2023-05-15 в 17 58 03](https://github.com/seaweedfs/seaweedfs/assets/9497591/5e99c07d-49fa-4630-97fb-9c064cac4173)
2 hour after run shell command `fs.verify` in 12:13
![Снимок экрана 2023-05-15 в 17 52 22](https://github.com/seaweedfs/seaweedfs/assets/9497591/3a29f311-55ff-42f2-9199-46d0dc2da02a)

**Comment by chrislusf** [comment]
https://github.com/seaweedfs/seaweedfs/pull/4422 is suspicious. Please try to skip this commit and test.

If still reproducible, please collect memory profiles.

**Comment by chrislusf** [comment]
cc @zemul

**Comment by kmlebedev** [comment]
> #4422 is suspicious. Please try to skip this commit and test.
> 
> If still reproducible, please collect memory profiles.

I spied on the memory consumption for 30 days and it seems that it was the same and I just didn’t pay attention to it.
![Снимок экрана 2023-05-16 в 12 24 21](https://github.com/seaweedfs/seaweedfs/assets/9497591/8a06ffa9-0ed4-469c-870a-e5c7aa5971b2)

A graph of the aggregation of the average value of memory consumption by availability zone (DC)
In each parameter and the set of server volumes is identical, but there are more user requests in the dk12 zone.

I looked at the code of the `fs.verify` command, which is parallel on all volume servers for each funk in the bucket, it checks VolumeNeedleStatus blocks
![Снимок экрана 2023-05-16 в 12 42 39](https://github.com/seaweedfs/seaweedfs/assets/9497591/7ce6a00f-cefa-4499-ae5d-bdcf3b460136)
In which the needle is filled but without data. And it somehow frees up memory. The GC is probably starting to clean up old filled data needles.

Perhaps after the data from the needle is transferred over the network, the memory from the Needle structure should be forcibly released. Data - The actual file data

https://github.com/seaweedfs/seaweedfs/blob/master/weed/storage/needle/needle_read.go#L114

**Comment by kmlebedev** [comment]
> How much traffic are there?

This metric was dropping, now keep it. I'll show you when there will be statistics for the day

**Comment by kmlebedev** [comment]
Stable playback, which hints at excessive memory allocation.

![image](https://github.com/seaweedfs/seaweedfs/assets/9497591/266c5e72-562d-46ab-a0d4-96cb39670aaf)

**Comment by kmlebedev** [comment]
@zemul Can you help reduce memory consumption?

**Comment by zemul** [comment]
> @zemul Can you help reduce memory consumption?

I didn't have that problem and didn't know where to start.

Is this caused by executing `fs.vertify`?

**Comment by kmlebedev** [comment]
> Is this caused by executing `fs.vertify`?

Yes, regularly. 

Moreover, if `fs.vertify` is not run, then after a few weeks the memory reaches the limits and OOM occurs

**Comment by kmlebedev** [comment]
you can also use `GOMEMLIMIT` https://pkg.go.dev/runtime
