### ISSUE TITLE
Incorrect version reported by `version` command

### ISSUE THREAD

**Issue by enspritz** [seaweedfs/seaweedfs#4483]
Hello!

**Describe the bug**
```bash
$ sudo docker run -it --rm chrislusf/seaweedfs:3.50 version
version 30GB 3.49 2e351aa96 linux amd64
```
Ask version `3.50` what its version is, and it reports `3.49`.

**Expected behavior**
The build version aught to match the container version.
```bash
version 30GB 3.50 2e351aa96 linux amd64
```

**Discussion**
Perhaps there is a way to define the version as a build-time constant in just one location (one source of truth) and reference it from everywhere else, possibly by templating. This can systemically eliminate such discrepancies in future.

Going further, ideally the version line identifies itself along with more specific information.
"I am weed version x.y.z, this build variant (full, large files), this VCS hash, built for this OS platform."
```
WEED_COMMAND, VERSION, BUILD_VARIANT, VCS_COMMIT_HASH, OS_PLATFORM
weed version 3.50 30GB 2e351aa96 linux amd64
```
Most important is that the version is tightly associated with the name of the tool, `weed` in this case. And since that is what the command `weed version` is asking, that information should come first.

Going even further, it could even be on several lines:
```
weed 3.50
SeaweedFS (build Git 2e351aa96, 30GB, linux amd64)
```
The first line implies "version" without stating so; we can speak it out loud as "this is weed version 3.50". The second line fully indicates that this is part of SeaweedFS, and gives more specific info.

Some examples from other tooling:
```bash
$ git --version
git version 2.33.0

$ java -version
openjdk version "1.8.0_345"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_345-b01)
OpenJDK 64-Bit Server VM (Temurin)(build 25.345-b01, mixed mode)

$ python3 --version
Python 3.9.2

$ ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
```

**Comment by roman901** [comment]
This bug is already fixed in master branch via https://github.com/seaweedfs/seaweedfs/commit/9204ee2d2dfd421753dad9fcc80c2b5ce3ea5326, but 3.50 release has been built earlier

**Comment by enspritz** [comment]
Got it!
