### ISSUE TITLE
Recreate volume from EC?

### ISSUE THREAD

**Issue by LoopControl** [seaweedfs/seaweedfs#4492]
Is it possible to tell seaweed to recreate a volume from the EC files?

One of the volumes is throwing errors and the .dat file isn't present for that volume in any of the servers. I am seeing what looks to be EC files in multiple servers though:

```
-rw-r--r-- 1 root root 107M May  6 10:19 1646.ec07
-rw-r--r-- 1 root root 107M May  6 09:41 1646.ec08
-rw-r--r-- 1 root root 107M May  6 10:20 1646.ec09
-rw-r--r-- 1 root root 107M May  6 09:41 1646.ec10
-rw-r--r-- 1 root root 107M May  6 10:21 1646.ec11
-rw-r--r-- 1 root root 107M May  6 09:42 1646.ec12
-rw-r--r-- 1 root root 107M May  6 10:22 1646.ec13
-rw-r--r-- 1 root root    0 May  6 09:42 1646.ecj
-rw-r--r-- 1 root root  62K May  6 10:22 1646.ecx
-rwxr-xr-x 1 root root   78 May  6 09:42 1646.vif
```
The error when trying to access files from that volume:
`I0522 15:19:18.475883 filechunk_manifest.go:197 read http://IP:8081/1646,611665de14653c failed, err: http://IP:8081/1646,611665de14653c?readDeleted=true: 500 Internal Server Error`

Any way to tell seaweed to recreate the volume from scratch?

**Comment by LoopControl** [comment]
Thanks. Unfortunately the restore of that volume failed with a “shard 7 missing”. Guess I’ll restore the files from backups

**Comment by chrislusf** [comment]
There is a command to fix missing shards also.
