### ISSUE TITLE
Wiki for pull metrics needs to be updated.

### ISSUE THREAD

**Issue by Meenakshi-Sachdeva** [seaweedfs/seaweedfs#4500]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/seaweedfs/seaweedfs/discussions

**Describe the bug**
https://github.com/seaweedfs/seaweedfs/wiki/System-Metrics#pull-metrics
It mentions same port number for all the servers but if say master is running 1234, volume should on 1235 or some other port otherwise we get error for port already in  use.

**Comment by chrislusf** [comment]
Welcome to update the wiki directly!

**Comment by Meenakshi-Sachdeva** [comment]
Thanks. Updated the page.
