### ISSUE TITLE
[Docs] Replication factor 002 not working?

### ISSUE THREAD

**Issue by achetronic** [seaweedfs/seaweedfs#4580]
**Describe the bug**
I'm not sure if this is a bug or bad configuration. Honestly I expected the replication factor 002 meant something like `I want the original file and two extra copies across 2 other servers in the same rack and same datacenter`.

The results exposed in the picture attached are with a new created cluster, 1 master, 3 volumes and only 1 uploaded file just to test this theory. I expected the same file was replicated across these 3 volume servers, with same size, etc. This is not what I see (file's size is ~53MB, 19MB, 19MB)

![Screenshot from 2023-06-15 01-54-58](https://github.com/seaweedfs/seaweedfs/assets/61636487/5b615fd7-6196-4c9d-8d2e-93b9646661ad)

The requests I did:
![Screenshot from 2023-06-15 01-55-20](https://github.com/seaweedfs/seaweedfs/assets/61636487/f005cd47-74b3-4b95-819e-246b1d3fa40f)

**System Setup**
![Screenshot from 2023-06-15 01-56-28](https://github.com/seaweedfs/seaweedfs/assets/61636487/4b552abd-d625-450a-81ec-e93f45df8e9b)

`weed version`
```
version 30GB 3.52 fb4b61036cd6389b18efc5343b766b1c5512ad1c linux arm64
```

`cat /etc/os-release`
```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Expected behavior**
Same file, across servers should be exactly the same?

**Comment by chrislusf** [comment]
do the reads return the same results?

**Comment by achetronic** [comment]
Well, I executed these three commands to test
```
curl http://192.168.2.11:8080/5,0914be4ab8 --output mimirtool-8080
curl http://192.168.2.11:8081/5,0914be4ab8 --output mimirtool-8081
curl http://192.168.2.11:8082/5,0914be4ab8 --output mimirtool-8082
```

and the output is the following:
![Screenshot from 2023-06-15 02-47-41](https://github.com/seaweedfs/seaweedfs/assets/61636487/67af7981-88dc-419f-8f12-271c79f54c7f)

So seem to be the same, but how? I mean, how is this storing this? (I feel I'm missing something) 
Shouldn't the `.dat` files at volume level have the same size when this volume servers are only storing 1 file for testing purposes?

**Comment by chrislusf** [comment]
very likely the entries are compressed.

Compression or not is a volume server local decision.

**Comment by achetronic** [comment]
> very likely the entries are compressed.
> 
> Compression or not is a volume server local decision.

mmmm is there an option to disable comoression to check it?

Last question related: Why I uploaded 1 file with 3 volume servers and it created like 3 volumes in each server? I mean (3 .idx + .vif + .dat) but only filled one? (5.dat, .idx and .vif mostly)

**Comment by achetronic** [comment]
> * you can send the file with a special mime type
> * this is a volume growth strategy, customizable in `master.toml`.

I would like to understand it a bit better to be able to help with the documentation 🙏🏻

- Regarding to the first point, I would expect the file is compressed or not in all de volume servers in the same way as the file has the same mimetype, so why is compressing the copies and not the actual uploaded one? After a while, some mechanism will compress the uploaded too?

- I see the mechanism to grow the number of volumes depends on how many copies you want, right? but how is this useful? Can you point a situation where it is needed to create volumes in advance just in case? 

```
# create this number of logical volumes if no more writable volumes# count_x means how many copies of data.# e.g.:# 000 has only one copy, copy_1# 010 and 001 has two copies, copy_2# 011 has only 3 copies, copy_3[master.volume_growth]copy_1 = 7 # create 1 x 7 = 7 actual volumescopy_2 = 6 # create 2 x 6 = 12 actual volumescopy_3 = 3 # create 3 x 3 = 9 actual volumescopy_other = 1 # create n x 1 = n actual volumes
```

Sorry for the amount of questions. In general, data storages are like hidden worlds :)

**Comment by chrislusf** [comment]
* This may be a bug as to why some volume servers did not compress one file while others are. But in general, they are not required to be exactly the same. There are no mechanism to compress either after the data is written.
* The write traffic may be high when one volume is full and it needs to create a new volume. Also, having multiple volumes to write increases throughput.

**Comment by achetronic** [comment]
> * This may be a bug as to why some volume servers did not compress one file while others are. But in general, they are not required to be exactly the same. There are no mechanism to compress either after the data is written.
> * The write traffic may be high when one volume is full and it needs to create a new volume. Also, having multiple volumes to write increases throughput.

2. Oh, so they are pre-created automatically to avoid creating them on actual demand improving writes reducing the times. Right?

1. Could we rise an issue for this potential bug? It would be awesome to fix it 🙂

**Comment by achetronic** [comment]
**About the point 2**, it's actually [really well explained here](https://github.com/seaweedfs/seaweedfs/wiki/Optimization#increase-concurrent-writes). Just found this peace of documentation and shared here just in case someone needs it 🙂

**Comment by achetronic** [comment]
Hey hey @chrislusf last ping before closing the issue. Wdyt about this?

> 1- Could we rise an issue for this potential bug? It would be awesome to fix it 🙂

**Comment by kmlebedev** [comment]
@achetronic Can you gather additional information so that we can localize the problem with different sizes of dat files?

1. `weed -v 9 fix /data`

**Comment by achetronic** [comment]
@kmlebedev Hey, I have uploaded more files and executed this command for all three volume server. The info it throws is
![Screenshot from 2023-06-19 23-28-21](https://github.com/seaweedfs/seaweedfs/assets/61636487/86e92f0c-d709-4fa8-b8b2-e5926101bc36)

- The data should be the same in all the servers, as I only uploaded the same three files on all them
- I see some line saying compressed false, for both three (???)

It's quite weird

**Comment by kmlebedev** [comment]
Seems the problem is here:
https://github.com/seaweedfs/seaweedfs/blob/master/weed/topology/store_replicate.go#L97

When uploading, the file is compressed, and the compression flag is not transmitted further to the replicas.

**Comment by achetronic** [comment]
Hey! @kmlebedev The steps to reproduce this are

```console
curl http://gluster-01.services.internal:9333/dir/assign\?dataCenter\=home\&rack\=office

curl -F file=@/home/achetronic/Downloads/playlist.7z http://192.168.2.11:8080/3,21e19922a1
```

response: `{"fid":"5,22ca735d02","url":"192.168.2.11:8080","publicUrl":"192.168.2.11:8080","count":1}`

```console
curl -F file=@/home/achetronic/Downloads/playlist.7z http://192.168.2.11:8080/5,22ca735d02
```
---

Regarding to the potential problem you mention, it seems like the opposite, because when I upload a file, it seems that is normal-sized in the node where I upload, but reduced in the rest of the nodes. Does it make sense?

**Comment by achetronic** [comment]
May be this clarify the topic a bit:
![Screenshot from 2023-06-20 09-10-52](https://github.com/seaweedfs/seaweedfs/assets/61636487/459b9feb-cc6d-42a8-bae2-5abb6a469102)

You can see the sizes of the volume 5, and moreover when I export the volume just to see some information, you can see the binary is gziped in the `volume server 2` and `volume server 3` but not in the `volume server 1`, so is it possible this flag is computed in the server where you upload the data but may be it is not being populated to the replicated ones?

**Comment by kmlebedev** [comment]
Yeah, I see that during replication, a reversion occurs, what was compressed into the replicas is not compressed, but what is compressed into the replicas is not compressed.
Just amazing.

**Comment by kmlebedev** [comment]
This explains why volume sizes of files can differ with the same number of files and they are constantly subject to a quick check of `volume.chek.disk`

https://github.com/seaweedfs/seaweedfs/issues/4140

**Comment by achetronic** [comment]
Well, i still dunno the codebase deeply to help a lot, so question: is it easy to fix? May be in the future I can collaborate better on this project

**Comment by achetronic** [comment]
@kmlebedev kindly ping :)

**Comment by kmlebedev** [comment]
> @kmlebedev kindly ping :)

Yes, I plan to take it to work myself

**Comment by kmlebedev** [comment]
@chrislusf Hi, Can you assign me this issue

**Comment by achetronic** [comment]
> @chrislusf Hi, Can you assign me this issue

@chrislusf Another kind ping 🙏🏼
