### ISSUE TITLE
修改volume的ttl

### ISSUE THREAD

**Issue by itzhoujun** [seaweedfs/seaweedfs#4583]
使用s3设置了ttl，使用一段时间后，修改了ttl。旧的数据所在的volume仍然还是旧的ttl，想问下是否有办法修改volume的ttl

**Comment by chrislusf** [comment]
the volume ttl can be changed. but not the file TTL.

**Comment by itzhoujun** [comment]
> the volume ttl can be changed. but not the file TTL.

how to change volume ttl

**Comment by chrislusf** [comment]
need to use this https://github.com/seaweedfs/seaweedfs/tree/master/unmaintained/change_superblock
