### ISSUE TITLE
weed filer.remote.gateway takes long time to upload relative big files

### ISSUE THREAD

**Issue by mervynzhang** [seaweedfs/seaweedfs#4604]
**Describe the bug**
I tried to do some performance testing, it looks like weed filer.remote.gateway takes long time to upload relative big files (58mb). 2 minutes for 58mb. 
<img width="318" alt="image" src="https://github.com/seaweedfs/seaweedfs/assets/11482400/28949caf-9d10-4c97-870c-3b76dea484b9">

**System Setup**
master and filer.remote.gateway are in same pod but different containers
/usr/bin/weed -logtostderr=true server -dir=/data -master.volumePreallocate -master.volumeSizeLimitMB=1024 -s3 -master.port=9333 -volume.port=8080 -volume.max=100 -master.volumeSizeLimitMB=10000 -master.volumePreallocate=true

weed filer.remote.gateway

- OS version
- output of `weed version`
version 30GB 3.52 fb4b61036 linux amd64

**Comment by chrislusf** [comment]
This is not parallelized yet.

**Comment by mervynzhang** [comment]
Is there a scheduled job to run upload? It looks like two minutes one upload.

**Comment by mervynzhang** [comment]
> 

Concurrency is 8, so the first 8 chunks are upload immediately, but next batch of chunks take about 1 minutes to upload. 

Not sure why next batch take so long, can anyone help to debug? I'm quite new to go.

**Comment by mervynzhang** [comment]
![11](https://github.com/seaweedfs/seaweedfs/assets/11482400/4f4b4439-192e-4802-96ab-bb6b50d4e10d)

**Comment by mervynzhang** [comment]
@chrislusf  
Hi Chris,

New findings. 

I tried change u.Concurrency of s3manager.NewUploaderWithClient to 1, the upload is fast (about 5s to upload 900mb file ).  u.Concurrency = 2 will take 1.5 mintues.  u.Concurrency = 4 takes about 6 minutes. Higer Concurrency  will take longer time. 

Thanks.

**Comment by chrislusf** [comment]
Interesting! We can change the concurrency level to 1 if it works better.

**Comment by mervynzhang** [comment]
Hi Chris,

u.Concurrency was updated in https://github.com/seaweedfs/seaweedfs/commit/9920d65bc0c146a58e1d89f31f36cca3b2f3e107, will you please revert it? 


btw, I also tried following code, resp.Body as reader is also fine, no matter what's the value of u.Concurrency. 

maybe c.bufferLock.Lock() has nagetive impact on this case? 
https://github.com/seaweedfs/seaweedfs/blob/a315490f7d4d2aa8b5226ea4029cb112edb88137/weed/filer/stream.go#L239

```
func main() {
	s3Svc := s3.New(session.Must(session.NewSession(&aws.Config{
		Endpoint: aws.String("http://localhost:8333"),
		Region:   aws.String(region),
		S3ForcePathStyle: aws.Bool(true),
	})))

	uploader := s3manager.NewUploaderWithClient(s3Svc, func(u *s3manager.Uploader) {
		u.PartSize = 8 * 1024 * 1024 
		u.Concurrency = 8
	})

	filename := "m2"
	url :="http://localhost:8888/buckets/mtest1/"+filename
	resp, err := http.Get(url)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

	input := &s3manager.UploadInput{
		Bucket: aws.String(bucket),
		Key:    aws.String(filename + "-up"),
		Body:   resp.Body,
	}
	result, err := uploader.Upload(input)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(result)
}

**Comment by mervynzhang** [comment]
> 

Hi Chris, @chrislusf  

should I create PR to set concurrency level to 1 ? 

Thanks

**Comment by chrislusf** [comment]
This is because `ChunkStreamReader` only has one buffer.

For concurrency of 8, the reader would need 8 buffers.
