### ISSUE TITLE
Second Filer first start bootstrap stuck

### ISSUE THREAD

**Issue by htsnorman** [seaweedfs/seaweedfs#4639]
**Describe the bug**
When running the filer services on a 3-node cluster, the first filer server starts perfectly (port 8888 and 8889 are reachable in read-only mode). However, when I try to start an additional filer service, it gets stuck during startup, and the required ports (8888, 18888, etc.) are not being listened to, and nothing happens. The live filer server continuously throws the following error messages:

`7300884
Jul  4 15:57:36 sofalvin-seaweedfs-a seaweedfs-volume[30449]: I0704 15:57:36.908767 meta_aggregator.go:103 subscribing remote 192.168.40.45:8888 meta change: connecting to peer filer 192.168.40.45:8888: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 192.168.40.45:18888: connect: connection refused"
Jul  4 15:57:38 sofalvin-seaweedfs-a seaweedfs-volume[30449]: I0704 15:57:38.641958 meta_aggregator.go:92 loopSubscribeToOneFiler read 192.168.40.45:8888 start from 2023-07-04 15:44:57.107300884 +0200 CEST 1688478297107300884
Jul  4 15:57:38 sofalvin-seaweedfs-a seaweedfs-volume[30449]: I0704 15:57:38.642976 meta_aggregator.go:103 subscribing remote 192.168.40.45:8888 meta change: connecting to peer filer 192.168.40.45:8888: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 192.168.40.45:18888: connect: connection refused"
Jul  4 15:57:40 sofalvin-seaweedfs-a seaweedfs-volume[30449]: I0704 15:57:40.376985 meta_aggregator.go:92 loopSubscribeToOneFiler read 192.168.40.45:8888 start from 2023-07-04 15:44:57.107300884 +0200 CEST 1688478297107300884
Jul  4 15:57:40 sofalvin-seaweedfs-a seaweedfs-volume[30449]: I0704 15:57:40.377856 meta_aggregator.go:103 subscribing remote 192.168.40.45:8888 meta change: connecting to peer filer 192.168.40.45:8888: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 192.168.40.45:18888: connect: connection refused"
Jul  4 15:57:42 sofalvin-seaweedfs-a seaweedfs-volume[30449]: I0704 15:57:42.111475 meta_aggregator.go:92 loopSubscribeToOneFiler read 192.168.40.45:8888 start from 2023-07-04 15:44:57.107300884 +0200 CEST 1688478297107300884
Jul  4 15:57:42 sofalvin-seaweedfs-a seaweedfs-volume[30449]: I0704 15:57:42.112280 meta_aggregator.go:103 subscribing remote 192.168.40.45:8888 meta change: connecting to peer filer 192.168.40.45:8888: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 192.168.40.45:18888: connect: connection refused"
Jul  4 15:57:43 sofalvin-seaweedfs-a seaweedfs-volume[30449]: I0704 15:57:43.846429 meta_aggregator.go:92 loopSubscribeToOneFiler read 192.168.40.45:8888 start from 2023-07-04 15:44:57.107300884 +0200 CEST 1688478297107300884
Jul  4 15:57:43 sofalvin-seaweedfs-a seaweedfs-volume[30449]: I0704 15:57:43.847666 meta_aggregator.go:103 subscribing remote 192.168.40.45:8888 meta change: connecting to peer filer 192.168.40.45:8888: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 192.168.40.45:18888: connect: connection refused"`

The second filer, which I'm trying to start, gets stuck at this point:

`root@sofalvin-seaweedfs-b:~# /usr/local/bin/weed filer -debug -port=8888 -port.readonly=8899 -master=192.168.40.44:9333,192.168.40.45:9333,192.168.40.62:9333 -dataCenter=datacenter-01 -defaultStoreDir=/opt/filer_store
I0704 15:44:57.043401 filer_server.go:141 default to create filer store dir in /opt/filer_store/filerldb2
I0704 15:44:57.046496 leveldb2_store.go:42 filer store leveldb2 dir: /opt/filer_store/filerldb2
I0704 15:44:57.046624 file_util.go:23 Folder /opt/filer_store/filerldb2 Permission: -rwxr-xr-x
I0704 15:44:57.111770 filer.go:163 create filer.store.id to 1700974077
I0704 15:44:57.111850 configuration.go:28 configured filer store to leveldb2
I0704 15:44:57.112903 master_client.go:20 the cluster has 2 filer
I0704 15:44:57.112932 filer_server.go:169 192.168.40.45:8888 bootstrap from peers [node_type:"filer"  address:"192.168.40.44:8888"  is_add:true  created_at_ns:1688478167862760066 node_type:"filer"  address:"192.168.40.45:8888"  is_add:true  created_at_ns:1688478297106983724]
I0704 15:44:57.113000 filer.go:91 bootstrap from 192.168.40.44:8888 clientId:501074952`

Restarting or restarting the second filer server resolves the issue and everything runs smoothly.

What could be causing this?

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
/usr/local/bin/weed master -ip=192.168.40.44 -port=9333 -mdir=/opt/seaweedfs -peers=192.168.40.44:9333,192.168.40.45:9333,192.168.40.62:9333 -defaultReplication=001
/usr/local/bin/weed volume -dir=/mnt/vol1 -port=8080 -mserver=192.168.40.44:9333,192.168.40.45:9333,192.168.40.62:9333 -dataCenter datacenter-01 -rack rack-01 -fileSizeLimitMB 1000
/usr/local/bin/weed filer -debug -port=8888 -port.readonly=8899 -master=192.168.40.44:9333,192.168.40.45:9333,192.168.40.62:9333 -dataCenter=datacenter-01 -defaultStoreDir=/opt/filer_store
- OS version
Debian 11
- output of `weed version`
version 30GB 3.53  linux amd64
- if using filer, show the content of `filer.toml`
/usr/local/bin/weed filer -debug -port=8888 -port.readonly=8899 -master=192.168.40.44:9333,192.168.40.45:9333,192.168.40.62:9333 -dataCenter=datacenter-01 -defaultStoreDir=/opt/filer_store

**Comment by chrislusf** [comment]
the second filer was bootstrapping from the first filer.

**Comment by htsnorman** [comment]
waited for 35 minutes, nothing happened, as soon as I restarted the filer 2 service, everything was fine immediately.
it wouldn't bother me in the basic case that it has to be started twice at the very first start, I have reinstalled the cluster from scratch several times and it is only the very first fresh bootstrap start that gets stuck and I definitely need a restart, I just want to do an automated installation and an unnecessary restart is a bit ugly there :(

**Comment by htsnorman** [comment]
`root@sofalvin-seaweedfs-b:~# /usr/local/bin/weed filer -master=192.168.40.44:9333,192.168.40.45:9333,192.168.40.62:9333 -port=8888 -port.readonly=8899 -dataCenter=datacenter-01
W0705 11:33:53.015789 filer_server.go:143 skipping default store dir in ./filerldb2
I0705 11:33:53.015923 masterclient.go:209 master 192.168.40.62:9333 redirected to leader 192.168.40.44:9333
I0705 11:33:53.021202 leveldb2_store.go:42 filer store leveldb2 dir: /opt/filer_store/filerldb2-b
I0705 11:33:53.021437 file_util.go:23 Folder /opt/filer_store/filerldb2-b Permission: -rwxr-xr-x
I0705 11:33:53.093273 filer.go:163 create filer.store.id to -2016172358
I0705 11:33:53.093402 configuration.go:28 configured filer store to leveldb2
I0705 11:33:53.095251 master_client.go:20 the cluster has 2 filer
I0705 11:33:53.095346 filer_server.go:169 192.168.40.45:8888 bootstrap from peers [node_type:"filer"  address:"192.168.40.44:8888"  is_add:true  created_at_ns:1688549583797002877 node_type:"filer"  address:"192.168.40.45:8888"  is_add:true  created_at_ns:1688549633086415972]
I0705 11:33:53.095500 filer.go:91 bootstrap from 192.168.40.44:8888 clientId:1789606189

#########

STUCK THIS LINE ^

AFTER RUN AGAIN WEED FILER COMMAND, EVERYTHING FINE:

########

root@sofalvin-seaweedfs-b:~# /usr/local/bin/weed filer -master=192.168.40.44:9333,192.168.40.45:9333,192.168.40.62:9333 -port=8888 -port.readonly=8899 -dataCenter=datacenter-01
W0705 11:34:17.129803 filer_server.go:143 skipping default store dir in ./filerldb2
I0705 11:34:17.130669 masterclient.go:209 master 192.168.40.45:9333 redirected to leader 192.168.40.44:9333
I0705 11:34:17.131155 leveldb2_store.go:42 filer store leveldb2 dir: /opt/filer_store/filerldb2-b
I0705 11:34:17.131191 file_util.go:23 Folder /opt/filer_store/filerldb2-b Permission: -rwxr-xr-x
I0705 11:34:17.239046 filer.go:167 existing filer.store.id = -2016172358
I0705 11:34:17.239096 configuration.go:28 configured filer store to leveldb2
I0705 11:34:17.240950 master_client.go:20 the cluster has 2 filer
I0705 11:34:17.241028 filer.go:121 192.168.40.45:8888 aggregate from peers [192.168.40.44:8888 192.168.40.45:8888]
I0705 11:34:17.257619 meta_aggregator.go:92 loopSubscribeToOneFiler read 192.168.40.44:8888 start from 2023-07-05 11:33:17.240982715 +0200 CEST 1688549597240982715
I0705 11:34:17.257899 filer.go:263 Start Seaweed filer server 30GB 3.53  public at 192.168.40.45:8899
I0705 11:34:17.258017 meta_aggregator.go:92 loopSubscribeToOneFiler read 192.168.40.45:8888 start from 2023-07-05 11:33:17.240982715 +0200 CEST 1688549597240982715
I0705 11:34:17.258563 meta_aggregator.go:103 subscribing remote 192.168.40.45:8888 meta change: connecting to peer filer 192.168.40.45:8888: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 192.168.40.45:18888: connect: connection refused"
I0705 11:34:17.258668 filer.go:282 Start Seaweed Filer 30GB 3.53  at 192.168.40.45:8888
I0705 11:34:17.259937 meta_aggregator.go:148 follow peer: 192.168.40.44:8888, last 2023-07-05 11:33:17.240982715 +0200 CEST (1688549597240982715)
I0705 11:34:17.259962 meta_aggregator.go:189 subscribing remote 192.168.40.44:8888 meta change: 2023-07-05 11:33:17.240982715 +0200 CEST, clientId:847908586
I0705 11:34:17.312701 filer_grpc_server_sub_meta.go:279 + listener filer:192.168.40.44:8888@192.168.40.44:50586
I0705 11:34:17.312867 filer_grpc_server_sub_meta.go:106  + filer:192.168.40.44:8888@192.168.40.44:50586 local subscribe / from 2023-07-05 11:33:53.086950337 +0200 CEST clientId:-891737475
I0705 11:34:17.312903 filer_grpc_server_sub_meta.go:119 read on disk filer:192.168.40.44:8888@192.168.40.44:50586 local subscribe / from 2023-07-05 11:33:53.086950337 +0200 CEST
I0705 11:34:17.312981 filer_grpc_server_sub_meta.go:138 read in memory filer:192.168.40.44:8888@192.168.40.44:50586 local subscribe / from 2023-07-05 11:33:53.086950337 +0200 CEST
I0705 11:34:18.868945 filer_grpc_server_sub_meta.go:279 + listener filer:192.168.40.44:8888@192.168.40.44:50588
I0705 11:34:18.868975 filer_grpc_server_sub_meta.go:106  + filer:192.168.40.44:8888@192.168.40.44:50588 local subscribe / from 2023-07-05 11:34:17.199918389 +0200 CEST clientId:-891737475
I0705 11:34:18.868999 filer_grpc_server_sub_meta.go:119 read on disk filer:192.168.40.44:8888@192.168.40.44:50588 local subscribe / from 2023-07-05 11:34:17.199918389 +0200 CEST
I0705 11:34:18.869051 filer_grpc_server_sub_meta.go:138 read in memory filer:192.168.40.44:8888@192.168.40.44:50588 local subscribe / from 2023-07-05 11:34:17.199918389 +0200 CEST
I0705 11:34:18.992637 meta_aggregator.go:92 loopSubscribeToOneFiler read 192.168.40.45:8888 start from 2023-07-05 11:33:17.240982715 +0200 CEST 1688549597240982715
I0705 11:34:18.993989 meta_aggregator.go:189 subscribing remote 192.168.40.45:8888 meta change: 2023-07-05 11:33:17.240982715 +0200 CEST, clientId:847908586
I0705 11:34:18.995256 filer_grpc_server_sub_meta.go:279 + listener filer:192.168.40.45:8888@192.168.40.45:57724
I0705 11:34:18.995287 filer_grpc_server_sub_meta.go:106  + filer:192.168.40.45:8888@192.168.40.45:57724 local subscribe / from 2023-07-05 11:33:17.240982715 +0200 CEST clientId:-847908586
I0705 11:34:18.995457 filer_grpc_server_sub_meta.go:119 read on disk filer:192.168.40.45:8888@192.168.40.45:57724 local subscribe / from 2023-07-05 11:33:17.240982715 +0200 CEST
I0705 11:34:18.995653 filer_grpc_server_sub_meta.go:138 read in memory filer:192.168.40.45:8888@192.168.40.45:57724 local subscribe / from 2023-07-05 11:33:17.240982715 +0200 CEST`

**Comment by htsnorman** [comment]
@chrislusf 

I examined the problem more closely because when I installed my first Seaweed cluster, I don't remember encountering this issue, and indeed I didn't. There was a refactor in the 3.45 release (https://github.com/seaweedfs/seaweedfs/commit/5db9fcccd4194660a8503696ac44c3539c29d41e) that heavily affected the filer service. I don't understand it well enough to grasp exactly what happened, but there must have been a good reason for it! :D

I didn't experience the issue in version 3.44, but in any release after 3.45, the same problem occurred (the bootstrap stuck). I created a new build where I "rolled back" the filer refactor from version 3.45 to version 3.53 in my own way. I did it in a very simple and straightforward manner:

(The main directory is 3.53, where I'm working)

```
cp ../seaweed-3.44/seaweedfs/weed/filer/filer.go weed/filer/filer.go
cp ../seaweed-3.44/seaweedfs/weed/pb/filer_pb_tail.go weed/pb/filer_pb_tail.go
cp ../seaweed-3.44/seaweedfs/weed/mount/meta_cache/meta_cache_subscribe.go weed/mount/meta_cache/meta_cache_subscribe.go
rm weed/server/filer_grpc_server_dlm.go
cp ../seaweed-3.44/seaweedfs/weed/command/filer_backup.go weed/command/filer_backup.go
cp ../seaweed-3.44/seaweedfs/weed/command/filer_meta_backup.go weed/command/filer_meta_backup.go
cp ../seaweed-3.44/seaweedfs/weed/command/filer_remote_sync_dir.go weed/command/filer_remote_sync_dir.go

make install
cp ~/go/bin/weed /usr/local/bin/
```

After building, the filer bootstrap worked perfectly again. I hope I could help, and I hope the issue can be reproduced so that you can investigate it.

By the way, thank you for your work. Seaweed is a great alternative in the market! <3

**Comment by rohitchormale** [comment]
I can confirm this issue. On restarting filer service it gets fixed.

**Comment by Ruakij** [comment]
I can also confirm this.
Started with 1 filer, wanted to add another one, the 2nd one got stuck when bootstrapping from the first one.

After killing it and restarting it seemed to start fine, but when checking the metadata, they were out of sync.

**Comment by chrislusf** [comment]
Thanks @htsnorman @rohitchormale @Ruakij 
sorry for my refactoring mistake!

**Comment by rohitchormale** [comment]
Thanks to you @chrislusf  for project. Keep doing good work :+1:
