### ISSUE TITLE
Volumes crash when run vacuum

### ISSUE THREAD

**Issue by noinhotnn** [seaweedfs/seaweedfs#4640]
**Describe the bug**
runtime error: invalid memory address or nil pointer dereference

**System Setup**
```
weed master -mdir="E:\Seaweedfs" -peers=10.1.11.7:2323 -ip=10.1.11.7 -port=2323 -defaultReplication=100 -volumeSizeLimitMB=500
weed volume -mserver=10.1.11.7:2323 -dataCenter=GPS1 -rack=DATA -dir="D:\Seaweedfs1" -ip=10.1.11.7 -max=0 -port=8085 
-dir.idx="E:\Seaweedfs1"
weed volume -mserver=10.1.11.7:2323 -dataCenter=GPS -rack=DATA -dir="D:\Seaweedfs" -ip=10.1.11.7 -max=0 -port=8086 -dir.idx="E:\Seaweedfs"
weed filer -defaultStoreDir="E:\Seaweedfs" -ip=10.1.11.7 -master=10.1.11.7:2323 -s3 -s3.config="config.json" -s3.port=8333
```
- OS version
`Windows 10 `
- output of `weed version`
`version 8000GB 3.53 2c4c2f0994604510631920f4d0d9ee817ec29224 windows amd64`
- if using filer, show the content of `filer.toml`
```
[leveldb2]
enabled = true
dir = "E:/Seaweedfs/filerldb2"
```
**Expected behavior**
i try to overwrite files by filer and run vacuum (vol/vacuum?garbageThreshold=0).  

**Screenshots**
![image](https://github.com/seaweedfs/seaweedfs/assets/13940206/4a74c329-62ca-4270-87ee-5210b13f0699)

**Comment by noinhotnn** [comment]
It still crashes with new error
![image](https://github.com/seaweedfs/seaweedfs/assets/13940206/39a8b201-f12a-4404-9a84-c47c18e125a0)

**Comment by noinhotnn** [comment]
@chrislusf Can you reopen this issue?

**Comment by chrislusf** [comment]
added a fix
