### ISSUE TITLE
ec.encode original volume maybe delete fail

### ISSUE THREAD

**Issue by Numblgw** [seaweedfs/seaweedfs#4642]
**Describe the bug**
ec.encode command maybe fail when execute delete original volume step
command:

```shell
weed shell -master=xxxx
lock
ec.encode -collection=xxxx -volumeId=xxxx
unlock
```

log output: 

```shell
markVolumeReadonly 154 on 10.117.32.36:9334 ...
markVolumeReadonly 154 on 10.117.32.34:9334 ...
markVolumeReadonly 154 on 10.117.32.35:9334 ...
........
........
delete volume 154 from 10.117.32.36:9334
delete volume 154 from 10.117.32.35:9334
delete volume 154 from 10.117.32.35:9334
```

> 10.117.32.35 delete execute repeated, 10.117.32.34 not delete

**System Setup**
any cluster with more than 2 replica, for example: -defaultReplication=020

**Screenshots**
![image](https://github.com/seaweedfs/seaweedfs/assets/44025291/281e95b6-0e68-4ccc-a576-7faf2c528c34)

**Additional context**
i think this caused by the shared memory of the locations slice.While iterating through the locations and deleting the original volume, the master client will also update the members in the locations.

**reproduce**: add a sleep within the loop. file: weed/shell/command_ec_encode.go, line: 185
![image](https://github.com/seaweedfs/seaweedfs/assets/44025291/f3a89a70-952c-476a-8533-318eb5b58377)

**Comment by chrislusf** [comment]
thanks for the detailed report and insights!
