### ISSUE TITLE
Append write data loss

### ISSUE THREAD

**Issue by wusongANKANG** [seaweedfs/seaweedfs#4648]
**Describe the bug**

When appending to a file, sometimes the written data may be deleted by mistake.

It's very easy to reproduce.

1: Append  write file

```
import os

os.system("rm a.txt")
file = 'a.txt'

for i in range(5000):
    with open(file, 'a+') as f:
        f.write("a\n")
```

2: do "ls" 

```
watch -n 1 ls
```

From the filer side, we can see that some data has been deleted.

![image](https://github.com/seaweedfs/seaweedfs/assets/75450248/f631cac6-3ae3-4dd4-87cf-86717d373689)

On the Mount side, we can see that the data is deleted because the offset of the file obtained by two  append operations is  same.
![image](https://github.com/seaweedfs/seaweedfs/assets/75450248/74a052b7-9fce-487f-95ed-ca4ef622ea86)

**System Setup**

seaweedfs 3.53

**Comment by xdadrm** [comment]
tried and that doesn't look like easily reproducable here :

root@local:/mnt/weed/tmp/xx# cat > test.py
import os

os.system("rm a.txt")
file = 'a.txt'

for i in range(5000):
    with open(file, 'a+') as f:
        f.write("a\n")

root@local:/mnt/weed/tmp/xx# python test.py
rm: cannot remove 'a.txt': No such file or directory

root@local:/mnt/weed/tmp/xx# wc -lc a.txt
 5000 10000 a.txt

root@local:/mnt/weed/tmp/xx# weed version
version 30GB 3.53 2c4c2f0994604510631920f4d0d9ee817ec29224 linux amd64

root@local:/mnt/weed/tmp/xx# python test.py
root@local:/mnt/weed/tmp/xx# wc -lc a.txt
 5000 10000 a.txt

**Comment by wusongANKANG** [comment]
@xdadrm   just appending write will not trigger this problem, you need to execute "ls" in the directory while appending


This is my script
```
~/tmp/weed_test/mount1$ cat ~/test_manifest.py
import os

os.system("rm a.txt")
file = 'a.txt'

for i in range(3000):
    with open(file, 'a+') as f:
        f.write("a\n")

```


The following two commands need to be executed at the same time

1: run script
```
python3  ~/test_manifest.py
rm: cannot remove 'a.txt': No such file or directory
```

2:  do "ls" in the directory while appending
```
~/tmp/weed_test/mount1$ watch -n 1 ls
```

I get:

```shell
~/tmp/weed_test/mount1$ cat a.txt | wc -l
2998
```

You can see that 2 rows of data lost this time


And i run filer with "-v=2", so i can see logs:
```
I0711 11:04:37.248214 filer_deletion.go:62 deleting fileIds [1,4f16da3ca31c]
I0711 11:04:59.723508 filer_deletion.go:62 deleting fileIds [2,52349c0370b0]
```  
two chunks are deleted.

**Comment by chrislusf** [comment]
any other logs between the 2 AddPage operations?

**Comment by wusongANKANG** [comment]
@chrislusf   I setup mount with "-v=4" .     All logs is here.

**Comment by xdadrm** [comment]
@wusongANKANG  you're right.
wc -lc a.txt
4971 9942 a.txt
