### ISSUE TITLE
When downloading file using awscli it gets slow after around 50% of download

### ISSUE THREAD

**Issue by Volemon** [seaweedfs/seaweedfs#4680]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
When downloading file using awscli it gets slow after around 50% of download.
```
Completed 10.8 MiB/118.6 MiB (200.1 MiB/s) with 1 file(s) remaining
Completed 29.8 MiB/118.6 MiB (322.4 MiB/s) with 1 file(s) remaining
Completed 50.0 MiB/118.6 MiB (10.4 MiB/s)) with 1 file(s) remaining
Completed 70.8 MiB/118.6 MiB (7.4 MiB/s) with 1 file(s) remaining 
```

**Setup:**
I use small docker-swarm cluster setup with 3 filers (default metadata), 3 volume servers, one master. 
- Volume size limit is set to 1024MB
- Replication is set up to 002

**Additional information**
It doesn't seem to be network or drives issue:

iperf3 between nodes gets up to 10Gbps
```
 ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  1.04 GBytes  8.90 Gbits/sec
[  5]   1.00-2.00   sec  1.08 GBytes  9.26 Gbits/sec
[  5]   2.00-3.00   sec  1.07 GBytes  9.23 Gbits/sec
[  5]   3.00-4.00   sec  1.07 GBytes  9.17 Gbits/sec
[  5]   4.00-5.00   sec  1.07 GBytes  9.17 Gbits/sec
```

I also get 6-7k IOPS randread on every node with fio

**Comment by Volemon** [comment]
I'm starting master with (docker CMD) `master -volumeSizeLimitMB=1024 -mdir=/data -defaultReplication=002`
filers with: 'filer -master=seaweedfs_master:9333 -ip.bind=0.0.0.0 -s3 -s3.config=/etc/seaweedfs/s3.json -s3.port=8000 -s3.allowEmptyFolder=false -s3.allowDeleteBucketNotEmpty=false`
and volumes with `volume -dir=/data -mserver=seaweedfs_master:9333 -max=0`

**Comment by chrislusf** [comment]
what is the command to use awscli?

**Comment by Volemon** [comment]
It was `s3 cp`
I typically use apache as proxy to filers and though it might be the issue so i tried both endpoint-urls -> directly to filer and through proxy with https
`aws --endpoint-url=http://172.18.0.4:8000 s3 cp s3://container/testfile ./testfile`

File was uploaded through:
`aws --endpoint-url=http://172.18.0.4:8000 s3 cp ./testfile s3://container/testfile `

**Comment by Volemon** [comment]
I think i have found the problem.
```
/data # iperf3 -c 172.19.67.120 -R
Connecting to host 172.19.67.120, port 5201
Reverse mode, remote host 172.19.67.120 is sending
[  5] local 172.19.67.122 port 43104 connected to 172.19.67.120 port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  6.83 KBytes  55.9 Kbits/sec
[  5]   1.00-2.00   sec   138 KBytes  1.13 Mbits/sec
[  5]   2.00-3.00   sec   423 KBytes  3.47 Mbits/sec
[  5]   3.00-4.00   sec   430 KBytes  3.52 Mbits/sec
[  5]   4.00-5.00   sec   423 KBytes  3.47 Mbits/sec
[  5]   5.00-6.00   sec   430 KBytes  3.52 Mbits/sec
[  5]   6.00-7.00   sec   423 KBytes  3.47 Mbits/sec
[  5]   7.00-8.00   sec   430 KBytes  3.52 Mbits/sec
[  5]   8.00-9.00   sec   423 KBytes  3.47 Mbits/sec
[  5]   9.00-10.00  sec   430 KBytes  3.52 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  3.56 MBytes  2.98 Mbits/sec  1066             sender
[  5]   0.00-10.00  sec  3.47 MBytes  2.91 Mbits/sec                  receiver
```
It seems to be an issue with docker-swarm overlay network. I will bump this issue when I find a solution.

**Comment by Volemon** [comment]
It was GRO enabled on hypervisors which made docker swarm network work very slow.
