### ISSUE TITLE
Git clone failed through S3 gateway

### ISSUE THREAD

**Issue by TDCBQ** [seaweedfs/seaweedfs#4690]
Describe the bug
Database: Mongodb replica set
Version: weed 3.54
Operation: Use s3fs to connect to the S3 gateway of seaweed, unable to git clone seaweedfs.git

![03Q777@C %M3}L}5D8A8Q8I](https://github.com/seaweedfs/seaweedfs/assets/37407560/279bf875-c1d5-477e-b8f8-9d2ee9fc196b)
![$573~Q11(RBTA%$JCZ}SQ_E](https://github.com/seaweedfs/seaweedfs/assets/37407560/962b758f-d56f-4913-ae39-c398ef911237)
![3OI11WKLJ~0Q$JYAWG5S~IK](https://github.com/seaweedfs/seaweedfs/assets/37407560/a8045eeb-d65e-4f83-9bc2-d5b0543e2466)
![image](https://github.com/seaweedfs/seaweedfs/assets/37407560/1a75d3d8-30d8-43e5-9398-25b5c2041495)

**Comment by TDCBQ** [comment]
The same goes for using Mongodb standalone
Quickly building a mongodb environment: docker run -d -p 27017:27017 --name mongodb mongo
![image](https://github.com/seaweedfs/seaweedfs/assets/37407560/3126ccb1-1833-4814-89c9-eb141c41bc43)

**Comment by chrislusf** [comment]
why not just use `weed mount`?

**Comment by TDCBQ** [comment]
1. Sorry, I only found this feature defect during use and hope to find and fix the problem
2. The weed mount lacks the IAM identity authentication for S3, and I only found that there is a problem with using the S3 gateway git clone through S3fs
