### ISSUE TITLE
Is it recommend to launch multiple volume servers per machine?

### ISSUE THREAD

**Issue by k-ye** [seaweedfs/seaweedfs#4717]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/seaweedfs/seaweedfs/discussions

example of a good issue report:
https://github.com/seaweedfs/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/seaweedfs/seaweedfs/issues/1008

**Describe the question**

Just noticed that there is the Discussion section, sorry if I misused the issues...

---

Hi!

I wonder if it's recommended to run multiple volume server processes on a single machine, suppose I have a huge disk? According to https://github.com/seaweedfs/seaweedfs/wiki/Production-Setup#add-volume-servers, the answer seems to be yes, with me configuring the index to use leveldb.

Theoretically, another approach is to give the master a huge `volumeSizeLimitMB`. I'd assume that this could hurt  the peformance, but would still like to get an opinion from you exprts.

Thanks!

**Comment by chrislusf** [comment]
Depending on the use case.

**Comment by k-ye** [comment]
> Depending on the use case.

There is nothing unusual. We just plan to host a FS cluster with lots of small files (MB-ish) for reading.

**Comment by chrislusf** [comment]
either option is ok, assuming there are no deletions.

**Comment by k-ye** [comment]
Thanks!
