### ISSUE TITLE
Error mounting using fuse "getent": executable file not found

### ISSUE THREAD

**Issue by ahsifer** [seaweedfs/seaweedfs#4760]
The following image shows the errors when mounting the seaweed cluster using the mount command. 

![image](https://github.com/seaweedfs/seaweedfs/assets/59507263/8379a6d7-3bf2-4a54-9e51-5e01f3cca978)
However, the cluster is mounted as shown below but there is no change in fstab entries.

![image](https://github.com/seaweedfs/seaweedfs/assets/59507263/fb484b67-98f6-4a6f-8dae-c9156a195900)

**Comment by chrislusf** [comment]
can you use "weed mount" directly?

**Comment by ahsifer** [comment]
@chrislusf  yes I can.

**Comment by ahsifer** [comment]
Also I have tried

![image](https://github.com/seaweedfs/seaweedfs/assets/59507263/9513ac63-09c9-41cc-a6b4-f963f9a76606)

**Comment by chrislusf** [comment]
```

  You can use -t weed on mount command:
  mv weed /sbin/mount.weed
  mount -t weed fuse /mnt -o "filer=localhost:8888,filer.path=/"

  Or you can use -t fuse on mount command:
  mv weed /sbin/weed
  mount -t fuse.weed fuse /mnt -o "filer=localhost:8888,filer.path=/"
  mount -t fuse "weed#fuse" /mnt -o "filer=localhost:8888,filer.path=/"

  To use without mess with your /sbin:
  mount -t fuse./home/user/bin/weed fuse /mnt -o "filer=localhost:8888,filer.path=/"
  mount -t fuse "/home/user/bin/weed#fuse" /mnt -o "filer=localhost:8888,filer.path=/"

  To pass more than one parameter use quotes, example:
  mount -t weed fuse /mnt -o "filer='192.168.0.1:8888,192.168.0.2:8888',filer.path=/"

```

**Comment by ahsifer** [comment]
@chrislusf thanks.
