### ISSUE TITLE
fuse mount full cacheDir will lead to unmount with error transport endpoint is not connected

### ISSUE THREAD

**Issue by ahsifer** [seaweedfs/seaweedfs#4761]
In my case, I want to cache data and metadata in the memory, therefore I have created a 1GB tmpfs (memory cache) mount and reserve 900MB for cacheDir for weed fuse mount. However, in the case of writing large files, the cacheDir is also used to buffer written data before they are sent to the remote storage according to @chrislusf comment https://github.com/seaweedfs/seaweedfs/issues/2586#issuecomment-1011873213 more then 900MB will be used from the cacheDir. Therefore, it will be very helpful to split the written data buffer from cached data and metadata directories because written file size could not be predictable and we cannot increase memory cache because it is expensive. The following image shows how writing random file lead to error=""Transport endpoint is not connected""
![image](https://github.com/seaweedfs/seaweedfs/assets/59507263/8f976c13-b110-4bdd-828e-284eef8a59c5)
and please correct me if I am missing something.

**Comment by chrislusf** [comment]
seems you want to have separate cache for read and write.

**Comment by ahsifer** [comment]
@chrislusf yes, that will be helpful.

**Comment by chrislusf** [comment]
added https://github.com/seaweedfs/seaweedfs/commit/6c7fa567d4b94790f213d0546b365a4e989a0e3d
