### ISSUE TITLE
many volume server with different disk size

### ISSUE THREAD

**Issue by ahengoodman** [seaweedfs/seaweedfs#4823]
1个master服务 + 2个volume服务。
其中1个volume服务有8T的存储，另一个volume服务有4T的存储。
请问，有8T存储的volume服务可以自动存储2/3的数据吗？有4T存储的volume服务可以自动存储1/3的数据吗？
@mountain @bmillemathias @alrs @Radtoo @thinxer 
thanks ！！！

**Comment by chrislusf** [comment]
yes
