### ISSUE TITLE
Seaweed FS S3 server over https does not work

### ISSUE THREAD

**Issue by janekmichalik** [seaweedfs/seaweedfs#4825]
**Describe the bug**
I m trying to configure the seaweedFS S3 server to run over https. I can see the configuration [options](https://github.com/seaweedfs/seaweedfs/blob/f24c7e803f0a14d35e2bb40a2ed838c80b8cf2e8/weed/command/s3.go#L39):
```
s3StandaloneOptions.portHttps = cmdS3.Flag.Int("port.https", 0, "s3 server https listen port")
s3StandaloneOptions.tlsPrivateKey = cmdS3.Flag.String("key.file", "", "path to the TLS private key file")
s3StandaloneOptions.tlsCertificate = cmdS3.Flag.String("cert.file", "", "path to the TLS certificate file")
```
So from my understanding it should work once https port is set with certs. However, those configuration options seem to have no effect, as after I have set them, access to https port is being rejected. 

**System Setup**
```
              exec /usr/bin/weed -logdir=/logs \
              server \
              -dir=/data \
              -s3 \
              -s3.port=8333 \
              -s3.port.https=8443 \
              -s3.config=/etc/seaweedfs/weed.json \
              -volume.max=2000 \  
              -ip=${POD_IP}
```
```
/data $ /usr/bin/weed version
version 30GB 3.54 358b3a489 linux amd64
```

**Expected behavior**
Seaweed FS S3 server working over https.

**Additional context**
I am trying to enable Istio STRICT mTLS mode on my cluster, so its expect client app (boto3) to communicate with seaweed fs server over https.

**Comment by kmlebedev** [comment]
The `s3.port` and `s3.port.https` options are used together only to get both http and https ports at the same time. If you only need an https port, then the `s3.port` and `s3.tls*` options are sufficient
