### ISSUE TITLE
Lots of ec volumes went missing

### ISSUE THREAD

**Issue by wzrdtales** [seaweedfs/seaweedfs#4861]
There are lots of ec volumes we noticed on one cluster that went missing

```
I0923 11:17:30.632873 store_ec.go:218 clearing ec shard 1859.1 locations: read ec shard 1859.1 from dt:8080: receiving ec shard 1859.1 from dt:8080: rpc error: code = Unknown desc = not found ec shard 1859.1
```

Interestingly

```
-rw-r--r-- 1 root root 104M Sep 21 19:21 /mnt/d2/weed/oc-gitlab-packages_1859.ec01
```

This shard exists, but it doesn't seem to be read.

Further debug logs

```
I0923 11:22:16.417412 store_ec.go:155 ReadEcShardNeedle needle id 388dbdabd8e2d2 Size:0, DataSize:0, Name:, Mime: Compressed:false intervals:[{BlockIndex:1028 InnerBlockOffset:379512 Size:669064 IsLargeBlock:false LargeBlockRowsCount:0} {BlockIndex:1029 InnerBlockOffset:0 Size:1048576 IsLargeBlock:false LargeBlockRowsCount:0} {BlockIndex:1030 InnerBlockOffset:0 Size:1048576 IsLargeBlock:false LargeBlockRowsCount:0} {BlockIndex:1031 InnerBlockOffset:0 Size:1048576 IsLargeBlock:false LargeBlockRowsCount:0} {BlockIndex:1032 InnerBlockOffset:0 Size:379640 IsLargeBlock:false LargeBlockRowsCount:0}]
I0923 11:22:16.418249 store_ec.go:288 read remote ec shard 1859.9 from dt71:8080
I0923 11:22:16.425111 store_ec.go:340 recover ec shard 1859.1 from other locations
I0923 11:22:16.425696 store_ec.go:288 read remote ec shard 1859.10 from dt71:8080
I0923 11:22:16.425743 store_ec.go:288 read remote ec shard 1859.9 from dt71:8080
I0923 11:22:16.425792 store_ec.go:288 read remote ec shard 1859.13 from dt64:8080
I0923 11:22:16.425799 store_ec.go:288 read remote ec shard 1859.12 from dt65:8080
I0923 11:22:16.425960 store_ec.go:288 read remote ec shard 1859.4 from dt67:8080
I0923 11:22:16.425710 store_ec.go:288 read remote ec shard 1859.6 from dt64:8080
I0923 11:22:16.426051 store_ec.go:288 read remote ec shard 1859.8 from dt70:8080
I0923 11:22:16.425902 store_ec.go:288 read remote ec shard 1859.0 from dt67:8080
I0923 11:22:16.426091 store_ec.go:288 read remote ec shard 1859.3 from dt68:8080
I0923 11:22:16.426107 store_ec.go:288 read remote ec shard 1859.5 from dt65:8080
I0923 11:22:16.426540 store_ec.go:293 read remote ec shard 1859.6 from dt64:8080: read ec shard 1859.6 from dt64:8080: receiving ec shard 1859.6 from dt64:8080: rpc error: code = Unknown desc = not found ec shard 1859.6
I0923 11:22:16.426568 store_ec.go:288 read remote ec shard 1859.6 from dt66:8080
I0923 11:22:16.426594 store_ec.go:293 read remote ec shard 1859.0 from dt67:8080: read ec shard 1859.0 from dt67:8080: receiving ec shard 1859.0 from dt67:8080: rpc error: code = Unknown desc = not found ec shard 1859.0
I0923 11:22:16.426655 store_ec.go:288 read remote ec shard 1859.0 from dt70:8080
I0923 11:22:16.439100 store_ec.go:388 recovered ec shard 1859.1 from other locations
I0923 11:22:16.440219 store_ec.go:340 recover ec shard 1859.2 from other locations
I0923 11:22:16.440409 store_ec.go:288 read remote ec shard 1859.10 from dt71:8080
I0923 11:22:16.440441 store_ec.go:288 read remote ec shard 1859.9 from dt71:8080
I0923 11:22:16.440494 store_ec.go:288 read remote ec shard 1859.4 from dt67:8080
I0923 11:22:16.440496 store_ec.go:288 read remote ec shard 1859.0 from dt67:8080
I0923 11:22:16.440531 store_ec.go:288 read remote ec shard 1859.12 from dt65:8080
I0923 11:22:16.440542 store_ec.go:288 read remote ec shard 1859.8 from dt70:8080
I0923 11:22:16.440548 store_ec.go:288 read remote ec shard 1859.13 from dt64:8080
I0923 11:22:16.440616 store_ec.go:288 read remote ec shard 1859.3 from dt68:8080
I0923 11:22:16.440657 store_ec.go:288 read remote ec shard 1859.5 from dt65:8080
I0923 11:22:16.440553 store_ec.go:288 read remote ec shard 1859.6 from dt64:8080
I0923 11:22:16.441044 store_ec.go:293 read remote ec shard 1859.0 from dt67:8080: read ec shard 1859.0 from dt67:8080: receiving ec shard 1859.0 from dt67:8080: rpc error: code = Unknown desc = not found ec shard 1859.0
I0923 11:22:16.441074 store_ec.go:288 read remote ec shard 1859.0 from dt70:8080
I0923 11:22:16.441145 store_ec.go:293 read remote ec shard 1859.6 from dt64:8080: read ec shard 1859.6 from dt64:8080: receiving ec shard 1859.6 from dt64:8080: rpc error: code = Unknown desc = not found ec shard 1859.6
I0923 11:22:16.441168 store_ec.go:288 read remote ec shard 1859.6 from dt66:8080
I0923 11:22:16.444783 store_ec.go:388 recovered ec shard 1859.2 from other locations
I0923 11:22:16.445897 volume_server_handlers_read.go:148 read /1859,388dbdabd8e2d2 isNormalVolume false error: readbytes: CRC error! Data On Disk Corrupted
```

However, this was fine just a short time ago. Something in 3.56 or 3.55 seems to have destroyed everything on here.

**Comment by wzrdtales** [comment]
This happened after the upgrade to 3.56, which we downgraded to 3.55 as it has major bugs as it seems

**Comment by wzrdtales** [comment]
We can find multiple instances of for example `ec.00` on different nodes. With different timestamp, looks like the balancing logic is not working properly.

**Comment by wzrdtales** [comment]
First guess is this is caused by ec.balance or ec.rebuild. We guess that b/c just overnight this happened. Some files that are now not accessible anymore, where accessible just yesterday.

Also in the master overview page ErasureCodingShards was showing a `-` number for one node.

**Comment by wzrdtales** [comment]
Has there been significant changes to the ec since `3.43`?

**Comment by chrislusf** [comment]
There were some benign looking error handling changes.

**Comment by wzrdtales** [comment]
@chrislusf See email, for some in depth details that I can't post here in this issue.

Here my last mail also for the issue tracker:

"
so, it took a lot of trial and error.

I was able to recover the file.

The following I did to make it work:

mv /mnt/d3/weed/redacted-2_1859.ec02 /root


What I noticed is, that all 1859 volume files were redacted-1_1859, except for this single one, that was named redacted-2. I moved this 0 byte file (redacted-2) to a different location, and immediately the file download and verify worked again.
"

**Comment by wzrdtales** [comment]
now the question is, how can this happen. Is it normal that there are the same volumeIds for multiple collections @chrislusf ?

**Comment by wzrdtales** [comment]
And one error remains, even though the file is again accessible, it still states 1859:3706301: volumeId 1859 not found with fs.verify

**Comment by wzrdtales** [comment]
command back, the file is again not accessible. hmm

**Comment by wzrdtales** [comment]
so its mostly not working, and just sporadically worked for a moment, now the error changed to ReadEcShardIntervals: too few shards given

**Comment by wzrdtales** [comment]
made it working again, by getting rid of all 0 byte files of volume 1859.

They are being created again and again though. So this is the issue then, at least for this file. Have to check what is going on with the other things @chrislusf

**Comment by wzrdtales** [comment]
the error volumeId 1859 not found in fs.verify remains though

**Comment by wzrdtales** [comment]
So summary:

There are 0 byte .ec** files created. There are duplicates of .ec** files. There are sometimes even duplicates on the same volumeId with a different collection.

How this happened? No idea yet.

**Comment by wzrdtales** [comment]
Found another instance of this pattern (with 5 different collections)

```
-rw-r--r-- 1 root root    0 Sep 22 07:06 /mnt/d4/weed/b1_1857.ec03
-rw-r--r-- 1 root root    0 Sep 22 09:10 /mnt/d4/weed/b2_1857.ec03
-rw-r--r-- 1 root root    0 Sep 22 11:13 /mnt/d4/weed/b3_1857.ec03
-rw-r--r-- 1 root root    0 Sep 22 18:37 /mnt/d1/weed/b4_1857.ec03
-rw-r--r-- 1 root root    0 Sep 22 15:05 /mnt/d1/weed/b5_1857.ec03
```

Not sure yet if this is something expected though @chrislusf

**Comment by chrislusf** [comment]
what is the output of `volume.list`?

there should not be different collection with the same volume id 1857. I do not understand why it happened.

**Comment by wzrdtales** [comment]
```
> volume.list -volumeId 1857
Topology volumeSizeLimit:1024 MB hdd(volume:3976/107208 active:3958 free:103232 remote:0)
  DataCenter dc1 hdd(volume:3976/107208 active:3958 free:103232 remote:0)
    Rack rack1 hdd(volume:3976/107208 active:3958 free:103232 remote:0)
      DataNode dt64:8080 hdd(volume:536/14487 active:534 free:13951 remote:0)
        Disk hdd(volume:536/14487 active:534 free:13951 remote:0)
          ec volume id:1857 collection:buck1 shards:[2 9]
        Disk hdd total size:0 file_count:0 
      DataNode dt64:8080 total size:0 file_count:0 
      DataNode dt65:8080 hdd(volume:537/14488 active:535 free:13951 remote:0)
        Disk hdd(volume:537/14488 active:535 free:13951 remote:0)
          ec volume id:1857 collection:buck1 shards:[1 8]
        Disk hdd total size:0 file_count:0 
      DataNode dt65:8080 total size:0 file_count:0 
      DataNode dt66:8080 hdd(volume:540/14492 active:539 free:13952 remote:0)
        Disk hdd(volume:540/14492 active:539 free:13952 remote:0)
          ec volume id:1857 collection:buck1 shards:[0 7]
        Disk hdd total size:0 file_count:0 
      DataNode dt66:8080 total size:0 file_count:0 
      DataNode dt67:8080 hdd(volume:537/14491 active:534 free:13954 remote:0)
        Disk hdd(volume:537/14491 active:534 free:13954 remote:0)
          ec volume id:1857 collection:buck1 shards:[10]
        Disk hdd total size:0 file_count:0 
      DataNode dt67:8080 total size:0 file_count:0 
      DataNode dt68:8080 hdd(volume:539/14492 active:537 free:13953 remote:0)
        Disk hdd(volume:539/14492 active:537 free:13953 remote:0)
          ec volume id:1857 collection:buck1 shards:[6 13]
        Disk hdd total size:0 file_count:0 
      DataNode dt68:8080 total size:0 file_count:0 
      DataNode dt69:8080 hdd(volume:537/14482 active:532 free:13945 remote:0)
        Disk hdd(volume:537/14482 active:532 free:13945 remote:0)
          ec volume id:1857 collection:buck1 shards:[6 13]
        Disk hdd total size:0 file_count:0 
      DataNode dt69:8080 total size:0 file_count:0 
      DataNode dt70:8080 hdd(volume:533/14391 active:530 free:13858 remote:0)
        Disk hdd(volume:533/14391 active:530 free:13858 remote:0)
          ec volume id:1857 collection:buck1 shards:[4]
        Disk hdd total size:0 file_count:0 
      DataNode dt70:8080 total size:0 file_count:0 
      DataNode dt71:8080 hdd(volume:217/5885 active:217 free:5668 remote:0)
        Disk hdd(volume:217/5885 active:217 free:5668 remote:0)
          ec volume id:1857 collection:buck1 shards:[3 5 11 12]
        Disk hdd total size:0 file_count:0 
      DataNode dt71:8080 total size:0 file_count:0 
    Rack rack1 total size:0 file_count:0 
  DataCenter dc1 total size:0 file_count:0 
total size:0 file_count:0 
```

In the volume list nothing is there of these weird ones.

This cluster is running two filers, leveldb. Is the synchronization between them enforced? I opened earlier a ticket where we noticed already before, that this synchronization does not seem to actually work in all cases. We had keys that exist only in one filer.

We were thinking already to switch to cockroachdb as a backend for the filer, to guarantee the HA, but have yet to test if scaling works with multiple filers accessing the same cockroachdb.

**Comment by chrislusf** [comment]
I do not see this from the `volume.list` output, which all have the same bucket `buck1`.

```
-rw-r--r-- 1 root root    0 Sep 22 07:06 /mnt/d4/weed/b1_1857.ec03
-rw-r--r-- 1 root root    0 Sep 22 09:10 /mnt/d4/weed/b2_1857.ec03
-rw-r--r-- 1 root root    0 Sep 22 11:13 /mnt/d4/weed/b3_1857.ec03
-rw-r--r-- 1 root root    0 Sep 22 18:37 /mnt/d1/weed/b4_1857.ec03
-rw-r--r-- 1 root root    0 Sep 22 15:05 /mnt/d1/weed/b5_1857.ec03
```

**Comment by wzrdtales** [comment]
buck1, is the replacement of original name I did, and equals to b1 of that list.

As you state correct, it is not in the list. That doesn't change the fact that the other output gets generated by `find /mnt/*/weed | grep 1857.ec* | xargs sudo ls -alh` and causes major problems.

**Comment by chrislusf** [comment]
the volume id should never be reused in other collections. I do not understand how it happened.

**Comment by wzrdtales** [comment]
I am studying the code to understand what is happening currently, the most interesting thing about the random files from other collections is, only the actual collection has its vif, ecx and ecj files. The random ones not.

```
-rw-r--r-- 1 root root    0 Sep 21 19:21 /mnt/d2/weed/b1_1857.ecj
-rw-r--r-- 1 root root 4.4K Sep 21 19:21 /mnt/d2/weed/b1_1857.ecx
-rwxr-xr-x 1 root root   78 Sep 21 19:21 /mnt/d2/weed/b1_1857.vif
```

**Comment by wzrdtales** [comment]
I don't have a good guess yet, but its either correlated to the multiple filers (although they should be syncing but as said just before, we already had issues with that not being true and items randomly missing, but I thought that already got fixed, b/c I didn't see this appear again in 3.43)

**Comment by wzrdtales** [comment]
```
"find /mnt/*/weed | grep _1857.* | xargs sudo ls -alh" 
-rw-r--r-- 1 root root    0 Sep 22 18:37 /mnt/d1/weed/b2_1857.ec03
-rw-r--r-- 1 root root    0 Sep 22 15:05 /mnt/d1/weed/b3_1857.ec03
-rw-r--r-- 1 root root 104M Sep 21 19:21 /mnt/d2/weed/b1_1857.ec06
-rw-r--r-- 1 root root 104M Sep 21 19:21 /mnt/d2/weed/b1_1857.ec13
-rw-r--r-- 1 root root    0 Sep 21 19:21 /mnt/d2/weed/b1_1857.ecj
-rw-r--r-- 1 root root 4.4K Sep 21 19:21 /mnt/d2/weed/b1_1857.ecx
-rwxr-xr-x 1 root root   78 Sep 21 19:21 /mnt/d2/weed/b1_1857.vif
-rw-r--r-- 1 root root    0 Sep 22 07:06 /mnt/d4/weed/b3_1857.ec03
-rw-r--r-- 1 root root    0 Sep 22 09:10 /mnt/d4/weed/b4_1857.ec03
-rw-r--r-- 1 root root    0 Sep 22 11:13 /mnt/d4/weed/b5_1857.ec03
```

Looking at this again, according to their timestamp, all of these extra volumeIds, definitely got created **WAY** later, so the volumeId existed for quite som time (multiple hours)

**Comment by wzrdtales** [comment]
Also next question is of course. Why does seaweedfs gets troubled by those foreign collection files. I did not yet find the point where the shards gets read in would be really helpful if you could point me there quickly

**Comment by wzrdtales** [comment]
Btw. this cluster was running fine for a long time on 3.43, troubles started after the upgrade to first 3.56 and then downgrade to 3.55 due to a complete lockup caused by a bug in 3.56 (which you seem to have fixed already but not released yet)

**Comment by chrislusf** [comment]
the system is designed to have only unique volume ids.

**Comment by wzrdtales** [comment]
> the system is designed to have only unique volume ids.

I guessed that, so I can pin point this is happening in `3.55`, according to the timestamps. And nothing special happened.

The targets that come to mind that could cause this are

```
ec.encode -fullPercent=95 -quietFor=1h
ec.rebuild -force
ec.balance -force
```

In 3.24 there was still a bug that was causing `ec.encode -fullPercent=95 -quietFor=1h` to not address collection correctly on its own. So we have had explicit `ec.encode -collection=b1 -fullPercent=95 -quietFor=1h` commands to work around this for a few buckets. In 3.55 this now works as expected. The extra collections on that volumeId actually contain collections that we did not erasure code before, so it can't be any of the explicit encode commands, but the general. And otherwise only the balancing and rebuilding is left.
Again trying currently to work through the logic.

Biggest question for me is why is collection_1857.ec03 and a parallel collection2_1857.ec03 even a problem currently for the  system. I found by now only logic which is explicitly building the name, and nothing that only filters for the ending `_volumeId.ecxx`

**Comment by wzrdtales** [comment]
One more info. It looks like these extra files were always created on the node that was used for the reconstruction action in that moment.

**Comment by wzrdtales** [comment]
Ok, the 0 byte files come could come from here https://github.com/seaweedfs/seaweedfs/blob/76a62859ffaf62bad4e31bbfa7bfdfa28bb7608c/weed/storage/erasure_coding/ec_encoder.go#L104

or https://github.com/seaweedfs/seaweedfs/blob/76a62859ffaf62bad4e31bbfa7bfdfa28bb7608c/weed/storage/erasure_coding/ec_encoder.go#L145

More likely the first one as it looks.

**Comment by wzrdtales** [comment]
Ok, so 0 byte files can be created if there is already a 0 byte file existing: https://github.com/seaweedfs/seaweedfs/blob/76a62859ffaf62bad4e31bbfa7bfdfa28bb7608c/weed/storage/erasure_coding/ec_encoder.go#L259-L261

This return causes the whole rebuild procedure to cancel without writing anything to the new files. But the new 0 byte files are not getting cleaned up as well.

So the possible scenario for a first 0 byte file in the first place might be an unfortunate exit or crash of the volume server. I am not sure if a crash is necessary, or if an exit would be enough. I will try if I can reproduce this with all this information, might be barking at the wrong tree though.

**Comment by wzrdtales** [comment]
That is not an explanation to the foreign collections at all yet though.

**Comment by wzrdtales** [comment]
I wrote a short script

```js
import { globStream } from 'glob'
import fs from 'fs/promises'

const hashmap = {}
const originals = {}
const delay = {}
const pt = '/mnt/d1/weed'.length

const gS = globStream(['/mnt/*/weed/*.ec[0-9][0-9]'])
gS.on('data', async path => {
  const vol = path.substring(path.lastIndexOf('_') + 1, path.length - 5)
  const fin = path.substring(pt, path.length - 5)
  const {size} = await fs.stat(path);

  if (!size) console.log(`0 byte ${path}`)

  if(!hashmap[vol] && size) {
	  hashmap[vol] = fin;
	  originals[vol] = path;
  }
  else if(hashmap[vol] && hashmap[vol] !== fin) {

	  if(originals[vol]) {
	  	console.log(`original ${originals[vol]}`)
		delete originals[vol]
	  }

	  console.log(`duplicate ${path}`, size)
	  delay[vol]?.forEach(x => console.log(`duplicate ${x.path}`, x.size))
	  delete delay[vol]
  } else if(!hashmap[vol] && size) {
	  if(!delay[vol]) delay[vol] = []
	  delay[vol].push({path, size});
  }
})
```
 (needs npm i glob)

To identify these weirdities and also the collection duplicates.

I found with that also instances, where 

```
-rw-r--r-- 1 root root 103M Sep 22 21:11 /mnt/d3/weed/b1_1904.ec04
-rw-r--r-- 1 root root    0 Sep 22 04:09 /mnt/d4/weed/b2_1904.ec04
```

the actual collection came later, than the foreign collection.

The only explanation that I could think of is that `req.Collection` is actually not a stable reference, but could change in the worst case. Everything else makes not much sense yet, but it is happening, just dunno why yet.

**Comment by wzrdtales** [comment]
Even found one example, where there is an instance without collection name + only foreign collections but not the actual one of the same ec shard, in the other cases the ec shard of the actual one was always there.

```
-rw-r--r-- 1 root root 103M Sep 21 20:08 /mnt/d1/weed/b1_1944.ec08
-rw-r--r-- 1 root root    0 Sep 22 04:45 /mnt/d4/weed/b2_1944.ec02
-rw-r--r-- 1 root root 0 Sep 22 05:38 /mnt/d4/weed/1944.ec02
```

**Comment by wzrdtales** [comment]
The only good thing out of all this is, that I get to know the codebase in depth :p

So something I suspected already, the info gets simply extracted by the underscore. Which makes sense of course:

https://github.com/seaweedfs/seaweedfs/blob/76a62859ffaf62bad4e31bbfa7bfdfa28bb7608c/weed/storage/disk_location.go#L109-L116

And regardless of the collection they get added to the same array

https://github.com/seaweedfs/seaweedfs/blob/master/weed/storage/disk_location_ec.go#L160-L173

That is why those foreign collections make trouble... .

I still have no Idea though how this happened. My guess is that the streaming change you reverted maybe is related to this. We had 3.56 running for one day. Then it completely locked up and marked all volumes non writeable and we downgraded to 3.55. So maybe those files were generated by a bug in 3.56 and causing trouble now in 3.55.

So the second logic probably should check also that the collection is not something else, and ignore these files (auto delete is probably only a good idea if it is a 0 byte file)

@chrislusf

**Comment by wzrdtales** [comment]
I think I might have found the issue @chrislusf 

https://github.com/seaweedfs/seaweedfs/blob/23f334dd13f1bf801a6f5df14742db8526b29afe/weed/server/volume_grpc_copy.go#L218

This call is being called without knowing yet whether the file exists or not and creates the file with whatever reached this function.

https://github.com/seaweedfs/seaweedfs/blob/23f334dd13f1bf801a6f5df14742db8526b29afe/weed/server/volume_grpc_erasure_coding.go#L142

This is called by

https://github.com/seaweedfs/seaweedfs/blob/23f334dd13f1bf801a6f5df14742db8526b29afe/weed/shell/command_ec_common.go#L72

which earlier gets called by

https://github.com/seaweedfs/seaweedfs/blob/23f334dd13f1bf801a6f5df14742db8526b29afe/weed/shell/command_ec_balance.go#L278

called by 

https://github.com/seaweedfs/seaweedfs/blob/23f334dd13f1bf801a6f5df14742db8526b29afe/weed/shell/command_ec_balance.go#L472

called by

https://github.com/seaweedfs/seaweedfs/blob/23f334dd13f1bf801a6f5df14742db8526b29afe/weed/shell/command_ec_balance.go#L359

The collection is not in a single step retrieved from the shard itself, nor the shards get filtered in any step by the collection being passed as parameter. But the initial collection name is what will reach the final copy command in the end. I might have missed something, but checked it multiple times now


T

**Comment by wzrdtales** [comment]
Let me know if I missed something and am wrong @chrislusf , am on the road for the next few hours again.

**Comment by chrislusf** [comment]
The call graph is correct.

**Comment by wzrdtales** [comment]
ok then this is the issue then
