### ISSUE TITLE
helm chart support for full jwt authentication and self certificate

### ISSUE THREAD

**Issue by yuvalyacoby** [seaweedfs/seaweedfs#4891]
Hello,
We use Seaweedfs in k8s, and we deploy it with the repo helm chart.
We are trying to enable all the security features and have encountered some problems:
1. In the helm chart, the `security.toml` is generated in the `security-configmap.yaml` template. In this file, only the `[jwt.signing]` entry is available, and there is no way to include also volume read jwt and filer update and read jwt. missing entries for:
```
[jwt.signing.read]
[jwt.filer_signing]
[jwt.filer_signing.read]
```
2. Once we edit this file and add these entries, the filer `livenessProbe` is failing with `401` `wrong jwt`. I see that for volume for example we have a `/status` route for this purpose that doesn't require jwt. Is there a similar route for filer? couldn't find one. Without it we can't enable the jwt protection, since the pod is failing liveness.
3. We use our own self-signed certificate in our cluster for several services, and would like to use the same certificate when making https calls to Seaweed. I see the helm chart is creating it's own CA and certificates and auto mount them when setting `enableSecurity=true`. Is there a way to utilize our own self signed certificates via the helm chart configuration?

If these things are indeed not supported in the helm, we will happily make a PR to add them, but wanted to check if maybe I've missed it before starting, and also if you have a recommendation/suggestion on how to easily add these features.
I think 1 and 2 are pretty straight-forward, 3 a bit more complex due to the extensiveness of how `enableSecurity` is currently used in the templates.

Thanks!

**Comment by chrislusf** [comment]
Yes,PRs are welcome!
