### ISSUE TITLE
volume.configure.replication seems to not work

### ISSUE THREAD

**Issue by zehweh** [seaweedfs/seaweedfs#4934]
**Describe the bug**
When using volume.configure.replication, the actual volume files still retain their old configuration.

**Test case**

Start a weed master (defaultReplication=020) and 3 volume servers: 

```
weed master -defaultReplication=020
weed volume -port=8081 -dir=/tmp/volume1 -max=100 -mserver="127.0.0.1:9333" -dataCenter=dc1 -rack=rack1
weed volume -port=8082 -dir=/tmp/volume2 -max=100 -mserver="127.0.0.1:9333" -dataCenter=dc1 -rack=rack2
weed volume -port=8083 -dir=/tmp/volume3 -max=100 -mserver="127.0.0.1:9333" -dataCenter=dc1 -rack=rack3
```

Create some volumes:
```
curl http://localhost:9333/dir/assign
```

It should look like this:
![Screenshot from 2023-10-23 16-49-42](https://github.com/seaweedfs/seaweedfs/assets/7746192/e9eea85c-6f77-4d12-9b48-740d0cd94c59)

Now, let's change the replication settings using weed shell:

```
weed shell
volume.configure.replication -collectionPattern * -replication 010
```

The volume servers correctly show the change in the logs:
``` 
I1023 14:52:01.272205 disk_location.go:182 data file /tmp/volume2/1.dat, replication=010 v=3 size=8 ttl=
```
The API also thinks, it is changed:
```
$ curl http://localhost:9333/vol/status?pretty=y|grep "ReplicaPlacement" -A 2

              "ReplicaPlacement": {
                "rack": 1
              },
```

But when we look at the .dat files using `change_superblock.go`, we see that it is still 020:

```
$ go run change_superblock.go -volumeId=1 -dir=/tmp/volume1
Current Volume Replication: 020
Current Volume TTL:
```

Just to make sure, we run some tests.

First, we fix the replication:
```
$ weed shell
lock
volume.fix.replication

> volume 2 replication 010, but over replicated +3
> volume 3 replication 010, but over replicated +3
> volume 1 replication 010, but over replicated +3
> deleting volume 2 from 10.23.1.43:8083 ...
> deleting volume 3 from 10.23.1.43:8083 ...
> deleting volume 1 from 10.23.1.43:8083 ...
```

Looks good. We now have 2 copies of every volume file:
![Screenshot from 2023-10-23 16-58-31](https://github.com/seaweedfs/seaweedfs/assets/7746192/58ec1a28-2cde-4d3d-a590-127338fcd9ca)

If we delete one and fix replication again, it should add it back.

```
weed shell
lock
volume.delete -node  10.23.1.43:8081 -volumeId 1
volume.fix.replication

> the number of locations for volume 1 has not increased yet, let's wait
> the number of locations for volume 1 has not increased yet, let's wait
> the number of locations for volume 1 has not increased yet, let's wait
> the number of locations for volume 1 has not increased yet, let's wait
> the number of locations for volume 1 has not increased yet, let's wait
> error: replicas volume 1 mismatch in topology
```

It did restore the missing copy but showed the error `error: replicas volume 1 mismatch in topology`.
The volume server log shows that it added the volume with replication 020:
```
I1023 15:03:29.264620 disk_location.go:182 data file /tmp/volume3/1.dat, replication=020 v=3 size=8 ttl=
```

If we query the API, it now also shows replication 020 for the restored copy:
```
curl http://localhost:9333/vol/status?pretty=y|grep "ReplicaPlacement" -A 2

             "ReplicaPlacement": {
                "rack": 1
              },
             "ReplicaPlacement": {
                "rack": 2
              },
```

**System Setup**
- Ubuntu 22.04
- output of `weed version`: version 30GB 3.57 0f8168c0c928bba3d2f48b0680d3bdce9c617559 linux amd64

**Expected behavior**
`volume.configure.replication` changes the replication setting in the volume files.

**Comment by zehweh** [comment]
Ok, I seem to have missed, that the superblock is no longer used for storing the replication settings. We now have a `.vif` file.

So the actual problem is not `volume.configure.replication`, it is `volume.fix.replication`, specifically this line:

https://github.com/seaweedfs/seaweedfs/blob/master/weed/server/volume_grpc_copy.go#L150

When `volume.fix.replication` copies all the files, it uses `volFileInfoResp.DatFileSize` as filesize for the `.vif` file while it is actually the filesize of the `.dat` file.
In my test case, the `.dat` file contains only the superblock (8 bytes). So it only copys 8 bytes of the `.vif` file which looks like this:

```
{
  "fil
```

Since the `.vif` file is broken, the volume server falls back to the superblock and shows 020 as replication.

**Comment by chrislusf** [comment]
Yes, the superblock and `.vif` should be in sync. Need to fix `volume.configure.replication`.

**Comment by chrislusf** [comment]
> So the actual problem is not `volume.configure.replication`, it is `volume.fix.replication`, specifically this line:
> 
> https://github.com/seaweedfs/seaweedfs/blob/master/weed/server/volume_grpc_copy.go#L150
> 
> When `volume.fix.replication` copies all the files, it uses `volFileInfoResp.DatFileSize` as filesize for the `.vif` file while it is actually the filesize of the `.dat` file.

This is a long-time bug that should have been fixed.
