### ISSUE TITLE
Path specific filer store writes to wrong db

### ISSUE THREAD

**Issue by Ochita** [seaweedfs/seaweedfs#4942]
**Describe the bug**
When writing to different s3 buckets, the filer writes metadata to the wrong database. 
For example, python script writes files to s3 bucket "incrops" and than another script starts writing to the "facebook" bucket. The filer creates a filemeta document with directory field equal to "k" in the "instagram_crops" database for new facebook files. At the same time, I used the command "aws s3 cp" to copy the test file to the "instagram" buket and filer creates a filemeta document with directory field equal to "am" in database "instagram_crops" for this file. 
If you first run the script for "facebook" bucket and only then for "instagram" bucket, the filer will create a filemeta document with a field equal to "m" in the "facebook_files" database for new instagram files.

![db](https://github.com/seaweedfs/seaweedfs/assets/8088126/fc3d7f89-3e66-48d4-9989-021b13f5cbd9)

**System Setup**
- weed volume -index=leveldbMedium -dir=/mnt/sda/seaweed -max=25 -mserver=host:port -ip=*** -port=*** -dataCenter=dc1 -rack=rack1 and 11 more with different rack  and path and port. 1 volume process per disk
- weed master -mdir=/home/seaweed/master -volumeSizeLimitMB=500000 -volumePreallocate -ip=*** -defaultReplication=010
- weed filer -ip=*** -master=host:port -defaultReplicaPlacement=010
- weed s3 -ip.bind=*** -port=*** -config=/etc/seaweedfs/s3conf.json
- Ubuntu 20.04.6 LTS
- weed version 8000GB 3.57 0f8168c0c928bba3d2f48b0680d3bdce9c617559 linux amd64
-  `filer.toml`
>  [mongodb]
> enabled = true
> uri = "uri"
> option_pool_size = 16
> database = "seaweed"
> 
> 
> [mongodb.buckets.facebook]
> enabled = true
> location = "/buckets/facebook/"
> uri = "uri"
> option_pool_size = 8
> database = "facebook_files"
> 
> 
> [mongodb.buckets.instagram]
> enabled = true
> location = "/buckets/instagram/"
> uri = "uri"
> option_pool_size = 8
> database = "instagram_files"
> 
> 
> [mongodb.buckets.twitter]
> enabled = true
> location = "/buckets/twitter/"
> uri = "uri"
> option_pool_size = 8 
> database = "twitter_files"
> 
> 
> [mongodb.buckets.tiktok]
> enabled = true
> location = "/buckets/tiktok/"
> uri = "uri"
> option_pool_size = 8
> database = "tiktok_files"
> 
> 
> [mongodb.buckets.incrops]
> enabled = true
> location = "/buckets/incrops/"
> uri = "uri"
> option_pool_size = 8
> database = "instagram_crops"

and more (total 10 buckets, but I tried with reduced config like above)

**Expected behavior**
Writing data to different buckets results in writing metadata to the corresponding databases, different for each bucket.

**Additional context**
In filer.toml mongodb uri is the same in all blocks cause all databases in same sharded cluster.
We need separate mongodb collections for each bucket cause our buckets are big and also we calculate some specific stats using mongodb aggregations which performs faster in disared case.

**Comment by Ochita** [comment]
I updated the issue. Is it ok now?

**Comment by chrislusf** [comment]
what is `incrops` in the description? I guess you mean `instagram_crops`? Please be accurate.

**Comment by Ochita** [comment]
It's actual directory field values. I think these values ​​depend on the name of the failed bucket. but they has variable lengh, in some cases I got "tagram" for instagram bucket, when its metadata goes to wrong database.

**Comment by Ochita** [comment]
I tried to set up different database account for each bucket, and it starts to write in different bucket. In my case if I firstly write to incrops bucket after restart, than all files writed to instagram bucket goes to incrops and showed by 'ls' command.

Also if I tried to crate instagram-crops bucket it just uses directory "-crops" in instagram bucket and all filemeta goes to instagram_files database, thats why I mess up with strange bucket names.

Seems like I need to try to set up different endpoint per bucket...

**Comment by Ochita** [comment]
I tried to set up different database account for each bucket, and it has no effect. But I figure out that replacement from my previous comment equals 7 letters cause word "incrops" is 7 letters length. if I change it than directory names changed to other substrings or filemeta starts to write in / directory and appears in other bucket. For example, I tested it with "instcrops" instead "incrops" bucket. "instcrops" same length as "instagram" so all files goes to bucket wich triggered first and appears by ls command in this bucket.

Seems like I need to try to set up different s3 proxy and filer per bucket...

**Comment by Ochita** [comment]
I managed to fix the problem by changing the names of the configurations in the filer.toml file. I removed ".bucket" from the name and left only 2 parts separated by a dot, like this
 `filer.toml`
> [mongodb.facebook]
> enabled = true
> location = "/buckets/facebook/"
> uri = "uri"
> option_pool_size = 8
> database = "facebook_files"
> 
> 
> [mongodb.instagram]
> enabled = true
> location = "/buckets/instagram/"
> uri = "uri"
> option_pool_size = 8
> database = "instagram_files"
> 
> 
> [mongodb.twitter]
> enabled = true
> location = "/buckets/twitter/"
> uri = "uri"
> option_pool_size = 8 
> database = "twitter_files"
> 
> 
> [mongodb.tiktok]
> enabled = true
> location = "/buckets/tiktok/"
> uri = "uri"
> option_pool_size = 8
> database = "tiktok_files"
> 
> 
> [mongodb.instagram-crops]
> enabled = true
> location = "/buckets/instagram-crops/"
> uri = "uri"
> option_pool_size = 8
> database = "instagram_crops"

And after that all works as desired. With same db account and proper bucket names.

**Comment by chrislusf** [comment]
Good to know! And right, the values in toml are hierarchical.
