### ISSUE TITLE
Filer's tikv filestore's prefix query error

### ISSUE THREAD

**Issue by duanhongyi** [seaweedfs/seaweedfs#4950]
Assuming I use the mini mc client.

Add an mc config:
```
#   mc config host add storage "${S3_ENDPOINT}" ${S3_ACCESSKEY} ${S3_SECRETKEY} --lookup path --api s3v4
```

Upload a file using the s3 API:
```
# mc cp /opt/go/bin/go storage/opt/go/bin/go
```

Test prefix query:
```
# mc ls  storage/opt/go/
```
The above command output is empty.

Test prefix query:
```
# mc ls  storage/opt/go/bin/
```
The above command output is empty.

Test prefix query:
```
# mc ls  storage/opt/go/bin/g
[2023-10-26 08:40:29 CST]  12MiB STANDARD go
```
The above command outputs normal results.

Test prefix query:
```
# mc ls  storage/opt/go/bin/go
```
The above command output is empty.

Other implementations such as leveldb, sqlite, and rocksdb can all return correctly. 
I suspect it's the problem with this function: https://github.com/seaweedfs/seaweedfs/blob/master/weed/filer/tikv/tikv_store.go#L210

**Comment by duanhongyi** [comment]
This issue can lead to errors in some applications that rely on prefix queries, such as [Container Registry](https://github.com/distribution/distribution).

**Comment by duanhongyi** [comment]
The same goes for using boto3 clients:

```
import boto3
import subprocess

ip = subprocess.getoutput('podman inspect --format "{{ .NetworkSettings.IPAddress }}" test-storage-metanode-weed')
client = boto3.client('s3', 
    endpoint_url='http://%s:8333' % ip, 
    config=boto3.session.Config(signature_version='s3v4'),
    aws_access_key_id='f4c4281665bc11ee8e0400163e04a9cd',
    aws_secret_access_key='f4c4281665bc11ee8e0400163e04a9cd',
)

keyCount = client.list_objects_v2(Bucket="opt",  MaxKeys=1000, Prefix="go")["KeyCount"]
print("KeyCount: %s" % keyCount) # KeyCount: 0 

keyCount = client.list_objects_v2(Bucket="opt",  MaxKeys=1000, Prefix="go/bin/")["KeyCount"]
print("KeyCount: %s" % keyCount) # KeyCount: 0 

keyCount = client.list_objects_v2(Bucket="opt",  MaxKeys=1000, Prefix="go/bin/g")["KeyCount"]
print("KeyCount: %s" % keyCount) # KeyCount: 1

keyCount = client.list_objects_v2(Bucket="opt",  MaxKeys=1000, Prefix="go/bin/go")["KeyCount"]
print("KeyCount: %s" % keyCount) # KeyCount: 0
```

**Comment by chrislusf** [comment]
which version? Try to use the git tip code.

**Comment by duanhongyi** [comment]
@chrislusf git master

**Comment by duanhongyi** [comment]
> which version? Try to use the git tip code.

I have made some modifications to the code and the problem has been basically resolved. I will strive to submit a PR this afternoon.

**Comment by duanhongyi** [comment]
#4952
