### ISSUE TITLE
webdav bug creates directories in wrong folder

### ISSUE THREAD

**Issue by Cottand** [seaweedfs/seaweedfs#4967]
**Describe the bug**
When using `weed webdav -filer.path` for a non `/` path, folders get created on the `/` of the filer instance the `weed webdav` is connected to

**System Setup**
weed 3.58

on seaweedfs docker container, arguments used for webdav:
```
          -logtostderr
          webdav
          -collection=arman
          -replication=010
          -port=${NOMAD_PORT_webdav}
          -filer=seaweedfs-filer-http.nomad:8888.18888
          -filer.path=/buckets/arman
          -cacheDir=/alloc/data/
          -cacheCapacityMB=1024
```
on seaweedfs docker container, arguments used for filer:
```
          -logtostderr
          filer
          -ip=${NOMAD_IP_http}
          -ip.bind=0.0.0.0
          -master=seaweedfs-master-http.nomad:${var.master_port_http}.${var.master_port_grpc}
          -port=${NOMAD_PORT_http}
          -port.grpc=${NOMAD_PORT_grpc}
          -metricsPort=${NOMAD_PORT_metrics}
          -webdav
          -webdav.collection=
          -webdav.replication=020
          -webdav.port=${NOMAD_PORT_webdav}
```

(so as you can see I am running a normal webdav instance with filer, and I am trying to set up a new one on a different container that points to a different path)

**Expected behavior**
When creating a folder in `weed webdav -filer.path=/buckets/arman` directory gets created under `/buckets/arman` in filer (for the example above).

**Actual Behaviour**
It gets created under the top-level `/` instead

**Comment by chrislusf** [comment]
There are 2 WebDAV servers started with your commands.

**Comment by Cottand** [comment]
Yes correct - the bug where the folder gets created under the wrong path happens when using the first WebDAV server, when using `webdav filer.path=...` and creating a folder with the WebDAV API there.

I would expect both of them to be able to coexist (nothing in the wiki says they cannot). I can try with a single one later today and report back.

**Comment by Cottand** [comment]
Here are the logs of the `weed webdav -filer.path=/buckets/arman` container when reproducing the issue.
what I did:
- start the webdav server and connect to it (with the MacOS finder WebDav client, as described [here](https://github.com/seaweedfs/seaweedfs/wiki/WebDAV#access-seaweedfs-via-webdav-on-mac))
- run `mkdir hi3` in the mounted folder (which can be found under `/Volumes` in MacOS 


```
I1031 11:33:44.826958 webdav_server.go:163 WebDavFileSystem.Mkdir /hi3
I1031 11:33:44.865382 filer_client.go:42 read /hi3/ <nil>: filer: no entry is found in filer store
I1031 11:33:44.865455 webdav_server.go:197 mkdir: directory:"/hi3"  entry:{is_directory:true  attributes:{mtime:1698752024  file_mode:2147484159  crtime:1698752024}}  signatures:-1514080707
I1031 11:33:44.944887 webdav_server.go:382 WebDavFileSystem.Stat /buckets/arman/._hi3
I1031 11:33:44.964318 filer_client.go:42 read /buckets/arman/._hi3 <nil>: filer: no entry is found in filer store
I1031 11:33:45.157272 webdav_server.go:382 WebDavFileSystem.Stat /buckets/arman/hi3/
I1031 11:33:45.160596 filer_client.go:42 read /buckets/arman/hi3/ <nil>: filer: no entry is found in filer store
```

as you can see, the webdav client just sends mkdir `/hi3` because from its PoV that is the root, even if it corresponds to `/buckets/arman` in the filer. I think the solution for this is probably around [webdav_server -> MkDir()](https://github.com/seaweedfs/seaweedfs/blob/master/weed/server/webdav_server.go#L161). Unlike `OpenFile()` or `Stat()` it does not have the following:

```go
	// Add filer.path
	fullFilePath = fs.option.FilerRootPath + fullFilePath
```

I _think_  this bug might also be present for `RemoveAll()` and `Rename()`
