### ISSUE TITLE
[mount] git clone fails

### ISSUE THREAD

**Issue by wozeparrot** [seaweedfs/seaweedfs#4973]
**Describe the bug**
When cloning a large repository (in this case https://github.com/NixOS/nixpkgs) the cloned pack is corrupted.

Bisect points to d4566d4aaa426b33015780c7cc18f887fc07cca4 as the bad commit, which is supposed to be a commit that makes `weed mount` more solid.

Tested on latest master.
![image](https://github.com/seaweedfs/seaweedfs/assets/25372613/74ee462a-d11e-4883-a894-804080759fa6)

Not sure if relevant but when git fails, `weed mount` prints:
```
read old data2 40010417 ns
read old data2 39947119 ns
read old data2 39928073 ns
read old data2 39865826 ns
read old data2 39849034 ns
read old data2 39784984 ns
read old data2 39766860 ns
read old data2 39696708 ns
read old data2 39679346 ns
read old data2 39615075 ns
read old data2 39595198 ns
read old data2 39533462 ns
```

**System Setup**
Start seaweedfs server: `weed server -dir=./data/ -filer`
Mount: `weed mount -dir ./mnt/`

**Expected behavior**
`git clone` does not fail.

**Additional context**
```
# weed version [built on commit d401e374f7aef02f5fd367c79c0be6778aca2042]
version 30GB 3.58  linux amd64
```

**Comment by okgolove** [comment]
It seems this is the same issue
https://github.com/seaweedfs/seaweedfs/issues/5412

**Comment by Jackbennett** [comment]
Not mentioned in the above referenced issue but I was also seeing a lot of `read old data <digits>ns` in the logs before error.
