### ISSUE TITLE
fs.mergeVolumes not working

### ISSUE THREAD

**Issue by isjo-org** [seaweedfs/seaweedfs#4989]
Hello, i tried to use this feature ( #https://github.com/seaweedfs/seaweedfs/pull/4907 ), but for me its not working?

**Describe the bug**
i got 2 volumes
`volume id:223 size:35573152 collection:"test" file_count:87 delete_count:9 deleted_byte_count:3949495 version:3 compact_revision:7 modified_at_second:1699371434`
`volume id:221 size:35585280 collection:"test" file_count:90 delete_count:10 deleted_byte_count:4383618 version:3 compact_revision:6 modified_at_second:1699371488 
`
now i trie to merge them via weed shell
`fs.mergeVolumes -fromVolumeId 223 -toVolumeId 221 -apply`

nothing happens, there is no output, also no log on master with v4

any idea?

**System Setup**
3 Master, 3 Filer, 4 Volume Server, each on Debian 11 + SeaweedFS 30GB 3.58

> weed master -options=/etc/seaweedfs/weed-master.conf
> root@01:~# cat /etc/seaweedfs/weed-master.conf 
> 
> ip=1
> defaultReplication=001
> peers=**1**:9333,**2**:9333,**3**:9333
> volumeSizeLimitMB=1024
> mdir=/var/weed-master
> metricsPort=9988
> v=4

> weed filer -options=/etc/seaweedfs/weed-filer.conf (**using cockroachdb @ /etc/seaweedfs/filer.toml **)
> root@01:~# cat /etc/seaweedfs/weed-filer.conf 
> 
> ip=1
> master=**1**:9333,**2**:9333,**3**:9333
> defaultReplicaPlacement=000
> metricsPort=9986
> s3=True
> s3.port=8333
> s3.config=/etc/seaweedfs/weed-filer-s3.json
> 
> webdav=True
> webdav.port=7333
> webdav.collection=webdav
> webdav.filer.path=/dav-test

> weed volume -options=/etc/seaweedfs/weed-volume.conf
> root@store-2:~# cat /etc/seaweedfs/weed-volume.conf 
> 
> ip=5
> mserver=**1**:9333,**2**:9333,**3**:9333
> max=0
> metricsPort=9987
> 
> dir=/var/weed-data1
> rack=R1
> dataCenter=Wurscht
> minFreeSpace=15

**Expected behavior**
volumes 223 merged to volume 221

**Comment by yeganemehr** [comment]
Hi

Since it must work with filer and files, you must provide a path to begin find and update files in filer database. So try this:
```
fs.mergeVolumes -fromVolumeId 223 -toVolumeId 221 -apply /buckets/
```
Or replace `/buckets/` with any directory path in your filer filesystem.

**Comment by isjo-org** [comment]
true that, many thanks, reading helps :)

working like a charm!
