### ISSUE TITLE
Incorrect write operations into s3 storage

### ISSUE THREAD

**Issue by Alexsandr-Random** [seaweedfs/seaweedfs#5058]
**Describe the bug**
There is a timeout in the drone.
In drone, the timeout occurs because the registry cannot replace/delete data in s3 when pushing a new image.
When debugging seaweedfs we found this:
14:45:48.998311 filer_delete_entry.go:79 deleting a folder /buckets/registry/docker/registry/v2/repositories/sandbox-dev-node/_uploads/909441e1-0daa-4b8c-9841-68bec38bf30d **has children: hashstates ...**

When we using the same setup but in linux fs itself - everything works perfectly. 
No one errors found anywhere except seaweedfs.

**System Setup**
setup:
drone (2 runners)
docker-registry with image storage in s3 (seaweedfs)

- OS version - Ubuntu 22.04 LTS
- version 30GB 3.59 27b34f379 linux amd64
- seaweedfs cluster runs under Nomad into docker
#### Commands to start each service:
- 
          "master",
          "-mdir=/var/local/seaweedfs/master",
          "-peers=10.44.1.11:9333,10.44.1.12:9333,10.44.1.13:9333",
          "-ip=${meta.vlan}",
          "-ip.bind=0.0.0.0",
          "-volumeSizeLimitMB=1024",
          "-defaultReplication=010"

-           "volume",
          "-mserver=10.44.1.11:9333,10.44.1.12:9333,10.44.1.13:9333",
          "-dataCenter=${node.datacenter}",
          "-rack=${node.unique.name}",
          "-ip.bind=0.0.0.0",
          "-dir=/var/local/seaweedfs/volume",
          "-ip=${meta.vlan}",
          "-port=${NOMAD_PORT_http}",
          "-port.grpc=${NOMAD_PORT_grpc}",
          "-idleTimeout=5",

-           "filer",
          "-dataCenter=${node.datacenter}",
          "-master=10.44.1.11:9333,10.44.1.12:9333,10.44.1.13:9333",
          "-ip.bind=0.0.0.0",
          "-ip=${meta.vlan}",
          "-port=${NOMAD_PORT_filer}",
          "-s3",
          "-s3.port=${NOMAD_PORT_s3}"
- if using filer, show the content of `filer.toml`
```bash
cat /local/filer.toml
[filer.options]
recursive_delete = true

[leveldb3]
enabled = true
dir = "/var/local/seaweedfs/filerldb3"
```

**Expected behavior**
docker-registry writes data correctly into s3 storage

**Additional context**
s3 setup: 
```json
{
  "identities":  [
    {
      "name":  "registry",
      "credentials":  [
        {
          "accessKey":  "secret123",
          "secretKey":  "secret12345"
        }
      ],
      "actions":  [
        "Read:registry",
        "Write:registry",
        "List:registry",
        "Tagging:registry",
        "Admin:registry"
      ],
      "account":  null
    },
```

docker-registry - latest version
seaweedfs - latest (ver 3.59)
drone - latest version

**Comment by Alexsandr-Random** [comment]
option 
s3.allowEmptyFolder=false
does not resolve issue. 
More verbose errors output: 

I1129 11:09:02.082294 filer_delete_entry.go:79 deleting a folder /buckets/registry/docker/registry/v2/repositories/sandbox-dev-node/_uploads/2c53aa7f-dce7-45de-9b75-cccee4549466 has children: hashstates ...
I1129 11:09:02.082312 filer_delete_entry.go:41 delete directory /buckets/registry/docker/registry/v2/repositories/sandbox-dev-node/_uploads/2c53aa7f-dce7-45de-9b75-cccee4549466: fail to delete non-empty folder: /buckets/registry/docker/registry/v2/repositories/sandbox-dev-node/_uploads/2c53aa7f-dce7-45de-9b75-cccee4549466
I1129 11:09:02.083291 filer_delete_entry.go:79 deleting a folder /buckets/registry/docker/registry/v2/repositories/sandbox-dev-node/_uploads has children: 334adfdf-7021-4378-b382-fca94f46184d ...
I1129 11:09:02.083309 filer_delete_entry.go:41 delete directory /buckets/registry/docker/registry/v2/repositories/sandbox-dev-node/_uploads: fail to delete non-empty folder: /buckets/registry/docker/registry/v2/repositories/sandbox-dev-node/_uploads

**Comment by chrislusf** [comment]
Please try this:

s3.allowEmptyFolder=true

**Comment by Alexsandr-Random** [comment]
The issue was related to the incorrect behavior of the registry garbage collector, which was damaging some files during cleanup due to the use of the **-m option** (a flag --delete-untagged that removes unreferenced blobs).

Executing the following command was causing problems:

```bash

exec -it registry registry garbage-collect /etc/docker/registry/config.yml -m
```

There are several issues associated with **-m option**, and one relevant link is: [GitHub Issue #3178](https://github.com/distribution/distribution/issues/3178).

The problem reported in this issue is that manifests stored in sub-repositories get deleted by garbage-collect with the -m flag, even though they are part of a fat manifest in the main repository.
