### ISSUE TITLE
Master assigns no volume IDs to remote volume server

### ISSUE THREAD

**Issue by Material-Scientist** [seaweedfs/seaweedfs#5099]
**Describe the bug**
Volume server on machine B is registered by master on machine A, but no volume IDs are assigned because of `rpc error: code = Unknown desc = ping master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:19333: connect: connection refused"`, as shown via `cluster.check` in `weed shell`.

The error appears when the master on machine A tries to make the volume server on machine B ping the master on its loopback address instead of the public IP:
`checking volume server 128.xxx.xx.181:8080 to master localhost:9333`.

**System Setup**
The master was launched on machine A with:
`weed master -port=9333 -defaultReplication=000 -ip="162.xx.xxx.77" -ip.bind="162.xx.xxx.77"`

The volume server was launched on machine B with:
`weed volume -dir="/root/test" -mserver="162.xx.xxx.77:9333" -port=8080 -dataCenter=dc3 -rack=rack1 -max=1`

- OS version: `Ubuntu 22.04.3`
- output of `weed version`: `version 30GB 3.59 27b34f37935fb3eddb9c7759acf397dbae20eb03 linux amd64`

**Expected behavior**
The master is supposed to have the remote volume server ping it on the public IP, not the master's loopback address.

**Screenshots**
- Local volume server (how it's supposed to look):
![image](https://github.com/seaweedfs/seaweedfs/assets/40465719/f26b348e-d4e6-4b98-811d-f1e7729ba514)

- Remote volume server (error):
![image](https://github.com/seaweedfs/seaweedfs/assets/40465719/db3f276a-0e56-4c03-8923-612d7208580a)

**Additional context**
- The firewalls have been configured to allow ports [8080, 9333, 18080, 19333] between both machines (via ufw), and a ping from machine B while the services are running shows that the machines can connect through these ports:
```bash
nc -zv 162.xx.xxx.77 9333
Connection to 162.xx.xxx.77 9333 port [tcp/*] succeeded!
```
```bash
nc -zv 162.xx.xxx.77 19333
Connection to 162.xx.xxx.77 19333 port [tcp/*] succeeded!
``` 

- Netstat on master server:
```bash
netstat -natp -tlnp |grep weed
tcp        0      0 127.0.0.1:19333         0.0.0.0:*               LISTEN      5389/weed           
tcp        0      0 162.xx.xxx.77:19333     0.0.0.0:*               LISTEN      5389/weed           
tcp        0      0 162.xx.xxx.77:9333      0.0.0.0:*               LISTEN      5389/weed           
tcp        0      0 127.0.0.1:9333          0.0.0.0:*               LISTEN      5389/weed           
tcp        0      0 162.xx.xxx.77:47296     162.xx.xxx.77:19333     ESTABLISHED 5389/weed           
tcp        0      0 162.xx.xxx.77:19333     128.xxx.xx.181:60684    ESTABLISHED 5389/weed           
tcp        0      0 162.xx.xxx.77:19333     128.xxx.xx.181:60694    ESTABLISHED 5389/weed           
tcp        0      0 162.xx.xxx.77:19333     162.xx.xxx.77:47296     ESTABLISHED 5389/weed 
```

- Netstat on volume server:
```bash
netstat -natp -tlnp |grep weed
tcp        0      0 128.xxx.xx.181:18080    0.0.0.0:*               LISTEN      3006368/weed        
tcp        0      0 128.xxx.xx.181:8080     0.0.0.0:*               LISTEN      3006368/weed        
tcp        0      0 128.xxx.xx.181:60694    162.xx.xxx.77:19333     ESTABLISHED 3006368/weed        
tcp        0      0 128.xxx.xx.181:60684    162.xx.xxx.77:19333     ESTABLISHED 3006368/weed  
```

As you can see, the machines have established connections on port `19333`, but the master server still additionally hosts connections to port `9333 `on `127.0.0.1`, despite having been configured with `-ip="162.xx.xxx.77" -ip.bind="162.xx.xxx.77"`, and subsequently wants machine B to connect to the master on the master's loopback address. Also, the first connection on port `9333` obviously works as the volume server would not otherwise show up in the 2nd screenshot.

**Comment by chrislusf** [comment]
```
weed volume -dir="/root/test" -mserver="162.xx.xxx.77:9333" -port=8080 -dataCenter=dc3 -rack=rack1 -max=1
```
try adding `-ip=xxxxxx`

**Comment by Material-Scientist** [comment]
Tried with:

```bash
weed volume -dir="/root/test" -mserver="162.xx.xxx.77:9333" -port=8080 -dataCenter=dc3 -rack=rack1 -max=1 -ip="128.xxx.xx.181"
```

and

```bash
weed volume -dir="/root/test" -mserver="162.xx.xxx.77:9333" -port=8080 -dataCenter=dc3 -rack=rack1 -max=1 -ip="128.xxx.xx.181" ip.bind="128.xxx.xx.181"
```

on remove volume server.

No change, unfortunately :/

```bash
cluster.check
Topology volumeSizeLimit:30000 MB hdd(volume:2/3 active:2 free:1 remote:0)
the cluster has 1 filers: [162.xx.xxx.77:8888]
the cluster has 2 volume servers: [162.xx.xxx.77:8081 128.xxx.xx.181:8080]
checking master localhost:9333 to volume server 162.xx.xxx.77:8081 ... ok round trip 0.997ms clock delta 0.104ms
checking master localhost:9333 to volume server 128.xxx.xx.181:8080 ... ok round trip 3.330ms clock delta 1.274ms
checking volume server 162.xx.xxx.77:8081 to master localhost:9333 ... ok round trip 3.957ms clock delta 1.542ms
checking volume server 128.xxx.xx.181:8080 to master localhost:9333 ... rpc error: code = Unknown desc = ping master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:19333: connect: connection refused"
checking filer 162.xx.xxx.77:8888 to master localhost:9333 ... ok round trip 2.749ms clock delta 1.042ms
checking filer 162.xx.xxx.77:8888 to volume server 162.xx.xxx.77:8081 ... ok round trip 2.007ms clock delta 0.626ms
checking filer 162.xx.xxx.77:8888 to volume server 128.xxx.xx.181:8080 ... ok round trip 2.025ms clock delta 0.875ms
checking volume server 162.xx.xxx.77:8081 to 128.xxx.xx.181:8080 ... ok round trip 2.449ms clock delta 1.019ms
checking volume server 128.xxx.xx.181:8080 to 162.xx.xxx.77:8081 ... ok round trip 2.426ms clock delta 0.743ms
checking filer 162.xx.xxx.77:8888 to 162.xx.xxx.77:8888 ... ok round trip 0.583ms clock delta 0.047ms
```

The local volume service is the only one that receives IDs from the master.

**Comment by chrislusf** [comment]
when starting weed shell, specify `-master=162.xx.xxx.77:9333`

**Comment by Material-Scientist** [comment]
Ah, I see!

When using `weed shell -master=162.xx.xxx.77:9333`, I get:

```bash
cluster.check
Topology volumeSizeLimit:30000 MB hdd(volume:2/3 active:2 free:1 remote:0)
the cluster has 1 filers: [162.xx.xxx.77:8888]
the cluster has 2 volume servers: [162.xx.xxx.77:8081 128.xxx.xx.181:8080]
checking master 162.xx.xxx.77:9333 to volume server 162.xx.xxx.77:8081 ... ok round trip 0.520ms clock delta 0.033ms
checking master 162.xx.xxx.77:9333 to volume server 128.xxx.xx.181:8080 ... ok round trip 0.801ms clock delta -0.024ms
checking volume server 162.xx.xxx.77:8081 to master 162.xx.xxx.77:9333 ... ok round trip 0.796ms clock delta -0.098ms
checking volume server 128.xxx.xx.181:8080 to master 162.xx.xxx.77:9333 ... ok round trip 0.681ms clock delta 0.178ms
checking filer 162.xx.xxx.77:8888 to master 162.xx.xxx.77:9333 ... ok round trip 0.682ms clock delta 0.080ms
checking filer 162.xx.xxx.77:8888 to volume server 162.xx.xxx.77:8081 ... ok round trip 0.582ms clock delta 0.064ms
checking filer 162.xx.xxx.77:8888 to volume server 128.xxx.xx.181:8080 ... ok round trip 0.602ms clock delta -0.083ms
checking volume server 162.xx.xxx.77:8081 to 128.xxx.xx.181:8080 ... ok round trip 0.575ms clock delta -0.088ms
checking volume server 128.xxx.xx.181:8080 to 162.xx.xxx.77:8081 ... ok round trip 0.645ms clock delta 0.141ms
checking filer 162.xx.xxx.77:8888 to 162.xx.xxx.77:8888 ... ok round trip 0.536ms clock delta -0.004ms
```

Now, the ping seems to work! However, the master still doesn't assign any volume IDs to the remote volume server.

**Comment by chrislusf** [comment]
New volumes will be allocated once the old volumes are close to full.

**Comment by Material-Scientist** [comment]
Ah OK, thanks!
