### ISSUE TITLE
Uncontrolled filler log growth

### ISSUE THREAD

**Issue by Alexsandr-Random** [seaweedfs/seaweedfs#5120]
**Describe the bug**
We are using docker images in official repo chrislusf/seaweedfs:3.59
So this report is 2in1 suggestion. 
Firstly - in one time our logs with approx size 15-100 mb each starts grows super-quickly (+40-50 gb\day).
What could cause so quick growth and how we could disable this logs\switch verbosity? And what happen if we delete them? (nothing, i hope) 

Secondly - why it so strange named and why here hidden folder .system?
Maybe the best solution is name it more clear like "logs\system-logs\..."
And maybe the best option is enable rotation of this logs by-default, for example, for 6 month or 1 year or by size? 
Add some docker-flags options or just enable this by default and describe log-functionality somewhere in README? 
https://github.com/seaweedfs/seaweedfs/blob/master/weed/filer/topics.go

**System Setup**
 - Ubuntu 22.04
-  weed version
version 30GB 3.59 27b34f379 linux amd64
#### Commands to start each service:
- 
          "master",
          "-mdir=/var/local/seaweedfs/master",
          "-peers=10.44.1.11:9333,10.44.1.12:9333,10.44.1.13:9333",
          "-ip=${meta.vlan}",
          "-ip.bind=0.0.0.0",
          "-volumeSizeLimitMB=1024",
          "-defaultReplication=010"

-           "volume",
          "-mserver=10.44.1.11:9333,10.44.1.12:9333,10.44.1.13:9333",
          "-dataCenter=${node.datacenter}",
          "-rack=${node.unique.name}",
          "-ip.bind=0.0.0.0",
          "-dir=/var/local/seaweedfs/volume",
          "-ip=${meta.vlan}",
          "-port=${NOMAD_PORT_http}",
          "-port.grpc=${NOMAD_PORT_grpc}",
          "-idleTimeout=5",

-           "filer",
          "-dataCenter=${node.datacenter}",
          "-master=10.44.1.11:9333,10.44.1.12:9333,10.44.1.13:9333",
          "-ip.bind=0.0.0.0",
          "-ip=${meta.vlan}",
          "-port=${NOMAD_PORT_filer}",
          "-s3",
          "-s3.port=${NOMAD_PORT_s3}"
- if using filer, show the content of `filer.toml`
```bash
cat /local/filer.toml
[filer.options]
recursive_delete = true

[leveldb3]
enabled = true
dir = "/var/local/seaweedfs/filerldb3"
```

**Expected behavior**
Logs growth normally and rotated automatically

**Comment by chrislusf** [comment]
You can delete the logs safely. You just lose the capability to replay the logs when needed, e.g., start another filer instance with embedded filer store.

**Comment by Alexsandr-Random** [comment]
@chrislusf Thanks for quick replay! 
What could you say about including by default log rotation inside seaweedfs containers? 
And what about describing log functionality into readme (i did not find anything what related to verbosity of filler logs and even did not know about filler logs existence until the moment of the issue)

**Comment by Alexsandr-Random** [comment]
For those interested in how the log issue and its growth were resolved (for those who find this issue later):

The root cause was Grafana (SQLite-based). If you run it on a volume without replication 000 (or with replication 010), everything will work, but a large number of logs will be created. The growth of these logs is caused by operations in SQLite. Obviously, it was a very bad idea to use a database in dfs.

**A small note from me:** If you have the opportunity to use another database instead of SQLite when deploying the application, it's better to use it. It will save a lot of time on migrations when scaling in the future.

**Comment by Alexsandr-Random** [comment]
@chrislusf the main problem is - i deleted 300Gb+ of logs, but disk space on my servers do not released. Why and what i should do with that? 
Maybe i need to run something like garbage collector? 
(i delete them via weed shell, for example,  **fs.rm -r 2023-12-01**)

**Comment by Alexsandr-Random** [comment]
anyone could help me? Why when i deleted logs - disk space not released? @chrislusf any comments about situation, please i have at least 30-35% disk used by logs what i recently deleted but its not freed any space.

**Comment by Alexsandr-Random** [comment]
anyone? 
@chrislusf  
Here's how to reproduce the situation:

1. Deploy a storage cluster for Grafana using SeaweedFS.
2. Configure some test alerts in Grafana.
3. Monitor the number of logs within the SeaweedFS cluster. Continue monitoring until the logs become significant (approximately one day).
4. Delete these logs.
5. Despite deleting the logs, disk space on the servers where the SeaweedFS cluster is deployed does not get freed up.
   
**Note:** It is not necessary to deploy Grafana specifically for this; you just need to observe substantial logs within SeaweedFS in topics:

```bash
fs.du topics
```

**Comment by chrislusf** [comment]
the deleted logs are just like normal files. The storage is released when the volumes are compacted.

**Comment by Alexsandr-Random** [comment]
@chrislusf  i think the same way, but what you could say about that: 
![image](https://github.com/seaweedfs/seaweedfs/assets/78373713/980d6869-df0b-424b-b2c0-f8bf6e7c518e)
6656053327 = 6.6 GB

next - i deleted all large files (each ~190-200mb)
![image](https://github.com/seaweedfs/seaweedfs/assets/78373713/47d74f64-19c8-4aaf-9ac1-77a23d47cb0b)

![image](https://github.com/seaweedfs/seaweedfs/assets/78373713/bc54de90-69b5-4114-85fb-c256c03a09b4)

Then we could watch dir size: 
![image](https://github.com/seaweedfs/seaweedfs/assets/78373713/02b2cbd8-16ab-4dc7-9491-b60477d3580c)
here we are - 1.3GB!

Okay, Lets compact drives! 
![image](https://github.com/seaweedfs/seaweedfs/assets/78373713/519b6a93-8a0a-4f72-b350-ed9c31223957)

And then check if we have released disk space. oh... not!...
![image](https://github.com/seaweedfs/seaweedfs/assets/78373713/9a3e5195-52b3-4f4c-a1d8-17cb6292e1ce)

also what i noticed - after delete (i deleted it approx 2 weeks ago - they recreated! really, after few time i do weed shell
check the logs size /topics and... they are still here!
what i do wrong? 

**After few minutes i see some impact of volume.vacuum but as i say - we released 5GB but here is released just 0.3GB. 
![image](https://github.com/seaweedfs/seaweedfs/assets/78373713/7e435e59-fa01-4039-a412-c5c7557ed01e)

**Comment by chrislusf** [comment]
The `-garbageThreshold` value matters when vacuuming. Need to set it to a low number to ensure all deleted content is compacted in all volumes.

**Comment by chrislusf** [comment]
see `volume.vacuum -h`

**Comment by Alexsandr-Random** [comment]
I tried volume.vacuum with option -garbageThreshold=0.1
but I got the same result as in the comment above.
Perhaps I should completely delete /topics (there are only logs there) or is it possible to identify the collection/volume and delete it completely?

**Comment by chrislusf** [comment]
can you attach the full output of `volume.list` in `weed shell`?

**Comment by Alexsandr-Random** [comment]
@chrislusf 
here is not so detailed output. (detailed -v 5) you could find in attachment file. 
[seawedfs.zip](https://github.com/seaweedfs/seaweedfs/files/13986743/seawedfs.zip)

> volume.list -v 4
Topology volumeSizeLimit:1024 MB hdd(volume:1711/1711 active:1711 free:0 remote:0)
  DataCenter my-dc hdd(volume:1711/1711 active:1711 free:0 remote:0)
    Rack w01.my-dc.com hdd(volume:529/529 active:529 free:0 remote:0)
      DataNode 10.44.1.11:8181 hdd(volume:529/529 active:529 free:0 remote:0)
        Disk hdd(volume:529/529 active:529 free:0 remote:0)
        Disk hdd total size:32428284512 file_count:2179664 deleted_file:7985 deleted_bytes:4250487388 
      DataNode 10.44.1.11:8181 total size:32428284512 file_count:2179664 deleted_file:7985 deleted_bytes:4250487388 
    Rack w01.my-dc.com total size:32428284512 file_count:2179664 deleted_file:7985 deleted_bytes:4250487388 
    Rack w02.my-dc.com hdd(volume:584/584 active:584 free:0 remote:0)
      DataNode 10.44.1.12:8181 hdd(volume:584/584 active:584 free:0 remote:0)
        Disk hdd(volume:584/584 active:584 free:0 remote:0)
        Disk hdd total size:28650642600 file_count:2083249 deleted_file:8882 deleted_bytes:4000445502 
      DataNode 10.44.1.12:8181 total size:28650642600 file_count:2083249 deleted_file:8882 deleted_bytes:4000445502 
    Rack w02.my-dc.com total size:28650642600 file_count:2083249 deleted_file:8882 deleted_bytes:4000445502 
    Rack w03.my-dc.com hdd(volume:598/598 active:598 free:0 remote:0)
      DataNode 10.44.1.13:8181 hdd(volume:598/598 active:598 free:0 remote:0)
        Disk hdd(volume:598/598 active:598 free:0 remote:0)
        Disk hdd total size:32619221232 file_count:3829841 deleted_file:4177 deleted_bytes:4617490587 
      DataNode 10.44.1.13:8181 total size:32619221232 file_count:3829841 deleted_file:4177 deleted_bytes:4617490587 
    Rack w03.my-dc.com total size:32619221232 file_count:3829841 deleted_file:4177 deleted_bytes:4617490587 
  DataCenter my-dc total size:93698148344 file_count:8092754 deleted_file:21044 deleted_bytes:12868423477 
total size:93698148344 file_count:8092754 deleted_file:21044 deleted_bytes:12868423477

**Comment by chrislusf** [comment]
there are 4GB or so garbages, mostly from 'nomad' or 'registry' collections. There are little garbage from filer logs.
```
total size:32619215704 file_count:3829835 deleted_file:4175 deleted_bytes:4617490343
```
