### ISSUE TITLE
weed filler.copy i/o timeout issue

### ISSUE THREAD

**Issue by zrenny** [seaweedfs/seaweedfs#5126]
I'm having issue when running `weed filer.copy `command.

Current I'm running seaweedfs locally using docker compose (https://github.com/seaweedfs/seaweedfs/blob/master/docker/seaweedfs-compose.yml)

The command I ran: 
`weed filer.copy -verbose -debug /path/to/my/local/dir http://localhost:8888/path/to/my/mnt/point/`

The error I got:
**W1222 10:34:47.878728 upload_content.go:170 uploading 2 to http://172.18.0.3:8080/4,128bec02c0: upload .file.jpg.eCwSm0 223807 bytes to http://172.18.0.3:8080/4,128bec02c0: Post "http://172.18.0.3:8080/4,128bec02c0": dial tcp 172.18.0.3:8080: i/o timeout**

Note that **172.18.0.3** is the internal address of my volume service container, and upon checking, port 8080 of volume service is indeed listening for connections.

Any ideas?

**Comment by zrenny** [comment]
after further testing, filer.copy seem to work fine with empty files

**Comment by chrislusf** [comment]
Added an option to fix this.
