### ISSUE TITLE
Slow Assign with a large number of volumes

### ISSUE THREAD

**Issue by ginn13** [seaweedfs/seaweedfs#5135]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
[GetActiveVolumeCount](https://github.com/seaweedfs/seaweedfs/blob/3.59/weed/topology/volume_layout.go#L347) function has high complexity when dc/rack/node topology is enabled.

Master-leader makes this complex calculation every time `Assign` called, thus every write has O(2*n^3) difficulty just to count active volumes.

https://github.com/seaweedfs/seaweedfs/blob/7eafa3420b8e5ae83c8873cddd03ded90a0fc921/weed/topology/volume_layout.go#L347-L372

With a large number of volumes (~50000) it takes up to 1000ms to pick needed volume and [a lot of CPU resources](https://github.com/seaweedfs/seaweedfs/issues/3886#issuecomment-1846849439).

**Expected behavior**
Seems, that master can keep active/crowded volumes in memory since all needed information already exist in topology.
We need some mapping, so the needed info about active/crowded volumes could be taken faster.

**Comment by bvanelst** [comment]
Currently I'm have a issue that could be or is related to this one.

I got strange behaviour/timeouts when I use replication=001. I have 7 volume servers with total 10k volumes in use and max 45k volumes. 

When I start a loop:
`$ while true; do curl --max-time 3 'http://localhost:9333/dir/assign?collection=data&replication=001'; echo "" ; done
`
I get once in a couple of seconds a timeout, but no error:
`curl: (28) Operation timed out after 3000 milliseconds with 0 bytes received
`
At that moment always see a volume growth message in the logging:
` seaweedfs-master[459769]: I0116 14:50:10.468052 master_server_handlers.go:125 dirAssign volume growth {"collection":"date","replication":{"node":1},"ttl":{"Count":0,"Unit":0}} from 10.0.9.12:40308
`
When I change the replication to 002 or when I use different racks with replication 010, these timeouts are gone for a while but came back after a couple of hours.

During this test, the cluster gets continuously new data uploaded, so the volumes are getting constantly filled.

I can't find any error in the volume or master server logging.

If you need any extra information, please let me know.

**Comment by chrislusf** [comment]
this bug has been addressed. 

@bvanelst your description showed a different issue. 
btw: why `data` collection is requested, but the log showed `date`?

**Comment by bvanelst** [comment]
I used a company name on my test in this example, I changed it by hand to data and made a type by date. I will submit a new issue with as much as info I can collect.
