### ISSUE TITLE
File cannot be located and results in an infinite loop

### ISSUE THREAD

**Issue by LuuucasChen** [seaweedfs/seaweedfs#5218]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
**Describe the bug**
1.During an accidental file read, the filer was unable to locate the file, even though it existed. However, after restarting, it successfully located the file. As shown in fig.1.
2.In this exceptional case, while using a Java client to read the file, I noticed that when the file could not be located, the read method returned 0 by default instead of throwing an exception. Because I overlooked this, the API I developed fell into an infinite loop. I am curious about the rationale behind this approach. Also, how should I better handle such situations? I sincerely hope to receive your advice. As shown in fig.2 and fig.3.

**Expected behavior**
Would it be better to throw an exception directly when the file cannot be located?

**Screenshots**
fig1
![5f2edf2dc74fd61cf4d5f24a95e5548](https://github.com/seaweedfs/seaweedfs/assets/68315469/fc5effe6-7ec5-4ef0-a384-dca5cc9328d7)
fig2
![13b1880a101d82d274864ec2b345d24](https://github.com/seaweedfs/seaweedfs/assets/68315469/6c0b5a67-b5b7-48db-8e4f-c52302a43c52)
fig3
![微信截图_20240120005939](https://github.com/seaweedfs/seaweedfs/assets/68315469/5103e953-1f7b-4240-a2d9-e7e71cdc0ec9)

**Comment by chrislusf** [comment]
Send a PR?

**Comment by LuuucasChen** [comment]
> Send a PR?

Okay, I have submitted a pull request. Please take a look at it when you have time. Thank you very much.
