### ISSUE TITLE
The 'path' parameter in filer.sync matches any bucket that has the prefix

### ISSUE THREAD

**Issue by bernardx** [seaweedfs/seaweedfs#5230]
**Describe the bug**
- I have those two buckets:
```
/buckets/test1
/buckets/test123
```
- run this command
`weed filer.sync -a=192.168.228.3:8888 -b=192.168.228.2:8888 -a.filerProxy -b.filerProxy -a.debug -b.debug  -a.path /buckets/test1 -b.path /buckets/test1`

-  upload some file to `/buckets/test123`
-  `test123` will be synced as a directory to the destination. (screenshot)

<img width="288" alt="Screenshot 2024-01-23 at 14 27 18" src="https://github.com/seaweedfs/seaweedfs/assets/397630/33a37dc3-daf3-4cb2-a7c9-3790ba4813df">

**System Setup**
`local-sync-mount-compose.yml`

**Expected behavior**
 Directory should not use prefix match
 
**Additional context**

I added a fix to bypass this issue. 
However, if this 'prefix match'  is expected behavior, maybe we should add a slash in the document to prevent misunderstanding:  `https://github.com/seaweedfs/seaweedfs/wiki/Filer-Active-Active-cross-cluster-continuous-synchronization` 

this line:
`weed filer.sync -a <filer1_host>:<filer1_port> -b <filer2_host>:<filer2_port> -a.path /filer1/path1/ -b.path /filer2/path2/`

**Comment by bernardx** [comment]
Hi, @chrislusf are you aware of this issue and pull request? What is your opinion on how to fix it?

**Comment by chrislusf** [comment]
changing the parameter name to `pathPrefix` should be good enough, or just add some help messages for the parameter.

**Comment by bernardx** [comment]
Ok, thanks.
