### ISSUE TITLE
[mount] Write failing when MTU to reach volume < 1500, process writing completely stuck

### ISSUE THREAD

**Issue by Dando-Real-ITA** [seaweedfs/seaweedfs#5235]
**Describe the bug**
I tried to change volumes published IP to be on a private VPN.
The VPN ( Nebula ) creates a tun interface with MTU = 1300, to account for internal headers.
All seems to work, untill I get some failed reads/writes.
It does not happen consistently, but randomly - like, most of the read/writes go through, and only some fail

However when it happens, the process writing in the mount folder gets completely stuck until the errors shows in the mount logs.
The block is so bad that even a SIGKILL on the process does not work if the errors do not show up in the mount logs.

In htop, it shows the writing process stuck in disk sleep mode and the parent becomes a zombie, and I can only remove them with a complete restart of the mount process

This shows up in the logs of mount ( nothing shows on volume logs ):

```
Jan 24 10:52:22 gpu01.nash02.usa.katapy.icu bash[2382315]: W0124 10:52:22.931935 upload_content.go:170 uploading 0 to http://vpn.gpu01.nash02.usa.katapy.icu:8081/540,18499f8a44026000c58252dc: upload .216.m3u8.3YdnsZ 981 bytes to http://vpn.gpu01.nash02.usa.katapy.icu:8081/540,18499f8a44026000c58252dc: Post "http://vpn.gpu01.nash02.usa.katapy.icu:8081/540,18499f8a44026000c58252dc": read tcp 100.64.0.1:9720->100.64.0.1:8081: read: message too long
[...]
Jan 24 11:02:49 gpu01.nash02.usa.katapy.icu bash[2382315]: W0124 11:02:49.617362 upload_content.go:170 uploading 0 to http://vpn.gpu01.nash02.usa.katapy.icu:8081/555,1849a1ee628260007599d473: upload .216_284064806.ts.4M2WPO 443785 bytes to http://vpn.gpu01.nash02.usa.katapy.icu:8081/555,1849a1ee628260007599d473: Post "http://vpn.gpu01.nash02.usa.katapy.icu:8081/555,1849a1ee628260007599d473": readfrom tcp 100.64.0.1:46248->100.64.0.1:8081: write tcp 100.64.0.1:46248->100.64.0.1:8081: write: message too long
```

In this test, I am using a single server that has the mount, master, filer and volume.
Volume is exposed with publicUrl mapped to the VPN IP
Mount is tested connecting to filer both via external IP and via VPN IP and the bug shows both ways

In production, I have a 3-server setup ( 3 master, 3 filer, 3 volumes ) and it seems to fail only when the upload is to the same volume where the mount is, like if there is a read-write optimization when source ip matches destination ip that does not take into account MTU.
It puzzles me that even a read of 981 bytes fails with the error

All works when I connect mount to the volume over an ip on an interface with >= 1500 MTU ( in my case, main interface is 9000 MTU )

**System Setup**
- Command: /opt/weed/bin/weed mount -filer=katapy.icu:8889,ns1.katapy.icu:8889 -dir=/mnt/seaweedfs/cache -cacheDir=/mnt/KTCACHE/.docker/cache_edge -cacheCapacityMB=9625 -chunkSizeLimitMB=30 -concurrentWriters=128 -volumeServerAccess=publicUrl -dirAutoCreate=true
- OS version: Ubuntu 22 LTS, kernel 5.15.0-76-generic x86_64
- output of `weed version`: version 30GB 3.61
- if using filer, show the content of `filer.toml`:
```
[filer.options]
recursive_delete = true
[leveldb2]
enabled = true
dir = "./filerldb2"                    # directory to store level db files
```

**Expected behavior**
No read/write error, regardless of MTU and src/dst IP when using mount

**Screenshots**
![image](https://github.com/seaweedfs/seaweedfs/assets/3657228/c8d3a206-ecb1-4c78-8c31-a67fa0339a31)

**Additional context**

**Comment by chrislusf** [comment]
this is beyond my knowledge.  How about try to use VPN IP for all servers and not to mix it up with external IP, and see how it goes?

**Comment by chrislusf** [comment]
from chat gpt :)
```
VPN and Tunneling Issues: Virtual Private Networks (VPNs) and other tunneling mechanisms may have specific requirements for the MTU. An MTU of 1300 may not be suitable for certain VPN configurations, and it's important to ensure compatibility.
```

**Comment by Dando-Real-ITA** [comment]
I would not trust chat gpt for anything :)

This is how it works: VPNs have a reduced MTU interface(s) because:
App data ( up to 1300 bytes ) + (VPN Header + TCP/UDP VPN Header + IP VPN Header) ( around 200 bytes )
Have to fit in a normal ethernet frame that has on average TCP/UDP Real Header + IP Real Header

Allowed frame can be bigger like 9000 bytes on LAN but when data transits over internet 1500 bytes is the working MTU, and VPNs have interfaces with MTU < 1500 to support WAN connected hosts

----

The other connections ( filer, master ) all work, I can see with -v 2 on mount both file ids assigned and entries created. I am connecting over VPN IP the mount to Filer and to Volume, while Filer to Master have a separate connection over VXLAN ( through docker swarm, has always worked and still works )

Reading the code, the blocking line is https://github.com/seaweedfs/seaweedfs/blob/0b71fae2e30f2129292bc1696498d99ce89df389/weed/operation/upload_content.go#L326
I have to dig more, because it seems that data was read into a buffer, when `UploadData()` is called, so it is not clear to me why the error believes it is reading from reading directly from tcp and writing directly, probably triggering some zero-copy mechanism

If the error is truly only for local ( which means only for weed mount trying to upload to a volume on the same machine using an interface with a < MTU 1500 ) but is stable in multi machine setting ( mount uploading to a different machine over the VPN ), I can bypass the error by mapping the local public url from vpn dns to 127.0.0.1 ( testing now ) and I will test tomorrow on multi machine, however this only masks the problem with a workaround.

**Comment by Dando-Real-ITA** [comment]
Seems that the problem is only when mount is uploading to a volume on the same host, through an interface with mtu < 1500, but there are no errors when uploading to volumes on other hosts using the vpn ip over the lower mtu interface

I bypassed the problem by mapping on each host their own vpn hostname to 127.0.0.1, thus using the loopback
