### ISSUE TITLE
filer.remote.sync taking a long time to upload large files 

### ISSUE THREAD

**Issue by aronneagu** [seaweedfs/seaweedfs#5243]
**Describe the bug**
filer.remote.sync takes over 2 minuntes to upload 1Gb from seaweed to Azure Storage
Issue is related to https://github.com/seaweedfs/seaweedfs/issues/5234

**System Setup**
```
> weed server -s3 -volume.max=300
> weed version
version 30GB 3.62 59b8af99b0aca1b9e88fec7b5f27c7d15e5e8604 linux amd64
> lsb_release -a 
root@cis01-seaweed-aneagu:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy- output of `weed version`
```

**Expected behavior**
filer.remote.sync uploading files to Azure much quicker

**Screenshots**
Uploading a file to seaweed using the S3 endpoint (connected via rclone for ease), the upload finished at 15:29:41
```
root@cis01-seaweed-aneagu:~# date;rclone --progress copyto 1gig seaweed-bcminiotest:bcminiotest/000test/1gig;date
Thu Jan 25 15:29:33 UTC 2024
Transferred:            1G / 1 GBytes, 100%, 141.121 MBytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         7.2s
Thu Jan 25 15:29:41 UTC 2024
```
Then the same file appeared in Azure Storage at 3:31:49. (see below)
![image](https://github.com/seaweedfs/seaweedfs/assets/1262715/171e5c1c-059d-4ddb-98c8-1beaedd09fcf)

It means it took filer.remote.sync 2 minutes and 8 seconds to upload from to Azure Storage (1Gb/2min = 8Mb/s)

This was run on a test VM running in Azure, with 4 cores/16Gb RAM, and no other processes running on that server.
Uploading files directly (tried both rclone/azcopy) from the VM to Azure Storage achieved 1Gbps speeds.

**Additional context**
Attaching the output from filer.remote.sync (verbose 4) and filer.meta.tail
[remote.sync.log](https://github.com/seaweedfs/seaweedfs/files/14054243/remote.sync.log)
[meta.tail.log](https://github.com/seaweedfs/seaweedfs/files/14054249/meta.tail.log)

**Comment by chrislusf** [comment]
Same as https://github.com/seaweedfs/seaweedfs/issues/5234
