### ISSUE TITLE
Helm chart publish policy on push to master can result on uncontrollable breaking changes

### ISSUE THREAD

**Issue by sberthier** [seaweedfs/seaweedfs#5264]
Since https://github.com/seaweedfs/seaweedfs/pull/5035 helm chart are published on push to master, erasing current version.

That may result to breaking changes in the same chart version, for instance with https://github.com/seaweedfs/seaweedfs/pull/5236.

Why not wait for a new release before publish new helm chart ?

**Comment by chrislusf** [comment]
Send a PR to fix this?

**Comment by sberthier** [comment]
Yes https://github.com/seaweedfs/seaweedfs/pull/5265
