### ISSUE TITLE
[Feature]Disable Filer UI via configuration

### ISSUE THREAD

**Issue by jerebear12** [seaweedfs/seaweedfs#5288]
**Describe the issue**

We have the Filer exposed publically and we can't require a JWT for reads due to our client's(client that reads from the Filer) limitations. This exposes all data stored in Seaweed to the public with no access control. 

**Expected behavior**

The current behavior **is** expected.

**Desired feature**

A configuration value that allows the UI to be disabled in the same way the Volume UI can be disabled. We don't want the request for a directory's metadata/contents to be exposed either. 

Let me know if you have questions!

**Additional context**

We have tried to block requests to the Filer that return the UI while allowing requests to media that are from our clients but we cannot block certain headers because of the nature of our client. 

This is somewhat time-sensitive for our product's development. 

PS. If you start working on this could you let me know? If I don't receive a response on this one soon I'll start on it myself. If you know how, but don't have the time I'd appreciate a few pointers on the implementation of this feature.

**Comment by chrislusf** [comment]
there is an existing option to make filer ui readonly.

**Comment by jerebear12** [comment]
> there is an existing option to make filer ui readonly.

Is this documented somewhere? If not, where is the option located?

**Comment by jerebear12** [comment]
Ah, you said readonly. It's still exposed to the public though, which is not what we want.

**Comment by jerebear12** [comment]
See: https://github.com/seaweedfs/seaweedfs/pull/5297

**Comment by jerebear12** [comment]
@chrislusf Are you able to merge #5297? If there need to be changes made before it can be merged I'd love to know what they are.

**Comment by chrislusf** [comment]
added one comment

**Comment by jerebear12** [comment]
Merged in #5297 

Thanks Chris!
