### ISSUE TITLE
Resize URL without 

### ISSUE THREAD

**Issue by SonGokussj4** [seaweedfs/seaweedfs#5298]
Hi, I'm trying to resize an image through URL

```bash
<host>:<port>/models/2/Cat_10_50cae49443.jpg?width=200&height=100
```

But this returns 200 or 304 Not Modified reponse.

And image is still in it's 4000x3000 (or something like that) glory.

Is this functionality still there? I tried to empty cache, do anonymous window, different browser (Chrome, Firefox), hard empty cache, nothing works.

Running SeaweedFS 3.57 in Docker container.

**Comment by SonGokussj4** [comment]
Tried in 3.62 with the same behaviour.
No resize.

**Comment by chrislusf** [comment]
Resize only works on volume server directly.
Filer server does not support this.

**Comment by SonGokussj4** [comment]
Okay. 

So I'm not able to get the resized picture by calling url with arguments, only if I exec into volume server docker and somehow call it there?

Am I missing something, is it possible to give a little bit of an explanation please?
