### ISSUE TITLE
panic: unaligned 64-bit atomic operation in weed mount on arm when reading a file

### ISSUE THREAD

**Issue by bolet** [seaweedfs/seaweedfs#5306]
**Describe the bug**
- Running a cluster of 3 arm and 2 arm64 nodes. The issue only happens on arm.
- `weed mount` crashes when reading a file.
- It does not crash when writing a file, reading or writing directories.

**System Setup**
- Command line: `weed mount -filer=peer2:8888 -dir=/mnt/weed`
- OS version: Debian 12 (armbian)
- output of `weed version`: `version 30GB 3.62 59b8af99b0aca1b9e88fec7b5f27c7d15e5e8604 linux arm`
- Server command line:
```
weed server -ip=peer2 -dir=/mnt/disk/weed -master.peers=peer2:9333,peer3:9333,peer4:9333,peer5:9333,peer1:9333 -filer
```

**Expected behavior**
Obviously, no panic.

**Screenshots**
```
weed-client.sh[22296]: panic: unaligned 64-bit atomic operation
weed-client.sh[22296]: goroutine 112 [running]:
weed-client.sh[22296]: runtime/internal/atomic.panicUnaligned()
weed-client.sh[22296]:         /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
weed-client.sh[22296]: runtime/internal/atomic.Store64(0x3db0894, 0x17b3dfd71c975816)
weed-client.sh[22296]:         /usr/local/go/src/runtime/internal/atomic/atomic_arm.s:291 +0x14
weed-client.sh[22296]: github.com/seaweedfs/seaweedfs/weed/filer.(*SingleChunkCacher).startCaching(0x3db0840)
weed-client.sh[22296]:         /github/workspace/weed/filer/reader_cache.go:183 +0x3c8
weed-client.sh[22296]: created by github.com/seaweedfs/seaweedfs/weed/filer.(*ReaderCache).ReadChunkAt in goroutine 1
weed-client.sh[22296]:         /github/workspace/weed/filer/reader_cache.go:117 +0x3ec
```

**Comment by bolet** [comment]
I don't know much Go, but I looks like the field `completedTimeNew` in struct `SingleChunkCacher` is misaligned.
The struct is defined in `filer/reader_cache.go:22`.
Maybe reordering the fields would solve the issue?

**Comment by bolet** [comment]
Beginner question: do we need `atomic` operation (line 183) when we use a `Lock` at function `startCaching` entry (line 160)?
The only other place the field is accessed is in function `ReadChunkAt` (line 81), which too uses a `Lock` at entry around the surrounding `ReaderCache` struct.

**Comment by bolet** [comment]
This little patch fixes the issue:
```
diff --git a/weed/filer/reader_cache.go b/weed/filer/reader_cache.go
index 27d40a78b..5e15c9a55 100644
--- a/weed/filer/reader_cache.go
+++ b/weed/filer/reader_cache.go
@@ -21,6 +21,7 @@ type ReaderCache struct {
 
 type SingleChunkCacher struct {
        sync.Mutex
+       completedTimeNew int64
        parent           *ReaderCache
        chunkFileId      string
        data             []byte
@@ -31,7 +32,6 @@ type SingleChunkCacher struct {
        shouldCache      bool
        wg               sync.WaitGroup
        cacheStartedCh   chan struct{}
-       completedTimeNew int64
 }
 
 func NewReaderCache(limit int, chunkCache chunk_cache.ChunkCache, lookupFileIdFn wdclient.LookupFileIdFunctionType) *ReaderCache {
```
Thanks for the opportunity to exercise!
As I'm not sure I did it right, I leave it as a comment here, anyone is welcome to make a PR.

**Comment by chrislusf** [comment]
https://github.com/seaweedfs/seaweedfs/pull/5308
