### ISSUE TITLE
write or admin permissions can delete S3 buckets？

### ISSUE THREAD

**Issue by 7y-9** [seaweedfs/seaweedfs#5311]
I've found that users with write permissions can delete S3 buckets.
Is it a good idea to change Write permissions to Admin permissions?
This way, there would be fewer risky operations.

**Comment by 7y-9** [comment]
#5312

**Comment by kmlebedev** [comment]
If you want to limit privileges only for administrators, then it’s better to do it here

https://github.com/seaweedfs/seaweedfs/blob/6181aa7594a7f8459910807e581d84adb2ab44c6/weed/s3api/s3api_server.go#L281

**Comment by 7y-9** [comment]
> If you want to limit privileges only for administrators, then it’s better to do it here
> 
> https://github.com/seaweedfs/seaweedfs/blob/6181aa7594a7f8459910807e581d84adb2ab44c6/weed/s3api/s3api_server.go#L281

Thanks for your reply. 
I saw this code through your guidance and modified my PR. 
Do you have time to have a look?
