### ISSUE TITLE
seaweedfs k8s csi and filer permission issue

### ISSUE THREAD

**Issue by chingchien-wu** [seaweedfs/seaweedfs#5325]
weed version : 3.57
seaweedfs-csi-driver-0.2.1
k8s version : 1.28

I am using Weed CSI to mount a PVC on Kubernetes. 
I can see /buckets/pvc through Filer and application can read/write anything from this.
However, when I upload an image through the Filer web GUI done, I got a 403 error from my application. 
Any ideas?

**Comment by chrislusf** [comment]
No idea without any details.
