### ISSUE TITLE
Seaweed Cloud Monitoring website no longer works, returning http error 521

### ISSUE THREAD

**Issue by NyaMisty** [seaweedfs/seaweedfs#5326]
**Describe the bug**
The Cloud Monitoring described in https://github.com/seaweedfs/seaweedfs/wiki/Cloud-Monitoring has a down server now.
Opening https://cloud.seaweedfs.com/ now returns a http error 521, which means backend of cloud.seaweedfs.com is no longer working.

**Additional context**
None

**Comment by chrislusf** [comment]
planning to remove this feature.
