### ISSUE TITLE
metadata log write failed no free volumes left when there are 313/320 free volumes

### ISSUE THREAD

**Issue by eliphatfs** [seaweedfs/seaweedfs#5328]
**Describe the bug**
I started a new server, with 8x40 = 320 volumes in total. Weed master UI shows 313 free volumes.

I mounted the filer and run `fio --randrepeat=1 --name=test --filename=fiotest --bs=128k --iodepth=1 --readwrite=read --size=2G -direct=1` to test the speed.

`fio` succeeded in laying out the file but fails reading (I am unsure if it is due to the filer error or jwt token for mount as the settings seem very vague, but grpc should work well). At this point I can no longer mount the filer any more, showing `failed to access mountpoint /home/orchid/weedtest: Transport endpoint is not connected`.

I checked the journalctl log of the volume servers and nothing is output. In the master server, it shows
`I0223 00:09:44.698102 filer_notify.go:104 metadata log write failed /topics/.system/log/2024-02-23/00-03.69f3354d: AssignVolume: rpc error: code = Unknown desc = no free volumes left for {"replication":{},"ttl":{"Count":0,"Unit":0}}.`

**System Setup**
- `/usr/local/bin/weed server -volume=0 -filer -filer.disk=ssd -dir=/weedfs -master.volumeSizeLimitMB=10000`
- `/usr/local/bin/weed volume -max=40 -disk=ssd -dir=/weedfs -mserver=10.8.149.13:9333` on 8 machines different from the master
- These commands are done by systemctl services with setups exactly as the wiki page.
- OS version: Ubuntu 22.04
- output of `weed version`: version 30GB 3.62 59b8af99b0aca1b9e88fec7b5f27c7d15e5e8604 linux amd64
- if using filer, show the content of `filer.toml`: no `filer.toml`
- security:
```
[jwt.signing]
key = "the_same_key"

[jwt.filer_signing]
key = "the_same_key"

[jwt.signing.read]
key = "the_same_key"

[jwt.filer_signing.read]
key = "the_same_key"

[access]
ui = false

[grpc]
ca = "/etc/ariesdockerd/certs/Aries_SeaweedFS_CA.crt"

[grpc.volume]
cert = "/etc/ariesdockerd/certs/volume01.crt"
key  = "/etc/ariesdockerd/certs/volume01.key"

[grpc.master]
cert = "/etc/ariesdockerd/certs/master01.crt"
key  = "/etc/ariesdockerd/certs/master01.key"

[grpc.filer]
cert = "/etc/ariesdockerd/certs/filer01.crt"
key  = "/etc/ariesdockerd/certs/filer01.key"

[grpc.client]
cert = "/etc/ariesdockerd/certs/client01.crt"
key  = "/etc/ariesdockerd/certs/client01.key"
```

**Expected behavior**

FIO should work, I should be able to mount, and no errors in filer log.

**Screenshots**
<img width="454" alt="image" src="https://github.com/seaweedfs/seaweedfs/assets/23738781/8f92a143-cae4-4cf8-8dd4-064bc6ce85ab">

**Comment by chrislusf** [comment]
Current code needs to have an empty or `hdd` disk type for the metadata logs.

**Comment by eliphatfs** [comment]
I only have ssd disks. How am I supposed to use it? Just tell volume server '-disk=hdd' anyway?
