### ISSUE TITLE
security s3 server startup failed

### ISSUE THREAD

**Issue by zuzuviewer** [seaweedfs/seaweedfs#5414]
1. `docker pull chrislusf/seaweedfs:3.64`
2. create certifications follow [security contifuration](https://github.com/seaweedfs/seaweedfs/wiki/Security-Configuration) into /opt/cert directory
3. create /opt/security.toml file and write config to it 
> [grpc]

> ca = "/Users/chris/.seaweedfs/out/SeaweedFS_CA.crt"

> [grpc.volume]

> cert = "/Users/chris/.seaweedfs/out/volume01.crt"

> key  = "/Users/chris/.seaweedfs/out/volume01.key"

> [grpc.master]

> cert = "/Users/chris/.seaweedfs/out/master01.crt"

> key  = "/Users/chris/.seaweedfs/out/master01.key"

> [grpc.filer]

> cert = "/Users/chris/.seaweedfs/out/filer01.crt"

> key  = "/Users/chris/.seaweedfs/out/filer01.key"

> [grpc.client]

> cert = "/Users/chris/.seaweedfs/out/client01.crt"

> key = "/Users/chris/.seaweedfs/out/client01.key"

4. `docker run -v /opt/security.toml:/etc/seaweedfs/security.toml -v /opt/cert:/Users/chris/.seaweedfs/out --network=host chrislusf/seaweedfs:3.64 server -s3`

filer server and volume server can't startup, server log:

![weaseed报错](https://github.com/seaweedfs/seaweedfs/assets/19585711/ef2887ff-ec59-4830-94a8-d254d5464857)

**Comment by kmlebedev** [comment]
Example of running docker with TLS
https://github.com/seaweedfs/seaweedfs/blob/master/docker/compose/tls.env
For the grpc client you also need to specify a client certificate

**Comment by zuzuviewer** [comment]
> Example of running docker with TLS https://github.com/seaweedfs/seaweedfs/blob/master/docker/compose/tls.env For the grpc client you also need to specify a client certificate

what do you mean, which client certificate, is grpc.client?

**Comment by zuzuviewer** [comment]
> Example of running docker with TLS https://github.com/seaweedfs/seaweedfs/blob/master/docker/compose/tls.env For the grpc client you also need to specify a client certificate

what do you mean, which client certificate, is grpc.client?

**Comment by zuzuviewer** [comment]
is certification path error, close it
