### ISSUE TITLE
Upgrade 3.63-> 3.64 Strange behaviour

### ISSUE THREAD

**Issue by NickyHeuperman** [seaweedfs/seaweedfs#5468]
**Describe the bug**
After upgrading seaweedfs from 3.63 to 3.64 s3 behaves weird.
New files uploaded through s3 are invisibles and nothing can be deleted
Uploading a file through s3 API does not return an error, listing the directory to which the file was uploaded however doesn't show the newly uploaded file, directories can be created but can not be deleted.
After downgrading the master/filer to 3.63 the file(s) are visible again and directories can be deleted once more.

**System Setup**
I'm running seaweed in semi microservice mode, I have a single master/filter combination run with:
exec /usr/bin/weed \
                -logtostderr=true \
                -v=2 \
                server \
                -filer \
                -metricsPort=9327 \
                -dir=/data \
                -volume.max=950 \
                -volume.minFreeSpacePercent=7 \
                -master.volumeSizeLimitMB=1024 \
                -ip.bind=0.0.0.0

And multiple s3 gateways run with:
exec /usr/bin/weed \
                s3 \
                -config=/config/s3.json \
                -port=8333 \
                -allowEmptyFolder=false \
                -metricsPort=9327 \
                -filer="seaweed:8888" \
                -ip.bind=0.0.0.0

**Expected behavior**
I expect files newly uploaded to be visible and directories being deletable

**Comment by chrislusf** [comment]
Is this due to https://github.com/seaweedfs/seaweedfs/pull/5350 ?
Or you can build a latest version to test?
