### ISSUE TITLE
unmarshalled error: replicating operations [0] is less than volume 234 replication copy count [2]

### ISSUE THREAD

**Issue by vincib** [seaweedfs/seaweedfs#5496]
**Describe the bug**

I have a 7 volumes + 3 masters + 3 filers (all filers using the same mysql) seaweedfs cluster
A few days ago I had to restart all my volume servers, so I restarted them one by one with a few minutes between each server.
Since then I have the following errros on all volume servers, spread on all volume IDs, that appears every once in a while: 

On volume servers : 

`2024-04-14T09:36:50.464426+02:00 octoswfs07 weedvolume[42850]: I0414 09:36:50.463794 store_replicate.go:35 replicating operations [0] is less than volume 24 replication copy count [2]`
`2024-04-14T09:36:50.464696+02:00 octoswfs07 weedvolume[42850]: I0414 09:36:50.463845 common.go:77 response method:POST URL:/24,ca6e4aa04fca50 with httpStatus:500 and JSON:{"error":"replicating operations [0] is less than volume 24 replication copy count [2]"}`

Most PUT (via S3) are working, but some are failing.
On a volume+filer server I have this in those cases: 

`Apr 14 04:15:01 octoswfs01 weedfiler[676626]: W0414 04:15:01.543964 upload_content.go:170 uploading 2 to http://10.10.4.156:8080/234,c9f1cccde25213: unmarshalled error http://10.10.4.156:8080/234,c9
f1cccde25213: replicating operations [0] is less than volume 234 replication copy count [2]`
`Apr 14 04:15:01 octoswfs01 weedfiler[676626]: E0414 04:15:01.544028 filer_server_handlers_write_upload.go:203 upload error: unmarshalled error http://10.10.4.156:8080/234,c9f1cccde25213: replicating
 operations [0] is less than volume 234 replication copy count [2]`
`Apr 14 04:15:01 octoswfs01 weedfiler[676626]: I0414 04:15:01.544103 common.go:77 response method:PUT URL:/buckets/mytest/cache/preview_cards/images/026/285/168/original/365128aaf335615e.jpg with httpStatus:500 and JSON:{"error":"unmarshalled error http://10.10.4.156:8080/234,c9f1cccde25213: replicating operations [0] is less than volume 234 replication copy count [2]"}`

**System Setup**

- Weed command lines : 

```
weed master -mdir=/data/master -peers=10.10.4.151:9333,10.10.4.152:9333,10.10.4.153:9333 \
-defaultReplication=001   -resumeState -volumePreallocate -volumeSizeLimitMB=10000

weed volume -dir=/data/volume -max=0 -index=memory -minFreeSpace=10GiB \
-mserver=10.10.4.151:9333,10.10.4.152:9333,10.10.4.153:9333 

weed filer -master=10.10.4.151:9333,10.10.4.152:9333,10.10.4.153:9333  -maxMB=20 -s3 \
-s3.allowDeleteBucketNotEmpty=false  -s3.config=/etc/seaweedfs/s3.json -s3.domainName=mydomain.fr \
-s3.port=0 -s3.localSocket=/run/s3.sock
```

- OS : debian 12 (bookworm) 
- weed version 30GB 3.64 b74e8082bac408138be99e128b8c28fd19eca7a6 linux amd64

filer.toml is using mysql2: (excerpt below)
```
[filer.options]
recursive_delete = false
[mysql2]  # or memsql, tidb
enabled = true
connection_max_idle = 2
connection_max_open = 100
connection_max_lifetime_seconds = 0
interpolateParams = false
enableUpsert = false
```

**Expected behavior**

- no failing PUT on S3

**Comment by vincib** [comment]
Note: I tried to remove one volume server entirely (service weed-filer stop + rm /data/volume/*.{idx,vif,dat} + service weed-filer start) 
and fix the replication of volumes (weed shell + lock + volume.fix.replication )
but after a few volumes have been transferred to that volume server, the same error message started to re-appear on this volume server ...

**Comment by vincib** [comment]
Today, we decided to juste *restart* the entire cluster and since then, we didn't have any error similar to the one above

our procedure to restart was 

- stop nginx proxy/cache
- stop filer servers
- stop volume servers
- stop masters
- start masters (3) and wait for them to elect one of them
- start all volumes (7)
- start all filers (3)
- start nginx proxy/cache
- test some uploads and many downloads :smile:

sorry if that bug was not really one, but it seems that on some case, restarting volume & filers is not enough, restarting masters are needed too...

**Comment by vincib** [comment]
I'm closing this issue, since it was just me not using weed shell to move volumes to different disk type, but changing the volume server command line :/ which was a bit too forceful...

**Comment by piajesse** [comment]
so I ran into this issue while I was doing shenanigans, and I think it can be reproduced by doing the following.
upload files at replication 002, take down one of the volume servers, change the replication to 001 or run `volume.fix.replication`, so that it becomes writable again, do some writes (vacuum, etc), accidentally restart the volume server that was taken down, the volume shows up as writable, but there isn't a consistency, so it produces this error.
