### ISSUE TITLE
The files on the mounted point are not deleted after the TTL expires

### ISSUE THREAD

**Issue by liangyihan** [seaweedfs/seaweedfs#5527]
**Describe the bug**
Create a bucket named "test2" with a TTL (Time To Live) of 1 minute. Upload files into the bucket. After the TTL expires, verify that the files no longer exist inside the bucket. However, the files on the mounted point are still present.

upload file
curl -F file=@Readme.txt "http://10.xxx.xx.x:9283/home/hdpu/lyh/mount_dir/test2/20240424/Readme1.txt"
curl -F file=@Readme.txt "http://10.xxx.xx.x:9283/home/hdpu/lyh/mount_dir/test2/20240424/Readme2.txt"
curl -F file=@Readme.txt "http://10.xxx.xx.x:9283/home/hdpu/lyh/mount_dir/test2/20240424/Readme3.txt"

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

./weed -logdir=/data/obs/hdd/log/master master -mdir=/data/obs/ssd/data/master -peers=10.xxx.xx.x:9666 -ip=10.xxx.xx.x -port=9666 -defaultReplication=000 -volumePreallocate -volumeSizeLimitMB=80

/weed -logdir=/data/obs/hdd/log/volume volume -index=leveldb -idleTimeout=30 -dir=/data/obs/ssd/data/volume,/data/obs/hdd/data/volume,/data/obs/warm/data/volume,/data/obs/cold/data/volume -disk=ssd,hdd,warm,cold -mserver=10.xxx.xx.x:9666 -dataCenter=dc -rack=rack1 -ip=10.xxx.xx.x -port=9189 -concurrentDownloadLimitMB=2048 -max=0

./weed -logdir=/data/obs/hdd/log/filer filer -master=10.xxx.xx.x:9666 -ip=10.xxx.xx.x -port=9283 -defaultReplicaPlacement=000 -maxMB=4 -s3 -s3.allowEmptyFolder -encryptVolumeData -s3.port=9383 -iam -iam.port=9483

./weed mount -cacheCapacityMB=0 -filer=10.xxx.xx.x:9283 -volumeServerAccess=filerProxy -dir=/home/hdpu/lyh/mount_dir/ -filer.path=/home/hdpu/lyh/mount_dir/

- OS version  centos7
- output of `weed version`  seaweedfs 3.15
- if using filer, show the content of `filer.toml`
[cassandra]
enabled = true
keyspace = "seaweedfs"
hosts = [
        "10.xxx.xx.x:9042",
    ]
username = ""
password = ""
 This changes the data layout. Only add new directories. Removing/Updating will cause data loss.
superLargeDirectories = []
 Name of the datacenter local to this filer, used as host selection fallback.
localDC = ""

**Expected behavior**
The files on the mounted point have been deleted.

**Screenshots**
![image](https://github.com/seaweedfs/seaweedfs/assets/45417436/daf66b57-fbae-4cb2-aba0-5f046c86beb1)

![image](https://github.com/seaweedfs/seaweedfs/assets/45417436/d115c59c-c188-4a32-b831-1bf3071727fb)

**Additional context**

**Comment by andrea-agostini** [comment]
@chrislusf Made a PR with a proposal to fix this problem, please be aware that I only gave a quick glance at the seaweed code, so with my patch there can possibly be some other unknown side effects.
Also, from what I've seen, atm an update event is only triggered when launching a fs.ls command on a weed shell (or by accessing filer UI from a browser), but shouldn't TTL expiration check better be triggered by something automatic instead? I mean, I can surely work around this and make a script to periodically call the weed shell command, but I think there could be an automatic job checking files and purging them when they're expired, or am I missing something?

**Comment by togettoyou** [comment]
> it's possible that the filer does not receive the list operation, so the `weed mount` still sees expired entries.

It seems that a list operation has already been performed, possibly because the `SubscribeMetaEvents` during the mount process did not handle the ttl type deletion notification?
