### ISSUE TITLE
nginx proxy to seaweedfs S3 server HEAD request return 403 error

### ISSUE THREAD

**Issue by hbh112233abc** [seaweedfs/seaweedfs#5535]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/seaweedfs/seaweedfs/discussions

example of a good issue report:
https://github.com/seaweedfs/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/seaweedfs/seaweedfs/issues/1008

**Describe the bug**
seaweedFS use S3 server like:
`./weed server -dir=/www/server/seaweedFS/data/ -master.volumeSizeLimitMB=1024 -s3 -s3.config=/www/server/seaweedFS/s3_config.json -filer`

s3.config like:
```
{
  "identities": [
    {
      "name": "admin",
      "credentials": [
        {
          "accessKey": "my accessKey",
          "secretKey": "my secretKey"
        }
      ],
      "actions": [
	"Admin",
        "Read",
        "ReadAcp",
        "List",
        "Tagging",
        "Write",
        "WriteAcp"
      ]
    }
  ]
}
```
only request ip:8333 use S3 server is ok, but when I use nginx proxy to S3 server [https://github.com/seaweedfs/seaweedfs/wiki/S3-Nginx-Proxy](https://github.com/seaweedfs/seaweedfs/wiki/S3-Nginx-Proxy)
POST,GET,DELETE request is ok,but HEAD request return 403 error

**System Setup**
- `./weed server -dir=/www/server/seaweedFS/data/ -master.volumeSizeLimitMB=1024 -s3 -s3.config=/www/server/seaweedFS/s3_config.json -filer`.
- Linux kylinv10 4.19.90-25.24.v2101.ky10.aarch64 #1 SMP Mon Feb 6 18:04:57 CST 2023 aarch64 aarch64 aarch64 GNU/Linux
- version 30GB 3.64 b74e8082bac408138be99e128b8c28fd19eca7a6 linux arm64
- if using filer, show the content of `filer.toml`

**Expected behavior**
I use python S3 client request check bucket is exist or object key is exists use HEAD request return error
when not set s3.config, every request is ok

**Screenshots**

**Additional context**

**Comment by dajrivera** [comment]
Hi could it be due to this nginx proxy setting? 

https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_convert_head

Try setting proxy_cache_convert_head to off.

**Comment by hbh112233abc** [comment]
> Hi could it be due to this nginx proxy setting?
> 
> https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_convert_head
> 
> Try setting proxy_cache_convert_head to off.

it's OK, setting `proxy_cache_convert_head to off` HEAD request is OK
