### ISSUE TITLE
error parse -port.readonly

### ISSUE THREAD

**Issue by IvanKirpichnikov** [seaweedfs/seaweedfs#5545]
Enter the command
'SeaweedFS filer -port 9335 -port.readonly 9336'
but throws an error
'Invalid '.readonly' value for the -port flag: strconv. ParseInt: parsing '.readonly': invalid syntax'

seaweedfs version 'Version 30GB 3.65 0edc5aad9a489d0c99213a45e27654703fa5da70 windows amd64'
system Windows 11

**Comment by SmsS4** [comment]
Have you seen this?
https://stackoverflow.com/questions/66794981/how-to-disable-override-powershell-dot-notation
Probably `filer -port 9335 '-port.readonly 9336'` works

**Comment by IvanKirpichnikov** [comment]
> Have you seen this? https://stackoverflow.com/questions/66794981/how-to-disable-override-powershell-dot-notation Probably `filer -port 9335 '-port.readonly 9336'` works
> 
> Looks like a powershell bug [PowerShell/PowerShell#6291](https://github.com/PowerShell/PowerShell/issues/6291)

No, I haven't. Thank you for your help
