### ISSUE TITLE
Error in setup

### ISSUE THREAD

**Issue by ali-hejazi** [seaweedfs/seaweedfs#5556]
Dear Chris
The following error is received during build:

`
root@objectstorage-01:~# cd seaweedfs/weed && make install
go install -ldflags="-s -w"
go: downloading github.com/aws/aws-sdk-go v1.51.30
go: downloading google.golang.org/api v0.176.0
go: downloading github.com/pierrec/lz4/v4 v4.1.18
go: downloading github.com/klauspost/compress v1.17.7
build github.com/seaweedfs/seaweedfs/weed: cannot load cmp: malformed module path "cmp": missing dot in first path element
make: *** [Makefile:10: install] Error 1
`

**Comment by kmlebedev** [comment]
Please check the golang version.
```
go version
go version go1.22.1 darwin/arm64
```
and run
```
go mod tidy
```

**Comment by ali-hejazi** [comment]
Thank you for your reply @kmlebedev 

`
go version
go version go1.13.8 linux/amd64
`

after running "go mod tidy":
`
        testing/slogtest: malformed module path "testing/slogtest": missing dot in first path element
`
