### ISSUE TITLE
Visualizations used in the Grafana boards are deprecated (AngularJS)

### ISSUE THREAD

**Issue by gtudan** [seaweedfs/seaweedfs#5592]
**Describe the bug**
Grafana complains that the visualizations (graphs) used for the Dashboard use the deprecated AngularJS component and will be removed soon.

**System Setup**
- Grafana dashboard from the helm chart
- Grafana 10.3

**Expected behavior**
The Graphs should be ported to the new visualization

**Screenshots**
<img width="1080" alt="image" src="https://github.com/seaweedfs/seaweedfs/assets/419425/6011df85-a881-4ddd-9039-7b24e8467678">

**Comment by gtudan** [comment]
@chrislusf Grafana allows to automatically migrate the Graphs to the Timeseries visualization (has to be done for each panel). The resulting PR will be huge, so before I go ahead I would like to make sure you are fine with this.

**Comment by chrislusf** [comment]
Welcome!
