### ISSUE TITLE
[Mount] File changes are not propagated to other mounts if they are executing the file

### ISSUE THREAD

**Issue by Dando-Real-ITA** [seaweedfs/seaweedfs#5649]
**Describe the bug**
I had this bug for a while, but only now I was able to isolate and replicate it

Consider 3 servers, each one has access to an executable file **script.sh** on SeaweedFS. The script is a long running process.
Server 1 and Server 2 are running the script.sh
Server 3 is not running the script.sh

I want to update script.sh, and for testing I update a comment with a timestamp at the top of file.

Step 1) I update the script from Server 3. Reading the same script from Server 1 or Server 2 show still the old version.
- Server 1: `# 2024-06-05 02:07:25`
- Server 2: `# 2024-06-05 02:07:25`
- Server 3: `# 2024-06-05 02:18:05`

Step 2) I update the script from Server 1. Server 3 sees the update, Server 2 is using the old version
- Server 1: `# 2024-06-05 02:19:58`
- Server 2: `# 2024-06-05 02:07:25`
- Server 3: `# 2024-06-05 02:19:58`

Similar effect is if I update from Server 2, then Server 2 and Server 3 match, but server 1 has the old version

Step 3) I update again from Server 3. Now all 3 servers have 3 different versions of the same file
- Server 1: `# 2024-06-05 02:19:58`
- Server 2: `# 2024-06-05 02:07:25`
- Server 3: `# 2024-06-05 02:25:23`

However, only the last one updated is the real script.sh.
I verified with weed sheel `fs.meta.cat script.sh` and `fs.cat script.sh`, connecting from both Server 1 and Server 2, that at every change, the fileId, timestamps etc are updated, and the data is the latest. Thus filer has the latest version always no matter which server updates the file.

When a vacuum happens, the mounts with the older versions lose access to the file because they try to get a chunk that does not exists:
```
Jun 05 01:09:17.836133 reader_at.go:159 fetching chunk &{FileId:4,18f373f609487000a5da75fb OffsetInChunk:0 ViewSize:18130 ViewOffset:0 ChunkSize:18130 CipherKey:[] IsGzipped:true ModifiedTsNs:1717489687525686323}: http://vpn.data01.nash01.usa.katapy.io:8080/4,18f373f609487000a5da75fb?readDeleted=true: 404 Not Found
Jun 05 01:09:17.836236 filehandle_read.go:65 file handle read /script.sh: http://vpn.data01.nash01.usa.katapy.io:8080/4,18f373f609487000a5da75fb?readDeleted=true: 404 Not Found
Jun 05 01:09:17.836268 weedfs_file_read.go:51 file handle read /script.sh 0: http://vpn.data01.nash01.usa.katapy.io:8080/4,18f373f609487000a5da75fb?readDeleted=true: 404 Not Found
Jun 05 01:09:17.837876 http_util.go:482 read http://vpn.data01.nash01.usa.katapy.io:8080/4,18f373f609487000a5da75fb failed, err: http://vpn.data01.nash01.usa.katapy.io:8080/4,18f373f609487000a5da75fb?readDeleted=true: 404 Not Found
Jun 05 01:09:17.837919 http_util.go:488 retry reading in 1s
Jun 05 01:09:18.840220 http_util.go:482 read http://vpn.data01.nash01.usa.katapy.io:8080/4,18f373f609487000a5da75fb failed, err: http://vpn.data01.nash01.usa.katapy.io:8080/4,18f373f609487000a5da75fb?readDeleted=true: 404 Not Found
Jun 05 01:09:18.840263 http_util.go:488 retry reading in 1.5s
Jun 05 01:09:20.341886 http_util.go:482 read http://vpn.data01.nash01.usa.katapy.io:8080/4,18f373f609487000a5da75fb failed, err: http://vpn.data01.nash01.usa.katapy.io:8080/4,18f373f609487000a5da75fb?readDeleted=true: 404 Not Found
Jun 05 01:09:20.341911 http_util.go:488 retry reading in 2.25s
Jun 05 01:09:22.594019 http_util.go:482 read http://vpn.data01.nash01.usa.katapy.io:8080/4,18f373f609487000a5da75fb failed, err: http://vpn.data01.nash01.usa.katapy.io:8080/4,18f373f609487000a5da75fb?readDeleted=true: 404 Not Found
Jun 05 01:09:22.594053 http_util.go:488 retry reading in 3.375s
Jun 05 01:09:25.971267 http_util.go:482 read http://vpn.data01.nash01.usa.katapy.io:8080/4,18f373f609487000a5da75fb failed, err: http://vpn.data01.nash01.usa.katapy.io:8080/4,18f373f609487000a5da75fb?readDeleted=true: 404 Not Found
Jun 05 01:09:25.971304 http_util.go:488 retry reading in 5.0625s
```

The file is not available to the mounts on Server 1 and Server 2 until the mount is restarted. When the mount is restarted, the latest version becomes visibile, but once the script is executed, the file is not updated again if steps 1-3 are repeated.

In my example I was using a bash script, but the same is true if a binary file is on SeaweedFS, being executed and then replaced with an updated version.

When a file that is not being executed, like test.txt is updated in any server, the others see the latest version. I usually test that the mount sync works by executing a command like `date >> /mnt/seaweedfs/test.txt` on one server, and `less /mnt/seaweedfs/test.txt` on the others always shows the latest version.
Also if I have a script which is not directly executed, like by using `python /mnt/seaweedfs/script.py` the updates to `/mnt/seaweedfs/script.py` are propagated correctly

**Summary**
Long story short, updates to scripts that are in a weed mount are not applied to other mounts if the file in these mounts is currently being **executed**. If the mount is not executing the file, it has always access to the latest version of the file

**System Setup**
- Command: /opt/weed/bin/weed-large-disk -v 0 mount -filer=vpn.katapy.io:8888,lh1.vpn.katapy.io:8888,lh2.vpn.katapy.io:8888,lh3.vpn.katapy.io:8888 -dir=/mnt/seaweedfs/cloud -cacheDir=/mnt/seaweedfs/.docker/cloud_edge -cacheCapacityMB=134995 -chunkSizeLimitMB=250 -concurrentWriters=128 -volumeServerAccess=publicUrl -dirAutoCreate=true
- OS version: Ubuntu 22 LTS, kernel 5.15.0-76-generic x86_64
- output of `weed version`: version 8000GB 3.65
- if using filer, show the content of `filer.toml`:
```
[filer.options]
recursive_delete = true
[leveldb2]
enabled = true
dir = "./filerldb2"                    # directory to store level db files
```

**Expected behavior**
The file should always be the latest version, even if it is executed. Linux for example supports modify/replate/delete executable files that are running, without impacting the running processes, because the version they are using is in memory.

**Additional context**
Minimal script.sh to reproduce the bug:
```
#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# 2024-06-05 03:08:45

while(true); do
  sleep 10
done
```
- Create the script on a seaweedfs mount shared between 3 servers
- Execute with `./script.sh &` on 2 Servers, do not execute on Server 3
- Execute step 1-3 and see how the files diverge
- Kill the script on server 1
- Check now on server 1, the data was updated with latest version, but not on server 2
- Kill on server 2 and verify the data was updated after the script was not executing anymore

**Comment by chrislusf** [comment]
* [This function](https://github.com/seaweedfs/seaweedfs/blob/master/weed/mount/meta_cache/meta_cache.go#L70) process metadata updates. Maybe you can debug with `weed -vmodule=meta_cache=3 mount ...`
* I suspect linux may use some temp file and overwrite the executable when it is done. Not too sure.

**Comment by Dando-Real-ITA** [comment]
Yes there is a tmp file involved, I started mount with the command as indicated

Step 1, I execute the script on Server 1, and update from Server 3.
This is what I see in the logs of mount on Server 1. The script did not update on Server 1.
```
Jun 05 09:49:55.606045 meta_cache.go:99 InsertEntry /.test.sh.swp
Jun 05 09:49:55.830090 meta_cache.go:99 InsertEntry /.test.sh.swp
Jun 05 09:50:01.561880 meta_cache.go:86 DeleteEntry /.test.sh.swp
Jun 05 09:50:01.562073 meta_cache.go:99 InsertEntry /.test.sh.swp
Jun 05 09:50:01.562168 meta_cache.go:99 InsertEntry /.test.sh.swp
Jun 05 09:50:08.627081 meta_cache.go:99 InsertEntry /test.sh
Jun 05 09:50:08.911588 meta_cache.go:86 DeleteEntry /.test.sh.swp
```
When I stopped the script, no new logs were written, but I can access the updated version on Server 1

Step 2, I update the file on Server 1, this are the logs I see on mount of Server 1:
```
Jun 05 09:55:29.887387 meta_cache.go:99 InsertEntry /.test.sh.swp
Jun 05 09:55:30.149269 meta_cache.go:99 InsertEntry /.test.sh.swp
Jun 05 09:55:31.231580 meta_cache.go:86 DeleteEntry /.test.sh.swp
```
Server 2 sees the updates right away.
I did run the same weed mount command on Server 2, which always sees the updates, this was the log:
```
Jun 05 10:05:54.514178 meta_cache.go:99 InsertEntry /.test.sh.swp
Jun 05 10:05:54.524612 meta_cache.go:99 InsertEntry /.test.sh.swp
Jun 05 10:05:58.323235 meta_cache.go:86 DeleteEntry /.test.sh.swp
Jun 05 10:05:58.325805 meta_cache.go:99 InsertEntry /.test.sh.swp
Jun 05 10:05:58.441934 meta_cache.go:99 InsertEntry /.test.sh.swp
Jun 05 10:05:59.452109 meta_cache.go:99 InsertEntry /test.sh
Jun 05 10:05:59.848657 meta_cache.go:86 DeleteEntry /.test.sh.swp
```

I then restarted Server 1 mount with v4, and I see that doFlush tries to acquire a lock to update the file and only when the lock is released by terminating the executing script it finally updates:
```
[Execute script]
Jun 05 10:14:04 I0605 10:14:04.590275 weedfs_dir_lookup.go:51 dir Lookup cache hit /test.sh
Jun 05 10:14:04 ActiveLock 1 Read locked 0 type=0 with waiters 0 active r0 w0.
Jun 05 10:14:04 I0605 10:14:04.591001 reader_at.go:179 zero2 [99,4096) of file size 99 bytes
Jun 05 10:14:04 I0605 10:14:04.591040 page_writer.go:54 ReadDirtyDataAt 0 [0, 4096)
Jun 05 10:14:04 ActiveLock 1 Read unlocked 0 type=0 with waiters 0 active r0 w0.
Jun 05 10:14:04 ActiveLock 2 ReleaseHandle wait for 0 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:04 ActiveLock 2 ReleaseHandle locked 0 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:04 ActiveLock 2 ReleaseHandle unlocked 0 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:04 ActiveLock 3 Read locked 1 type=0 with waiters 0 active r0 w0.
[Update on other server]
Jun 05 10:14:04 I0605 10:14:04.594303 reader_at.go:179 zero2 [99,4096) of file size 99 bytes
Jun 05 10:14:04 I0605 10:14:04.594321 page_writer.go:54 ReadDirtyDataAt 1 [0, 4096)
Jun 05 10:14:04 ActiveLock 3 Read unlocked 1 type=0 with waiters 0 active r0 w0.
Jun 05 10:14:04 I0605 10:14:04.594380 weedfs_file_sync.go:98 doFlush /test.sh fh 1
Jun 05 10:14:04 ActiveLock 4 doFlush wait for 1 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:04 ActiveLock 4 doFlush locked 1 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:04 ActiveLock 4 doFlush unlocked 1 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:04 I0605 10:14:04.594844 weedfs_file_sync.go:98 doFlush /test.sh fh 1
Jun 05 10:14:04 ActiveLock 5 doFlush wait for 1 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:04 ActiveLock 5 doFlush locked 1 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:04 ActiveLock 5 doFlush unlocked 1 type=1 with waiters 0 active r0 w0.
[...]
Jun 05 10:14:44 I0605 10:14:44.355158 weedfs_stats.go:35 reading filer stats: ttl:"0s"
Jun 05 10:14:44 I0605 10:14:44.357534 weedfs_stats.go:41 read filer stats: total_size:22020096000000 used_size:618738021919 file_count:182483
Jun 05 10:14:44 I0605 10:14:44.605082 weedfs_file_sync.go:98 doFlush /test.sh fh 1
Jun 05 10:14:44 ActiveLock 13 doFlush wait for 1 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:44 ActiveLock 13 doFlush locked 1 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:44 ActiveLock 13 doFlush unlocked 1 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:44 I0605 10:14:44.606103 weedfs_file_sync.go:98 doFlush /test.sh fh 1
Jun 05 10:14:44 ActiveLock 14 doFlush wait for 1 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:44 ActiveLock 14 doFlush locked 1 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:44 ActiveLock 14 doFlush unlocked 1 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:49 I0605 10:14:49.889432 weedfs_file_sync.go:98 doFlush /test.sh fh 1
Jun 05 10:14:49 ActiveLock 15 doFlush wait for 1 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:49 ActiveLock 15 doFlush locked 1 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:49 ActiveLock 15 doFlush unlocked 1 type=1 with waiters 0 active r0 w0.
[Stop the script]
Jun 05 10:14:49 ActiveLock 16 ReleaseHandle wait for 1 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:49 ActiveLock 16 ReleaseHandle locked 1 type=1 with waiters 0 active r0 w0.
Jun 05 10:14:49 ActiveLock 16 ReleaseHandle unlocked 1 type=1 with waiters 0 active r0 w0.
```

Is this read lock necessary to conflict with doFlush? It seems to be the cause

**Comment by Dando-Real-ITA** [comment]
I am looking at the code and seems that if we acquire the lock in weedfs_file_sync.go doFlush after the check for dirtymetadata and isoverquota, it should fix the problem, because in this case Server 1 was not writing the file so it has no dirty metadata but fuse was not getting any update because doFlush was not returning, waiting for the lock

Moving the lock after allows a fast return if there are no local changes

**Comment by Dando-Real-ITA** [comment]
I tested the inversion on a local branch, it did help with same-server access ( a process reading data written by another process in the same server ) but not inter-server, and at this point I am not sure why

I notice this in the previous log:
`doFlush wait for 1 type=1 with waiters 0 active r0 w0.`
Seems to be waiting for something but readers and writers are 0. How does it happen?

**Comment by Dando-Real-ITA** [comment]
I tested the same script on a shared SSHFS fuse mount, and this is what I noted:
- When Server 3 updates the script, on both Server 1 and Server 3 `stat` command show updated Modify and Change times, and they match.
- The data is updated on both sides even while the script is running on Server 1
Which confirms this is expected behaviour for fuse filesystems

When I use Seaweedfs mount:
- Command `stat` shows that on Server 3 Modify and Change time is updated, while on Server 1 they are at the old values
- The data did not update
- When I stop the script, and execute `stat` on the file on Server 1, it shows the Modify and Change times updated, and data match

It seems that when `ReleaseHandle` is executed the data is updated, however I can't find the relationship in the code, `AtomicUpdateEntryFromFiler` is not checking for file handlers to update the entries.

**Comment by Dando-Real-ITA** [comment]
Ok now I found this:
invalidateFunc in: https://github.com/seaweedfs/seaweedfs/blob/d8da4bbaa713db935514b74f44b5a498bbe5ad7e/weed/mount/weedfs.go#L107
is an empty function, thus where `AtomicUpdateEntryFromFiler` is called, the cache is not invalidated: https://github.com/seaweedfs/seaweedfs/blob/d8da4bbaa713db935514b74f44b5a498bbe5ad7e/weed/mount/meta_cache/meta_cache_subscribe.go#L43

So maybe the reason that things work after the file is closed is that `ReleaseHandle` destroys the dirty page: https://github.com/seaweedfs/seaweedfs/blob/d8da4bbaa713db935514b74f44b5a498bbe5ad7e/weed/mount/filehandle.go#L111

And at next reopen it recreates with latest data with a new dirtyPage.
