### ISSUE TITLE
请问预签名listObjects方式，为什么会额外的xml中 包含 <script/>。而sdk client访问没有返回此部分

### ISSUE THREAD

**Issue by linger000** [seaweedfs/seaweedfs#5712]
<img width="1255" alt="image" src="https://github.com/seaweedfs/seaweedfs/assets/31945909/98c35c18-e068-4b47-95d1-876081f883f3">

**Comment by chrislusf** [comment]
there is a test for this https://github.com/seaweedfs/seaweedfs/blob/8211b29689b2f5a09d2ee244be91658268a687ea/weed/s3api/s3api_object_handlers_list_test.go#L10

please follow the issue template and add the details on how to reproduce.

**Comment by linger000** [comment]
tag:3.57

1.生成预签名URL
URL url = client.generatePresignedUrl(new GeneratePresignedUrlRequest(bucket, "").withMethod(HttpMethod.GET));
2.浏览器点击访问url

**Comment by chrislusf** [comment]
```
URL url = client.generatePresignedUrl(new GeneratePresignedUrlRequest(bucket, "").withMethod(HttpMethod.GET));
```
This is java code? Please make it easy to reproduce.

**Comment by linger000** [comment]
浏览器自动处理导致。
