### ISSUE TITLE
Filer leveldb3 files not being cleaned up

### ISSUE THREAD

**Issue by srisch** [seaweedfs/seaweedfs#5728]
**Describe the bug**
Old `.ldb` files seem to be sticking around forever - We have TTL's set on our bucket lets call it `some-collection` and that ttl is 90days.

The volumes appear to be getting removed correctly however I've noticed that the filer seems to have `.ldb` files sticking around from 5-6 months ago and i'm unsure what's safe to cleanup or how to automatically ensure they're being removed.  Is there a config option i'm missing?  This current setup is only using 1x filer with no replication enabled.

Example
```
2148726 Feb 23 05:41 60044397.ldb
970974 Feb 23 05:41 60044398.ldb
2152089 Feb 23 06:26 60054341.ldb
2149477 Feb 23 06:26 60054344.ldb
2155249 Feb 23 06:26 60054345.ldb
2148030 Feb 23 06:26 60054346.ldb
2152615 Feb 23 06:26 60054348.ldb
2150026 Feb 23 06:26 60054349.ldb
650219 Feb 23 06:26 60054350.ldb
2151487 Feb 23 06:33 60055658.ldb
467144 Feb 23 06:33 60055659.ldb
2143871 Feb 23 06:33 60056053.ldb
2146110 Feb 23 06:33 60056054.ldb
```

**System Setup**
Filer 
```
ExecStart=/usr/local/bin/weed filer -encryptVolumeData -master=10.0.x.x:9333 -ip.bind=10.0.x.x -s3 -s3.config=/etc/seaweedfs/config.json -metricsPort=1235 -concurrentUploadLimitMB=2048 -maxMB=32`
```
- OS version
`Ubuntu 22.0.4 LTS`
- output of `weed version`
`version 8000GB 3.58 d1e83a3b4df0c515d0aeb75dfbc8f398a771a90a linux amd64`
- if using filer, show the content of `filer.toml`
```
[leveldb3]
enabled = true
dir = "./filerldb3"
```

**Expected behavior**
Should these old `.ldb` files be automatically removed?

Update - Do not remove these .ldb files manually - bad things happen as I've found out, and it kicks off a recovery process.

**Comment by srisch** [comment]
I ran `collection.delete`, the `.ldb` files persisted, so I completely wiped the folder out via `rm -r` as I was running into disk space issues - I have another deployment I can check that uses replication to see if the issue exists there too.  It would be good to know if there's a setting I missed, or the expected behavior around TTL's.

**Comment by chrislusf** [comment]
the TTLed entries are removed when listing the directory. There are no auto-TTL inside leveldb by itself.

also, the leveldb would only soft-delete old data in levels, which are not cleaned up until compaction happens.
