### ISSUE TITLE
filer服务器之间的数据没有完全同步

### ISSUE THREAD

**Issue by mu0641** [seaweedfs/seaweedfs#5739]
你好，我在使用seaweedfs， 我有两个filer分别在两台服务器上，分别是a和b使用同一个master，b是后面才启用的，现在b只能同步启动后时间点a上面的路径更新，这个时间之前a所有的路径信息并没有同步到b,  我想要a，b 对外都能正常找到文件，应该怎么做？

**Comment by chrislusf** [comment]
use latest version, and restart b from a clear state.

**Comment by mu0641** [comment]
我把所有的环境都升级 到 version 8000GB 3.69 ac6fd36c06f9cd6740cb2ff7e97c1ba92d55bf2c linux amd64   ，同时把B的filerldb2删除了，启动B还是没有同步A所有的路径，只同步当前A新的路径信息

**Comment by chrislusf** [comment]
I can not reproduce.

**Comment by mu0641** [comment]
我重新找了一台C服务器，就可以了，是不是A服务器需要清理什么，或者B服务器的tmp目录也要清理什么

**Comment by mu0641** [comment]
`./weed filer.meta.backup -config=/root/weed/backup_filer.toml 
F0703 18:07:51.164279 filer_meta_backup.go:66 Failed to load /root/weed/backup_filer.toml file.
Please use this command to generate the a backup_filer.toml file
    weed scaffold -config=filer -output=.


goroutine 1 [running]:
github.com/seaweedfs/seaweedfs/weed/glog.stacks(0x0)
        /github/workspace/weed/glog/glog.go:768 +0x85
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).output(0x3fb0820, 0x3, 0xc0007fcd20, {0x32882d0?, 0xc0005ffd20?}, 0x3?, 0x0)
        /github/workspace/weed/glog/glog.go:719 +0x38a
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).printf(0x3fb0820, 0x3, {0x24c7e31, 0x78}, {0xc0005ffd20, 0x3, 0x3})
        /github/workspace/weed/glog/glog.go:657 +0x10a
github.com/seaweedfs/seaweedfs/weed/glog.Fatalf(...)
        /github/workspace/weed/glog/glog.go:1154
github.com/seaweedfs/seaweedfs/weed/command.runFilerMetaBackup(0x3f927f8?, {0xc0000505f0?, 0x1?, 0x1?})
        /github/workspace/weed/command/filer_meta_backup.go:66 +0x15d
main.main()
        /github/workspace/weed/weed.go:95 +0x3d9
[root@localhost weed]# pwd
/root/weed
[root@localhost weed]# ls -l
total 61288
-rw-r--r--  1 root root   162777 Jul  3 17:46 a.txt
-rw-r--r--  1 root root    10879 Jul  3 18:07 backup_filer.toml
-rw-r--r--  1 root root        0 Jul  3 17:42 bb.txt
drwxr-xr-x 10 root root     4096 Jul  3 16:54 filerldb2
-rw-r--r--  1 root root    10875 Jul  3 17:58 filer.toml
drwxr-xr-x  2 root root     4096 Jul  3 16:53 key
-rw-r--r--  1 root root      976 Jul  3 16:54 security.toml
-rwxr-xr-x  1 root root 62550168 Jul  1 14:28 weed
`
你好 ，我这个backup_filer.toml 文件明明时存在的，一直提示不存在。我用脚手架生成的是一个 filer.toml，我把名字改成backup_filer.toml 了

**Comment by chrislusf** [comment]
Make a reproducible case so that other people can help.

**Comment by chrislusf** [comment]
added 8943a572d8c742fd1d095623dc4cda0ea49e026c to print out the error message
