### ISSUE TITLE
Helm Chart release glitched to 4.0.0

### ISSUE THREAD

**Issue by gtudan** [seaweedfs/seaweedfs#5741]
**Describe the bug**
When trying to update to the 3.69 release of the helm chart I noticed that the version went from 4.0.0.
https://github.com/seaweedfs/seaweedfs/blob/gh-pages/helm/seaweedfs-4.0.0.tgz

Was that intentional, or did something go wrong during the release?

**Expected behavior**
I expected the helm chart versioning to stay in sync with the seaweedfs versioning.

**Comment by chrislusf** [comment]
this is from https://github.com/seaweedfs/seaweedfs/issues/5681

**Comment by gtudan** [comment]
So this is intentional, and the chart will be versioned independent of SeaweedFS from now on?

**Comment by chrislusf** [comment]
It should but now it's hard to keep them in sync.
