### ISSUE TITLE
S3 API not delete objects containing space in the objects name

### ISSUE THREAD

**Issue by MaxVorobyev** [seaweedfs/seaweedfs#5748]
**Describe the bug**
If we try to delete s3 object containing space in the objects name, S3 API delete request return 204 code, and don't delete s3 object from bucket.

**System Setup**
- ./weed server -dir=./data -s3
- Ubuntu 24.04
- version 30GB 3.69 ac6fd36c06f9cd6740cb2ff7e97c1ba92d55bf2c linux amd64

List s3 bucket:

```
Hypertext Transfer Protocol
    GET /test?fetch-owner=true&list-type=2&max-keys=100 HTTP/1.1\r\n
    Host: 127.0.0.1:8333\r\n
    User-Agent: aws-sdk-go/1.33.5 (go1.16.3; linux; amd64)\r\n
    Authorization: AWS4-HMAC-SHA256 Credential=1/20240707/us-west-2/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=5cf82776aa5deabd2299dbdf7e97698e9473e346c7f5adf1e3867f0cae5497d1\r\n
    X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\n
    X-Amz-Date: 20240707T122227Z\r\n
    Accept-Encoding: gzip\r\n
```
Reply from server:

```
    HTTP/1.1 200 OK\r\n
    Accept-Ranges: bytes\r\n
    Content-Length: 483\r\n
    Content-Type: application/xml\r\n
    Server: SeaweedFS S3\r\n
    X-Amz-Request-Id: 1720354947122408834\r\n
    Date: Sun, 07 Jul 2024 12:22:27 GMT\r\n
    \r\n
    [HTTP response 1/1]
    [Time since request: 0.004410766 seconds]
    [Request in frame: 4]
    [Request URI: http://127.0.0.1:8333/test?fetch-owner=true&list-type=2&max-keys=100]
    File Data: 483 bytes
eXtensible Markup Language
    <?xml
    <ListBucketResult
        xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
        <Name>
            test
            </Name>
        <Prefix>
            </Prefix>
        <MaxKeys>
            100
            </MaxKeys>
        <IsTruncated>
            false
            </IsTruncated>
        <Contents>
            <Key>
                Barents Sea resorts.mp4
                </Key>
            <ETag>
                &#34;8dbc5736856cac8cdf7e6b2973029f04-113&#34;
                </ETag>
            <Size>
                297363893
                </Size>
            <Owner>
                <ID>
                    3e8
                    </ID>
                </Owner>
            <StorageClass>
                STANDARD
                </StorageClass>
            <LastModified>
                2024-07-07T11:57:51Z
                </LastModified>
            </Contents>
        <KeyCount>
            1
            </KeyCount>
        </ListBucketResult>
```

Try to delete object "Barents Sea resorts.mp4" :

```
Hypertext Transfer Protocol
    DELETE /test/Barents%20Sea%20resorts.mp4 HTTP/1.1\r\n
    Host: 127.0.0.1:8333\r\n
    User-Agent: aws-sdk-go/1.33.5 (go1.16.3; linux; amd64)\r\n
    Authorization: AWS4-HMAC-SHA256 Credential=1/20240707/us-west-2/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=7163f3303bdae3c0b44e7eb74d4d7da16caba6c6035fa9e25aa757972c528d3a\r\n
    X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\n
    X-Amz-Date: 20240707T122854Z\r\n
    Accept-Encoding: gzip\r\n
    \r\n
    [Full request URI: http://172.16.9.5:8333/test/Barents%20Sea%20resorts.mp4]
    [HTTP request 1/2]
    [Response in frame: 16]
    [Next request in frame: 18]
```

Server reply:

```
Hypertext Transfer Protocol
    HTTP/1.1 204 No Content\r\n
    Server: SeaweedFS S3\r\n
    Date: Sun, 07 Jul 2024 12:28:54 GMT\r\n
    \r\n
    [HTTP response 1/2]
    [Time since request: 0.001203952 seconds]
    [Request in frame: 14]
    [Next request in frame: 18]
    [Next response in frame: 24]
    [Request URI: http://127.0.0.1:8333/test/Barents%20Sea%20resorts.mp4]
```
Correct s3 object deletion log:
```
I0707 18:44:06.375164 s3api_object_handlers_delete.go:28 DeleteObjectHandler test /IMG_20240628_122449.jpg
I0707 18:44:06.375205 filer_util.go:65 delete entry /buckets/test//IMG_20240628_122449.jpg: directory:"/buckets/test" name:"/IMG_20240628_122449.jpg" is_delete_data:true ignore_recursive_error:true
I0707 18:44:06.375573 filer_grpc_server.go:292 DeleteEntry directory:"/buckets/test" name:"/IMG_20240628_122449.jpg" is_delete_data:true ignore_recursive_error:true
I0707 18:44:06.375708 filer_delete_entry.go:124 deleting entry /buckets/test/IMG_20240628_122449.jpg, delete chunks: true
I0707 18:44:06.375935 log_read.go:60 localMeta:filer:172.16.9.5:8888@172.16.9.5:50080 ReadFromBuffer at 2024-07-07 15:43:48.892873468 +0000 UTC batch 7. Read bytes 231 batch 7
I0707 18:44:06.376041 log_read.go:136 localMeta:filer:172.16.9.5:8888@172.16.9.5:50080 sent messages ts[2024-07-07 15:29:35.749117356 +0000 UTC,2024-07-07 15:44:06.375788231 +0000 UTC] size 1
I0707 18:44:06.376056 log_read.go:60 localMeta:filer:172.16.9.5:8888@172.16.9.5:50080 ReadFromBuffer at 2024-07-07 15:44:06.375788231 +0000 UTC batch 7. Read bytes 0 batch 7
I0707 18:44:06.376231 log_read.go:60 aggMeta:s3@172.16.9.5:50066 ReadFromBuffer at 2024-07-07 15:43:48.892873468 +0000 UTC batch 6. Read bytes 231 batch 6
I0707 18:44:06.376274 log_read.go:136 aggMeta:s3@172.16.9.5:50066 sent messages ts[2024-07-07 15:30:36.5095439 +0000 UTC,2024-07-07 15:44:06.375788231 +0000 UTC] size 1
I0707 18:44:06.376287 log_read.go:60 aggMeta:s3@172.16.9.5:50066 ReadFromBuffer at 2024-07-07 15:44:06.375788231 +0000 UTC batch 6. Read bytes 0 batch 6
I0707 18:44:06.377022 volume_write.go:217 delete needle 8,108300000000
I0707 18:44:06.380510 s3api_object_handlers_list.go:42 ListObjectsV2Handler test
I0707 18:44:06.380714 filer_grpc_server.go:42 ListEntries directory:"/buckets/test" limit:102
I0707 18:44:06.381961 s3api_object_handlers_list.go:42 ListObjectsV2Handler test
I0707 18:44:06.382162 filer_grpc_server.go:42 ListEntries directory:"/buckets/test" limit:1002
I0707 18:44:06.383579 filer_grpc_server.go:42 ListEntries directory:"/buckets/test" startFromFileName:"Barents Sea resorts.mp4" limit:101
I0707 18:44:06.384547 error_handler.go:96 status 200 application/xml:
```
Object with space in names deletion attempt log:
```
I0707 18:45:52.328931 s3api_object_handlers_delete.go:28 DeleteObjectHandler test /Barents Sea resorts.mp4
I0707 18:45:52.328976 filer_util.go:65 delete entry /buckets/test//Barents%20Sea%20resorts.mp4: directory:"/buckets/test" name:"/Barents%20Sea%20resorts.mp4" is_delete_data:true ignore_recursive_error:true
I0707 18:45:52.329357 filer_grpc_server.go:292 DeleteEntry directory:"/buckets/test" name:"/Barents%20Sea%20resorts.mp4" is_delete_data:true ignore_recursive_error:true
I0707 18:45:52.333662 s3api_object_handlers_list.go:42 ListObjectsV2Handler test
I0707 18:45:52.333900 filer_grpc_server.go:42 ListEntries directory:"/buckets/test" limit:102
I0707 18:45:52.335852 s3api_object_handlers_list.go:42 ListObjectsV2Handler test
I0707 18:45:52.336083 filer_grpc_server.go:42 ListEntries directory:"/buckets/test" limit:1002
I0707 18:45:52.336744 filer_grpc_server.go:42 ListEntries directory:"/buckets/test" startFromFileName:"Barents Sea resorts.mp4" limit:101
I0707 18:45:52.338088 error_handler.go:96 status 200 application/xml:
test100falseBarents Sea resorts.mp4"8dbc5736856cac8cdf7e6b2973029f04-113"2973638933e8STANDARD2024-07-07T11:57:51Z1
```

**Expected behavior**
Delete s3 object from bucket

**Additional context**
The bug appears since version 3.66

**Comment by kmlebedev** [comment]
It’s strange why then ceph s3 tests pass?

**Comment by MaxVorobyev** [comment]
Correct s3 object deletion log:
`I0707 18:44:06.375164 s3api_object_handlers_delete.go:28 DeleteObjectHandler test /IMG_20240628_122449.jpg
I0707 18:44:06.375205 filer_util.go:65 delete entry /buckets/test//IMG_20240628_122449.jpg: directory:"/buckets/test" name:"/IMG_20240628_122449.jpg" is_delete_data:true ignore_recursive_error:true
I0707 18:44:06.375573 filer_grpc_server.go:292 DeleteEntry directory:"/buckets/test" name:"/IMG_20240628_122449.jpg" is_delete_data:true ignore_recursive_error:true
I0707 18:44:06.375708 filer_delete_entry.go:124 deleting entry /buckets/test/IMG_20240628_122449.jpg, delete chunks: true
I0707 18:44:06.375935 log_read.go:60 localMeta:filer:172.16.9.5:8888@172.16.9.5:50080 ReadFromBuffer at 2024-07-07 15:43:48.892873468 +0000 UTC batch 7. Read bytes 231 batch 7
I0707 18:44:06.376041 log_read.go:136 localMeta:filer:172.16.9.5:8888@172.16.9.5:50080 sent messages ts[2024-07-07 15:29:35.749117356 +0000 UTC,2024-07-07 15:44:06.375788231 +0000 UTC] size 1
I0707 18:44:06.376056 log_read.go:60 localMeta:filer:172.16.9.5:8888@172.16.9.5:50080 ReadFromBuffer at 2024-07-07 15:44:06.375788231 +0000 UTC batch 7. Read bytes 0 batch 7
I0707 18:44:06.376231 log_read.go:60 aggMeta:s3@172.16.9.5:50066 ReadFromBuffer at 2024-07-07 15:43:48.892873468 +0000 UTC batch 6. Read bytes 231 batch 6
I0707 18:44:06.376274 log_read.go:136 aggMeta:s3@172.16.9.5:50066 sent messages ts[2024-07-07 15:30:36.5095439 +0000 UTC,2024-07-07 15:44:06.375788231 +0000 UTC] size 1
I0707 18:44:06.376287 log_read.go:60 aggMeta:s3@172.16.9.5:50066 ReadFromBuffer at 2024-07-07 15:44:06.375788231 +0000 UTC batch 6. Read bytes 0 batch 6
I0707 18:44:06.377022 volume_write.go:217 delete needle 8,108300000000
I0707 18:44:06.380510 s3api_object_handlers_list.go:42 ListObjectsV2Handler test
I0707 18:44:06.380714 filer_grpc_server.go:42 ListEntries directory:"/buckets/test" limit:102
I0707 18:44:06.381961 s3api_object_handlers_list.go:42 ListObjectsV2Handler test
I0707 18:44:06.382162 filer_grpc_server.go:42 ListEntries directory:"/buckets/test" limit:1002
I0707 18:44:06.383579 filer_grpc_server.go:42 ListEntries directory:"/buckets/test" startFromFileName:"Barents Sea resorts.mp4" limit:101
I0707 18:44:06.384547 error_handler.go:96 status 200 application/xml: <?xml version="1.0" encoding="UTF-8"?>`

Object with space in names deletion attempt log:
`I0707 18:45:52.328931 s3api_object_handlers_delete.go:28 DeleteObjectHandler test /Barents Sea resorts.mp4
I0707 18:45:52.328976 filer_util.go:65 delete entry /buckets/test//Barents%20Sea%20resorts.mp4: directory:"/buckets/test" name:"/Barents%20Sea%20resorts.mp4" is_delete_data:true ignore_recursive_error:true
I0707 18:45:52.329357 filer_grpc_server.go:292 DeleteEntry directory:"/buckets/test" name:"/Barents%20Sea%20resorts.mp4" is_delete_data:true ignore_recursive_error:true
I0707 18:45:52.333662 s3api_object_handlers_list.go:42 ListObjectsV2Handler test
I0707 18:45:52.333900 filer_grpc_server.go:42 ListEntries directory:"/buckets/test" limit:102
I0707 18:45:52.335852 s3api_object_handlers_list.go:42 ListObjectsV2Handler test
I0707 18:45:52.336083 filer_grpc_server.go:42 ListEntries directory:"/buckets/test" limit:1002
I0707 18:45:52.336744 filer_grpc_server.go:42 ListEntries directory:"/buckets/test" startFromFileName:"Barents Sea resorts.mp4" limit:101
I0707 18:45:52.338088 error_handler.go:96 status 200 application/xml: <?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>test</Name><Prefix></Prefix><MaxKeys>100</MaxKeys><IsTruncated>false</IsTruncated><Contents><Key>Barents Sea resorts.mp4</Key><ETag>&#34;8dbc5736856cac8cdf7e6b2973029f04-113&#34;</ETag><Size>297363893</Size><Owner><ID>3e8</ID></Owner><StorageClass>STANDARD</StorageClass><LastModified>2024-07-07T11:57:51Z</LastModified></Contents><KeyCount>1</KeyCount></ListBucketResult>`

**Comment by kmlebedev** [comment]
There is still a hotfix, but it needs to be improved
https://github.com/seaweedfs/seaweedfs/pull/5736

**Comment by kmlebedev** [comment]
@chrislusf Hello looks, so is there any extra coding here?
https://github.com/seaweedfs/seaweedfs/commit/e6bfd061c71ef7ef06e559a6d1d041b997ea633f

**Comment by kmlebedev** [comment]
@chrislusf [Here](https://github.com/seaweedfs/seaweedfs/commit/e6bfd061c71ef7ef06e559a6d1d041b997ea633f) you replaced the http proxy request with a grpc request, but did not remove the URL encoding

**Comment by chrislusf** [comment]
Added a fix. Need to add tests for this case, in case of regression.
