### ISSUE TITLE
Unable to delete some files from s3 API

### ISSUE THREAD

**Issue by loic-fremaux** [seaweedfs/seaweedfs#5796]
**Describe the bug**
Some files still exists after deletion from s3 client (S3 Browser) with path style and signatures v4.
In the same bucket, I can delete some files but it doesn't work for some others.

**System Setup**
- List the command line to start
- weed -v=4 master -ip=X.X.X.X -port=9333 -mdir=/srv/wfs -metricsPort=9103 -defaultReplication=000
- weed -v=4 filer -dataCenter=bagn -rack=rack1 -ip=X.X.X.X -metricsPort=9105 -s3 -s3.config=/etc/seaweedfs/s3.json -s3.dataCenter=bagn -master=X.X.X.X:9333
- weed -v=4 volume -dir=/srv/wfs/data01 -max=200 -disk=hdd -port=8080 -dataCenter=bagn -rack=rack1 -ip=X.X.X.X -metricsPort=9104 -mserver=X.X.X.X:9333

- OS version : debian 12 (proxmox lxc)
- output of `weed version` : version 30GB 3.69 ac6fd36c06f9cd6740cb2ff7e97c1ba92d55bf2c linux amd64
- default filer config

**Additional context**
Here are the filer logs

In this case, the file still exists after deletion (message(3).txt)
```
Jul 18 08:34:27 WFS-FIL01 weed[3125]: I0718 08:34:27.131740 s3api_object_handlers_delete.go:28 DeleteObjectHandler filetransfer-tm /message(3).txt
Jul 18 08:34:27 WFS-FIL01 weed[3125]: I0718 08:34:27.131773 filer_util.go:65 delete entry /buckets/filetransfer-tm//message%283%29.txt: directory:"/buckets/filetransfer-tm" name:"/message%283%29.txt" is_delete_data:true ignore_recursive_error:true
Jul 18 08:34:27 WFS-FIL01 weed[3125]: I0718 08:34:27.136578 filer_grpc_server.go:292 DeleteEntry directory:"/buckets/filetransfer-tm" name:"/message%283%29.txt" is_delete_data:true ignore_recursive_error:true
```

The file is successfuly removed (Postman-win64-Setup.exe
```
Jul 18 09:22:08 WFS-FIL01 weed[3125]: I0718 09:22:08.605090 s3api_object_handlers_delete.go:28 DeleteObjectHandler filetransfer-tm /Postman-win64-Setup.exe
Jul 18 09:22:08 WFS-FIL01 weed[3125]: I0718 09:22:08.605102 filer_util.go:65 delete entry /buckets/filetransfer-tm//Postman-win64-Setup.exe: directory:"/buckets/filetransfer-tm" name:"/Postman-win64-Setup.exe" is_delete_data:true ignore_recursive_error:true
Jul 18 09:22:08 WFS-FIL01 weed[3125]: I0718 09:22:08.605308 filer_grpc_server.go:292 DeleteEntry directory:"/buckets/filetransfer-tm" name:"/Postman-win64-Setup.exe" is_delete_data:true ignore_recursive_error:true
Jul 18 09:22:08 WFS-FIL01 weed[3125]: I0718 09:22:08.605409 filer_delete_entry.go:124 deleting entry /buckets/filetransfer-tm/Postman-win64-Setup.exe, delete chunks: true
```

Maybe it is related to the filename (special chars) ?
I should also point out that deletion works in all cases from the filer web interface.

**Comment by chrislusf** [comment]
this duplicated https://github.com/seaweedfs/seaweedfs/issues/5748
