### ISSUE TITLE
COSI Driver

### ISSUE THREAD

**Issue by kvaps** [seaweedfs/seaweedfs#5838]
Kubernetes has standard interface for provisioning ObjectStorage volumes
- https://github.com/kubernetes-sigs/container-object-storage-interface-api
- https://github.com/kubernetes-sigs/container-object-storage-interface-controller

It would be nice to create driver for SeaweedFS

**Comment by kvaps** [comment]
It seems implementation should be really simple
https://github.com/rook/rook/tree/v1.14.9/pkg/operator/ceph/object/cosi

**Comment by chrislusf** [comment]
Need to see the demand for COSI. Please comment here if you want this.

**Comment by kvaps** [comment]
Actually I started working on the COSI driver for SeaweedFS. Thanks to ChatGPT, I was able to generate code from the s3gw-cosi driver this evening. I haven't tested it yet but will do so tomorrow. 🙂 

https://github.com/aenix-io/seaweedfs-cosi-driver

**Comment by kvaps** [comment]
The main logic is here. I would appreciate it if you could take a quick look at how it suggests creating S3 buckets and granting access to them, and provide some feedback if it's done incorrectly:

https://github.com/aenix-io/seaweedfs-cosi-driver/blob/seaweedfs/pkg/driver/provisioner.go

**Comment by chrislusf** [comment]
Amazing! It looks fine.

**Comment by kvaps** [comment]
I tested new driver, and it works!


first I saved my certs and configuration locally:
```
kubectl exec -n tenant-root seaweedfs-filer-1 -- tar -C /usr/local/share/ca-certificates/ -cf- . | tar -C  ~/.seaweedfs/ca-certificates/ -xvf-
```

Then I started seaweedfs-cosi-driver:
```
WEED_GRPC_CLIENT_KEY=/Users/kvaps/.seaweedfs/ca-certificates/client/tls.key WEED_GRPC_CLIENT_CERT=/Users/kvaps/.seaweedfs/ca-certificates/client/tls.crt WEED_GRPC_CA=/Users/kvaps/.seaweedfs/ca-certificates/client/ca.crt COSI_ENDPOINT=unix:///tmp/cosi.sock SEAWEEDFS_FILER=10.244.1.51:18888 bin/seaweedfs-cosi-driver -v 10
```

and [container-object-storage-interface-provisioner-sidecar](https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar):
```
go build -o artifacts/objectstorage-sidecar cmd/objectstorage-sidecar/*.go
artifacts/objectstorage-sidecar -d unix:///tmp/cosi.sock --kubeconfig ~/.kube/config -v 5
```


buckets are provisioning and access is granting:

```yaml
> fs.ls buckets
sample-bcc215ebca8-c77f-45b1-8153-51384ef0cc0a
> s3.configure
{
    {
      "name":  "ba-5a56712d-027d-4fa1-a985-7989ebafc2bd",
      "credentials":  [
        {
          "accessKey":  "c724b096eed6feb90376a2bbe81986a1",
          "secretKey":  "c03093d5c046da0271f3f161244a891a373970a33e118bb1d63a63031e4fa0a8"
        },
        {
          "accessKey":  "8ac29f7ebf99cce3a33185781ee85cc1",
          "secretKey":  "3e43c3e264a2c9562f41cc041d3541f52068a49c55117b4e60c4d50d09db18c7"
        }
      ],
      "actions":  [
        "Read:sample-bcc215ebca8-c77f-45b1-8153-51384ef0cc0a",
        "Write:sample-bcc215ebca8-c77f-45b1-8153-51384ef0cc0a",
        "List:sample-bcc215ebca8-c77f-45b1-8153-51384ef0cc0a",
        "Tagging:sample-bcc215ebca8-c77f-45b1-8153-51384ef0cc0a"
      ],
      "account":  null
    }
  ],
  "accounts":  []
}
```

**Comment by kvaps** [comment]
@chrislusf can we create github.com/seaweedfs/seaweedfs-cosi-driver for this driver, i'd like to submit it there

**Comment by chrislusf** [comment]
done and invited you.

**Comment by kvaps** [comment]
Okay, I created PR to add this to official Helm chart https://github.com/seaweedfs/seaweedfs/pull/5843

Short notes:
- Drive reworked and tested manually
- Official COSI-sidecar image also contain some bugs, I prepared upstream PR to fix the sidecar container https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar/pull/139#event-13714532195
- Also PR for adding SeaweedFS COSI driver on official website https://github.com/container-object-storage-interface/container-object-storage-interface.github.io/pull/12

**Comment by chrislusf** [comment]
Thanks!

> * Official COSI-sidecar image also contain some bugs, I prepared upstream PR to fix the sidecar container

Is this bug specific to this COSI driver?

**Comment by kvaps** [comment]
No, this is common bug of sidecar comtroller
