### ISSUE TITLE
filer can't run with default filer.toml

### ISSUE THREAD

**Issue by wangxf2000** [seaweedfs/seaweedfs#5870]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/seaweedfs/seaweedfs/discussions

example of a good issue report:
https://github.com/seaweedfs/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/seaweedfs/seaweedfs/issues/1008

**Describe the bug**
create filer.toml with command: /usr/local/bin/weed scaffold -config filer -output="/etc/seaweedfs"
the filer service can't start with error: F0808 17:39:03.431692 config.go:55 Reading /etc/seaweedfs/filer.toml: While parsing config: toml: basic strings cannot have new lines
goroutine 1 [running]:
then I use the simplest  filer.toml config, it works well.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- /usr/local/bin/weed -logdir=/seaweedfs/log/filer filer -port=8888 -master=localhost:9333
- OS version Rocky/Centos 8
- output of `weed version`: 3.7.1
- if using filer, show the content of `filer.toml`

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
fixed in 2074e7db67e7c24d51a951689aab1c260e823127

**Comment by wangxf2000** [comment]
default filer.toml file，On line 288, the ssl_key_file is missing a double quotation mark. It should be ssl_key_file = "".

**Comment by wangxf2000** [comment]
default filer.toml file，On line 288, the ssl_key_file is missing a double quotation mark. It should be ssl_key_file = "".

**Comment by wangxf2000** [comment]
default filer.toml file，On line 288, the ssl_key_file is missing a double quotation mark. It should be ssl_key_file = "".
