### ISSUE TITLE
fs.mergeVolumes  -dir /topics/.system/log/  -apply true

### ISSUE THREAD

**Issue by MapleWhiteZZZ** [seaweedfs/seaweedfs#5911]
sor

collection.list
`collection:""   volumeCount:2013        size:1183523972184      fileCount:400004        deletedBytes:1180865444790      deletion:398743
collection:"xxxx"        volumeCount:8523        size:89372631003560     fileCount:344991057     deletedBytes:9991091246616      deletion:30512898`

  volumeCount:2013 used by  topics logs ;
so i want  `fs.mergeVolumes  -dir /topics  -apply true`  to merge volume  and delete empty;

i have a try
when  fs.mergeVolumes  -dir /topics/    is ok;

when fs.mergeVolumes  -dir /topics/  -apply true  ;     -dir  is useless

**Comment by MapleWhiteZZZ** [comment]
version  version 30GB 3.67 af95c58fa linux amd64

**Comment by chrislusf** [comment]
the logic looks fine. Could you add some println to debug this? https://github.com/seaweedfs/seaweedfs/blob/master/weed/shell/command_fs_merge_volumes.go#L126

**Comment by MapleWhiteZZZ** [comment]
thank you；it is ok
