### ISSUE TITLE
Volume vacuum problem,How to start a multi-threaded vacuum task

### ISSUE THREAD

**Issue by winding345** [seaweedfs/seaweedfs#5928]
We use `version 8000GB 3.67 d3032d1e805ab363242c833d9a61db59b3941f21 linux amd64` large-disk version, and our work may produce lots of trash. We need a high speed volume vacuum.

When we used it, we found that vacuum task can only vacuum one volume at the same time. And we cannot specify that he immediately vacuum the volume with a specific volume_id.Command `volume.vacuum -volumeId xxx` of weed shell  doesn't seem to work,We speculate that volume just joined the vacuum queue.

Is there any other way to quickly clean up the trash in the volume?

**Comment by chrislusf** [comment]
Could you please share some more details about your use case?

**Comment by winding345** [comment]
> Could you please share some more details about your use case?

We build an iceberg on s3 of seaweedfs. We will periodically overwrite data in iceberg. Therefore too much trash were produced.

**Comment by chrislusf** [comment]
Just added parallel vacuuming in https://github.com/seaweedfs/seaweedfs/commit/446329681175dbce771378e7c46bbabfeaa4b74e

**Comment by winding345** [comment]
> Just added parallel vacuuming in [4463296](https://github.com/seaweedfs/seaweedfs/commit/446329681175dbce771378e7c46bbabfeaa4b74e)

Thank you very much. Looking forward to the next release
