### ISSUE TITLE
WORM (Write once read many) support 

### ISSUE THREAD

**Issue by 27149chen** [seaweedfs/seaweedfs#5954]
Is there a plan or roadmap to support [WORM (Write once read many)](https://en.wikipedia.org/wiki/Write_once_read_many) ?
I find a related issue (https://github.com/seaweedfs/seaweedfs/issues/4268). But that issue discusses S3, while I am more interested in fuse mount.

**Comment by chrislusf** [comment]
you can run `weed mount -readonly` for readonly mode.

**Comment by 27149chen** [comment]
@chrislusf readonly means I can not create any new files, but worm means I can open a new file, write something and close, after that, I can not write it again

**Comment by 27149chen** [comment]
@chrislusf  there are some issues in your pr
1. worm files should not be deleted (see https://en.wikipedia.org/wiki/Write_once_read_many)
2. modify time will change, so I can write&close a file again and again in 10 second
3. there are some other ways to modify a file within the mount point, like uploading a file directly thru filer
