### ISSUE TITLE
Log files take huge amount of storage

### ISSUE THREAD

**Issue by facorazza** [seaweedfs/seaweedfs#6057]
**Describe the bug**

The logs take an insane amount of storage.

**System Setup**

Deployed using helm for both seaweedfs and seaweedfs-csi-driver

- `/usr/bin/weed -logdir=/logs -v=1 master -port=9333 -mdir=/data -ip.bind=0.0.0.0 -defaultReplication=001 -metricsPort=9327 -volumeSizeLimitMB=1000 -ip=${POD_NAME}.${SEAWEEDFS_FULLNAME}-master.seaweedfs -peers=${SEAWEEDFS_FULLNAME}-master-0.${SEAWEEDFS_FULLNAME}-master.seaweedfs:9333`
- ` /usr/bin/weed -logdir=/logs -v=1 filer -port=8888 -metricsPort=9327 -dirListLimit=100000 -defaultReplicaPlacement=001 -ip=${POD_IP} -s3 -s3.port=8333 -s3.allowEmptyFolder=true -s3.config=/etc/sw/seaweedfs_s3_config -master=${SEAWEEDFS_FULLNAME}-master-0.${SEAWEEDFS_FULLNAME}-master.seaweedfs:9333`
- `/usr/bin/weed -logdir=/logs -v=1 volume -port=8080 -metricsPort=9327 -dir /data -dir.idx=/idx -max 0 -ip.bind=0.0.0.0 -readMode=proxy -index=leveldb -minFreeSpacePercent=7 -ip=${POD_NAME}.${SEAWEEDFS_FULLNAME}-volume.seaweedfs -compactionMBps=50 -mserver=${SEAWEEDFS_FULLNAME}-master-0.${SEAWEEDFS_FULLNAME}-master.seaweedfs:9333`
- weed mount arguments:
  ```
      --endpoint=$(CSI_ENDPOINT)
      --filer=$(SEAWEEDFS_FILER)
      --nodeid=$(NODE_ID)
      --driverName=$(DRIVER_NAME)
      --cacheDir=/var/cache/seaweedfs
      --components=node
  ```
- output of `weed version`: `version 30GB 3.72 e50d85c0f linux amd64`

**Expected behavior**

Is there any way to keep the log size at bay other than periodically purging the logs?
How safe is it to clear the logs?

**Screenshots**

![Image Pasted at 2024-9-24 12-26](https://github.com/user-attachments/assets/9131d6c5-8d00-4408-acff-670e8b5c6069)

**Comment by chrislusf** [comment]
what is running on the mount?

**Comment by facorazza** [comment]
> what is running on the mount?

- custom software uploading files via S3 APIs
- collections for tools such as loki, influxdb, fission

Influxdb has some erratic behaviour. Sometimes it hangs and the index has to be manually rebuilt.

Most of the storage is used by the "" collection.

This is the maintenance script I'm using:

```shell
scripts = """
      volume.vacuum
      fs.mergeVolumes -apply
      volume.vacuum
      volume.deleteEmpty -force
      volume.fix.replication
      volume.balance -force
    """
```

**Comment by chrislusf** [comment]
Are there any large files that are frequently modified?

**Comment by facorazza** [comment]
I'm not sure tbh. Maybe the db data of both influx and loki. Is it possible to figure out the files changed from the log files?

**Comment by facorazza** [comment]
it could also be that sw logs pretty frequently that it can't find new volumes to assign to. The logs are collected by loki which in turn updates its db and indexes. I'm not sure that's enough to get to that kind of storage utilization however

**Comment by Material-Scientist** [comment]
Probably modifying some (large) file frequently. I've also made that mistake in the past (e.g. Kafka log segment).

**Comment by facorazza** [comment]
Could be I'll close this one
