### ISSUE TITLE
[S3] Signature V4 doesn't work with reverse proxy

### ISSUE THREAD

**Issue by er2off** [seaweedfs/seaweedfs#6086]
**Describe the bug**

When you try to use S3 signature v4 with URL like `https://your.server/s3`, Seaweed throws error:
> ERROR: S3 error: 403 (SignatureDoesNotMatch): The request signature we calculated does not match the signature you provided. Check your key and signing method.

When try to access directly by port or by using v2 (`signature_v2 = True` in s3cmd), everything works fine.

**System Setup**
- output of `weed version`: was 3.72 during tests but seems like latest 3.74 still have this bug.

**Additional context**

`/s3` is reverse proxy to s3 port, for Caddy it's something like
```caddy
redir /s3 /s3/
handle_path /s3/* {
	reverse_proxy localhost:8333
}
```

**Comment by chrislusf** [comment]
please add header `X-Forwarded-For` and use this commit https://github.com/seaweedfs/seaweedfs/commit/f747767aa10da345c19a61a63687d52876efe6a5

**Comment by er2off** [comment]
> please add header `X-Forwarded-For` and use this commit [f747767](https://github.com/seaweedfs/seaweedfs/commit/f747767aa10da345c19a61a63687d52876efe6a5)

Caddy automatically sets `X-Forwarded-For` header (and I checked this one more time with http server, it's value is public IP). Still 403

**Comment by chrislusf** [comment]
did you use this commit [f747767](https://github.com/seaweedfs/seaweedfs/commit/f747767aa10da345c19a61a63687d52876efe6a5) ?

**Comment by er2off** [comment]
yes

**Comment by er2off** [comment]
Hm, looks like s3cmd is trying to use your.server/s3 as host
```
DEBUG: Using signature v4
DEBUG: get_hostname(None): your.server/s3
DEBUG: canonical_headers = host:your.server/s3
x-amz-content-sha256:<REDACTED>
x-amz-date:20241002T173031Z

DEBUG: Canonical Request:
GET
/

host:your.server/s3
x-amz-content-sha256:<REDACTED>
x-amz-date:20241002T173031Z

host;x-amz-content-sha256;x-amz-date
<REDACTED>
----------------------
DEBUG: signature-v4 headers: {'x-amz-date': '20241002T173031Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=<REDACTED>/20241002/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=<REDACTED>', 'x-amz-content-sha256': '<REDACTED>'}
```

**Comment by er2off** [comment]
So I'm able to access if change X-Forwarded-For (renamed locally to X-Forwarded-Host to be more correct) to your.server/s3
For Caddy it will look like
```caddy
handle_path /s3/* {
	reverse_proxy localhost:8333 {
		header_up X-Forwarded-Host your.server/s3
	}
}
```

**Comment by chrislusf** [comment]
* Do you need to change the source code? If so, please send a PR.
* This is worth documenting. Maybe add a section in https://github.com/seaweedfs/seaweedfs/wiki/Production-Setup ?

**Comment by er2off** [comment]
> Maybe add a section in https://github.com/seaweedfs/seaweedfs/wiki/Production-Setup ?

Maybe. It's actually an undefined behavior (because official AWS S3 uses subdomains) so this works only with s3cmd. rclone and aws-cli correctly subdivides host but keeps `/s3` in signed part (original path will be stripped at reverse proxy) so check will fail again.
Possible solution to support all clients is to check both with subpath and without it. But I don't know is it worth because even minio [doesn't want support this way](https://github.com/minio/minio/issues/10162).
