### ISSUE TITLE
As of v3.75 s3 connections fail with signature erorrs

### ISSUE THREAD

**Issue by gsxdsm** [seaweedfs/seaweedfs#6104]
**Describe the bug**
After updated to 3.75, my s3 client (CloudMounter, s3Drive, others) on Mac no longer can connect to my Seaweed S3 server. Error:

"The request signature we calculated does not match the signature you provided. Check your key and signing method. error -1.)"

My s3 server is behind a kubernetes loadbalancer (cilium) with cilium ingress. I'm accessing via a Cloudflare tunnel - both access from the tunnel and direct through the ingress url fail the same way.

**Comment by chrislusf** [comment]
how to reproduce it?

**Comment by gsxdsm** [comment]
1. weed command args:
            -logtostderr=true
            -v=4
            s3
            -config=/auth/config.json
            -ip.bind=0.0.0.0
            -port=8333
            -port.grpc=18333
            -filer=seaweedfs-filer:8888
            -allowEmptyFolder

2. When connecting directly to a forwarded kubernetes port on localhost, it works. It fails when using an ingress (default cilium ingress, no options). 


3. Connecting using CloudMounter and s3drive on mac - both standard configurations that worked in 3.74 now fail in 3.75. 

I'm guessing its something in https://github.com/seaweedfs/seaweedfs/pull/6092/commits/eb51c6ac02eaf73fcac460461592d389cd4aca4d#diff-e859e2f69804cf2ad0be2840401299a6fda63ddbb76b965785693a0f7afa9440R688

**Comment by chrislusf** [comment]
how to reproduce step 2 or 3?

**Comment by chrislusf** [comment]
> I'm guessing its something in [eb51c6a#diff-e859e2f69804cf2ad0be2840401299a6fda63ddbb76b965785693a0f7afa9440R688](https://github.com/seaweedfs/seaweedfs/commit/eb51c6ac02eaf73fcac460461592d389cd4aca4d#diff-e859e2f69804cf2ad0be2840401299a6fda63ddbb76b965785693a0f7afa9440R688)

Yes. The code change was added to make it easier to add a proxy/loadBalancer. Not sure why it is doing the opposite.

**Comment by gsxdsm** [comment]
2. Ingress:
spec:
  ingressClassName: cilium
  rules:
    - host: sws3.c.myhost.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-s3
                port:
                  number: 8333

3. I'm just using the hostname above and my access key/secret key to configure both CloudMounter and s3Drive apps on mac - see:
<img width="689" alt="Screenshot 2024-10-07 at 11 46 47 PM" src="https://github.com/user-attachments/assets/140452fd-cb55-4230-a00b-49bfab9e9756">

**Comment by gsxdsm** [comment]
Yeah, the code change made my working proxy/load balancer no longer work :-)

3.74 works perfectly with those defaults. The cilium ingress is just the default ingress setup that works for everything. I used the bitnami helm chart, but also reproduced it with the seaweedfs helm chart. Tried creating a manual ingress rule as well. For whatever reason the new change doesn't seem to work with default ingress setups.

**Comment by chrislusf** [comment]
Not familiar with kubernetes. Maybe you can debug by adding some println around the lines in the PR.

**Comment by gsxdsm** [comment]
Will do some debugging, but I believe the default Helm chart in the repo now won't work for S3 with this change.

**Comment by gsxdsm** [comment]
Will close this - it works in a regular docker container just not in Kubernetes

**Comment by chrislusf** [comment]
> Will close this - it works in a regular docker container just not in Kubernetes

This is really interesting.why is that?

**Comment by gsxdsm** [comment]
With the docker container I'm connecting just to the IP, so no issues with ingress/X-Forward-For or X-Forward-Host headers. But in Kubernetes when using ingress (vs. the port mapping) something with the headers appears to not be set properly. There might be a configuration parameter on Kubernetes to make it work, but my ingress reverse proxy provider (cilium) didn't have anything that looked promising. I bet nginx would make it easier, but I don't have cycles to dig in further.

**Comment by amoutaux** [comment]
I'm having the same issue with 3.75 and regular Docker containers (it's not Kubernetes-related): "The request signature we calculated does not match the signature you provided. Check your key and signing method".

My setup is simple:
1 master
1 volume
1 filer -s3

Accessing the S3 Gateway from the same host works fine. I get the error message as soon as I try to access the host from a different machine through my company proxy (with or without credentials enabled). I pinned down the version for now.

@gsxdsm Did you figure out a way to make things work with the latest image ?

**Comment by chrislusf** [comment]
@amoutaux how do you configure the proxy?

**Comment by amoutaux** [comment]
@chrislusf sorry for such a late answer, I completely forgot about this and just realize now, shame on me. .. I bumped to v3.96 since then and wasn't able to reproduce.
