### ISSUE TITLE
automating shell commands and ec encode/decode

### ISSUE THREAD

**Issue by valan** [seaweedfs/seaweedfs#6108]
My goal is to be able to periodically check ec volumes and decode the ones that have had a certain threshold of files deleted in order to compact them and then re-encode when they fill back up again.

It looks like volume file deletion data is available within some of the shell commands, but I'm not sure how to automate any of those since they are in an interactive shell. Is there a way to run them from an external script or can what I want to do be done in the http api? Or am I thinking about this the wrong way?

**Comment by chrislusf** [comment]
Does this work for you?

```
echo "lock; ec.decode .... ; unlock" | weed shell
```

**Comment by valan** [comment]
yeah that works, I can totally work with that, thank you!

**Comment by valan** [comment]
I'm actually wondering now, is it even possible to get the amount of deleted files/bytes for an ec volume without converting back to a normal volume first? seems like the http api only gives info about normal volumes
