### ISSUE TITLE
How is the traffic distributed?

### ISSUE THREAD

**Issue by dmitrydeco** [seaweedfs/seaweedfs#6128]
Hi, I’ve been trying to find information, but I couldn't. I have a master server and two volume servers. When I upload a file (in this case to the server on port 8081), the file is accessible from all file servers:

```

 391438 ?        Sl    12:36 ./weed master
 391613 ?        Sl     4:40 ./weed volume -dir=/tmp/data1 -max=5 -mserver=localhost:9333 -port=8080
 391949 ?        Sl     4:14 ./weed volume -dir=/tmp/data2 -max=10 -mserver=localhost:9333 -port=8081

localhost@localhost:~$ curl -I http://127.0.0.1:8081/6,e9c277988b
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Disposition: inline; filename="testfile.deb"
Content-Length: 30242980
Content-Type: application/vnd.debian.binary-package
Etag: "cdd82d94"
Last-Modified: Tue, 15 Oct 2024 07:27:28 GMT
Server: SeaweedFS Volume 30GB 3.77
Date: Tue, 15 Oct 2024 07:28:53 GMT

localhost@localhost:~$ curl -I http://127.0.0.1:8080/6,e9c277988b
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Disposition: inline; filename="testfile.deb"
Content-Length: 30242980
Content-Type: application/vnd.debian.binary-package
Date: Tue, 15 Oct 2024 07:28:59 GMT
Etag: "cdd82d94"
Last-Modified: Tue, 15 Oct 2024 07:27:28 GMT
Server: SeaweedFS Volume 30GB 3.77

localhost@localhost:~$ curl -I http://127.0.0.1:9333/6,e9c277988b
HTTP/1.1 308 Permanent Redirect
Content-Type: text/html; charset=utf-8
Location: http://127.0.0.1:8081/6,e9c277988b
Date: Tue, 15 Oct 2024 07:29:07 GMT
```
I have two questions:

Why is the file accessible on both servers?
When I access the server on port 8080, where this file is not present, does the file get downloaded through the server on port 8081 or 8080? I need to know whether traffic is consumed on both servers or not. Thanks

**Comment by chrislusf** [comment]
the volume server can proxy to the right volume server with the volume.

**Comment by dmitrydeco** [comment]
@chrislusf  Thank you for your reply. Am I correct in understanding that in this case, traffic will only go from the server where the file is stored if I request it from another volume server? All my files are stored fully, without chunks.

**Comment by chrislusf** [comment]
that's correct.
