### ISSUE TITLE
 restoring .idx? files.dat and .vif exist

### ISSUE THREAD

**Issue by ridervka** [seaweedfs/seaweedfs#6160]
Hello everyone. I saw this message. Maybe someone knows how to restore .idx? files.dat and .vif exist

              Only the idx and dat files are needed. (btw: actually the idx files can be re-generated from dat files also.)

The master should accept the migrated volumes as writable (for replicated volumes only if the replication copies are all live).

Check http://master:port/dir/status?pretty=y to see which volumes are writable.

_Originally posted by @chrislusf in https://github.com/seaweedfs/seaweedfs/issues/57#issuecomment-69423938_

**Comment by kmlebedev** [comment]
> Hello everyone. I saw this message. Maybe someone knows how to restore .idx? files.dat and .vif exist

```
cd volumeDataDir
weed fix -volumeId 99 .
```

**Comment by ridervka** [comment]
Спасибо дорогой! @kmlebedev
