### ISSUE TITLE
`fs.configure` can't set `diskType` to empty string

### ISSUE THREAD

**Issue by trim21** [seaweedfs/seaweedfs#6165]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/seaweedfs/seaweedfs/discussions

example of a good issue report:
https://github.com/seaweedfs/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/seaweedfs/seaweedfs/issues/1008

**Describe the bug**

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
- output of `weed version`
- if using filer, show the content of `filer.toml`

**Expected behavior**

once `diskType` is added to fs.configure, but there is to way to reset it to empty string unless `-delete` and re-add a new one:

```text
fs.configure -locationPrefix=/buckets/torrents/ -apply -replication=004 -disk ""
{
  "version":  0,
  "locations":  [
    {
      "locationPrefix":  "/buckets/torrents/",
      "collection":  "",
      "replication":  "004",
      "ttl":  "",
      "diskType":  "hdd",
      "fsync":  false,
      "volumeGrowthCount":  0,
      "readOnly":  false,
      "dataCenter":  "",
      "rack":  "",
      "dataNode":  "",
      "maxFileNameLength":  0,
      "disableChunkDeletion":  false,
      "worm":  false
    }
  ]
}
```

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
"hdd" is the same as the empty string

**Comment by trim21** [comment]
> "hdd" is the same as the empty string

Thanks, no wonder why filer doesn't save any data on ssd volume.
