### ISSUE TITLE
Chunk was not found after creation

### ISSUE THREAD

**Issue by Werberus** [seaweedfs/seaweedfs#6180]
**Describe the bug**
In rare cases chunks are lost on volume.
Chronology of events:
- writing the object
- chunk and meta are created
- trying to get an object
- we get an error from the volume server: "404 Not Found"
- deleting an object

I'm attaching a log from the filer. 15419,125fdba732959c7a corresponds to the file /buckets/data/commits/9fd45ae7a5f8.tmp
[filer.log](https://github.com/user-attachments/files/17574846/filer.log)

**System Setup**
We have SeaweedFS running on Kubernetes via SeaweedFS Operator. There are 3 Masters, 48 Volume Servers, 32 Filers (with Scylla as its backend)

- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount":

  Master:
  ```
  weed -logtostderr=true master -volumeSizeLimitMB=30720 -defaultReplication=001 -ip=$(POD_NAME).seaweedfs1-test-master-peer.seaweedfs-test -peers=seaweedfs1-test-master-0.seaweedfs1-test-master-peer.seaweedfs-test:9333,seaweedfs1-test-master-1.seaweedfs1-test-master-peer.seaweedfs-test:9333,seaweedfs1-test-master-2.seaweedfs1-test-master-peer.seaweedfs-test:9333 -metricsPort=9999`
  ```
  Volume Server:
  ```
  weed -logtostderr=true volume -port=8444 -max=0 -ip=$(POD_NAME).seaweedfs1-test-volume-peer.seaweedfs-test -metricsPort=9999 -mserver=seaweedfs1-test-master-0.seaweedfs1-test-master-peer.seaweedfs-test:9333,seaweedfs1-test-master-1.seaweedfs1-test-master-peer.seaweedfs-test:9333,seaweedfs1-test-master-2.seaweedfs1-test-master-peer.seaweedfs-test:9333 -dir=/data0 -concurrentDownloadLimitMB=0 -concurrentUploadLimitMB=0`
  ```
  Filer:
  ```
  weed -logtostderr=true filer -port=8888 -ip=$(POD_NAME).seaweedfs1-test-filer-peer.seaweedfs-test -master=seaweedfs1-test-master-0.seaweedfs1-test-master-peer.seaweedfs-test:9333,seaweedfs1-test-master-1.seaweedfs1-test-master-peer.seaweedfs-test:9333,seaweedfs1-test-master-2.seaweedfs1-test-master-peer.seaweedfs-test:9333 -metricsPort=9999 -s3 -concurrentUploadLimitMB=0
  ```
 
- OS version: Fedora CoreOS 33.20210426.3.0
- output of `weed version`: version 8000GB 3.77
- if using filer, show the content of `filer.toml`:
```
[leveldb2]
enabled = false
[etcd]
enabled = false
servers = "seaweed-etcd.seaweedfs:2379"
timeout = "3s"
[cassandra]
enabled = true
keyspace="seaweedfs"
hosts=[
  "seaweed-scylla-client.seaweedfs:9042",
]
superLargeDirectories = [
]
```

**Expected behavior**
There should be no arbitrary deletion of chunks

**Comment by chrislusf** [comment]
Thanks for the details! 

The logs are interesting:
* The chunk could not be read back. So the chunk creation failed.
* It seems the chunk was not created successfully but the error was not surfacing.
* If the chunk was deleted, the `readDeleted=true` should be able to read it back.

Added a commit for more logs.

Question: does the file size of 29 look correct?

**Comment by Werberus** [comment]
Hi @chrislusf . Thanks a lot for the quick response. We have taken the latest changes to the work. Testing and collecting logs may take several days. I will definitely come back with feedback based on the results.

> Question: does the file size of 29 look correct?
It's impossible to say for sure right now. We have a large number of small files that are frequently added and deleted. But the size is within the expected range. We will try to track the size

**Comment by Werberus** [comment]
We noticed the following in the volume server logs. One vid belongs to several collections. I suspect that the problems may be related to this. Report after calling "volume.fix.replication" and "volume.delete.empty -force" in attachments
[volume.log](https://github.com/user-attachments/files/17633544/volume.log)

The volume.list in the weed shell confirms this

`echo volume.list | weed shell | grep 15392`

- volume id:15392 size:31619960184 collection: "gobul1" file_count:22837 delete_count:3743 deleted_byte_count:933940892 replica_placement:1 version:3 modified_at_second:1730807474
- volume id:15392 size:35636160760 collection: "gobul1" file_count:24579 delete_count:3952 deleted_byte_count:950364650 replica_placement:1 version:3 modified_at_second:1730807474
- volume id:15392 size:9853036368 collection: "spark-history" file_count:17940 delete_count:1524 deleted_byte_count:486638952 replica_placement:1 version:3 modified_at_second:1730807558 
- volume id:15392 size:6926127208 collection: "spark-history" file_count:9763 delete_count:886 deleted_byte_count:256688978 replica_placement:1 version:3 modified_at_second:1730807558

`echo volume.list | weed shell | grep 15424`

- volume id:15424  size:28294511568  collection:"data"  file_count:21444  delete_count:10936  deleted_byte_count:153690320  replica_placement:1  version:3  modified_at_second:1730808661 
- volume id:15424  size:4357648256  collection:"gobul1"  file_count:11935  delete_count:9971  deleted_byte_count:49976437  replica_placement:1  version:3  modified_at_second:1730808667 
- volume id:15424  size:32255748504  collection:"gobul1"  file_count:23856  delete_count:11703  deleted_byte_count:201153889  replica_placement:1  version:3  modified_at_second:1730808667 
- volume id:15424  size:28297698016  collection:"data"  file_count:31397  delete_count:20590  deleted_byte_count:156190026  replica_placement:1  version:3  modified_at_second:1730808667 

`echo volume.list | weed shell | grep 15423`

- volume id:15423  size:4109742032  collection:"gobul1"  file_count:12052  delete_count:10210  deleted_byte_count:74888960  replica_placement:1  version:3  modified_at_second:1730808660 
- volume id:15423  size:32220027248  collection:"gobul1"  file_count:24119  delete_count:11944  deleted_byte_count:230892931  replica_placement:1  version:3  modified_at_second:1730808660 
- volume id:15423  size:28139447432  collection:"data"  file_count:26527  delete_count:15917  deleted_byte_count:159795136  replica_placement:1  version:3  modified_at_second:1730808611 
- volume id:15423  size:28139380496  collection:"data"  file_count:26459  delete_count:15862  deleted_byte_count:159724785  replica_placement:1  version:3  modified_at_second:1730808660 


In our case, four identical volume ids are present on four different servers, probably we periodically get to the wrong place when requesting serverUrls.

**Comment by kmlebedev** [comment]
I analyzed my logs and see similar regular bursts of such errors.
The most unpleasant thing is that the 404 error code is disguised as a valid response.
<img width="1608" alt="image" src="https://github.com/user-attachments/assets/248cb4ff-f0d7-4478-9456-739f20c9708e">

**Comment by kmlebedev** [comment]
I found the problematic file using fs.verify and it was written a year ago, perhaps the problem is old and was fixed earlier

```
fs.verify -concurrency 20 /buckets/backups
> fs.meta.cat /buckets/backups/seaweedfs_develop/config
{
  "name": "config",
  "isDirectory": false,
  "chunks": [
    {
      "fileId": "236,031336146cae1bff",
      "offset": "0",
      "size": "155",
      "modifiedTsNs": "1700572952877286506",
      "eTag": "qI1HpZG/2nVKIYziHRWg5A==",
      "sourceFileId": "",
      "fid": {
        "volumeId": 236,
        "fileKey": "51590676",
        "cookie": 1823349759
      },
      "sourceFid": null,
      "cipherKey": "",
      "isCompressed": false,
      "isChunkManifest": false
    }
  ],
  "attributes": {
    "fileSize": "155",
    "mtime": "1700572952",
    "fileMode": 432,
    "uid": 989,
    "gid": 986,
    "crtime": "1700572952",
    "mime": "",
    "ttlSec": 0,
    "userName": "",
    "groupName": [],
    "symlinkTarget": "",
    "md5": "qI1HpZG/2nVKIYziHRWg5A==",
    "rdev": 0,
    "inode": "0"
  },
  "extended": {},
  "hardLinkId": "",
  "hardLinkCounter": 0,
  "content": "",
  "remoteEntry": null,
  "quota": "0"
}chunks 1 meta size: 130 gzip:158

date -d @1700572952
Tue Nov 21 13:22:32 UTC 2023
```

**Comment by chrislusf** [comment]
* You may want to just mark these volumes as readonly.
* The volume id conflicts could happen when masters are restarted from scratch and the volume server holding the largest volume ids are not reporting to the masters yet. Newer releases should have a delay long enough. When was this cluster first created, and how often do you need to restart the cluster or upgrade?

**Comment by Werberus** [comment]
It is the newly recorded files that are corrupted, perhaps they just got into the "shared" volume. We have received a list of such volumes and will try to mark them as readonly. And let's take a break to see if new ones appear.

>  When was this cluster first created, and how often do you need to restart the cluster or upgrade?

The cluster is about two years old. We do not update often, over the past year we have updated to 3.59 and 3.77, not counting the latest updates for the problem's debug. The specifics of the cluster do not allow us to do this too often

**Comment by Werberus** [comment]
The data about the volume servers from the master-0 server differs from other servers.
master-0: [master0.log](https://github.com/user-attachments/files/17647583/master0.log)

master-1 and more: [master1.log](https://github.com/user-attachments/files/17647585/master1.log)

**Comment by kmlebedev** [comment]
@Werberus I looked carefully at your launch parameters and I strongly recommend that you enable raft from hashicorp for the weed master, since you are deploying to k8s, the state of raft may be lost during redeployment, so do not allow all masters to stop at the same time during an update, but update one by one. This will allow you to transfer a snapshot of the state between them, which may not happen with regular raft.

**Comment by kmlebedev** [comment]
I also recommend running `volume.check.disk -volumeId` for these volumes and immediately using volume.mark to make them readonly

**Comment by Werberus** [comment]
@kmlebedev  Thanks for the recommendations. We will definitely test raft from hashicorp and will to mark problem volumes as readonly. We will continue to monitor the situation. Right now we are really experiencing problems with the masters when updating seaweedfs

**Comment by kmlebedev** [comment]
> Thanks for the recommendations. We will definitely test raft from hashicorp and will to mark problem volumes as readonly. We will continue to monitor the situation. Right now we are really experiencing problems with the masters when updating seaweedfs

That's exactly why I came to PR with hashicorp, since I also lived in k8s and we encountered similar problems

**Comment by Werberus** [comment]
Thank you, there were no new "problematic" volumes after switching to hashicorp. Those that remain have been transferred to readonly. Can close the issue.
