### ISSUE TITLE
SubscribeMetadata can miss some events when big files are written to filer via s3

### ISSUE THREAD

**Issue by half-life666** [seaweedfs/seaweedfs#6181]
**Describe the bug**
We use `SubscribeMetadata` API to subscribe events from filer, so we can capture all the file metadata, to build service on top of that. Since the filer metadata is independent from upper layer access protocols, like fuse or s3, no matter which protocol, you can always subscribe to filer to get the file metadata events.

Our setup is as below:
- Start weed master, volume, filer and enable s3 service
- Start weed mount as well for s3 filer
- Write a simple server to subscribe the filer events using `SubscribeMetadata`
- Use a tool (like rclone) to write files to weed s3 endpoint

When we write a batch of large files, like 50 files with 512MB size, we can only receive like 10+ or 20+ file create events from subscriber.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
```
/usr/bin/weed -logtostderr=true master -mdir=/data -volumePreallocate -volumeSizeLimitMB=1024 -ip=192.168.3.138 -volumePreallocate=false -volumeSizeLimitMB=4096 -defaultReplication=000
/usr/bin/weed -logtostderr=true volume -dir=/data -dir=/mnt/weed1 -mserver=localhost:9333 -max=0 -port=8080 -metricsPort=9325 -preStopSeconds=1
/usr/bin/weed -logtostderr=true volume -dir=/data -dir=/mnt/weed2 -mserver=localhost:9333 -max=0 -port=8081 -metricsPort=9326 -preStopSeconds=1
/usr/bin/weed -logdir=/var/log/udm filer -master=localhost:9333 -port 8888 -s3 -s3.config=/etc/seaweedfs/s3.json -s3.port=8333 -s3.allowEmptyFolder=false -s3.allowDeleteBucketNotEmpty=false
```
- OS version
- output of `weed version`
version 30GB 3.77  linux amd64

- if using filer, show the content of `filer.toml`

**Expected behavior**
subscriber should return file counts match to files written

**Screenshots**

**Additional context**
after some debugging, we found the problem is at the implementation of MetaAggregator, but we can't identify which part of it has problem, below is the code of `SubscribeMetadata`:

```go


	for {

		glog.V(4).Infof("read on disk %v aggregated subscribe %s from %+v", clientName, req.PathPrefix, lastReadTime)

		processedTsNs, isDone, readPersistedLogErr = fs.filer.ReadPersistedLogBuffer(lastReadTime, req.UntilNs, eachLogEntryFn)
		if readPersistedLogErr != nil {
			return fmt.Errorf("reading from persisted logs: %v", readPersistedLogErr)
		}
		if isDone {
			return nil
		}

		if processedTsNs != 0 {
			lastReadTime = log_buffer.NewMessagePosition(processedTsNs, -2)
		}

		//glog.V(4).Infof("read in memory %v aggregated subscribe %s from %+v", clientName, req.PathPrefix, lastReadTime)

		//lastReadTime, isDone, readInMemoryLogErr = fs.filer.MetaAggregator.MetaLogBuffer.LoopProcessLogData("aggMeta:"+clientName, lastReadTime, req.UntilNs, func() bool {
		//	fs.filer.MetaAggregator.ListenersLock.Lock()
		//	fs.filer.MetaAggregator.ListenersCond.Wait()
		//	fs.filer.MetaAggregator.ListenersLock.Unlock()
		//	if !fs.hasClient(req.ClientId, req.ClientEpoch) {
		//		return false
		//	}
		//	return true
		//}, eachLogEntryFn)
		//if readInMemoryLogErr != nil {
		//	if readInMemoryLogErr == log_buffer.ResumeFromDiskError {
		//		continue
		//	}
		//	glog.Errorf("processed to %v: %v", lastReadTime, readInMemoryLogErr)
		//	if readInMemoryLogErr != log_buffer.ResumeError {
		//		break
		//	}
		//}
		//if isDone {
		//	return nil
		//}
		//if !fs.hasClient(req.ClientId, req.ClientEpoch) {
		//	glog.V(0).Infof("client %v is closed", clientName)
		//	return nil
		//}

		time.Sleep(1127 * time.Millisecond)
	}

	//return readInMemoryLogErr
```

if I comment out `MetaAggregator` part, **there will be no events missing any more**, so our suspect is the memory buffer in `MetaAggregator` may has wrapped in some situation, which we haven't figured out yet.

The reason for hitting this easily I believe is when using s3 to transfer files to seaweed, each file will be uploaded to /`root_dir/.uploads/xxx` filer directory first by multi part logic, then will be deleted, so it will generate more number of events than transfering using posix protocol, and it's possible (?) that the `MetaAggregator` memory buffer some how lost some of the events.

**Comment by chrislusf** [comment]
Could you try to tweak these 2 constants and see which one helped:
```
const BufferSize = 4 * 1024 * 1024
const PreviousBufferCount = 3
```
* increase `PreviousBufferCount` to a larger number, e.g. 32
* increase `BufferSize` to 64 * 1024 * 1024

**Comment by half-life666** [comment]
I tried change `PreviousBufferCount` to 10, and still same result.

**Comment by half-life666** [comment]
The log file size is not so big:

![图片](https://github.com/user-attachments/assets/4abbe9bf-1636-44e2-92a9-4cfaa988aef0)

**Comment by half-life666** [comment]
> Could you try to tweak these 2 constants and see which one helped:
> 
> ```
> const BufferSize = 4 * 1024 * 1024
> const PreviousBufferCount = 3
> ```
> 
>     * increase `PreviousBufferCount` to a larger number, e.g. 32
> 
>     * increase `BufferSize` to 64 * 1024 * 1024

I tried to change `BufferSize` to 8 * 1024 * 1024, `PreviousBufferCount` to 32, and writing 100 * 512MB files, no events is lost. 

But I don't how to set a safe value base on current tests. Another idea is to prevent recording internal events, like events generated under .uploads/xxx path, and then setting above values a bit larger, which should be working for most situations.

**Comment by half-life666** [comment]
See pr https://github.com/seaweedfs/seaweedfs/pull/6183
