### ISSUE TITLE
[Question] Is FUSE mount data stored locally?

### ISSUE THREAD

**Issue by Stitch10925** [seaweedfs/seaweedfs#6202]
I have a FUSE mount to a seaweedfs filer which is working great, but I have seen the hard disk space increase slowly over time. It isn't to clear to me where the increase is coming from, but I was wondering if the data in the mount directory is actually written to disk and then "synced" to the filer and volumes.

In other words, is a local copy of the data stored in the mount location or does the mount work like a normal mount and not store any local data?

**Comment by chrislusf** [comment]
there are buffer data written to disks.

**Comment by Stitch10925** [comment]
And this buffer data lives only until the data is pushed to the volumes and is then cleaned up?

**Comment by evgmik** [comment]
> And this buffer data lives only until the data is pushed to the volumes and is then cleaned up?

Not exactly. Everything which you read from the mount point, will be cached (if it is enabled) and will sit there until remount, or pushed away by newer reads. This cache, strored on disk, will grow to a certain number (128 MB is the default) and then stay more or less constant.
