### ISSUE TITLE
Update maintenance script without restarting master

### ISSUE THREAD

**Issue by bradmurray** [seaweedfs/seaweedfs#6216]
Is there a way to update the master.toml without restarting the master service? My master service almost always has a lock because it is running the script in the toml. I would like to be able to add a run once for the next time it unlocks, but if I edit the toml it seems to only pick it up the next time the service starts. I have to either get lucky and catch it when it's not busy doing maintenance or I have to restart the service.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
`weed master -mdir=/root/weedmaster -ip=weedmb.bm -ip.bind=0.0.0.0 -port=9333 -metricsPort=9331 -volumeSizeLimitMB=250000 -volumePreallocate`
`weed filer -master=weedmb.bm:9333 -ip=weedmb.bm -ip.bind=0.0.0.0 -port=9335 -metricsPort=9332 -defaultStoreDir=/root -ui.deleteDir=false`
`weed volume -ip=weedvd2.bm -ip.bind=0.0.0.0 -mserver=weedmb.bm:9333 -port=9334 -metricsPort=9331 -disk hdd -dir=/mnt/weed -dir.idx=/root/weedvol -max 1`

- OS version
`6.8.12-3-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-3 (2024-10-23T11:41Z) x86_64 Linux`

- output of weed version
`version 8000GB 3.79 228946369cad29ee8edc07a42a2e0d218ba16d0b linux amd64`

- `master.toml`
```
scripts = """
  lock
  ec.encode -fullPercent=95 -quietFor=1h
  ec.rebuild -force
  ec.balance -force
  volume.deleteEmpty -quietFor=24h -force
  volume.balance -force
  volume.fix.replication
  s3.clean.uploads -timeAgo=24h
  unlock
"""
```
- `filer.toml`
```
[filer.options]
master = "weedmb.bm:9333"
recursive_delete = false
port = 9335

[filer.ui]
deleteDir = false

[leveldb2]
enabled = true
dir = "/root/filerldb2"
```

**Comment by Material-Scientist** [comment]
You could just run the maintenance in a separate script by having it connect to the weed shell. That way, the master doesn't have to be restarted, and you can implement your own reload logic.
