### ISSUE TITLE
s3 documentation error

### ISSUE THREAD

**Issue by dsyscms** [seaweedfs/seaweedfs#6237]
https://github.com/seaweedfs/seaweedfs/wiki/Production-Setup

Setup S3 API
Follow [Amazon S3 API](https://github.com/seaweedfs/seaweedfs/wiki/Amazon-S3-API) to generate a json config file, to assign accessKey and secretKey for different identities, and give read/write permissions to different buckets.

Start s3 together with filer. This avoids the setup for s3 to support multiple filers.
`
weed filer -s3 -s3.config=<config.json> -port=8333
`
The endpoint is http://<s3_server_host>:8333.

Correct writing
`
weed filer -s3 -s3.config=<config.json> -s3.port=8333
`

**Comment by chrislusf** [comment]
fixed. You can actually modify wiki page directly.
