### ISSUE TITLE
Not able to establish a connection between master and volume service. error is:  I1202 06:12:38.236069 volume_grpc_client_to_master.go:43 checkWithMaster localhost:9333: get master localhost:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:19333: connect: connection refused"

### ISSUE THREAD

**Issue by Sagar9921** [seaweedfs/seaweedfs#6308]
**Described the bug**

I am trying to self host the seaweedfs by using docker-compose.
Successfully created a docker-compose.yaml file.

                          //docker-compose.yaml//
                          
--------------------------------------------------------------------------------------------------------------------------------------------
                          
services:
  master:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-master
    ports:
      - "9333:9333"
      - "19333:19333"  # Master replication port
    command: >
      master
      -ip=seaweedfs-master  # Bind to the container name for internal networking
      -ip.bind=0.0.0.0  # Bind to all available interfaces
      -defaultReplication=001
      -port=9333
    volumes:
      - master-data:/data
    restart: always
    networks:
      - seaweedfs_network

  volume:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-volume
    ports:
      - "8080:8080"  # Volume server port for external access
    command: >
      volume
      ./weed
      -max=5
      -mserver=master:9333  # Connect to master server
      -ip=seaweedfs-volume  # Bind to the container name for internal networking
      -ip.bind=0.0.0.0  # Bind to all available interfaces
      -dir=/data  # Directory for storing data
      -port=8080
    volumes:
      - volume-data:/data
    restart: always
    networks:
      - seaweedfs_network
  filer:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-filer
    ports:
      - "8888:8888"  # Filer server port for external access
    command: >
      filer
      -master=master:9333  # Connect to master server
      -ip=seaweedfs_filer  # Bind to the container name for internal networking
      -ip.bind=0.0.0.0  # Bind to all available interfaces
      -defaultReplicaPlacement=001
      -dataCenter=default
      -port=8888
    volumes:
      - filer-data:/data
    restart: always
    networks:
      - seaweedfs_network

volumes:
  master-data:
  volume-data:
  filer-data:

networks:
  seaweedfs_network:
    driver: bridge
    name: custom_seaweedfs_network
----------------------------------------------------------------------------------------------------------------------------------------------

i am able to establish a connection between master service and filer service. But my volume service is not able to establish a connection with master service.

error is :- 
ubuntu@ip-172-31-1-58:~/seaweedfs$ docker logs seaweedfs-volume
I1202 06:11:42.699052 file_util.go:27 Folder /data Permission: -rwxr-xr-x
I1202 06:11:42.700673 volume_grpc_client_to_master.go:43 checkWithMaster localhost:9333: get master localhost:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:19333: connect: connection refused"

master is running on port 9333   [Able to Access it]
volume is  running on port 8080 [Not-able to Access it]
filer is running on port 8888[ Able to Access it]

note: all 3 container are running none of the container is exiting.
Note: Ports are enabled in security group.

**Expected behavior**
volume service shuld be able to communicate with master service and volume service shuld be accessable on port 8080.
@seaweedfs
@SeaweedFS 

![image](https://github.com/user-attachments/assets/6b7d4dbe-1611-4af2-ab94-bda50e531968)
![image](https://github.com/user-attachments/assets/1de403b0-8490-4007-8c6c-8162610dd9f4)
![image](https://github.com/user-attachments/assets/6bbce82a-7962-4fe4-8cba-f065e06570e7)

**Comment by chrislusf** [comment]
duplicated wtih https://github.com/seaweedfs/seaweedfs/discussions/6309
